### ISSUE TITLE
Static and shared libraries for rubinius

### ISSUE THREAD

**Issue by chickenkiller** [rubinius/rubinius#1043]
Right, so I reopen the same topic as issue #809 after getting my feet wet about the topic.

The commit chickenkiller/rubinius@00e764ac9a047dc86a50a22c6a44279aade28432 attempts to make static the static library useable, and to improve the overall process.

I'd like to get as much feedback as possible from interested people because I have no way to test this on other platforms than Linux. @jameskilton, can you confirm I've not broken the darwin platform? It's also possible that your workaround for ffi_environ is not necessary anymore, but I'm not 100% sure.

The gist https://gist.github.com/911589 should still work without modification.

Thanks everyone for your feedback, I know there's still a lot of room for improvement.

Cheers
Lionel

**Comment by brixen** [comment]
See https://github.com/rubinius/rubinius/pull/1099#issuecomment-167493615 and https://github.com/rubinius/rubinius/pull/1099#issuecomment-167628559.
