### ISSUE TITLE
RBX exits without handling LocalJumpError exception in closure

### ISSUE THREAD

**Issue by chuckremes** [rubinius/rubinius#1312]
https://gist.github.com/1301471

Adding a "return" to a Proc should produce a LocalJumpError. MRI catches this exception and prints it out. RBX just exits.

Example came from http://innig.net/software/ruby/closures-in-ruby.rb

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
