### ISSUE TITLE
In irb, variable is not created if it's defined in code that never runs

### ISSUE THREAD

**Issue by pointlessone** [rubinius/rubinius#1547]
In MRI (and JRuby) following code will not raise NameError.

``` ruby
if false
  a = 1
end

a
# => nil
```

In rbx that code that will raise NameError: undefined local variable or method `a' on an instance of Object.

According to [issue 2362](http://bugs.ruby-lang.org/issues/2362) in Ruby Redmine this behavior is "well-known and well-documented". On the other hand I couldn't find it in Rubyspec anywhere.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
