### ISSUE TITLE
Pure Rubinius C++ API

### ISSUE THREAD

**Issue by funny-falcon** [rubinius/rubinius#1851]
I wonder if its possible to write extension using native C++ Rubinius internals.

I think, many people, which bother to write MRI C extension, will also be happy to write Rubinius C++ extension to get maximum from both platforms.

For example, I really wish to write pure Rubinius version of my gem [bin_utils](https://github.com/funny-falcon/bin_utils),  both cause there are some mri api functions not provided by Rubinius and cause I wish it will be as fast as possible without fighting against JIT.

**Comment by brixen** [comment]
This may be possible in the future, but it's not a priority right now.

**Comment by funny-falcon** [comment]
You just killed the project.

**Comment by YorickPeterse** [comment]
@funny-falcon Feel free to reply with constructive comments. Merely stating we "killed" the project by focusing our time elsewhere is not going to help.

**Comment by brixen** [comment]
@funny-falcon it's not killed, but it's not possible to make progress on this right now. I'm working through two phases: 1. clean up old tickets (many of which are as old as 2011 or 2010 and haven't seen any activity by anyone for years); and 2. adding a set of milestones for things that are compatible for the direction Rubinius is evolving and add PRs to those that can actually be worked on.

It's going to take some time to work through this process and I appreciate your patience.

There's a bunch of work to be done before this API is possible in a reasonable fashion. It's still on my list and will either be its own milestone or part of a similar one (eg the embedding API).

**Comment by funny-falcon** [comment]
excuse me for my emotional sentence.
I just feel, that high performance api is one of the most important thing (after fixing String slowness).
It is more important than CRuby API compatibility, imo. (and JRuby did it right way)
But, it just my opinion. Sorry for being noisy.

**Comment by brixen** [comment]
@funny-falcon I agree that functionality to support your needs is a high priority and I'm working to structure things so it gets the attention it needs. I also think a lot of your use cases could be better served *without* an external API. And those changes benefit everyone who uses Rubinius. Until you can experiment with those, you won't know whether they provide enough benefit for your case.

To a large extent, any external API is going to be limiting and require careful tradeoffs. On the other hand, if you can work within the Rubinius instruction set, improvements to the overall system benefit you. For example, if you could generate executable code directly, would you still have as much need for an external API?

Either way, we've been building a lot of infrastructure support over the past year and much better release process, so we'll be able to experiment more easily and quickly. I hope you'll look at the stuff coming and get involved if you can. I don't think you're being noisy.
