### ISSUE TITLE
Missing concurrency primitives

### ISSUE THREAD

**Issue by thedarkone** [rubinius/rubinius#1867]
I'm implementing a thread safe hash-like [`ThreadSafe::Cache`](https://github.com/thedarkone/thread_safe/blob/cache/lib/thread_safe/cache.rb) data structure that is internally used by Rails 4.0: https://github.com/rails/rails/pull/8510.

The current [rbx implementation](https://github.com/headius/thread_safe/blob/master/lib/thread_safe/atomic_reference_cache_backend.rb) is based on wrapping everything in `Rubinius::AtomicReference`, as you can imagine - this is not terribly efficient.

What is needed:
###### Volatile tuple

`Rubinius::Tuple` additions:
- `Tuple#volatile_get(index)` volatile read
- `Tuple#volatile_set(index, value)` volatile write
- `Tuple#cas(index, expected_value, new_value)` a strong CAS with volatile read/write semantics

or a new `Rubinius::VolatileTuple` with volatile semantics for `[]`, `[]=` and `cas` method.
###### Volatile i-vars

Here I'm seeing these alternative APIs:

**i-var based API** (my preferred variant)

``` ruby
class Foo
  volatile :bar
  volatile :@bar # alternative syntax?

  def hello
    @bar # volatile read
    @bar = 1 # volatile write
    cas_bar(1, 2) # => true
    # no way to do non-volatile reads or writes of @bar
  end
end
```

**Method based API**

``` ruby
class Foo
  attr_volatile :bar

  def hello
    bar # volatile read
    self.bar = 1 # volatile write
    cas_bar(1, 2) # => true
    @bar # non-volatile read, *dangerous* use at your own risk
    @bar = 1 # non-volatile write, *dangerous* use at your own risk
  end
end
```

**Struct based API**

``` ruby
class Foo < VolatileStruct.new(:bar)
  def hello
    bar # volatile read
    self[:bar] # volatile read
    self.bar = 1 # volatile write
    self[:bar] = 1 # volatile write
    cas_bar(1, 2) # => true
    cas(:bar, 2, 3) # => true
    @test = 1 # other non declared i-vars are *not* volatile
  end
end
```

All of the i-var volatile extension APIs might require including a module (`include Rubinius::Volatile`) or have other VM-imposed restrictions like no `metaclass` volatiles, requiring that volatile fields be declared upfront before a first instance of the class is instantiated etc.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
