### ISSUE TITLE
Ensure the tests for these C-exts pass on Rubinius

### ISSUE THREAD

**Issue by brixen** [rubinius/rubinius#2006]
Here is a list of popular C-ext gems. Ensure the tests for each pass on Rubinius in 1.x and 2.x branches.

<h1>Needs help</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>1.x (Ruby 1.8.7)</th>
      <th>2.x (Ruby 2.x)</th>
      <th>Tested?</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><a href="https://github.com/flori/json">JSON</a></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=flori&repo-name=json&ruby-engine=rbx-1" /></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=flori&repo-name=json&ruby-engine=rbx-2" /></td>
      <td><a href="https://travis-ci.org/flori/json">Travis (o)</a></td>
    </tr>
    <tr>
      <td><a href="https://github.com/cowboyd/therubyracer">therubyracer</a></td>
    <td><img src="https://travis-build-status.herokuapp.com/?owner-name=cowboyd&repo-name=therubyracer&ruby-engine=rbx-1" /></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=cowboyd&repo-name=therubyracer&ruby-engine=rbx-2" /></td>
      <td><a href="https://travis-ci.org/cowboyd/therubyracer">Travis (o)</a></td>
    </tr>
    <tr>
      <td><a href="">fast-xs</a></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=brianmario&repo-name=fast_xs&ruby-engine=rbx-1" /></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=brianmario&repo-name=fast_xs&ruby-engine=rbx-2" /></td>
      <td><a href="https://travis-ci.org/brianmario/fast_xs">Travis (o)</a></td>
    </tr>
    <tr>
      <td><a href="http://github.com/luislavena/sqlite3-ruby">sqlite3-ruby</a></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=luislavena&repo-name=sqlite3-ruby&ruby-engine=rbx-1" /></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=luislavena&repo-name=sqlite3-ruby&ruby-engine=rbx-2" /></td>
      <td><a href="https://travis-ci.org/luislavena/sqlite3-ruby">Travis (o)</a></td>
    </tr>
    <tr>
      <td><a href="https://github.com/slyphon/zookeeper">zookeeper</a></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=slyphon&repo-name=zookeeper&ruby-engine=rbx-1" /></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=slyphon&repo-name=zookeeper&ruby-engine=rbx-2" /></td>
      <td><a href="https://travis-ci.org/slyphon/zookeeper">Travis (o)</a></td>
    </tr>
    <tr>
      <td><a href="http://github.com/thoughtbot/capybara-webkit">capybara-webkit</a></td>
      <td>x[3]</td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=thoughtbot&repo-name=capybara-webkit&ruby-engine=rbx-2" /></td>
      <td><a href="https://travis-ci.org/thoughtbot/capybara-webkit">Travis (o)</a></td>
    </tr>
    <tr>
      <td><a href="http://rubyeventmachine.com/">EventMachine</a></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=eventmachine&repo-name=eventmachine&ruby-engine=rbx-1" /></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=eventmachine&repo-name=eventmachine&ruby-engine=rbx-2" /></td>
      <td><a href="https://travis-ci.org/eventmachine/eventmachine">Travis (o)</a></td>
    </tr>
    <tr>
      <td><a href="http://unicorn.bogomips.org/">Unicorn</a></td>
      <td><a href="https://gist.github.com/4070179">-</a></td>
      <td><a href="https://gist.github.com/4070223">-</a></td>
      <td><a href="#">Local</a> [1]</td>
    </tr>
    <tr>
      <td><a href="http://raindrops.bogomips.org/">raindrops</a></td>
      <td>?</td>
      <td>?</td>
      <td>?</td>
    </tr>
    <tr>
      <td><a href="http://rainbows.rubyforge.org/">rainbows</a></td>
      <td>?</td>
      <td>?</td>
      <td>?</td>
    </tr>
    <tr>
      <td><a href="http://bogomips.org/kgio/">kgio</a></td>
      <td>?</td>
      <td>?</td>
      <td>?</td>
    </tr>
    <tr>
      <td><a href="http://code.macournoyer.com/thin/">thin</a>[5]</td>
      <td>?</td>
      <td>?</td>
      <td><a href="https://travis-ci.org/macournoyer/thin">Travis (o)</a></td>
    </tr>
    <tr>
      <td><a href="http://github.com/brianmario/mysql2">mysql2</a></td>
      <td>+</td>
      <td>+</td>
      <td><a href="https://github.com/rubinius/rubinius/issues/2006#issuecomment-16284362">Local</a></td>
    </tr>
    <tr>
      <td><a href="https://bitbucket.org/ged/ruby-pg">pg</a></td>
      <td>+</td>
      <td>+</td>
      <td><a href="https://github.com/rubinius/rubinius/issues/2006#issuecomment-16284362">Local</a></td>
    </tr>
    <tr>
      <td><a href="https://github.com/vmg/redcarpet">RedCarpet</a></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=vmg&repo-name=redcarpet&ruby-engine=rbx-2" /></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=vmg&repo-name=redcarpet&ruby-engine=rbx-2" /></td>
      <td><a href="https://github.com/rubinius/rubinius/issues/2006#issuecomment-10384064">Travis (o)</td>
    </tr>
    <tr>
      <td><a href="https://github.com/sparklemotion/nokogiri">nokogiri</a></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=sparklemotion&repo-name=nokogiri&ruby-engine=rbx-1" /></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=sparklemotion&repo-name=nokogiri&ruby-engine=rbx-2" /></td>
      <td><a href="https://travis-ci.org/sparklemotion/nokogiri">Travis (o)</a></td>
    </tr>
    <tr>
      <td><a href="http://github.com/brianmario/yajl-ruby">yajl-ruby</a></td>
     <td><img src="https://travis-build-status.herokuapp.com/?owner-name=brianmario&repo-name=yajl-ruby&ruby-engine=rbx-1" /></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=brianmario&repo-name=yajl-ruby&ruby-engine=rbx-2" /></td>
      <td><a href="https://travis-ci.org/brianmario/yajl-ruby">Travis (o)</a></td>
    </tr>
    <tr>
      <td><a href="https://github.com/libgit2/rugged">rugged</a></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=libgit2&repo-name=rugged&ruby-engine=rbx-1" /></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=libgit2&repo-name=rugged&ruby-engine=rbx-2" /></td>
      <td><a href="https://travis-ci.org/libgit2/rugged">Travis (o)</a></td>
    </tr>
    <tr>
      <td><a href="https://github.com/djberg96/sys-proctable">sys-proctable</a></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=jc00ke&repo-name=sys-proctable&ruby-engine=rbx-1" /></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=jc00ke&repo-name=sys-proctable&ruby-engine=rbx-2" /></td>
      <td><a href="https://travis-ci.org/jc00ke/sys-proctable">Travis (u)</a></td>
    </tr>
    <tr>
      <td><a href="http://github.com/codahale/bcrypt-ruby">bcrypt-ruby</a></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=codahale&repo-name=bcrypt-ruby&ruby-engine=rbx-1&x=1" /></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=codahale&repo-name=bcrypt-ruby&ruby-engine=rbx-2" /></td>
      <td><a href="https://travis-ci.org/codahale/bcrypt-ruby">Travis (o)</a></td>
    </tr>
    <tr>
      <td><a href="http://github.com/hpricot/hpricot">hpricot</a></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=hpricot&repo-name=hpricot&ruby-engine=rbx-1" /></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=hpricot&repo-name=hpricot&ruby-engine=rbx-2" /></td>
      <td><a href="https://travis-ci.org/hpricot/hpricot">Travis (o)</a></td>
    </tr>
    <tr>
      <td><a href="http://github.com/blackwinter/rb-gsl">rb-gsl</a></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=blackwinter&repo-name=rb-gsl&ruby-engine=rbx-1" /></td>
      <td><img src="https://travis-build-status.herokuapp.com/?owner-name=blackwinter&repo-name=rb-gsl&ruby-engine=rbx-2" /></td>
      <td><a href="https://travis-ci.org/blackwinter/rb-gsl">Travis (o)</a></td>
    </tr>
  </tbody>
</table>

_Note_: `Travis (o)` means the owner of the repo is testing on Travis (official) and `Travis (u)` means it's unofficial (one of us set it up)
[1] @kungfumike's findings
[2] vmg/redcarpet#172
[3] They don't test 1.8.x so we won't either.
[4] Locally I get an `undefined method 'spawn' on Kernel` https://gist.github.com/4145191
[5] rbx has been added to the `.travis.yml` but the tests aren't running on Travis. Some issue w/Travis.

We can add to this list as well.

Some of these may already pass, but we should verify them all.

**Comment by edmundhighcock** [comment]
Could we add rb-gsl to the table? 

https://rubygems.org/gems/rb-gsl/versions/1.16.0.4

It is very useful for ppl in the scientific community who want to leverage the multi-threadness and other great features of Rubinius. I've posted an issue on their github page as well,

https://github.com/blackwinter/rb-gsl/issues/28

and I don't think it should be a massive amount of work, but it would probably be much quicker for a rubinius dev than an rb-gsl dev. I'm going to have a look at it, but as I am neither a rubinius dev nor an rb-gsl dev I think it will take me quite a while!

**Comment by jc00ke** [comment]
@edmundhighcock once blackwinter/rb-gsl#29 is merged I can add it to the table.

**Comment by YorickPeterse** [comment]
Updated the table so it now lists rbx-1 vs rbx-2 as the `-X` based mode options were removed quite a while ago.

**Comment by jc00ke** [comment]
Thx @YorickPeterse

**Comment by edmundhighcock** [comment]
Hi all, thanks for getting on to this so quickly... awesome!

**Comment by brixen** [comment]
Rubinius encourages people to experiment with existing Ruby projects, but migrating from MRI is not an activity that has been very successful in the past.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to better support people interested in trying to run their existing projects on Rubinius.
