### ISSUE TITLE
eventmachine fork test failure with rubinius

### ISSUE THREAD

**Issue by ttilley** [rubinius/rubinius#2044]
This one was fairly confusing because the individual test, when run by itself, passes just fine. The subprocess exits cleanly, the test can assert it received the text it expected from the subprocess via an IO.pipe, and all is well. However, when run after a test that calls into EM.error_handler, the forked process will not die.

This is a version of the test with just the two implicated factors: forking and EM.error_handler:

```ruby
require 'em_test_helper'

class TestFork < Test::Unit::TestCase
  def test_error_handler_idempotent # issue 185
    errors = []
    ticks = []
    EM.error_handler do |e|
      errors << e
    end

    EM.run do
      EM.next_tick do
        ticks << :first
        raise
      end
      EM.next_tick do
        ticks << :second
      end
      EM.add_timer(0.001) { EM.stop }
    end

    assert_equal 1, errors.size
    assert_equal [:first, :second], ticks
  end

  def test_fork_safe
    return unless cpid = Process.fork { exit! } rescue false

    read, write = IO.pipe
    EM.run do
      cpid = Process.fork do
        write.puts "forked"
        EM.run do
          EM.next_tick do
            write.puts "EM ran"
            exit!
          end
        end
      end
      EM.stop
    end
    Process.waitall
    assert_equal "forked\n", read.readline
    assert_equal "EM ran\n", read.readline
  ensure
    read.close rescue nil
    write.close rescue nil
  end

end
```

If I add STDERR.puts debug statements, it does get as far as the `exit!` before hanging.

Due to what the error handler block actually DOES here, one could argue that the test is written poorly (and it is) to not remove the error handler as part of cleanup. In rubinius's case, that errors array is perhaps not kept alive by a reference from the block as it's passed into the EM C API?

**Comment by brixen** [comment]
EM is a problematic extension due to the MRI C-API and EM's approach to working around MRI's inability to utilize parallelism. If someone wants to send a PR with a fix for this, if it's actually a Rubinius, issue, please feel free to do so.
