### ISSUE TITLE
Support accessing Fiber-locals and backtraces for a Fiber

### ISSUE THREAD

**Issue by halorgium** [rubinius/rubinius#2200]
As part of debugging @celluloid, I have been wanting to diagnose where the `Fiber`s are running and their various locals. 

I would expect the following to work. 

``` ruby
Thread.current[:key] = "outside"
fiber = Fiber.new do
  Thread.current[:key] = "inside"
  Fiber.yield
end
fiber.resume
fiber[:key] == "inside" # true
fiber.backtrace # ...
```

I also wonder whether `Fiber#[]` should be implemented, so `Fiber.current[:key]` is possible. 

/cc @evanphx

**Comment by ioquatix** [comment]
+1

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
