### ISSUE TITLE
Bunny master tests fail on Rubinius

### ISSUE THREAD

**Issue by michaelklishin** [rubinius/rubinius#2327]
Here's an [example run](https://travis-ci.org/ruby-amqp/bunny/jobs/6815043). This happens consistently.

How to reproduce:

 * Install RabbitMQ with Homebrew or get a [standalone Mac bundle](www.rabbitmq.com/install-standalone-mac.html)
 * Clone `ruby-amqp/bunny`
 * Run `./bin/ci/before_script.sh`, it may ask for sudo. It won't do any harm to your system.
 * `bundle install --binstubs`
 * `./bin/rspec -c spec`

CRuby 2.0, 1.9.3 and JRuby in 1.9 mode all work great. It would be nice to track down what's going on with Rubinius.

Per discussion with @dbussink.

**Comment by brixen** [comment]
Current [Travis run](https://travis-ci.org/ruby-amqp/bunny/builds/48148052) seems to only be failing due to this https://github.com/rubysl/rubysl-socket/issues/7
