### ISSUE TITLE
Building Melbourne for Rubinius, fails on armv7l

### ISSUE THREAD

**Issue by martinffx** [rubinius/rubinius#2331]
I'm trying to build rbx-2.0.0-rc1 using `rbenv-build`

My build keeps failing when trying to build `melbourne`, here is my [full stacktrace](https://gist.github.com/martinffx/5516817/raw/78ca7b37ab920fb22e6bd10b20114ea64ff75b77/ruby-build.log).

Here is the output of `lscpu`

```
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
```

Any idea about how to go about resolving this issue?

**Comment by brixen** [comment]
If someone has time to dedicate to looking at build issues, or ARM equipment to donate, please let us know.
