### ISSUE TITLE
Implement ripper

### ISSUE THREAD

**Issue by Rotonen** [rubinius/rubinius#2377]
http://www.ruby-doc.org/stdlib-1.9.3/libdoc/ripper/rdoc/Ripper.html

Currently not implemented.

**Comment by saizai** [comment]
https://github.com/railsbp/rails_best_practices relies on ripper.

**Comment by brixen** [comment]
@saizai perhaps send a PR to convert to [parser](https://github.com/whitequark/parser). /c @whitequark

**Comment by saizai** [comment]
@brixen They're choosing not to. See e.g. https://github.com/railsbp/rails_best_practices/issues/140 https://github.com/railsbp/rails_best_practices/issues/75

**Comment by brixen** [comment]
@saizai looks like Rubocop uses parser https://github.com/bbatsov/rubocop/blob/master/rubocop.gemspec#L42, I guess they can duke it out.

I'm happy to hear arguments for how supporting rails_best_practices adds value to Rubinius and justifies spending effort to support a very poor MRI API (ripper) when a better alternative (parser) already exists and is used by a (partial, at least, and arguable more successful) competitor of rails_best_practices. These decisions are hard to make and I'd like to know how to make them better. From my perspective, almost anything I can spend time on improving in Rubinius would be more important and valuable for its users than spending time on ripper.

**Comment by saizai** [comment]
I've got no position re ripper vs parser; don't really know either. From
the sidelines, it seems like this is something about Ruby standards /
introspection that would be well served by y'all collaborating on a
standard that's robustly supported.

Personally, I like rbx and Rails and best practices checks. I'd like to use
them together, however it works out. I also think it would be good for the
Ruby community in general for stuff like this to not get splintered into
incompatible implementations.

**Comment by YorickPeterse** [comment]
Having spent significant time using Ripper and looking into the details I strongly oppose supporting it. From a user perspective https://github.com/whitequark/parser is superior and more portable (it works across all Rubies). JRuby recently added support for Ripper IIRC but it took them several years to get it done (I remember asking them about it at least 2+ years ago).

The closest thing to a parser "standard" is the parser Gem (see above) itself. It's updated very frequently, compatible from Ruby 1.8 until the latest available version, has a consistent API and works across the 3 main implementations. If RubySpec was any indication of how difficult it is to standardize things I highly doubt Ripper will ever be specified properly.

Maybe one day we'll have it, but until then there are far more important things we need to sort out first.
