### ISSUE TITLE
Make ObjectSpace.each_object(Class|Module) faster

### ISSUE THREAD

**Issue by dgutov** [rubinius/rubinius#2390]
For example, using the same approach as JRuby.

See here for the rationale: https://groups.google.com/forum/?fromgroups#!topic/rubinius-dev/fB1bosW5URY

That thread doesn't show the last two replies, so if more details are needed, please ask.

**Comment by brixen** [comment]
If someone wants to open a PR with a patch to make ObjectSpace faster, please feel free to do so. Otherwise, this issue isn't actionable.
