### ISSUE TITLE
Faster Primality Testing and Factorization Methods for Ruby

### ISSUE THREAD

**Issue by jzakiya** [rubinius/rubinius#2438]
I developed much faster versions of the std lib words "prime?" and "prime_division" as their replacements.  Below is my paper I've written on them, with a link to the gist code.

http://www.scribd.com/doc/150217723/Improved-Primality-Testing-and-Factorization-in-Ruby

These methods perform extremely fast in Rubinius (see benchmarks)  but could probably be made faster particular to it.

**Comment by brixen** [comment]
@jzakiya Thanks for your work on this. Since the primes-utils gem is available, people really wanting to use it have an easy avenue to do so.

If someone wants to open a PR for this so we can discuss specific code impact, feel free to do so.
