### ISSUE TITLE
getaddrinfo causing crash under sidekiq

### ISSUE THREAD

**Issue by cpuguy83** [rubinius/rubinius#2507]
Stack traces: https://gist.github.com/cpuguy83/6063381

**Comment by brixen** [comment]
@cpuguy83 to be able to debug something like this we either need to be able to run the code or we need your help to eg include some instrumentation for the code that is ultimately calling getaddrinfo.

I realize debugging these things can be frustrating. If you think of some tooling we could add to Rubinius to assist, please let us know.
