### ISSUE TITLE
assignment-in-if statement inconsistency

### ISSUE THREAD

**Issue by jfredett** [rubinius/rubinius#2603]
I'm on a roll these last couple weeks.

In particular, in rbx:

```
def test
  return foo.bar if foo = get_foo
  #snip 
end
```

fails in MRI, but succeeds in RBX, given that `get_foo` returns something which responds to `bar` or nil. In particular, it complains that `foo` doesn't exist on MRI.

I'll add a working repro script shortly.

**Comment by YorickPeterse** [comment]
The first snippet seems to work the same on both MRI 2.1.4 and Rbx 2.5.1, the latter still misbehaves on Rbx.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
