### ISSUE TITLE
UDP sockets fail when sending multiple packets to non-listening port

### ISSUE THREAD

**Issue by cheald** [rubinius/rubinius#2661]
* rubinius 2.0.0 (2.1.0  2013-10-04 JI) [x86_64-linux-gnu]
* Linux luna 3.8.9-200.fc18.x86_64 #1 SMP Fri Apr 26 12:50:07 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Attempting to send data on a non-bound UDP socket raises an exception when you attempt the send multiple times to an unconnected endpoint. Since UDP is a stateless protocol, I would expect sends to non-open endpoints to fail silently.

The first send appears to succeed, but the next send fails. The third send succeeds, and so on; every other UDPSocket#send fails if the target endpoint is not connected.

    rubinius-2.0.0 :016 > require 'socket'
     => false
    rubinius-2.0.0 :017 > sock = UDPSocket.open
     => #<UDPSocket:0x99f8 :>
    rubinius-2.0.0 :018 > sock.send "bogus", 0, "127.0.0.1", 999
     => 5
    rubinius-2.0.0 :019 > sock.send "bogus", 0, "127.0.0.1", 999
    Errno::ECONNREFUSED: Connection refused - send(2)
    from kernel/common/errno.rb:17:in `handle'
    from /usr/local/rvm/gems/rbx-2.0.0@global/gems/rubysl-socket-2.0.0/lib/rubysl/socket.rb:1336:in `send'
    from kernel/platform/pointer.rb:306:in `new'
    from /usr/local/rvm/gems/rbx-2.0.0@global/gems/rubysl-socket-2.0.0/lib/rubysl/socket.rb:1333:in `send'
    from (irb):19
    from kernel/common/block_environment.rb:53:in `call_on_instance'
    from kernel/common/eval.rb:176:in `eval'
    from kernel/common/kernel.rb:440:in `loop'
    from kernel/bootstrap/proc.rb:20:in `call'
    from kernel/common/throw_catch.rb:30:in `catch'
    from kernel/common/throw_catch.rb:8:in `register'
    from kernel/common/throw_catch.rb:29:in `catch'
    from kernel/bootstrap/proc.rb:20:in `call'
    from kernel/common/throw_catch.rb:30:in `catch'
    from kernel/common/throw_catch.rb:8:in `register'
    from kernel/common/throw_catch.rb:29:in `catch'
    from /usr/local/rvm/gems/rbx-2.0.0@global/gems/rubysl-irb-2.0.3/bin/irb:12:in `__script__'
    from kernel/common/kernel.rb:427:in `load'
    from /usr/local/rvm/gems/rbx-2.0.0@global/bin/irb:19:in `__script__'
    from kernel/delta/code_loader.rb:66:in `load_script'
    from kernel/delta/code_loader.rb:182:in `load_script'
    from kernel/loader.rb:641:in `script'
    from kernel/loader.rb:822:in `main'
    'rubinius-2.0.0 :005 > sock.send "bogus", 0, "127.0.0.1", 999
     => 5

Contrast this to MRI 2.0.0-p247:

    2.0.0p247 :001 > require 'socket'
     => true
    2.0.0p247 :002 > sock = UDPSocket.open
     => #<UDPSocket:fd 7>
    2.0.0p247 :003 > sock.send "bogus", 0, "127.0.0.1", 999
     => 5
    2.0.0p247 :004 > sock.send "bogus", 0, "127.0.0.1", 999
     => 5
    2.0.0p247 :005 > sock.send "bogus", 0, "127.0.0.1", 999
     => 5

And JRuby 1.7.4:

    jruby-1.7.4 :003 > require 'socket'
     => true
    jruby-1.7.4 :004 > sock = UDPSocket.open
     => #<UDPSocket:fd 19>
    jruby-1.7.4 :005 > sock.send "bogus", 0, "127.0.0.1", 999
     => 5
    jruby-1.7.4 :006 > sock.send "bogus", 0, "127.0.0.1", 999
     => 5
    jruby-1.7.4 :007 > sock.send "bogus", 0, "127.0.0.1", 999
     => 5

**Comment by YorickPeterse** [comment]
Fixed by the recent release of rubysl-socket, see https://github.com/rubysl/rubysl-socket for more information. These changes are available as of Rubinius 3.3.
