### ISSUE TITLE
mysql2 related crashes when running specs

### ISSUE THREAD

**Issue by sayap** [rubinius/rubinius#2662]
When running the specs of my application, the process would crash intermittently. Seems like a similar issue to https://github.com/rubinius/rubinius/issues/2655, but specific to mysql2.

https://gist.github.com/sayap/6861102

rubinius 2.0.0 (2.1.0  2013-10-04 JI) [x86_64-linux-gnu]

Linux henry 3.11.1-ck1 #1 SMP PREEMPT Sun Sep 22 17:47:30 MYT 2013 x86_64 Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz GenuineIntel GNU/Linux

**Comment by YorickPeterse** [comment]
@sayap Did you manage to figure out a way to reproduce this in the mean time?

**Comment by YorickPeterse** [comment]
Closing this one due to the lack of feedback. Feel free to re-open if the issue still persists when using Rubinius 2.5.3.

**Comment by sodabrew** [comment]
I'm starting to see this pretty often on Travis with rbx-2.5.7: https://gist.github.com/sodabrew/656e0f44d33d6b46dc1b

**Comment by sodabrew** [comment]
I guess, basically, "what would cause rb_gc_mark to segfault, and should I be testing against that condition before calling it?"

**Comment by YorickPeterse** [comment]
My guess is that either our GC is messed up or somehow `rb_gc_mark` is passing bogus data to the GC. GDB should reveal more information but requires being able to reproduce this outside of Travis. Having seen this pattern before I wouldn't be surprised if somehow a `NULL` is being passed around where it shouldn't.

**Comment by sodabrew** [comment]
I started search for bugs with "saw_object" and traced my way to https://github.com/sparklemotion/nokogiri/issues/1047 - since mysql2 is also a C extension, the issues might be related?

**Comment by brixen** [comment]
@sodabrew didn't you recently fix another GC-related issue in mysql2? Could this be related? Did you run this under Valgrind? Is this consistently reproducible when running the tests? Have you built Rubinius in debug mode (`./configure --debug-build`) and run this so you can inspect the Ruby Data object from which `rb_gc_mark` is being called?

**Comment by tamird** [comment]
I built rbx in debug and [reproduced](https://gist.github.com/tamird/ccb74572aeb2858e25e7)

**Comment by YorickPeterse** [comment]
@tamird When this occurs could you please provide GDB backtraces as explained at http://rubini.us/doc/en/how-to/obtaining-gdb-backtraces/? Also if you could print the various variables in the offending call frame (using `p some-variable-name-here`) that would hopefully give more insight in what kind of data is being passed around.

**Comment by sodabrew** [comment]
I haven't seen any failures on Travis today - Is it possible that Rubinius 2.5.8 fixes this?

**Comment by tamird** [comment]
https://travis-ci.org/brianmario/mysql2/jobs/71173451

**Comment by tamird** [comment]
Interestingly this failed in Rubocop!

**Comment by sodabrew** [comment]
Yep, bummer. Here's a gist of that crash for future reference: https://gist.github.com/sodabrew/e7de223e019a390a3926

**Comment by brixen** [comment]
In general, the MRI C-API for Rubinius is deprecated, but that doesn't mean it will be going anywhere soon. Compatibility for C-extensions will continue to be evaluated on a case-by-case basis. However, C-extensions that depend on functions that examine or manipulate built-in MRI data structures will never be supported.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated.
