### ISSUE TITLE
IO#ensure_open_and_writable might not check writability correctly

### ISSUE THREAD

**Issue by godfat** [rubinius/rubinius#2685]
As shown by this:

``` ruby
rd = IO.popen('echo test')
wr = IO.popen('cat', 'r+')
IO.copy_stream(rd, wr)
p wr.read(5) # => "test\n" expected.
```

Executed in oneliner:

```
$ ./bin/rbx -ve 'IO.copy_stream(IO.popen("echo test"), i=IO.popen("cat", "r+")); p i.read(5)'
rubinius 2.0.0n282 (2.1.0 1052afac 2013-10-09 JI) [x86_64-darwin12.2.1]
An exception occurred evaluating command line code:

    not opened for writing (IOError)

Backtrace:

  IO(IO::BidirectionalPipe)#ensure_open_and_writable at kernel/common/io.rb:1456
                     IO::StreamCopier#run at kernel/common/io.rb:309
                           IO.copy_stream at kernel/common/io.rb:347
                 { } in Object#__script__ at -e:1
  Rubinius::BlockEnvironment#call_on_instance at kernel/common/block_environment.rb:53
            Kernel(Rubinius::Loader)#eval at kernel/common/eval.rb:176
                   Rubinius::Loader#evals at kernel/loader.rb:615
                    Rubinius::Loader#main at kernel/loader.rb:829
```

While MRI works as expected:

```
$ ruby -ve 'IO.copy_stream(IO.popen("echo test"), i=IO.popen("cat", "r+")); p i.read(5)'
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.2.1]
"test\n"
```

Since I am not sure how to fix this for now,
and there's a test failure in this test case:
"uses a trailing Hash in the Array for spawn-like settings"
on my computer, I don't attempt to fix it for now,
but I could add a spec if we're going to fix this
before actually fix it.

Thanks for looking into this.

**Comment by YorickPeterse** [comment]
Still occurs on commit 4417909e57f781fc14f6dda55964c5f34696f9c2.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
