### ISSUE TITLE
Global variables with local scope

### ISSUE THREAD

**Issue by patriciomacadden** [rubinius/rubinius#2711]
I'm sorry if this issue has already been reported, I searched the issues but I didn't found a duplicate.

There are some ruby globals that should have local scope, like `$~` and `$_` and in rubinius they don't. Please refer to [this](http://www.rubyist.net/~slagell/ruby/globalvars.html) and [this](https://github.com/ruby/ruby/blob/trunk/doc/globals.rdoc) documents.

My setup:
- rubinius 2.0.0 (2.1.0  2013-10-04 JI) [x86_64-darwin12.5.0]
- rbenv 0.4.0-67-g3300587

[This gist](https://gist.github.com/patriciomacadden/557be4c83247c136269f) is the test case I'm using, with the output of ruby 2.0, rubinius and jruby.

I would love to help, but I don't know where to start.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
