### ISSUE TITLE
Unable to rbx -S gem install bundler with rubinius 2.1.1 on OpenBSD

### ISSUE THREAD

**Issue by jeremyevans** [rubinius/rubinius#2732]
This is with:

    rubinius 2.1.1 (2.1.0 be67ed17 2013-10-18 JI) [i386-openbsd]

This appears to be caused by something encoding related, and should be reproducible on Linux when `LANG=C`:

    LANG=C rbx -S gem install bundler

This causes the following error:

    ERROR:  While executing gem ... (Gem::Package::FormatError)
        package is corrupt, exception while verifying: invalid byte sequence in US-ASCII (ArgumentError) in /usr/obj/ports/bundler-1.3.5-rbx/bundler-1.3.5.gem
        /usr/local/lib/rubinius/library/rubygems/package.rb:550:in `verify_entry'
        /usr/local/lib/rubinius/library/rubygems/package.rb:558:in `verify_files'
        /usr/local/lib/rubinius/library/rubygems/package/tar_reader.rb:64:in `each'
        /usr/local/lib/rubinius/library/rubygems/package.rb:557:in `verify_files'
        /usr/local/lib/rubinius/library/rubygems/package.rb:487:in `verify'
        /usr/local/lib/rubinius/library/rubygems/package/tar_reader.rb:28:in `new'
        /usr/local/lib/rubinius/library/rubygems/package.rb:484:in `verify'
        kernel/common/io.rb:606:in `open'
        kernel/common/kernel.rb:510:in `open'
        /usr/local/lib/rubinius/library/rubygems/package.rb:483:in `verify'
        /usr/local/lib/rubinius/library/rubygems/package.rb:464:in `spec'
        /usr/local/lib/rubinius/library/rubygems/source/specific_file.rb:7:in `initialize'
        /usr/local/lib/rubinius/library/rubygems/dependency_installer.rb:257:in `find_spec_by_name_and_version'
        /usr/local/lib/rubinius/library/rubygems/dependency_installer.rb:173:in `available_set_for'
        /usr/local/lib/rubinius/library/rubygems/dependency_installer.rb:398:in `resolve_dependencies'
        /usr/local/lib/rubinius/library/rubygems/dependency_installer.rb:351:in `install'
        /usr/local/lib/rubinius/library/rubygems/commands/install_command.rb:180:in `install_gem'
        /usr/local/lib/rubinius/library/rubygems/commands/install_command.rb:194:in `install_gems'
        kernel/bootstrap/array.rb:66:in `each'
        /usr/local/lib/rubinius/library/rubygems/commands/install_command.rb:190:in `install_gems'
        /usr/local/lib/rubinius/library/rubygems/commands/install_command.rb:146:in `execute'
        /usr/local/lib/rubinius/library/rubygems/command.rb:305:in `invoke_with_build_args'
        /usr/local/lib/rubinius/library/rubygems/command_manager.rb:167:in `process_args'
        /usr/local/lib/rubinius/library/rubygems/command_manager.rb:137:in `run'
        /usr/local/lib/rubinius/library/rubygems/gem_runner.rb:54:in `run'
        /usr/local/lib/rubinius/library/bin/gem.rb:21:in `__script__'
        kernel/delta/code_loader.rb:66:in `load_script'
        kernel/delta/code_loader.rb:198:in `load_script'
        kernel/loader.rb:651:in `script'
        kernel/loader.rb:833:in `main'

It's possible this is rubygems related and not rubinius related, but it is working on ruby 2.0.0 (rubygems 2.0.3), ruby 2.1.0.preview1 (rubygems 2.2.0.preview.1), and jruby 1.7.6 (rubygems 2.1.9), which all have various rubygems versions above and below rubinius 2.1.1 (rubygems 2.1.5).

**Comment by brixen** [comment]
Setting the correct environment variables is necessary.
