### ISSUE TITLE
Rubinius build options override those provided to gem installs

### ISSUE THREAD

**Issue by stouset** [rubinius/rubinius#2734]
Apologies for the vague title, but I'm still working on figuring out the root of this issue myself.

If I attempt to install the `rubysl-openssl` standard library with a custom OpenSSL directory (e.g., `gem install rubysl-openssl -- --with-openssl-dir=/usr/local/opt/openssl`), the `mkmf` library generates an `extconf.h` that is based off of the system-wide OpenSSL installation and not the custom one as expected.

The generated Makefile itself is fine, and contains references to the custom OpenSSL directory.

This problem goes away if I recompile Rubinius with `--with-opt-dir=/usr/local/opt/openssl`, but this seems to defeat one of the advantages of factoring the standard library into separate gems. It looks like `mkmf` is getting some of its configuration information from Rubinius' build options, rather than the `gem install` options.

**Comment by brixen** [comment]
See https://github.com/rubysl/rubysl-openssl/issues/12
