### ISSUE TITLE
Some failures when running the mspecs on OpenBSD

### ISSUE THREAD

**Issue by jeremyevans** [rubinius/rubinius#2737]
rbx -v

```
rubinius 2.1.1 (2.1.0 be67ed17 2013-10-18 JI) [i386-openbsd]
```

Running the mspecs on OpenBSD i386 yields the following near the end

```
2156 files, 19039 examples, 148844 expectations, 22 failures, 0 errors
```

See https://gist.github.com/jeremyevans/7145471 for a list of the errors output.

Also, I had to skip the File.open FIFO test as that was causing the tests to halt.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
