### ISSUE TITLE
 Too many open files - creating pipe (Errno::EMFILE)

### ISSUE THREAD

**Issue by thehappycoder** [rubinius/rubinius#2740]
rubinius-2.1.1

I have a ruby script that does some manipulations with the files. Loads them, saves to db via paperclip gem.

After a while, it crashes with the Errno::EMFILE error at:
picture.picture = file

```
file = nil
        begin
          picture = AdPicture.new
          picture.ad_id = ad.id
          file = File.new("#{Rails.root}/images_ann/#{old_ad.photo}")
          picture.picture = file
          picture.save!
        rescue Paperclip::Error, ActiveRecord::RecordInvalid, Errno::ENOENT => e
          p e
          ad.legacy_not_migrated_photo = old_ad.photo
          ad.save!(validate: false)
        ensure
          file.close if file
        end
```

On ruby-2.0.0 (MRI) it runs fine.

**Comment by brixen** [comment]
@thehappycoder I fixed an issue where File#reopen was not closing the original descriptor. Please test on 2.5.0 and re-open if you still have this issue.
