### ISSUE TITLE
still missing some socket constants

### ISSUE THREAD

**Issue by nocode** [rubinius/rubinius#2756]
version: 2.1.0 3b6cdd50 2013-10-31 JI
This probably requires Linux or recent FreeBSD (10 or 9, I forget)

Socket.new(:AF_UNIX, :SOCK_SEQPACKET, 0) fails with:
    Missing or uninitialized constant: Socket::Constants::PF_AF_UNIX (NameError)

So then I tried: Socket.new(:UNIX, :SOCK_SEQPACKET, 0)
Which fails with:
    unknown socket type SOCK_SEQPACKET (SocketError)

However, I finally got it working with: Socket.new(:UNIX, :SEQPACKET, 0)

**Comment by YorickPeterse** [comment]
Fixed by the recent release of rubysl-socket, see https://github.com/rubysl/rubysl-socket for more information. These changes are available as of Rubinius 3.3.
