### ISSUE TITLE
Unable to unpack bootstrap gems during configure

### ISSUE THREAD

**Issue by avaranovich** [rubinius/rubinius#2764]
Hello

I am on MacOS 10.9. Check out a fresh project. bundle. ./configure

end up with the following error in configure.log

Checking dependencies for rubinius-debugger (2.0.0)
Checking dependencies for rubysl (2.0.12)

Fetching gems...

Unpacking bootstrap gems...
ERROR:  While executing gem ... (Gem::Package::FormatError)
    package metadata is missing in /Users/avaranovich/projects/rubinius/vendor/cache/rubinius-melbourne-2.0.0.19.gem
Unable to unpack bootstrap gems.

**Comment by YorickPeterse** [comment]
Closing this one as various changes have been made to the build system since. Feel free to re-open this issue if it surfaces again.
