### ISSUE TITLE
IO#read without args on a socket should return ASCII-8BIT string

### ISSUE THREAD

**Issue by nocode** [rubinius/rubinius#2772]
external_encoding on sockets seem to always be ASCII-8BIT on MRI
sockets are special somehow (but IMHO, all IO should be ASCII-8BIT
on *nix).

require 'socket'
a, b = UNIXSocket.pair
p a.external_encoding
p b.external_encoding
b.close
s = a.read
p s.encoding

**Comment by YorickPeterse** [comment]
Still the case as of 4417909e57f781fc14f6dda55964c5f34696f9c2.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
