### ISSUE TITLE
Object finalizers should not be executed on Process.exit!

### ISSUE THREAD

**Issue by razielgn** [rubinius/rubinius#2788]
MRI 2.1 documentation states [1] that `Process.exit` runs `at_exit` and object finalizers.
For `Process.exit!` it states: "(It) exits the process immediately. No exit handlers are run.". No explicit mentions of object finalizers, but running this piece of code:

```ruby
at_exit { puts "at_exit function" }
ObjectSpace.define_finalizer("string",  proc { puts "in finalizer" })
exit!
```

On all MRI implementations (2.1.0-preview1, 2.0.0, 1.9.3, 1.8.7), nothing gets print, while on RBX 2.2.0 (f66ada6) it prints

```
in finalizer
```

`at_exit` is correctly skipped, but finalizers are apparently run anyway.

Is this considered a bug or just a deviance from MRI?

[1] http://www.ruby-doc.org/core-2.1.0/Process.html#method-c-exit-21

**Comment by brixen** [comment]
As @dbussink noted, we run finalizers on a separate thread and that thread runs concurrently with no synchronization between it and the threads that are running Ruby code. Defined finalizers run at some nondeterministic point after an object is no longer reachable and before the process ultimately exits.

Closing this as won't fix.
