### ISSUE TITLE
Travis weirdness

### ISSUE THREAD

**Issue by stakach** [rubinius/rubinius#2802]
Travis doesn't seem to be able to find Rubinius 2.2
https://travis-ci.org/cotag/ruby-tls/jobs/14467394

Not doing anything too crazy in the travis.yml:
```
language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - rbx-19mode   # Rubinius in 1.9 mode
  - rbx-20mode
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-20mode
```

**Comment by YorickPeterse** [comment]
Closing this as `rbx-2` now works on Travis. Feel free to re-open if needed.
