### ISSUE TITLE
#accept_nonblock doesn't raise IO::WaitReadable

### ISSUE THREAD

**Issue by judofyr** [rubinius/rubinius#2803]
The following code works nicely in MRI (i.e. it does nothing), but raises Errno::EAGAIN (which has not been extended with IO::WaitReadable) in Rubinius.

```ruby
require 'socket'
port = rand(10000) + 1024
server = TCPServer.new('0.0.0.0', port)
begin
  server.accept_nonblock
rescue IO::WaitReadable
end
```

```
$ ruby -v
rubinius 2.2.1 (2.1.0 3ed43137 2013-11-17 JI) [x86_64-darwin13.0.0]
```

**Comment by YorickPeterse** [comment]
Fixed by the recent release of rubysl-socket, see https://github.com/rubysl/rubysl-socket for more information. These changes are available as of Rubinius 3.3.
