### ISSUE TITLE
Superclass mismatch: OpenSSL::Cipher != OpenSSL::Cipher::Cipher (TypeError)

### ISSUE THREAD

**Issue by batizhevsky** [rubinius/rubinius#2806]
problem with run rails under rubinius 

trace + gemfile.lock:
https://gist.github.com/leonko/974a2576f52501b16df8

$ rbx -v
rubinius 2.2.1 (2.1.0 3ed43137 2013-11-17 JI) [x86_64-darwin13.0.0]

build from rvm

$ uname -a
Darwin MacBook-Pro 13.0.0 Darwin Kernel Version 13.0.0: Thu Sep 19 22:22:27 PDT 2013; root:xnu-2422.1.72~6/RELEASE_X86_64 x86_64

**Comment by maokomioko** [comment]
Issue still persists with ruby-openssl 2.3.0 and rbx-2.5.8 or head.
Can someone please take a look at it?
