### ISSUE TITLE
SIGBUS during compile

### ISSUE THREAD

**Issue by mjc** [rubinius/rubinius#2813]
on commit 7820d0d3445b68dc36bbbbf15c61fdc8a5df976a I got a SIGBUS while rake was running.  Still trying to reproduce it but here is the crash report.

https://gist.github.com/anonymous/6c575d61a037800fa9c3

**Comment by mjc** [comment]
Hi, I cannot reproduce this anymore but I've upgraded too many things to be sure that it's gone. :(

**Comment by YorickPeterse** [comment]
In that case I'll close this issue for the time being, feel free to re-open if needed.
