### ISSUE TITLE
String#scan is slow

### ISSUE THREAD

**Issue by kwleland** [rubinius/rubinius#2821]
String#scan is 3 times slower than MRI and is the cause weak performance (3x slower) on the bm_norvig_spelling.rb benchmark.

  text = File.new('holmes.txt').read.downcase  
  #holmes.txt available from norvig's website

  100.times do
    a = text.scan(/[a-z]+/)
  end

Timings:

rbx-2.2.1

real    0m19.131s
user    0m19.066s
sys 0m0.894s

ruby-2.1.0-preview1

real    0m6.260s
user    0m5.847s
sys 0m0.146s

Profiler (just around the 100.times block)

Thread 1: total running time: 152.02466238300002s

%   cumulative   self                self     total
      time   seconds   seconds      calls  ms/call  ms/call  name
       ------------------------------------------------------------
       31.44  152.02     47.80        100   478.03  1520.23  String#scan
       12.46   43.32     18.94   10818600     0.00     0.00  MatchData#ÆÅ
       10.97   22.23     16.68   10818600     0.00     0.00  MatchData#matched_area
        8.56   15.53     13.02   10818600     0.00     0.00  MatchData#collapsing?
        6.16    9.66      9.37   10818700     0.00     0.00  Regexp#search_region
        6.12    9.30      9.30       2460     3.78     3.78  GC.collect_young
        5.89   10.92      8.96   10818600     0.00     0.00  MatchData#length
        4.28   16.17      6.51   10818700     0.00     0.00  Regexp#match_from
        3.56    7.95      5.42   10818600     0.00     0.00  Array#<<
        2.03    3.40      3.09   10818600     0.00     0.00  String#byteslice
        1.47    2.53      2.23   10818600     0.00     0.00  Array#set_index
        1.42    3.06      2.16   32455800     0.00     0.00  Rubinius::Tuple#at
        1.42    3.07      2.16   32455800     0.00     0.00  Fixnum#==
        0.96    2.07      1.46   21637200     0.00     0.00  Rubinius::Tuple#ÆÅ
        0.72    1.40      1.10   10818600     0.00     0.00  MatchData#full
        0.62    1.26      0.95   10818600     0.00     0.00  Rubinius::Tuple#fields
        0.48    1.05      0.73   10818600     0.00     0.00  Fixnum#<=
        0.47    1.02      0.72   10818600     0.00     0.00  Fixnum.===
        0.47    1.02      0.72   10818600     0.00     0.00  Fixnum#-
        0.47    1.01      0.71   10818700     0.00     0.00  Fixnum#+
        0.01    0.01      0.01         36     0.40     0.40  GC.collect_mature
        0.00  152.02      0.00          1     0.62 152024.36  Integer#times
        0.00  152.02      0.00        100     0.00  1520.24  Object::**script**<6> æå
        0.00  152.02      0.00          1     0.03 152024.39  Object::**script**<5> æå

   24 methods called a total of 248,830,798 times

A little experiment where I called Regexp#search_region 10818700 times walking through the string 4 chars at a time and resetting as appropriate, took around 5 seconds in Rubinius. So the primitive is apparently around 25 percent of the total time.

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.
