### ISSUE TITLE
NoMethodError: undefined method `[]' on nil:NilClass.

### ISSUE THREAD

**Issue by funal125** [rubinius/rubinius#2826]
I have done some test, and found a strange error. Here is my code

[25] pry(main)> a = "11111"
=> "11111"
[26] pry(main)> a.size.times { |i| a[i] }
=> 5

It looks ok, 

[37] pry(main)> 10_000.times { a.size.times { |i| a[i] } }
=> 10000

It also looks ok,but

[38] pry(main)> 100_000.times { a.size.times { |i| a[i] } }
NoMethodError: undefined method `[]' on nil:NilClass.
from kernel/delta/kernel.rb:78:in`[](method_missing)'

what happened?

**Comment by YorickPeterse** [comment]
This still produces said error:

```ruby
a = "11111"
100_000.times { a.size.times { |i| a[i] } }
```

One-liner:

    rbx -e 'a = "11111"; 100_000.times { a.size.times { |i| a[i] } }'

This doesn't occur when disabling the JIT.

**Comment by brixen** [comment]
The Rubinius JIT is being rewritten from the ground up. To support this effort, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler infrastructure
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to work extensively on making the JIT extremely good.
