### ISSUE TITLE
"include" does not behave the same in rubinius as in MRI or JRuby

### ISSUE THREAD

**Issue by rossman2** [rubinius/rubinius#2829]
If you include a module then attempt to modify a class from the included module, you must specify the modules namespace or a new class is created instead of modifying the modules class.  For example, if the following code was in a file named "mymod.rb":

<pre><code>
module TestMod
   class SupportClass
      def print_modclass_method
         puts "This is from the module's class method"
      end
   end
end
</code></pre>

Then "require" the file and include the "TestMod" namespace as follows:

<pre><code>
require './mymod.rb'
include TestMod

class TestMod::SupportClass  # This line works in rubinius
#class SupportClass  # This line does NOT work in rubinius, but does in jruby and mri

   def print_should_add
      puts "This is from the dynamically added method"
   end
end

SupportClass.new.print_should_add
SupportClass.new.print_modclass_method
</code></pre>

As noted, the commented out line does not work in rubinius, but it will work properly in JRuby and MRI.  What it appears to do is create a new class which shadows the TestMod::SupportClass.  Therefore the call to "print_modclass_method" fails because it does not exist in "SupportClass".

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
