### ISSUE TITLE
Signals not handled when main thread executes join

### ISSUE THREAD

**Issue by southerngs** [rubinius/rubinius#2835]
I noticed that when creating multiple threads that Rubinius was not terminating my script when i pressed `ctrl-c`.  The following is a simple script that demonstrates the problem:

```
Signal.trap("SIGINT") do
  puts "Caught SIGINT"
  exit
end

def func 
  while true do
    sleep(0.1)
    puts "Thread running"
  end
end

t = Thread.new{ func() }
t.join
```

When running this script with MRI, typing `ctlr-c` causes the program to exit with the message `Caught SIGINT`.  But when run with Rubinius the script ignores `ctrl-c` and the rbx process has to be killed to terminate the program. Note that the signal handler and the printing are not necessary, I only added them to check why the process seemed hung.  The following also has the same problem:

```
t = Thread.new{ while true do sleep(0.1) end }
t.join
```

And the problem is related to `join` because the following correctly catches and terminates the script when `ctrl-c` is typed:

```
t = Thread.new{ while true do sleep(0.1) end }
while true do sleep(0.1) end
```

I tested when building from head on the master branch while running with Ubuntu 12.04.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
