### ISSUE TITLE
pry-remote client fails

### ISSUE THREAD

**Issue by hassan** [rubinius/rubinius#2842]
Trying to run pry-remote to inspect a process running under pow results in the error:

   allocator undefined for Thread (TypeError)  

full stack trace:  https://gist.github.com/hassan/0ae6e7e9bf5b125e54fe

MRI client works as expected.

**Comment by YorickPeterse** [comment]
This still occurs as of 4417909e57f781fc14f6dda55964c5f34696f9c2. Repro:

```ruby
# test.rb
require 'pry-remote' # gem install pry-remote

foo = 10

binding.pry_remote
```

Run the script, then in a separate terminal window run `pry-remote`.

**Comment by sempervictus** [comment]
The MRI can be annoying... Moreover, it looks like the server side doesnt like this much either, just saw a "down to the innards of RBX" stack trace. Will try to grab one next time i induce it.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
