### ISSUE TITLE
GC performance slow with lots of long surviving non-trivial objects

### ISSUE THREAD

**Issue by kwleland** [rubinius/rubinius#2858]
By non-trivial, I mean not Object.new or Fixnum.

This is the principal reason for slow relative performance (2x) on bm_list.rb

If I hack bm_survivor_rate_100.rb to use a simple Point object with 2 instance
  variables eg Point.new(1,i)  then things are 70 percent slower than MRI2.1.

If I hack bm_survivor_rate_100.rb to use [1,i] for my persistent objects then things 
  take 4 times as long as on MRI2.1

GC.stat tells the story that the problem time  is indeed in the gc.

Also it seems like a minor fix is needed to get the correct survivor rates and an
if-statement should be added so that the benchmark will also run on MRI for relative comparisons.

Pull request to change 8 files is in the making. Currently planning on using the
  small array ([1,i]) as the persistent object as it has the greater relative effect.

**Comment by brixen** [comment]
There have been a number of significant changes to GC operating parameters and diagnostic facilities added. If this is still an issue, please re-open with diagnostics logs and StatsD output for the process. If you need help getting that set up, please let me know.
