### ISSUE TITLE
close_on_exec flags on child process

### ISSUE THREAD

**Issue by washu** [rubinius/rubinius#2863]
when using puma in clustered mode (i.e. it forks a child) if that child process has a Process.span, popen, system or (backtick) call when that sub process of the child exists, it appears some file descriptors are inheriting and being closed resulting in non deterministic behaviour. Its behaving differeently than MRI 2.1.0 

test case to see effect
1. stub any rails app
2. start rails using puma -w 1 (starts 1 worker process)
3. any action can be called with a `ps -ef` or something similiar
4. run as rbx .. worker process has its comm pipe to the parent closed, thinking it died.
5. run as mri and it works as expected.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
