### ISSUE TITLE
Support the ARM architecture

### ISSUE THREAD

**Issue by jemc** [rubinius/rubinius#2867]
Rubinius would benefit from being the go-to solution for high-performance Ruby on ARM devices.

I discussed this matter with @brixen and @YorickPeterse on IRC.  They mentioned that the main blocker is the JIT (and possibly memory management), which would require some nontrivial changes.

**Comment by jurajpaulo** [comment]
Any news on the ARM front?

**Comment by jemc** [comment]
@jurajpaulo work on MCJIT support is ongoing at https://github.com/rubinius/rubinius/pull/3367

The rest of the ARM work will likely follow after that part is working.

**Comment by burningTyger** [comment]
Out of curiosity, would it be reasonably fast compared to JRuby? I'm running an app on a RaspberryPi and MRI is doing ok. JRuby is terribly slow. Can't tell why, probably caused by the JVM? I'm trying to squeeze a liitle more speed out of my box.

**Comment by YorickPeterse** [comment]
@burningTyger Without a working implementation of MCJIT that's impossible to tell.

**Comment by headius** [comment]
@burningTyger I have run JRuby on ARM and it was always much faster than MRI. Not sure what runtime you're using, but the perf ratio for me was about the same as on a desktop machine.

Please file a bug. JRuby should definitely not be slower than MRI, even on ARM.

**Comment by burningTyger** [comment]
@headius thank you for your answer. I was just test running the different Rubies on my RasPi 2. It is running on all cores but still a bit slow. I will open an issue on JRuby.

**Comment by brixen** [comment]
In general, Rubinius enthusiastically supports experimentation and welcomes ideas for features that enhance developer ability to create amazing software.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to support more efforts around experimentation.
