### ISSUE TITLE
Kernel(Class)#tcp_server_loop (method_missing)

### ISSUE THREAD

**Issue by jineshkj** [rubinius/rubinius#2869]
I am getting the following error while running a TCP Echo Server given at http://rosettacode.org/wiki/Echo_server#Ruby (second one):

[jinesh@jinesh-dell-xps EchoServer]$ ruby echo.rb
An exception occurred running echo.rb:

    undefined method `tcp_server_loop' on Socket (Class) (NoMethodError)

Backtrace:

  Kernel(Class)#tcp_server_loop (method_missing) at kernel/delta/kernel.rb:78
                       Object#__script__ at echo.rb:7
        Rubinius::CodeLoader#load_script at kernel/delta/code_loader.rb:66
        Rubinius::CodeLoader.load_script at kernel/delta/code_loader.rb:201
                 Rubinius::Loader#script at kernel/loader.rb:649
                   Rubinius::Loader#main at kernel/loader.rb:831

My  ruby version is:

[jinesh@jinesh-dell-xps EchoServer]$ ruby --version
rubinius 2.2.3.n365 (2.1.0 a8f62121 2013-12-31 JI) [x86_64-linux-gnu]

**Comment by YorickPeterse** [comment]
Fixed by the recent release of rubysl-socket, see https://github.com/rubysl/rubysl-socket for more information. These changes are available as of Rubinius 3.3.
