### ISSUE TITLE
[security] Build-time RPATH in gems' .so

### ISSUE THREAD

**Issue by r-stu31** [rubinius/rubinius#2873]
Shared object libraries installed with gems include RPATH with build-time path. This is wrong and has security implications. Example using Rubinius built on 1.1.2014 from the `/tmp/rubinius` directory and installed to `/opt/rubinius_2014010100`:

```
$ readelf -d /opt/rubinius_2014010100/gems/gems/rubysl-openssl-2.0.5/lib/openssl/openssl.so | fgrep RPATH
 0x000000000000000f (RPATH)              Library rpath: [/tmp/rubinius/staging/lib:/usr/pkg/lib]
```

The path `/tmp/rubinius/staging/lib` should not be there (the path `/usr/pkg/lib` is correct).

**Comment by brixen** [comment]
I'll make `--without-rpath` the default.
