### ISSUE TITLE
Fails to install with rbenv

### ISSUE THREAD

**Issue by ohler55** [rubinius/rubinius#2876]
I'm not sure if this is a Rubinius problem or rbenv problem. I am able to build from the github repo.

To recreate, install rbenv, install ruby-build, and then try the following...

~> rbenv install rbx-2.2.3
Downloading yaml-0.1.4.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/36c852831d02cf90508c29852361d01b
Installing yaml-0.1.4...
Installed yaml-0.1.4 to /Users/ohler/.rbenv/versions/rbx-2.2.3

Downloading rubinius-2.2.3.tar.bz2...
-> http://dqw8nmjcqpjn7.cloudfront.net/d9978cf1a4e8f0310db63e49834f9837
Installing rubinius-2.2.3...

BUILD FAILED

Inspect or clean up the working tree at /var/folders/r7/n8tgl9rs0sz7rb2wvqpdss4r0000gn/T/ruby-build.20140107213645.893
Results logged to /var/folders/r7/n8tgl9rs0sz7rb2wvqpdss4r0000gn/T/ruby-build.20140107213645.893.log

Last 10 log lines:
Installing rubinius-toolset (0.1.1)
Installing rubinius-melbourne (2.0.1.0)
Installing rubinius-processor (2.0.1)
Using bundler (1.5.1)
Updating files in vendor/cache
  * rubinius-ast-2.0.11.gem
Your bundle is complete!
It was installed into ./vendor/bundle
./configure:4:in `require': no such file to load -- bundler/setup (LoadError)
	from ./configure:4:in `<main>'

**Comment by YorickPeterse** [comment]
rbenv made various changes recently for supporting Rubinius 2.5 and such. I'm closing this issue for the time being but feel free to re-open if the problem surfaces again.
