### ISSUE TITLE
rubinius 2.2.4 compile issue

### ISSUE THREAD

**Issue by wtn** [rubinius/rubinius#2920]
I am experiencing a crash:

```
1: LD vm/vm
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
/Users/wtn/.gem/ruby/2.1.0/gems/rubinius-melbourne-2.0.1.0/lib/rubinius/melbourne/melbourne.bundle: [BUG] Segmentation fault at 0x00000000000438
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin13.0]
```

**Comment by YorickPeterse** [comment]
What's the status of this, do these problems still occur when using Rubinius 2.5.2?

**Comment by YorickPeterse** [comment]
Closing this due to the lack of feedback since my last reply and since quite a lot has changed since Rubinius 2.2. Feel free to re-open if the problem persists when using the latest version of Rubinius.
