### ISSUE TITLE
The binding behaviour with respect to local variables is inconsistent with MRI

### ISSUE THREAD

**Issue by kyrylo** [rubinius/rubinius#2940]
The code.

``` ruby
bindings = [binding, binding, binding, binding]
bindings.each_with_index { |bind, idx| bind.eval("x = #{ idx }") }
puts 'Output:'
p bindings.map { |bind| bind.eval('x') }
```

Let's run that code.
#### Rubinius 2.2.5

```
rubinius 2.2.5 (2.1.0 e543ba32 2014-02-08 JI) [x86_64-linux-gnu]
```

```
Output:
[3, 3, 3, 3]
```
#### MRI 1.8.7

```
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
```

```
Output:
[3, 3, 3, 3]
```
#### MRI 1.9.3 and greater

```
Output:
[0, 1, 2, 3]
```

Personally, I find the current Rubinius' behaviour understandable. Each different binding object references to the same scope it was created in. However, I don't have much knowledge or MRI's and Rubinius' internals, so I have no idea what led them to do this. I consider this a bug, though.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
