### ISSUE TITLE
Hash#to_yaml does not work with Ranges as keys

### ISSUE THREAD

**Issue by snex** [rubinius/rubinius#2941]
rubinius 2.2.4 (2.1.0 fd07f670 2014-02-01 JI) [x86_64-darwin13.0.0]
Darwin ... 13.0.0 Darwin Kernel Version 13.0.0: Thu Sep 19 22:22:27 PDT 2013; root:xnu-2422.1.72~6/RELEASE_X86_64 x86_64
rvm 1.25.16 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

```
> require 'yaml'
=> false
> str = {(0..1) => 1}.to_yaml
=> "--- \n!ruby/range ? \n  begin: 0\n  end: 1\n  excl: false\n  :@begin: 0\n  :@end: 1\n  :@excl: false\n: 1\n\n"
> YAML.load(str)
ArgumentError: syntax error on line 2, col -1: `  begin: 0
  end: 1
  excl: false
  :@begin: 0
  :@end: 1
  :@excl: false
: 1

'
```

**Comment by YorickPeterse** [comment]
This no longer occurs as of 4417909e57f781fc14f6dda55964c5f34696f9c2 as we (since a short while) now use Psych as the default YAML engine.
