### ISSUE TITLE
Debugger doesn't seem to work with the JIT

### ISSUE THREAD

**Issue by chrisseaton** [rubinius/rubinius#2942]
I'm trying out the Rubinius debugger, but I can't seem to get it set a breakpoint on a method that has already been compiled. They do work before the method is compiled.

Expected behaviour is that the breakpoints would work on compiled code, and presumably the compiled code would be deoptimized when I install the breakpoint.

This is with v2.2.4, Mac, x86_64.

Take this test file, `test.rb`.

```
require 'rubinius/debugger'

def foo
  a = 1
  b = 2
  c = 3
end

10_000_000.times do
  foo
end

Rubinius::Debugger.start

10_000_000.times do
  foo
end
```

Run it and set a breakpoint on line 5. The breakpoint doesn't seem to work.

```
$ rubinius/bin/ruby test.rb

| Breakpoint: Object#__script__ at test.rb:13 (38)
| 13: Rubinius::Debugger.start
debug> b Object#foo:5
| Set breakpoint 1: test.rb:5 (+4)
debug> c
$
```

Perhaps it's the JIT - try it with JIT disabled.

```
$ rubinius/bin/ruby -Xint test.rb 

| Breakpoint: Object#__script__ at test.rb:13 (38)
| 13: Rubinius::Debugger.start
debug> b Object#foo:5
| Set breakpoint 1: test.rb:5 (+4)
debug> c

| Breakpoint: Object#foo at test.rb:5 (4)
| 5:   b = 2
debug> exit
$
```

Now it works.

We can also make it work by not running enough iterations to provoke the JIT -
change 10_000_000 to 1.

```
$ rubinius/bin/ruby test.rb 

| Breakpoint: Object#__script__ at test.rb:13 (37)
| 13: Rubinius::Debugger.start
debug> b Object#foo:5
| Set breakpoint 1: test.rb:5 (+4)
debug> c

| Breakpoint: Object#foo at test.rb:5 (4)
| 5:   b = 2
debug> exit
$
```

**Comment by chrisseaton** [comment]
This doesn't apply now that Rubinius doesn't have a JIT, so closing.

**Comment by brixen** [comment]
@chrisseaton the new interpreter / JIT won't use the old mechanism anyway, so this wouldn't apply. Thanks for closing.
