### ISSUE TITLE
File.writable? does not consider extended ACL

### ISSUE THREAD

**Issue by quark-zju** [rubinius/rubinius#2943]
Steps to reproduce:

``` bash
setfacl -R -m u:`whoami`:rwX /opt/rubies/rbx-2.2.5/gems
```

``` ruby
File.writable?('/opt/rubies/rbx-2.2.5/gems') # => false, while MRI returns true.
```

Versions:
- rubinius 2.2.5 (2.1.0 e543ba32 2014-02-08 JI) [x86_64-linux-gnu]
- Debian 7.4 amd64

I use `setfactl` to grant users in `rubygems` group write ability to rubygems directories. This issue makes bundler believe I do not have writable access and ask sudo password every time.

If people are busy with other issues, I can try to look into this when I am free (probably several weeks later).

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
