### ISSUE TITLE
Move verify_build_signature/RedCard checks into a task

### ISSUE THREAD

**Issue by postmodern** [rubinius/rubinius#2950]
Having the `verify_build_signature or $cleaning` and `RedCard.check` in the top-level of the Rakefile makes debugging broken/outdated builds a pain. I had to manually remove these checks just to run `rake -T` and `rake -P`. Instead, these should be moved into a `check` task.

**Comment by brixen** [comment]
Once the Ruby dependency to build is removed, this won't be necessary as the artifacts will be deterministically built from source and configuration variables without dependence on other components.
