### ISSUE TITLE
unexpected ArgumentError in curried Proc

### ISSUE THREAD

**Issue by headius** [rubinius/rubinius#2951]
This issue is copied from jruby/jruby#1523 and reported here as a courtesy since JRuby and Rubinius share the same Proc#curry implementation. The fix there should apply to Rubinius as well.

--

[This Travis run](https://travis-ci.org/phluid61/mug/jobs/19374153) shows an unexpected ArgumentError in `Proc#call` after sequential calls to `#curry` and `#call`

Effective code is:
```ruby
l = lambda{|a,b,c| a+b+c }
l1 = l.curry.call(1)
l2 = l1.curry.call(2)
l2.curry.call(3) #=> 6
l1.curry.call(2,3) #=> ArgumentError
```

**Comment by YorickPeterse** [comment]
Still occurs as of 4417909e57f781fc14f6dda55964c5f34696f9c2.
