### ISSUE TITLE
rbx gem install nokogiri hangs

### ISSUE THREAD

**Issue by undying** [rubinius/rubinius#2958]
when I`m trying to install nokogiri gem, installation process hangs with such strace:

```
mprotect(0x7f9137400000, 6291456, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f9137a00000, 6291456, PROT_READ|PROT_WRITE) = 0
mprotect(0x7f9137a00000, 6291456, PROT_NONE) = 0
mprotect(0x7f9137400000, 6291456, PROT_READ|PROT_WRITE) = 0
futex(0x2ed8eec, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x2ed8ee8, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x2e7c304, FUTEX_CMP_REQUEUE_PRIVATE, 1, 2147483647, 0x2e7c2d0, 426) = 1
futex(0x2e7c2d0, FUTEX_WAKE_PRIVATE, 1) = 1
```

but when I`m using --no-doc key
```
 rbx gem install nokogiri --no-doc 
```
installation ends successfully

rubinius 2.2.5.n55 (2.1.0 5cffe7b0 2014-02-24 JI) [x86_64-linux-gnu]

Linux kron 3.13.2-gentoo #1 SMP Fri Feb 14 15:14:06 MSK 2014 x86_64 Intel(R) Core(TM) i7-2677M CPU @ 1.80GHz GenuineIntel GNU/Linux

**Comment by YorickPeterse** [comment]
Does this problem still occur on Rubinius 2.5.2?

**Comment by shanetmoore** [comment]
Seems to work on 2.5.2.

```
➜  ~  gem install nokogiri --no-rdoc --no-ri
Building native extensions.  This could take a while...
gem install nokogiriSuccessfully installed nokogiri-1.6.6.2
1 gem installed
```

```
➜  ~  gem install nokogiri
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.6.2
Parsing documentation for nokogiri-1.6.6.2
Done installing documentation for nokogiri after 2 seconds
1 gem installed
```

```
➜  ~  ruby -v
rubinius 2.5.2 (2.1.0 7a5b05b1 2015-01-30 3.4 JI) [x86_64-linux-gnu]
```

**Comment by YorickPeterse** [comment]
@shanetmoore Thanks for looking into this. 

@chaitanyav @undying: could you confirm if this is indeed working for you using 2.5.2/2.5.3?

**Comment by chaitanyav** [comment]
@YorickPeterse 

It works 

    ~/Downloads/rubinius-2.5.3/rubinius/bin  ᐅ ./gem install nokogiri
    Fetching: mini_portile-0.6.2.gem (100%)
    Successfully installed mini_portile-0.6.2
    Fetching: nokogiri-1.6.6.2.gem (100%)
    Building native extensions.  This could take a while...
    Successfully installed nokogiri-1.6.6.2
    2 gems installed


    ~/Downloads/rubinius-2.5.3/rubinius/bin  ᐅ ./ruby -v
    rubinius 2.5.3 (2.1.0 2482b093 2015-04-29 3.5.1 JI) [x86_64-darwin14.3.0]

**Comment by YorickPeterse** [comment]
Sweet, thanks. In that case I'll close this issue, feel free to re-open if the issue re-occurs.
