### ISSUE TITLE
Fatal error in libpthread

### ISSUE THREAD

**Issue by mighe** [rubinius/rubinius#2964]
We're developing the concurrent-ruby gem and we got a fatal error during in our travis-ci tests:

```
CRASH: A fatal error has occurred.
Backtrace:
/home/travis/.rvm/rubies/rbx-2.2.5/bin/rbx[0x596c50]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xfcb0)[0x7f6d62e9fcb0]
```

See https://travis-ci.org/jdantonio/concurrent-ruby/jobs/19947637

**Comment by YorickPeterse** [comment]
Closing this issue, if the problem still persists (or re-surfaces) feel free to re-open this issue.
