### ISSUE TITLE
gem install couchbase raises error

### ISSUE THREAD

**Issue by weemanjz** [rubinius/rubinius#2966]
When I'm trying to install couchbase gem I get the following error
https://gist.github.com/weemanjz/4ab4c2a33adf7b1a0c32

rubinius 2.2.5 (2.1.0 e543ba32 2014-02-08 JI) [x86_64-linux-gnu]
Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux

**Comment by YorickPeterse** [comment]
The following snippet from the log seems to be the culprit:

```
gethrtime.c: In function ‘gethrtime’:
gethrtime.c:86:5: warning: implicit declaration of function ‘clock_gettime’ [-Wimplicit-function-declaration]
gethrtime.c:86:23: error: ‘CLOCK_MONOTONIC’ undeclared (first use in this function)
gethrtime.c:86:23: note: each undeclared identifier is reported only once for each function it appears in
In file included from /home/weeman/.rvm/rubies/rbx-2.2.5/vm/include/capi/ruby/backward/st.h:2:0,
                 from couchbase_ext.h:22,
                 from gethrtime.c:18:
````

Does this still occur when using Rubinius 2.5.2?

**Comment by weemanjz** [comment]
There is a different error now:
https://gist.github.com/weemanjz/716bb24e5dca567925ce

**Comment by YorickPeterse** [comment]
This is caused by the following: https://github.com/couchbase/couchbase-ruby-client/blob/1d17825f0352f42ccc59f17ab3003d349807fccb/ext/couchbase_ext/couchbase_ext.h#L77-L79

This can probably be solved by adding a `#define HAVE_TYPE_ST_INDEX_T 1` somewhere in our C CAPI.

**Comment by brixen** [comment]
In general, the MRI C-API for Rubinius is deprecated, but that doesn't mean it will be going anywhere soon. Compatibility for C-extensions will continue to be evaluated on a case-by-case basis. However, C-extensions that depend on functions that examine or manipulate built-in MRI data structures will never be supported.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated.
