### ISSUE TITLE
Crash on external command and puma

### ISSUE THREAD

**Issue by davbeck** [rubinius/rubinius#3002]
rbx is crashing, consistently, at 2 places in my rails app. One is when Paperclip is used, and the other is when ffmpeg is used. It would appear that they are both crashing when an external command (ImagMagick or ffmpeg) is called. Unfortunately, I'm not seeing much of a backtrace. The weird thing is, from console, and running locally on my machine, both of those work just fine.

https://gist.github.com/anonymous/961047875d2c564dca50

**Comment by kayakyakr** [comment]
I believe this is the issue that I am running into as well. Having to run puma outside of clustered mode, which is less than ideal for a larger server.

**Comment by brixen** [comment]
@kayakyakr what version of Rubinius, what version of Puma? Gist of a log or terminal output?

**Comment by kayakyakr** [comment]
Currently upgrading puma & rbx. Was rbx-2.2.10, puma 2.9. Log won't help much, it's failing silently after calling the "file" command.

**Comment by kayakyakr** [comment]
Still occurs on rbx-2.5.2, puma 2.11.

The last line of my log reads:
> I, [2015-05-12T11:52:15.417241 #1266]  INFO -- : Command :: file -b --mime '/tmp/9226b33158f36f9d30d41e12224c037c20150512-1266-1dpix8u.pdf'

The only other related log file is with nginx:
> 2015/05/12 13:48:07 [error] 788#0: *32 upstream prematurely closed connection while reading response header from upstream, client: , server: _, request: "POST / HTTP/1.1", upstream: "http://0.0.0.0:8080", host: "", referrer: ""

Swap workers from 2 to 0, it works, but any sort of clustered mode and it does not.

@davbeck suggested up above to test with the paperclip example app, and that should continue to be true.

**Comment by YorickPeterse** [comment]
@kayakyakr If there's an actual system crash you should be able to find crash info in the Rubinius log file, which is by default located in `/tmp` (usually called something like `/tmp/rbx-USERNAME.log`).

**Comment by kayakyakr** [comment]
Nothing in rbx log. Doesn't seem to be a system crash.

**Comment by brixen** [comment]
@kayakyakr 2.5.3 is the latest, please use that to check.

**Comment by brixen** [comment]
@kayakyakr also, the default location for the Rubinius log on Linux is `/tmp/rbx-$USER.log` where `$USER` is the name of the user executing the Rubinius process. Please check that file exists and gist the contents when running your test.

**Comment by kayakyakr** [comment]
2.5.3 hasn't hit RVM and I've spent too much time on this already. I'll let rvm catch up and try it again later.

**Comment by YorickPeterse** [comment]
@kayakyakr I'm fairly sure you can install new Ruby versions that aren't explicitly defined yet in RVM, though I might be confusing this with ruby-install.

**Comment by kayakyakr** [comment]
Again, too much time already spent on this issue. Found a workaround and moved on. Will come back to it eventually. Sorry guys, can't be your guinea pig today.

**Comment by tmornini** [comment]
@kayakyakr So you know, @brixen put a ton of work into in 2.5.3 fixing issues in this general neighborhood. Giving this a spin when you have a chance would be very, very useful.

Have a great day.

**Comment by kayakyakr** [comment]
Will do. Just didn't have time to do more today. Appreciate that I've got 3 owners/collaborators messaging me about it.

**Comment by tmornini** [comment]
We all appreciate what a PITA it is doing a great job like you're doing here.

Thanks again.

**Comment by kayakyakr** [comment]
Good news guys: early returns say 2.5.3 seems to be behaving as expected. Worked in staging. Going to deploy to production, see if the same can be said.

**Comment by kayakyakr** [comment]
And production is working. Thanks for fixing the issue before I even knew I had it!

**Comment by brixen** [comment]
@kayakyakr great to hear and your help is much appreciated! I'll take a look at the Paperclip repro as well.

Thanks for your words of encouragement, @tmornini.

**Comment by brixen** [comment]
I can repro the issue described with Paperclip, looking into it.

**Comment by tmornini** [comment]
@brixen I'm always happy to help

**Comment by brixen** [comment]
Much of the internals of Rubinius have been completely or mostly rewritten in the past couple years. This includes the garbage collector, concurrency facilities, Fibers, much of the instruction set, and a migration away from "primitive" functions that implement Ruby features.

Since a number of segfaults or process hangs have occurred in these features over time, this issue may be fixed.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once these capabilities are more robust, it will be possible to more efficiently debug and fix any process crashes.

Other than these core capabilities, PRs to fix any specific issue are always welcome.
