### ISSUE TITLE
Return from eigenclass does not unroll properly

### ISSUE THREAD

**Issue by headius** [rubinius/rubinius#3010]
When an eigenclass body appears in a method, returns from that body should return from the method.

```
system ~/projects/jruby $ rvm rbx-2.1.1 do ruby -e 'def foo; p 1; class << self; return; p 2; end; p 3; end; foo'
1
3

system ~/projects/jruby $ rvm ruby-2.1.1 do ruby -e 'def foo; p 1; class << self; return; p 2; end; p 3; end; foo'
1
```

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
