### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by ghazel** [rubinius/rubinius#3014]
```
$ ruby --version
rubinius 2.2.6 (2.1.0 68d916a5 2014-03-10 JI) [x86_64-linux-gnu]
```

https://gist.github.com/anonymous/701ea4731abc5f5dd874

**Comment by brixen** [comment]
This looks SSL related, too. See https://github.com/rubinius/rubinius/issues/3025#issuecomment-360588992
