### ISSUE TITLE
tr and tr_s do not have consistent results with MRI in some situation, and sometimes they will be broken.

### ISSUE THREAD

**Issue by funal125** [rubinius/rubinius#3015]
- Inconsistent result

```
MRI, 2.1.1
[13] pry(main)> 'abc'.tr_s('^c','我')
=> "我c"

rbx-2.2.6
[40] pry(main)> 'abc'.tr_s('^c','我')
=> "\xE6c"
```
- Crash

```
MRI, 2.2.1
[2] pry(main)> '我abc'.tr_s('我b','我')
=> "我a我c"

rbx-2.2.6
pry(main)> '我abc'.tr_s('我b','我')
NoMethodError: undefined method `>=' on nil:NilClass.
from kernel/delta/kernel.rb:78:in `>= (method_missing)'
```
- But i found MRI did have some bugs. Check the following example

```
[14] pry(main)> 'abc'.tr('^c','我')
=> "\u0011\u0011c"
[15] pry(main)> 'abc'.tr_s('^c','我')
=> "我c"
```

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
