### ISSUE TITLE
Some methods in string should not use the same algorithm for multibye and singlebye character

### ISSUE THREAD

**Issue by funal125** [rubinius/rubinius#3019]
After revewing some code in string.rb. I found some method, like delete, mix the multibye and singlebye together. It will leads some problem obscure. Here is an example:

In rbx-2.2.6:
[3] pry(main)> a = '我 love you'
=> "我 love you"
[4] pry(main)> a.delete '戒'
=> "\x91 love you"

In ruby-2.1.1
 a = '我 love you'
=> "我 love you"
[2] pry(main)> a.delete '戒'
=> "我 love you"

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
