### ISSUE TITLE
Incorrect return value for splat assignment with many post-splat variables

### ISSUE THREAD

**Issue by thomasbrus** [rubinius/rubinius#3037]
Came across another issue, related to #3030:

On MRI

```ruby
arr = [1, 2, 3, 4, 5]
*a, b, c, d = *arr # => [1, 2, 3, 4, 5]
arr # => [1, 2, 3, 4, 5]
```

On Rubinius 2.2.7 (also on 2.2.6)

```ruby
arr = [1, 2, 3, 4, 5]
*a, b, c, d = *arr # => [1, 2]
arr # => [1, 2]
```

The reason for this seems to be that `Array#pop` is called for each of the post-splat variables (b, c, d). Thus the resulting value of `arr` is [1, 2].

By the way, if I were to make any chances to rubinius-ast, how could I test those locally? Do I have to recompile/rebuild rubinius each time to test behavior like in this issue? Thanks in advance:)

**Comment by YorickPeterse** [comment]
This seems to have been resolved since:

```
~ $ chruby rbx-git
~ $ irb
irb(main):001:0> arr = [1, 2, 3, 4, 5]
=> [1, 2, 3, 4, 5]
irb(main):002:0> *a, b, c, d = *arr
=> [1, 2, 3, 4, 5]
irb(main):003:0> arr
=> [1, 2, 3, 4, 5]
irb(main):004:0> RUBY_DESCRIPTION
=> "rubinius 3.11.c9 (2.2.0 7489a077 2016-01-22 3.5.2 JI) [x86_64-linux-gnu]"
```
