### ISSUE TITLE
rand doesn't seem to provide random number for a large enough limit

### ISSUE THREAD

**Issue by amcvega** [rubinius/rubinius#3053]
Here a simple test case:

``` ruby
lim = 10_000_000_000

n = 20

n.times do
  puts(rand(-lim..lim))
end

```

When running this I get the following result:

```
➜  ruby  ruby -v
rubinius 2.2.7 (2.1.0 build 2014-05-20 JI) [x86_64-linux-gnu]
➜  ruby  ruby rand_test.rb
-7070295185
-8125147908
-8121139205
-7451964937
-6577447939
-5772150821
-7194078241
-7602959499
-5708188417
-7475948625
-8837396483
-8030807045
-9131948099
-5923144705
-7866147877
-6244574765
-8406312067
-5944828947
-5706409491
-5845923337

```

I expected to at least get at least a few positive numbers approximately half the time but every time I run the script, it just gives me negative numbers. When I run the script with a limit of 1_000_000_000 or less, it seems to behave as expected.

Here's the same test under MRI 2.1.1

```
➜  ruby  ruby -v
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]
➜  ruby  ruby rand_test.rb
-3295874603
-2803158131
7627272990
-1816902097
-1006118531
135277851
9486712478
-6746449458
5020077110
4254455872
-6182422574
7043240492
-3920015767
6209470698
-6022382948
9299149416
809718185
-1115886247
-3254854560
9966790586

```

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
