### ISSUE TITLE
Advice on gathering VM stats for Rubinius

### ISSUE THREAD

**Issue by jasonrclark** [rubinius/rubinius#3055]
The last couple versions of New Relic's Ruby agent (http://github.com/newrelic/rpm) have included a new feature to track VM stats. I'd love to hear from the Rubinius team about how we can improve coverage on those metrics.

At this point RPM's UI responds to a certain set of metrics, so the simplest bet for improving things is to fill in the gaps of what's gathered between MRI and Rubinius.

On the positive side, here's what we get out of the box on Rubinius today (code at https://github.com/newrelic/rpm/blob/master/lib/new_relic/agent/vm/rubinius_vm.rb):

```
:gc_runs        => GC.count
:major_gc_count => gc_stats[:full][:count]
:minor_gc_count => gc_stats[:young][:count]
:thread_count   => Thread.list.size
:total_memory   => Gathered for process by same mechanism between MRI and Rubinius
```

On MRI we also gather the following. If there's any way to get an equivalent number, those are easy for us to add in:

```
:gc_total_time          => Time spent in GC (calculated by our monotonic GC profiler given GC::Profiler's need for frequent resets https://github.com/newrelic/rpm/blob/master/lib/new_relic/agent/vm/monotonic_gc_profiler.rb)
:heap_live              => GC.stat[:heap_live_slot] (:heap_live_num on 2.0.0)
:heap_free              => GC.stat[:heap_live_slot] (:heap_live_num on 2.0.0)
:total_allocated_object => GC.stat[:total_allocated_object]

:method_cache_invalidations   => RubyVM.stat[:global_method_state]
:constant_cache_invalidations => RubyVM.stat[:global_constant_state]
```

While it's certainly more work, I'm also interested in hearing what other information for VM tuning might be valuable to gather.

**Comment by YorickPeterse** [comment]
Closing this since the agent now does track a whole slew of Rbx metrics.
