### ISSUE TITLE
Process.spawn incomplete? (error in exec.js)

### ISSUE THREAD

**Issue by fwoeck** [rubinius/rubinius#3060]
With the current exec.js I see this error. @josh mentioned, that it might be due to an incomplete implementation of Process.spawn https://github.com/sstephenson/execjs/issues/148

The "{err: [:child, :out]}" in lib/execjs/external_runtime.rb#125

```
output = sh(binary.split(' ') + [filename, {err: [:child, :out]}])
```

causes a

```
TypeError: Coercion error: :child.to_str => String failed
  (in /opt/dokmatic1/app/assets/javascripts/emberapp.js.coffee)
kernel/common/type.rb:26:in `execute_coerce_to'
kernel/common/type.rb:19:in `coerce_to'
kernel/common/kernel.rb:147:in `StringValue'
kernel/common/type.rb:339:in `coerce_to_path'
kernel/common/file.rb:1112:in `initialize'
kernel/alpha.rb:94:in `new'
kernel/common/io.rb:624:in `open'
kernel/common/process.rb:218:in `setup_redirects'
kernel/common/hash.rb:342:in `each'
kernel/common/process.rb:211:in `setup_redirects'
kernel/common/io.rb:810:in `popen'
```

when run with rubinius 2.2.7. This doesn't happen when I simply remove the hash:

```
output = sh(binary.split(' ') + [filename])
```

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
