### ISSUE TITLE
Minitest 4.7.5 test suite fails one test with rubinius 2.2.7

### ISSUE THREAD

**Issue by graaff** [rubinius/rubinius#3062]
Trying to run the minitest 4.7.5 test suite with rubinius 2.2.7 (2.1.0 build 2014-05-20 JI) [x86_64-linux-gnu] gives me this error:

```
  1) Error:
TestMiniTestMock#test_mock_args_does_not_raise:
NoMethodError: unmocked method :equal?, expected one of []
    kernel/common/kernel.rb:195:in `==='
    kernel/common/enumerable.rb:304:in `all?'
    kernel/bootstrap/array.rb:76:in `each'
    kernel/common/enumerable.rb:304:in `all?'
    /var/tmp/portage/dev-ruby/minitest-4.7.5-r1/work/rbx/minitest-4.7.5/test/minitest/test_minitest_mock.rb:72:in `test_mock_args_does_not_raise'
    kernel/common/enumerable.rb:49:in `collect'
    kernel/bootstrap/proc.rb:20:in `call'
    kernel/bootstrap/thread.rb:391:in `__run__'
```

Tests were run with "rbx -Ilib:bin:test:. -S testrb test"

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
