### ISSUE TITLE
$stdout.reopen and Open3.popen3 incompatible with MRI

### ISSUE THREAD

**Issue by keroami** [rubinius/rubinius#3063]
The code below has a different result on MRI (1.8 up to and including 2.1) compared to Rubinius (git master 2f4ebeb2c, somewhat beyond 2.2.7). In the former, the contents of the file "stdout" are:
```
in order:
First line
Last line
```
For rubinius the contents are:
```
Last line
First line
```

```ruby
require 'open3'
$stdout.reopen File.new("stdout", "w+")
puts "in order:"
puts "First line"
Open3.popen3("ls") {|stdin, stdout, err|  }
puts "Last line"
```

**Comment by YorickPeterse** [comment]
This appears to have been resolved in the mean time, closing.
