### ISSUE TITLE
Crash when working with fibers

### ISSUE THREAD

**Issue by jolisper** [rubinius/rubinius#3065]
https://gist.github.com/anonymous/8aa4fadf93566f6b3bf8

rbx -v: rubinius 2.2.6 (2.1.0 68d916a5 2014-03-10 JI) [x86_64-linux-gnu]
rvm -v: rvm 1.25.26 (stable)

Create several fibers and put it in an array, iterate the array and resume one fiber per iteration.

**Comment by tak1n** [comment]
This error doesn't occure anymore.
Tried to run the specified benchmark and it worked.

Reopen if you still have this issue.
