### ISSUE TITLE
Add support for :blocking=>true with Rubinius::FFI::Library#attach_function

### ISSUE THREAD

**Issue by jemc** [rubinius/rubinius#3074]
I'm trying to use Rubinius::FFI where currently ::FFI is being used, and came across the following compatibility issue:

``` ruby
attach_function :zmq_socket, [:pointer, :int], :pointer, :blocking => true
```

Rubinius::FFI#attach_function says:

> Attach a C function to this module. The arguments can have two forms:
> 
> ``` ruby
>   attach_function c_name, [c_arg1, c_arg2], ret
>   attach_function mod_name, c_name, [c_arg1, c_arg2], ret
> ```
> 
> In the first form, `c_name` will also be used for the name of the module
> method. In the second form, the module method name is `mod_name`.
> 
> The `c_name` and `mod_name` can be given as Strings or Symbols.
> 
> The types of the arguments to the C function, `c_arg1`, `c_arg2`, etc, are
> given as an array even if there is only one.
> 
> The final argument, `ret`, is the type of the return value from the C
> function.

(From https://github.com/rubinius/rubinius/blob/master/kernel/platform/library.rb#L86-L130)

It appears Rubinius doesn't have a method signature to support the use of keyword arguments / option hashes like `:blocking => true`.

Does Rubinius support making attached functions blocking, and if so, how?  I can submit a PR to make it compatible with that syntax.  If not currently supported, the PR would likely have to get into C++ space...

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
