### ISSUE TITLE
Crash on running bundle

### ISSUE THREAD

**Issue by blackxored** [rubinius/rubinius#3079]
Hangs at installing versionist = 1.3.0
https://gist.github.com/anonymous/44c6af8d1523fffafdbb

**Comment by tak1n** [comment]
Just did `gem install versionist -v '1.3.0'` and everything was installed fine on rbx 2.5.5

@blackxored Could you please try to reproduce your bug on 2.5.5 or post the Gemfile which caused to crash rbx on bundle install.

**Comment by blackxored** [comment]
I don't have that Gemfile at hand anymore, but this was an albeit old version considering you guys already at 2.5 so you might feel free to close.

**Comment by tak1n** [comment]
Closing this for now, feel free to reopen or open a new issue when having further problems with rbx.
