### ISSUE TITLE
Ferret fails to build C extension

### ISSUE THREAD

**Issue by sempervictus** [rubinius/rubinius#3088]
gem install ferret on HEAD (rubinius 2.2.10.n195 (2.1.0 11af1de8 2014-07-14 JI) [x86_64-linux-gnu]) results in http://pastebin.com/bCUkUzeu
Seems the C extension fails on frb_rb_hash_size. IIRC there are issues with the way some gems implement RHASH and other C runtime based accessors to what in our runtime are pure Ruby structures.

This was discovered while attempting to build Treat for RBX again, Birch still seems to release without @dbussink's patch, though install from git fixes this, but running Treat::Core::Installer.install attempts to install ferret and the fun stops there.

**Comment by brixen** [comment]
In general, the MRI C-API for Rubinius is deprecated, but that doesn't mean it will be going anywhere soon. Compatibility for C-extensions will continue to be evaluated on a case-by-case basis. However, C-extensions that depend on functions that examine or manipulate built-in MRI data structures will never be supported.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated.
