### ISSUE TITLE
Rubinius crash

### ISSUE THREAD

**Issue by neoecos** [rubinius/rubinius#3091]
Hi, using rbx 2.2.10 with rails 3.2.19 with config.threadsafe! this started to happend

https://gist.github.com/fd92b9fd20315e5111fd

**Comment by YorickPeterse** [comment]
@neoecos Any news, can you provide a way to reproduce this?

**Comment by YorickPeterse** [comment]
Closing this due to lack of further feedback. Feel free to re-open if the issue still persists when using the latest version of Rubinius.
