### ISSUE TITLE
Parent process can not get Signal.trap during Process.waitpid

### ISSUE THREAD

**Issue by sonots** [rubinius/rubinius#3097]
I created a small piece of codes to reproduce this issue as belows:

``` ruby
module Fluent
  class Supervisor
    def initialize
      @finished = false
      install_supervisor_signal_handlers
    end

    def start
      puts "Starting #{Process.pid}"
      @main_pid = fork do
        install_main_signal_handlers
        while !@finished
          sleep 1
          puts Process.pid
        end
      end
      # while !@finished
      #   sleep 1
      #   puts Process.pid
      # end
      Process.waitpid(@main_pid)
    end

    def install_supervisor_signal_handlers
      trap :INT do
        puts "fluentd supervisor process get SIGINT"
        @finished = true
      end
    end

    def install_main_signal_handlers
      trap :INT do
        puts "fluentd main process get SIGINT"
        @finished = true
      end
    end
  end
end

Fluent::Supervisor.new.start
```

With this code, sending INT signal to the supervisor process does not trap the INT signal. 

``` bash
$ bundle exec ruby supervisor.rb
Starting 9541
9553
9553
9553
$ kill -INT 9541
# nothing happens. No signal trap
```

Uncommenting the `puts` loop in the supervisor process not to go into `Process.waitpid`, the supervisor process could successfully receive the INT signal. 

``` bash
$ kill -INT 9541
fluentd supervisor process get SIGINT 
```

It seems the parent process can not get `Signal.trap` during `Process.waitpid`. 

rbx version and and os are belows:

```
$ ruby -v 
rubinius 2.2.10.n209 (2.1.0 91884d32 2014-07-28 JI) [x86_64-linux-gnu]
$ uname -a
Linux vagrant-centos62-64 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
CentOS release 6.5 (Final)
```

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
