### ISSUE TITLE
Add support for MCJIT

### ISSUE THREAD

**Issue by southerngs** [rubinius/rubinius#3098]
I read on the [LLVM mailing list](http://article.gmane.org/gmane.comp.compilers.llvm.devel/75175) that support for the old JIT interface is being removed from mainline LLVM code.

I know that #2867 mentions adding support for MCJIT within the context of supporting ARM.  However, I thought it might make sense to have an issue for tracking conversion to MCJIT for existing architectures.

**Comment by YorickPeterse** [comment]
Closing this in favour of pull request https://github.com/rubinius/rubinius/pull/3367.
