### ISSUE TITLE
Handle different library names for linking llvm shared between autotools build and cmake build

### ISSUE THREAD

**Issue by darix** [rubinius/rubinius#3103]
a3d10bf7 introduced

```
["-lLLVM-#{Rubinius::BUILD_CONFIG[:llvm_version]}"]
```

for linking the shared library version of llvm. This seems only to be the valid library name with the autotools based build of llvm. When using the cmake based build you get the same filenames as with the static build just with .so instead of .a.

currently I use the following patch:

```
Index: rakelib/blueprint.rb
===================================================================
--- rakelib/blueprint.rb.orig   2014-04-24 16:32:55.000000000 +0200
+++ rakelib/blueprint.rb        2014-07-30 15:12:38.676286173 +0200
@@ -223,7 +223,8 @@ Daedalus.blueprint do |i|
     ldflags = `#{conf} --ldflags`.strip.split(/\s+/)

     if Rubinius::BUILD_CONFIG[:llvm_shared]
-      objects = ["-lLLVM-#{Rubinius::BUILD_CONFIG[:llvm_version]}"]
+      # objects = ["-lLLVM-#{Rubinius::BUILD_CONFIG[:llvm_version]}"]
+      objects = `#{conf} --libs`.strip.split(/\s+/)
     else
       objects = `#{conf} --libfiles`.strip.split(/\s+/)
     end
```

In the discussion we came to the conclusions:
1. open bug against llvm-config to set proper value for llvm-config --libs in the autotools build. (FTR: heftig runs on arch linux)
2. implement a fall through check:
   - test if we can link with "-lLLVM-#{Rubinius::BUILD_CONFIG[:llvm_version]}"
   - if that fails, test if we can link with the output of llvm-config --libs.
   - barf if we still dont know how to link llvm.
   - falling back to the static linking when the user requested shared linking would be bad.

**Comment by brixen** [comment]
This is probably fixed. Rubinius will only support the current version of LLVM and will build without JIT support when LLVM is not available.
