### ISSUE TITLE
compile problem with 2.2.10 and -fno-rtti

### ISSUE THREAD

**Issue by bchill** [rubinius/rubinius#3113]
OS: CentOS 5.10
Ruby: 2.1.2
Rubinus: 2.2.10

Since rubinus is no longer supposed to require RTTI, I don't understand this error. Is this related to the older gcc/g++ on CentOS 5?

Brian

---

$ rake 
.
.
.
Running 193 tasks using 4 parallel threads
1: CXX vm/arguments.cpp
2: CXX vm/agent_components.cpp
3: CXX vm/agent.cpp
4: CXX vm/accessor_primitives.cpp
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/tr1/functional: In static member function ‘static bool std::tr1::_Function_base::_Base_manager<_Functor>::_M_manager(std::tr1::_Any_data&, const std::tr1::_Any_data&, std::tr1::_Manager_operation)’:
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/tr1/functional:904: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/tr1/functional: In static member function ‘static bool std::tr1::_Function_base::_Ref_manager<_Functor>::_M_manager(std::tr1::_Any_data&, const std::tr1::_Any_data&, std::tr1::_Manager_operation)’:
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/tr1/functional:982: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/tr1/functional_iterate.h: In static member function ‘static bool std::tr1::_Function_handler<void ()(), _Member _Class::*>::_M_manager(std::tr1::_Any_data&, const std::tr1::_Any_data&, std::tr1::_Manager_operation)’:
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/tr1/functional_iterate.h:572: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/tr1/functional_iterate.h: In member function ‘const std::type_info& std::tr1::function<_Res ()()>::target_type() const’:
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/tr1/functional_iterate.h:883: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/tr1/functional_iterate.h: In member function ‘_Functor\* std::tr1::function<_Res ()()>::target()’:
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/tr1/functional_iterate.h:892: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/tr1/functional_iterate.h: In member function ‘const _Functor\* std::tr1::function<_Res ()()>::targe
.
.
.

**Comment by tak1n** [comment]
@bchill can you please retry with rbx 2.5.5?

**Comment by brixen** [comment]
Rubinius currently only supports Clang as a compiler. When using Clang, it's important to only use the Clang stdlib or the GCC stdlib but _never_ mix use of the two (see the note here https://book.rubinius.com/manuscript/getting_rubinius.html#ubuntudebian).
