### ISSUE TITLE
Could not open library sqlite3_native.so (sequel gem)

### ISSUE THREAD

**Issue by jackdesert** [rubinius/rubinius#3115]
I am porting my application from MRI to Rubinius. My application is called "daily_lager", and here are the steps to pull down the source and attempt to run it under rubinius. Unfortunately, it seems to be breaking on something to do with sqlite3_native.so.

    $ git clone git@github.com:jackdesert/daily_lager
    $ cd daily_lager
    $ git checkout rubinius
    $ rbenv local rbx-2.2.7
    $ bundle
    $ bundle exec rackup config-daily_lager.ru
    An exception occurred running /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/bin/rackup:

        LoadError::InvalidExtensionError: Could not open library /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/sqlite3-1.3.9/lib/sqlite3/sqlite3_native.so - /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/sqlite3-1.3.9/lib/sqlite3/sqlite3_native.so: undefined symbol: sqlite3_column_database_name (Sequel::AdapterNotFound)

    Backtrace:

               Rubinius::NativeMethod.load_extension at kernel/common/native_method.rb:26
                   Rubinius::CodeLoader#load_library at kernel/delta/code_loader.rb:234
                        Rubinius::CodeLoader#require at kernel/common/code_loader.rb:130
                        Rubinius::CodeLoader.require at kernel/common/code_loader.rb:237
                              Kernel(Object)#require at kernel/common/kernel.rb:705
                                  Object#__script__ at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/sqlite3-1.3.9/lib
                                                       /sqlite3.rb:6
                        Rubinius::CodeLoader.require at kernel/common/code_loader.rb:243
                              Kernel(Object)#require at kernel/common/kernel.rb:705
                                  Object#__script__ at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/sequel-4.13.0/lib/sequel
                                                       /adapters/sqlite.rb:1
                        Rubinius::CodeLoader.require at kernel/common/code_loader.rb:243
                               Kernel(Class)#require at kernel/common/kernel.rb:705
                      Sequel::Database.load_adapter at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/sequel-4.13.0/lib/sequel
                                                       /database/connecting.rb:97
                     Sequel::Database.adapter_class at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/sequel-4.13.0/lib/sequel
                                                       /database/connecting.rb:26
                           Sequel::Database.connect at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/sequel-4.13.0/lib/sequel
                                                       /database/connecting.rb:46
                                     Sequel.connect at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/sequel-4.13.0/lib/sequel
                                                       /core.rb:95
                                   Object#__script__ at daily_lager.rb:9
                        Rubinius::CodeLoader.require at kernel/common/code_loader.rb:243
                       Kernel(Rack::Builder)#require at kernel/common/kernel.rb:705
             { } in Object(Rack::Builder)#__script__ at config-daily_lager.ru:1
            BasicObject(Rack::Builder)#instance_eval at kernel/common/eval.rb:43
                           Rack::Builder#initialize at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/rack-1.5.2/lib/rack
                                                       /builder.rb:55
                                           Class#new at kernel/alpha.rb:94
                            { } in Object#__script__ at config-daily_lager.ru+9
         Rubinius::BlockEnvironment#call_on_instance at kernel/common/block_environment.rb:53
                                  Kernel(Class)#eval at kernel/common/eval.rb:176
                      Rack::Builder.new_from_string at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/rack-1.5.2/lib/rack
                                                       /builder.rb:49
                           Rack::Builder.parse_file at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/rack-1.5.2/lib/rack
                                                       /builder.rb:40
     Rack::Server#build_app_and_options_from_config at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/rack-1.5.2/lib/rack
                                                       /server.rb:277
                                   Rack::Server#app at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/rack-1.5.2/lib/rack
                                                       /server.rb:199
                           Rack::Server#wrapped_app at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/rack-1.5.2/lib/rack
                                                       /server.rb:314
                                 Rack::Server#start at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/rack-1.5.2/lib/rack
                                                       /server.rb:250
                                 Rack::Server.start at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/rack-1.5.2/lib/rack
                                                       /server.rb:141
                                   Object#__script__ at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/gems/rack-1.5.2/bin/rackup:4
                                 Kernel(Object)#load at kernel/common/kernel.rb:447
                                   Object#__script__ at /home/vagrant/.rbenv/versions/rbx-2.2.7/gems/bin/rackup:23
                    Rubinius::CodeLoader#load_script at kernel/delta/code_loader.rb:66
                    Rubinius::CodeLoader.load_script at kernel/delta/code_loader.rb:152
                             Rubinius::Loader#script at kernel/loader.rb:649
                               Rubinius::Loader#main at kernel/loader.rb:825

System details:
Ubuntu 12.04 inside Vagrant on OSX
rubinius installed via `rbenv install`

**Comment by YorickPeterse** [comment]
Any update on this, does this issue still persist using the latest version of Rubinius?

**Comment by YorickPeterse** [comment]
Closing this due to the lack of feedback since my last comment. Feel free to re-open if the issue still persists.
