### ISSUE TITLE
Dont make Errno::EPERM a hardfail in the Process.setrlimit test

### ISSUE THREAD

**Issue by darix** [rubinius/rubinius#3139]
This can happen when you build as non root.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
