### ISSUE TITLE
Configure script can't find LLVM 3.5 shared libs

### ISSUE THREAD

**Issue by caio-s-o** [rubinius/rubinius#3147]
When running configure, I've observed that the script can't find LLVM shared libraries (3.5.0). By checking the script code, it can be seen that it is missing a <b>-std=c++11</b> flag in line 913.

**Comment by YorickPeterse** [comment]
We no longer compile/bundle our own LLVM packages and the build process in various places uses `-std=c++11`. Closing this issue, feel free to re-open if the problem still persists.
