### ISSUE TITLE
Dir.glob over-matching

### ISSUE THREAD

**Issue by johnmuhl** [rubinius/rubinius#3149]
~~~ sh
touch abc äbc
ruby -e 'p Dir.glob("a*").size'
~~~

MRI and JRuby return 1 but Rubinius returns 2.

**Comment by aidansteele** [comment]
I think I might have an idea about the cause. I get `1` with a case-insensitive HFS+ partition (the default), but `2` with a case-sensitive HFS+ partition. 

Interestingly, globbing on the command line in bash returns both either way (in the case of `$ ls a*`).

**Comment by aidansteele** [comment]
Some more background information:

rbx-2.4.1:
* `ruby -e 'p Dir.glob("A*").size'

**Comment by aidansteele** [comment]
Some more background information:

rbx-2.4.1:
* `ruby -e 'p Dir.glob("A*").size'` => `0` (case-sensitive partition)
* `ruby -e 'p Dir.glob("A*").size'` => `0` (default)

mri-2.2.0:
* `ruby -e 'p Dir.glob("A*").size'` => `0` (case-sensitive partition)
* `ruby -e 'p Dir.glob("A*").size'` => `1` (default)

It appears that MRI is sensitive to case (but not diacritics) on sensitive HFS+.
