### ISSUE TITLE
Some string methods don't support multibyte-character

### ISSUE THREAD

**Issue by ryoqun** [rubinius/rubinius#3156]
The following methods are implemented in C++ without being aware of multi-byte characters. 
- String#count
- String#delete!
- String#dump
- String#tr
- Regexp#escape

I'd rather like to hear opinion: should we extend the existing C++ implementation to support multibyte char or switch to a shiny new Ruby implementation, which will be written by me?

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
