### ISSUE TITLE
require picking up gems outside of bundle

### ISSUE THREAD

**Issue by jasonrclark** [rubinius/rubinius#3164]
Ran into an issue in our CI environment where Rubinius was loading gems that weren't in our `Gemfile`. Here's the simplest duplication I've been able to get to:

1) Uninstall all versions of `activesupport`, `activemodel` and `activerecord`
2) `gem install activerecord`
3) With an empty `Gemfile`:

```
source "https://rubygems.org"
```

4) Run this script:

```
require 'bundler/setup'
Bundler.require

require 'active_record'
puts ActiveRecord::VERSION::STRING
```

With this setup, you see the version printed, despite the fact that `activerecord` is not in our `Gemfile` and shouldn't be able to load.

While in this specific set of steps the script runs, I've also ended up with gems loading seemingly random versions, probably by file-system ordering (for instance [this gist](https://gist.github.com/jasonrclark/7b1220f6153a58fd01bc) where you can see ActiveRecord 4.2 ending up calling into ActiveModel 3.0). That's the main point behind step 1)--getting down to a single version takes the variability out of the test.

For reference, the expected result which I see from MRI is:

```
boo.rb:4:in `require': cannot load such file -- active_record (LoadError)
    from boo.rb:4:in `<main>'
```

If there's anything I can do to help out with this, let me know. Thanks for all you do!

Version information:

```
rbx -v
rubinius 2.2.10 (2.1.0 bf61ae2e 2014-06-27 JI) [x86_64-darwin12.5.0]

uname -a
Darwin Soupy.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64

rbenv --version
rbenv 0.4.0-95-gf71e227

gem --version
2.4.2

bundle --version
Bundler version 1.7.3
```

**Comment by brixen** [comment]
Ruby `require` has been completely rewritten and gems are no longer used for stdlib, so there's no gem loading that is not performed by rubygems itself.

Please open a new issue if the problem exists on 3.94 or later.
