### ISSUE TITLE
Error while updating rubysl-openssl

### ISSUE THREAD

**Issue by weirdpercent** [rubinius/rubinius#3171]
gem_make.out: https://gist.github.com/weirdpercent/566d99252d055be1c266
rbx-2.2.10
Linux vmint 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:31:42 UTC 2014 i686 i686 i686 GNU/Linux

**Comment by YorickPeterse** [comment]
rubysl-openssl was recently updated to the latest version of the code used by MRI, we've also had numerous Rubinius releases since 2.2.10. If you're still experiencing this problem feel free to re-open this issue.
