### ISSUE TITLE
compilation issue on OpenSUSE

### ISSUE THREAD

**Issue by mpapis** [rubinius/rubinius#3176]
followed instructions from README:
- using `rbx-2.3.0.tar.bz2` https://gist.github.com/mpapis/085a0f7fd10d0c07a563
- \+ `clang` https://gist.github.com/mpapis/e6f79c7ef85fe7d08410
- using `master` https://gist.github.com/mpapis/7be0204a6d28ca827d5a

**Comment by brixen** [comment]
In general, Rubinius enthusiastically supports experimentation and welcomes ideas for features that enhance developer ability to create amazing software.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to support more efforts around experimentation.
