### ISSUE TITLE
rbx 2.3 segfaults when installing pry

### ISSUE THREAD

**Issue by diegoviola** [rubinius/rubinius#3177]
System:

Arch Linux x86_64
LLVM 3.5.0
Rubinius 2.3.0 (installed with ruby-install 0.5.0)

Problem:

rbx segfaults when installing pry: https://gist.github.com/d0b072685dc90ab1d8ab

**Comment by tak1n** [comment]
@diegoviola , @YorickPeterse does this still occur on rbx 2.5.5, as the related issue #3230 has been resolved.

`gem install pry --rdoc --ri` works for me on fedora 22 beta

**Comment by brixen** [comment]
The Rubinius JIT is being rewritten from the ground up. To support this effort, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler infrastructure
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to work extensively on making the JIT extremely good.
