### ISSUE TITLE
Rational * BigDecimal coerces into Float

### ISSUE THREAD

**Issue by fengb** [rubinius/rubinius#3181]
MRI:

```
irb(main):001:0> (BigDecimal(1) * Rational(1)).class
=> BigDecimal
irb(main):002:0> (BigDecimal(1) * 0.1).class
=> BigDecimal
```

RBX 2.3.0:

```
irb(main):001:0> (BigDecimal(1) * Rational(1)).class
=> Float
irb(main):002:0> (BigDecimal(1) * 0.1).class
=> Float
```

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
