### ISSUE TITLE
Using cloudapp gem crashes Rubinius 2.2.10

### ISSUE THREAD

**Issue by eerohele** [rubinius/rubinius#3197]
**[Crash report](https://gist.github.com/b4cbaf377897cc64441d)**.

Rubinius installed with [ruby-install](https://github.com/postmodern/ruby-install) by doing:

```bash
ruby-install rbx
```
Version info:

```bash
❯ ruby --version
rubinius 2.2.10 (2.1.0 bf61ae2e 2014-06-27 JI) [x86_64-darwin14.0.0]
```

Steps to reproduce:

```bash
❯ gem install cloudapp
❯ cloudapp ~/Desktop/Screen\ Shot\ 2014-11-11\ at\ 11.16.25.png
```

FWIW, the `cloudapp` gem works fine for me with MRI.

**Comment by YorickPeterse** [comment]
@eerohele I can install the cloudapp Gem fine on Rbx master, can you retry with 2.4.1/master to see if the issue still occurs for you?

**Comment by eerohele** [comment]
@YorickPeterse: Yeah, installing works fine (I introduced some confusion about that above — sorry about that). It's using the gem that causes the crash.

Here's a [Gist with the stack trace on RBX 2.4.1](https://gist.github.com/eerohele/75ecf188767cc425828c), installed with `ruby-install rbx 2.4.1 -i ~/.rubies/rbx-2.4.1 -- --llvm-config /usr/local/Cellar/llvm/3.5.0_2/bin/llvm-config`.

This seems to be a platform-specific issue, because I tried RBX + cloudapp on an Ubuntu virtual machine a while back and it worked fine. This could also be a bug in the gem or one of its dependencies, of course — I can take a better look at the stack trace at some point.

**Comment by YorickPeterse** [comment]
@eerohele Can you run the Gem using `gdb rbx --args `which cloudapp` path/to/some/image`, then get a full backtrace as described in https://github.com/rubinius/rubinius/issues/3245#issuecomment-69229450 ? That would help us pinpoint where exactly it crashes.

**Comment by eerohele** [comment]
@YorickPeterse: I'm quite a bit out of my area of expertise here so I hope I got this even remotely right...

Looks like [gdb has been replaced with lldb](http://stackoverflow.com/a/19554500/825783) since OS X Mavericks. I tried installing gdb by doing `brew install homebrew/dupes/gdb`, but it's apparently [not capable of debugging universal binaries](http://stackoverflow.com/a/20975057/825783). So I tried lldb instead and, using [Apple's documentation](https://developer.apple.com/library/mac/documentation/IDEs/Conceptual/gdb_to_lldb_transition_guide/document/lldb-command-examples.html) as a reference, did this:

```bash
$ lldb rbx -- $(which cloudapp) quicksort.ex
(lldb) r
(lldb) bt all
```

[Here's the output](https://gist.github.com/eerohele/049eee5da9e153188640). I couldn't figure out how to turn logging on in lldb, so I just copy-pasted what appeared in my terminal window.

I'm not sure whether that contains the information you require, though. Does it help?

**Comment by YorickPeterse** [comment]
@eerohele That looks like the correct output, thanks!

**Comment by YorickPeterse** [comment]
Relevant bits:

```
* thread #1: tid = 0x344ab, 0x000000010900efb0 libcrypto.1.0.0.dylib`CRYPTO_get_ex_data + 13, name = 'rbx.ruby.main', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x188)
  * frame #0: 0x000000010900efb0 libcrypto.1.0.0.dylib`CRYPTO_get_ex_data + 13
    frame #1: 0x0000000108f7970d openssl.bundle`ossl_ssl_verify_callback(preverify_ok=0, ctx=0x00007fff5fbed0c0) + 45 at ossl_ssl.c:331
    frame #2: 0x00000001090bfbe6 libcrypto.1.0.0.dylib`X509_verify_cert + 1198
    frame #3: 0x0000000108fe1716 libssl.1.0.0.dylib`ssl_verify_cert_chain + 287
    frame #4: 0x0000000108fc1983 libssl.1.0.0.dylib`ssl3_get_server_certificate + 373
    frame #5: 0x0000000108fc08fa libssl.1.0.0.dylib`ssl3_connect + 1291
    frame #6: 0x0000000108f793d8 openssl.bundle`ossl_start_ssl(self=4329546256, func=0x0000000108fde50d, funcname=0x0000000108f8a2a0, nonblock=0) + 152 at ossl_ssl.c:1266
    frame #7: 0x000000010015fd5c rbx`rubinius::Object* rubinius::NativeMethod::executor_implementation<rubinius::ZeroArguments>(rubinius::State*, rubinius::CallFrame*, rubinius::Executable*, rubinius::Module*, rubinius::Arguments&) [inlined] rubinius::NativeMethod::func(this=<unavailable>, val=<unavailable>) + 15 at native_method.hpp:374
    frame #8: 0x000000010015fd4d rbx`rubinius::Object* rubinius::NativeMethod::executor_implementation<rubinius::ZeroArguments>(rubinius::State*, rubinius::CallFrame*, rubinius::Executable*, rubinius::Module*, rubinius::Arguments&) [inlined] rubinius::ZeroArguments::invoke(state=<unavailable>, env=<unavailable>) + 11 at native_method.cpp:223
    frame #9: 0x000000010015fd42 rbx`rubinius::Object* rubinius::NativeMethod::executor_implementation<rubinius::ZeroArguments>(state=0x0000000101500760, previous=<unavailable>, exec=0x0000000109533878, mod=0x0000000103df63f0, args=<unavailable>) + 1266 at native_method.cpp:710
```

This looks like a problem with rubysl-openssl of sorts, in particular the following function: https://github.com/rubysl/rubysl-openssl/blob/a376d63e66d4fe89e5a84497d94c8447249b0e21/ext/rubysl/openssl/ossl_ssl.c#L325

**Comment by eerohele** [comment]
Can't reproduce with Rubinius 2.5.8 on El Capitan. I'll close this one.
