### ISSUE TITLE
Kernel#proc does not support implicit blocks

### ISSUE THREAD

**Issue by jimmycuadra** [rubinius/rubinius#3202]
In MRI, if you call `Kernel#proc` without a block, but a block was passed to the enclosing method, it will use that block. For example:

``` ruby
def capture_block
  proc
end

capture_block { "I'm a block!" } # => #<Proc:0x007fbf3a381368@(some_file.rb):4>
```

Under Rubinius 2.3.0, the above code results in the following exception:

```
ArgumentError: block required
	from kernel/common/kernel.rb:605:in `proc'
	from (irb):7:in `capture_block'
	from (irb):9
	from kernel/common/block_environment.rb:53:in `call_on_instance'
	from kernel/common/eval.rb:176:in `eval'
	from kernel/common/kernel.rb:478:in `loop'
	from kernel/bootstrap/proc.rb:20:in `call'
	from kernel/common/throw_catch.rb:30:in `catch'
	from kernel/common/throw_catch.rb:8:in `register'
	from kernel/common/throw_catch.rb:29:in `catch'
	from kernel/bootstrap/proc.rb:20:in `call'
	from kernel/common/throw_catch.rb:30:in `catch'
	from kernel/common/throw_catch.rb:8:in `register'
	from kernel/common/throw_catch.rb:29:in `catch'
	from kernel/delta/code_loader.rb:66:in `load_script'
	from kernel/delta/code_loader.rb:152:in `load_script'
	from kernel/loader.rb:645:in `script'
	from kernel/loader.rb:799:in `main'irb(main):010:0>
```

**Comment by jemc** [comment]
For reference, there is talk of deprecating this behavior:
https://bugs.ruby-lang.org/issues/10499

Thanks, @headius :+1:

**Comment by jimmycuadra** [comment]
I'm gonna close this issue since it sounds like this behavior is going to be removed from MRI, and should not be added to Rubinius. Also, I changed the code I was using that helped me discover this, so I don't need it any more myself.

**Comment by brixen** [comment]
@jimmycuadra thanks for letting us know. FWIW, `Proc.new` is equivalent to `proc` according to `ri proc`, so if you really needed this behavior, it's there. Wouldn't be hard to make `proc` behave the same as `Proc.new`. If you're interested, see `core/kernel.rb` and `core/proc.rb`.

**Comment by brixen** [comment]
@jimmycuadra since we already had this behavior and since it's easy to support and supporting it doesn't really affect anything else, I went ahead and fixed it so `proc` is basically `Proc.new`.
