### ISSUE TITLE
Rubinius 2.2.6 build failure with ruby-install

### ISSUE THREAD

**Issue by schneems** [rubinius/rubinius#3207]
Cannot get RBX 2.2.6 to build using `ruby-install`

Here is the full output: https://gist.github.com/schneems/a2d366e5747dc936d6fe

I'm on a mac:

![](https://www.dropbox.com/s/m1ognzhyv0e5ubs/Screenshot%202014-11-12%2020.54.58.png?dl=1)

Any thoughts?

**Comment by istana** [comment]
for those on Linux systems (this is for Debian unstable - replace llvm 4.0 with your version) trying to install Rubinius:

```
sudo apt-get install ncurses-dev
sudo apt-get install lldb-4.0 llvm-4.0 llvm-4.0-dev llvm-4.0-runtime
sudo ln -s /usr/bin/llvm-config-4.0 /usr/bin/llvm-config
rbenv install rbx-3.60
#or some other installer
```
