### ISSUE TITLE
Hang in Sidekiq worker when using `` or system()

### ISSUE THREAD

**Issue by johnmuhl** [rubinius/rubinius#3216]
[Example Sinatra application](/johnmuhl/rubinius-sidekiq)
[Samples of the stalled processes](https://gist.github.com/johnmuhl/b0ff55efa6eb50ff6be8)

After a few requests jobs stop being processed by Sidekiq and further jobs never start.

**Comment by tak1n** [comment]
Does this still occur on 2.5.5 for you?
I tried your example sinatra app and couldn't reproduce the error on 2.5.5

**Comment by johnmuhl** [comment]
Fixed in 2.5.5
