### ISSUE TITLE
NoMethodError: undefined method `to_str' on false:FalseClass in mysql2 gem

### ISSUE THREAD

**Issue by ahwatts** [rubinius/rubinius#3217]
The other day, this app (https://github.com/ahwatts/mogilefs_s3_device), which is essentially a half-implemented WebDAV server that acts as an interface to S3 for our internal file-storage system, got in to a weird state and started throwing a lot of errors with this stack trace: https://gist.github.com/ahwatts/0b6c004d2c1943d4bccb . I suspect one or more of the database connections in our connection pool was broken somehow, because some requests were functioning while others were throwing this error.

It's entirely possible that I'm doing something wrong and unsupported here, but I'm not sure how to trace through the call down to the MySQL extension and then back up to Rubinius, and was wondering if y'all had any insight into this.

Rubinius version:
rubinius 2.2.10 (2.1.0 bf61ae2e 2014-06-27 JI) [x86_64-linux-gnu]

OS uname:
Linux alt-storage1.internal.domain 2.6.32-431.20.3.el6.x86_64 #1 SMP Thu Jun 19 21:14:45 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Stack trace:
https://gist.github.com/ahwatts/0b6c004d2c1943d4bccb

Source code:
https://github.com/ahwatts/mogilefs_s3_device

**Comment by YorickPeterse** [comment]
@ahwatts Could you retry this with Rbx 2.4.1 to see if the issue still persists there?

**Comment by YorickPeterse** [comment]
Closing this due to lack of further feedback. Feel free to re-open if the issue still persists when using the latest version of Rubinius.
