### ISSUE TITLE
Ensure the tests for these projects run on Travis

### ISSUE THREAD

**Issue by jc00ke** [rubinius/rubinius#3221]
Let's list them out here and then work on a dashboard. We should incorporate #2006 and #2121 in the dashboard.
- [ ] sidekiq
- [ ] celluloid
- [ ] suckerpunch
- [ ] Rails
  - [ ] ActiveSupport
  - [ ] ActionMailer
  - [ ] ActionPack
  - [ ] ActionView
  - [ ] ActiveJob
  - [ ] ActiveModel
  - [ ] ActiveRecord
- [ ] [New Relic RPM](https://github.com/newrelic/rpm) (blocked by https://github.com/newrelic/rpm/pull/197)
- [ ] [Psych](https://github.com/tenderlove/psych)
- [ ] [rspec-mocks](https://github.com/rspec/rspec-mocks) (and others)

**Comment by YorickPeterse** [comment]
Added Rails & friends to the list.

**Comment by YorickPeterse** [comment]
Added psych to the list.

**Comment by YorickPeterse** [comment]
Added rspec-mocks to the list after talking to @samphippen. He mentioned the rspec team would like for rspec to pass on Rbx/Travis but they're currently having some issues with it. Travis failures:

https://travis-ci.org/rspec/rspec-mocks/jobs/48813684
https://travis-ci.org/rspec/rspec-core/jobs/48852957

Interesting enough some specs that fail on MRI seem to pass on Rubinius (e.g. `./spec/rspec/mocks/matchers/receive_messages_spec.rb`).

**Comment by bjfish** [comment]
This dashboard is a very early WIP:
https://github.com/bjfish/rubinius-gem-dashboard

but it does provide at a glance the gems listed above

**Comment by bjfish** [comment]
Add PR for Psych https://github.com/tenderlove/psych/pull/224

**Comment by bjfish** [comment]
New Dashboard http://bjfish.github.io/rubinius-gem-build-status/

**Comment by brixen** [comment]
Rubinius encourages people to experiment with existing Ruby projects, but migrating from MRI is not an activity that has been very successful in the past.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to better support people interested in trying to run their existing projects on Rubinius.
