### ISSUE TITLE
TCPSocket is missing local_address method

### ISSUE THREAD

**Issue by hassan** [rubinius/rubinius#3227]
```
2.1.0 (main):0 > TCPSocket.open("localhost","80"){ |s| p s.local_address }
NoMethodError: undefined method `local_address' on an instance of TCPSocket.
```

In MRI, local_address is implemented in BasicSocket, and returns an Addrinfo object.

Discovered trying to run the 'bunny' (RabbitMQ client) specs but all you need to reproduce is the one-liner above (specifying a port with something listening on it, of course).

**Comment by godfat** [comment]
Just run into this. Here's the ticket for reference:
https://github.com/rubysl/rubysl-socket/issues/7
