### ISSUE TITLE
I/O calls do not invalidate `String#ascii_only?` cache

### ISSUE THREAD

**Issue by FooBarWidget** [rubinius/rubinius#3236]
`String#ascii_only?` has a cache, but I/O calls that modify the string do not invalidate this cache. Here is the simplest test case:

```
a, b = IO.pipe
a.binmode
b.binmode
b.write("\xE2\x9C\x93")
b.close

buf = "".force_encoding("binary")
p buf.ascii_only?  # should be true
a.read(1, buf)
p buf.ascii_only?  # should be false
```

Rubinius 2.2.10 returns true, true. MRI returns true, false.

Unfortunately I have not been able to get Rubinius 2.4.1 working, so I couldn't test on that version.

This seemingly simple bug can cause all sorts of encoding problems, for example https://github.com/phusion/passenger/issues/1169. In https://github.com/phusion/passenger/issues/1169#issuecomment-66618120, I described how a change in Passenger accidentally triggered the bug.

**Comment by YorickPeterse** [comment]
Tagging this as "performance" as any change we make to invalidating the cache should take performance into account. That is, invalidating the cache should _only_ happen when needed in order to ensure no decrease in performance.
