### ISSUE TITLE
Does not implement ObjectSpace::WeakMap

### ISSUE THREAD

**Issue by rkh** [rubinius/rubinius#3241]
Both MRI and JRuby implement `ObjectSpace::WeakMap`. Should Rubinius also implement it?

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
