### ISSUE TITLE
Implements guards against unwanted input in kernel Ruby code.

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3242]
Certain parts of Ruby have dedicated errors for unexpected input (https://github.com/rubinius/rubinius/pull/3077 for example). While we can't add guards for _unexpected_ input we can add guards (in some shape or form) that state what a method _can_ deal with.

We'll need to come up with a system where we don't have to add special tags all over the place while still retaining some form of type/behaviour safety.

**Comment by brixen** [comment]
In general, Rubinius enthusiastically supports experimentation and welcomes ideas for features that enhance developer ability to create amazing software.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to support more efforts around experimentation.
