### ISSUE TITLE
Drive adoption via specific projects

### ISSUE THREAD

**Issue by sandstrom** [rubinius/rubinius#3254]
I think the idea behind Rubinius (implementing most of Ruby in Ruby itself) is great, so I want to see this project succeed.

One thing that may be helpful is to single out particular software projects and make them run really well on Rubinius. This will mostly entail work in the project itself, not in Rubinius. But by making Rubinius the primary runtime for the project, it'll increase participation and interest in Rubinius itself.

Some properties of such a project that'll probably be useful:
1. Should ideally be self-contained, not a library or framework. That way, less things can break, since no additional, end-user developed code is running on top. Optimizations are also easier.
2. Should use aspects of Ruby that Rubinius is extra good at, e.g. speed or introspection.
3. Should be popular in itself, since the purpose is to increase interest adoption of Rubinius.

You'll probably have better thoughts on candidates, but some that come to mind are:
1. Logstash: popular, performance sensitive, memory introspection may be useful
2. Chef: self-contained and popular
3. Rubocop: self-contained, ubiquitous, performance may be important
4. Sidekiq: performance is important

Things to do could be improving documentation on running the project with Rubinius, making adjustments to make use of specific features in Rubinius (where relevant), make enhancements to Rubinius tailored specifically to these projects (similar to the Rails-MRI symbols garbage collection improvement).

What do you think? Good idea, bad?

[1] https://github.com/elasticsearch/logstash
[3] https://github.com/opscode/chef
[4] https://github.com/bbatsov/rubocop
[5] https://github.com/mperham/sidekiq

**Comment by lucasmartins** [comment]
@brixen Nice to read this discussion, about leveraging Sidekiq on Rubinius, [MailCannon](https://github.com/lucasmartins/mailcannon) is an Open Source project running at production for an year, I'm not working on the company which I created it for anymore but I'm sure I can get updated production metrics with the guys who do.

**Comment by brixen** [comment]
@lucasmartins it would be awesome to have a dialogue with folks supporting MailCannon in production. The new(-ish) Rubinius Metrics stuff was created exactly to address the problem of understanding performance without resorting to artificial (and nearly useless) benchmarking. The next step is to make it even easier to get the results of Rubinius Metrics. If you can put me in contact with someone, that would be awesome!

**Comment by lucasmartins** [comment]
@joaohornburg John, can you catch up on this thread? @brixen runs the Rubinius project and it would be awesome if you could give him some metrics about MailCannon running in production. Optimizing Sidekiq on RBX would leverage the adoption.  It still runs on RBX right?

**Comment by lucasmartins** [comment]
@pcasaretto Hey Paulo, can you catch up on this thread? @brixen runs the Rubinius project and it would be awesome if you could give him some metrics about MailCannon running in production. Optimizing Sidekiq on RBX would leverage its adoption. It still runs on RBX right?

**Comment by pcasaretto** [comment]
@andrehjr is the guy running MailCannon these days.

**Comment by sandstrom** [comment]
@brixen just curious if you've found any good targets?

**Comment by brixen** [comment]
@sandstrom mostly focused on production apps at this time, but I think Discourse could be a good app, especially to demonstrate concurrency, concurrent garbage collection, and the built-in Metrics with StatsD output.

Any interest in looking into setting up a Discourse test app and environment?

**Comment by sandstrom** [comment]
No time, sorry (https://github.com/rubinius/rubinius/issues/3254#issuecomment-68307151)

**Comment by digitalextremist** [comment]
Right now `sidekiq` will `segfault` with `Rubinius` ( https://github.com/mperham/sidekiq/issues/2489 )

But otherwise, I have been doing all my latest `Celluloid` related work using `Rubinus` and would like to continue to. I will be doing deeper comparisons to `jRuby` in different types of operations, system configurations, etc.

**Comment by brixen** [comment]
Rubinius encourages people to experiment with existing Ruby projects, but migrating from MRI is not an activity that has been very successful in the past.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to better support people interested in trying to run their existing projects on Rubinius.
