### ISSUE TITLE
rbx 2.4.1 upgrade errors

### ISSUE THREAD

**Issue by jzakiya** [rubinius/rubinius#3255]
/home/jzakiya/.rvm/log/1419522856_rbx-2.4.1/rake.log
https://gist.github.com/jzakiya/bca4c6fd7e79992d7032

**Comment by YorickPeterse** [comment]
@jzakiya As mentioned by @jc00ke we'll need more info such as:

* What tool are you using for installing Rbx (RVM, manual, etc)
* The _full_ build output and contents of any generated log files
* The contents of `config.rb` if it exists
* Output of `llvm-config --version`

**Comment by jzakiya** [comment]
OK, have time now to refocus on this.

System:
Lenovo laptop: I5 cpu, 6 GB
PCLinuxOS 32-bit KDE distro, GCC 4.7.2
rvm installer.

I was upgrading rbx-2.2.10 to 2.4.1 with: 
rvm uprade  rbx-2.2.10  rbx-2.4.1
and got the errors shown in the gist.

After 2.2.10, I have never been able to upgrade or install any newer rbx version with rvm.
FYI, I had no problem upgrading to ruby-2.2.0 and jruby-1.7.18 with rvm, only rbx has problems.

**Comment by YorickPeterse** [comment]
@jzakiya Are you able to build Rubinius from source? You can do so as following:

```
git clone git@github.com:rubinius/rubinius.git
git checkout v2.4.1
bundle install
./configure --prefix=/path/to/where/you/want/to/install/rubinius
rake install
```

**Comment by jzakiya** [comment]
I get this error:
--------------------------------------------------------------------
jzakiya@localhost ~ $ git clone git@github.com:rubinius/rubinius.git
Cloning into 'rubinius'...
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
------------------------------------------------------------------------------

**Comment by YorickPeterse** [comment]
Ah, I figured you would be authenticated with Github (via your public key). You can use the following URL for the clone instead:

    https://github.com/rubinius/rubinius.git

**Comment by jzakiya** [comment]
OK, I was able to clone and start the install process, but rake aborted leaving me this output:

rake aborted!
Error compiling
/home/jzakiya/.rvm/gems/ruby-2.2.0/gems/daedalus-core-0.2.0/lib/daedalus.rb:68:in `command'
/home/jzakiya/.rvm/gems/ruby-2.2.0/gems/daedalus-core-0.2.0/lib/daedalus.rb:254:in `link'
/home/jzakiya/.rvm/gems/ruby-2.2.0/gems/daedalus-core-0.2.0/lib/daedalus.rb:774:in `build'
/home/jzakiya/.rvm/gems/ruby-2.2.0/gems/daedalus-core-0.2.0/lib/daedalus.rb:877:in `block in linear_tasks'
/home/jzakiya/.rvm/gems/ruby-2.2.0/gems/daedalus-core-0.2.0/lib/daedalus.rb:876:in `each'
/home/jzakiya/.rvm/gems/ruby-2.2.0/gems/daedalus-core-0.2.0/lib/daedalus.rb:876:in `linear_tasks'
/home/jzakiya/.rvm/gems/ruby-2.2.0/gems/daedalus-core-0.2.0/lib/daedalus.rb:872:in `start'
/home/jzakiya/.rvm/gems/ruby-2.2.0/gems/daedalus-core-0.2.0/lib/daedalus.rb:989:in `block in build'
/home/jzakiya/.rvm/gems/ruby-2.2.0/gems/daedalus-core-0.2.0/lib/daedalus.rb:980:in `each'
/home/jzakiya/.rvm/gems/ruby-2.2.0/gems/daedalus-core-0.2.0/lib/daedalus.rb:980:in `build'
/home/jzakiya/rubinius/rakelib/vm.rake:240:in `block in <top (required)>'
/home/jzakiya/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/home/jzakiya/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => spec => build => build:build => vm/vm
(See full trace by running task with --trace

**Comment by jemc** [comment]
That's not the entire traceback, but looking at your `rake.log` gist in the OP, it looks like you're hitting the same error.  As @YorickPeterse mentioned, can you tell us the output of `llvm-config --version`?  It looks like your LLVM installation is missing some feature that rubinius is using.

**Comment by jzakiya** [comment]
jzakiya@localhost ~ $ llvm-config --version
3.4.2

**Comment by YorickPeterse** [comment]
This might be a reason for this problem happening: http://stackoverflow.com/questions/21477407/llvm-3-5-fails-to-link

@jzakiya can you paste the output of `llvm-config --ldflags --cflags --libnames`?

**Comment by jzakiya** [comment]
jzakiya@localhost ~ $ llvm-config --ldflags --cflags --libnames
-L/usr/lib/llvm  -lz -lpthread -lffi -lcurses -lrt -ldl -lm 
-I/usr/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -fomit-frame-pointer -fPIC
libLLVMLTO.a libLLVMLinker.a libLLVMipo.a libLLVMVectorize.a libLLVMBitWriter.a libLLVMR600CodeGen.a libLLVMR600Desc.a libLLVMR600Info.a libLLVMR600AsmPrinter.a libLLVMTableGen.a libLLVMDebugInfo.a libLLVMOption.a libLLVMX86Disassembler.a libLLVMX86AsmParser.a libLLVMX86CodeGen.a libLLVMSelectionDAG.a libLLVMAsmPrinter.a libLLVMX86Desc.a libLLVMX86Info.a libLLVMX86AsmPrinter.a libLLVMX86Utils.a libLLVMIRReader.a libLLVMBitReader.a libLLVMAsmParser.a libLLVMMCDisassembler.a libLLVMMCParser.a libLLVMInstrumentation.a libLLVMInterpreter.a libLLVMMCJIT.a libLLVMJIT.a libLLVMCodeGen.a libLLVMObjCARCOpts.a libLLVMScalarOpts.a libLLVMInstCombine.a libLLVMTransformUtils.a libLLVMipa.a libLLVMAnalysis.a libLLVMRuntimeDyld.a libLLVMExecutionEngine.a libLLVMTarget.a libLLVMMC.a libLLVMObject.a libLLVMCore.a libLLVMSupport.a

**Comment by YorickPeterse** [comment]
Argh, I forgot to also include the `--libs` option, could you paste the output of the following?: `llvm-config --libs`. On my system I get the following:

```
-lLLVMLTO -lLLVMObjCARCOpts -lLLVMLinker -lLLVMipo -lLLVMVectorize -lLLVMBitWriter -lLLVMIRReader -lLLVMAsmParser -lLLVMR600CodeGen -lLLVMR600Desc -lLLVMR600Info -lLLVMR600AsmPrinter -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter -lLLVMHexagonCodeGen -lLLVMHexagonAsmPrinter -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMCppBackendCodeGen -lLLVMCppBackendInfo -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter -lLLVMTableGen -lLLVMDebugInfo -lLLVMOption -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMJIT -lLLVMLineEditor -lLLVMMCAnalysis -lLLVMMCDisassembler -lLLVMInstrumentation -lLLVMInterpreter -lLLVMCodeGen -lLLVMScalarOpts -lLLVMInstCombine -lLLVMTransformUtils -lLLVMipa -lLLVMAnalysis -lLLVMProfileData -lLLVMMCJIT -lLLVMTarget -lLLVMRuntimeDyld -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMExecutionEngine -lLLVMMC -lLLVMCore -lLLVMSupport
```

I suspect LLVM is adding a certain library to the output of `--libs` but _not_ to the output of `--ldflags` meaning it would fail to link as appears to be the case in this situation.

**Comment by jzakiya** [comment]
jzakiya@localhost ~ $ llvm-config --libs
-lLLVMLTO -lLLVMLinker -lLLVMipo -lLLVMVectorize -lLLVMBitWriter -lLLVMR600CodeGen -lLLVMR600Desc -lLLVMR600Info -lLLVMR600AsmPrinter -lLLVMTableGen -lLLVMDebugInfo -lLLVMOption -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMIRReader -lLLVMBitReader -lLLVMAsmParser -lLLVMMCDisassembler -lLLVMMCParser -lLLVMInstrumentation -lLLVMInterpreter -lLLVMMCJIT -lLLVMJIT -lLLVMCodeGen -lLLVMObjCARCOpts -lLLVMScalarOpts -lLLVMInstCombine -lLLVMTransformUtils -lLLVMipa -lLLVMAnalysis -lLLVMRuntimeDyld -lLLVMExecutionEngine -lLLVMTarget -lLLVMMC -lLLVMObject -lLLVMCore -lLLVMSupport

**Comment by YorickPeterse** [comment]
Hmpf, it seems neither of us have the option in there (as mentioned in the StackOverflow thread) while I can compile just fine. Is it possible for you to try and compile Rubinius with LLVM 3.5.0? That's the version I'm using, perhaps there's something going on with LLVM 3.4.x.

**Comment by jzakiya** [comment]
I put in a request yesterday for the PCLOS developers to upgrade to version 3.5.
It is was in the process of being upgraded, and had to be sent to testing.
If everything works out it may be released as an upgrade within the next few days,
When it is, I'll try again and see what happens.

You might want to discuss this problem with the rvm people to let them know of this
error profile.

**Comment by jzakiya** [comment]
OK.  My distro upgraded llvm to from 3.4.2 to 3.5.0 and it seemed to do the trick.

I was able to upgrade from 2.2.10 to 2.4.1, though there were some errors cited in the output.

Here is the gist of the output screen dump of the upgrade.

https://gist.github.com/anonymous/7fcfc590656b876c872e

In spite of the listed errors, the upgrade finished, rbx-2.4.1 was listed under: rvm list
and I am able to do a: rvm use rbx, and run irb sessions.

Is there anything else I need to do to resolve any of the listed errors?

**Comment by YorickPeterse** [comment]
@jzakiya The error looks vaguely familiar to the output I've seen when RVM tries to update the bundled RubyGems and fails miserably at it for reasons unknown. You can bypass this by using `rvm install xxx --rubygems ignore`. The error itself shouldn't interfere with Rubinius in any way, so you should be good to go. Feel free to close this issue once you're all set :)
