### ISSUE TITLE
Return from inside an iter inside a lambda inside a method differs from MRI.

### ISSUE THREAD

**Issue by jemc** [rubinius/rubinius#3259]
In  ruby `lambda` (and `->()`) works differently from iters when it comes to `return` as control flow.  Rubinius follows MRI on this, but has unexpected behavior when the return is inside an iter inside a lambda inside a method.  The expected behavior is that the return will skip the iter and end the lambda, but not the method, because a return inside an iter skips the iter, and a return inside a lambda ends the lambda (but not the enclosing method or lambda).  The following example illustrates this behavior, and the unexpected behavior on rubinius:

MRI (2.1.2):

``` ruby
pry(main)> def foo; x = []; proc { return x << 1 }.call << 2 end; foo
=> [1]
pry(main)> def foo; x = []; lambda { return x << 1 }.call << 2 end; foo
=> [1, 2]
pry(main)> def foo; x = []; lambda { proc { return x << 1 }.call << 2 }.call << 3 end; foo
=> [1, 3]
pry(main)> def foo; x = []; proc { lambda { return x << 1 }.call << 2 }.call << 3 end; foo
=> [1, 2, 3]
```

rbx-2.4.1:

``` ruby
pry(main)> def foo; x = []; proc { return x << 1 }.call << 2 end; foo
=> [1]
pry(main)> def foo; x = []; lambda { return x << 1 }.call << 2 end; foo
=> [1, 2]
pry(main)> def foo; x = []; lambda { proc { return x << 1 }.call << 2 }.call << 3 end; foo
=> [1]
pry(main)> def foo; x = []; proc { lambda { return x << 1 }.call << 2 }.call << 3 end; foo
=> [1, 2, 3]
```

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
