### ISSUE TITLE
kernel/platform/pointer_accessors.rb says it is generated, but isn't, but probably should be

### ISSUE THREAD

**Issue by jemc** [rubinius/rubinius#3261]
According to the comment at the header of `kernel/platform/pointer_accessors.rb`, the file is generated code.
https://github.com/rubinius/rubinius/blob/58d397733b6ec1ae003b296ba4ab27a65e8629dc/kernel/platform/pointer_accessors.rb#L1-L3

However, I can find no trace of the code the generates this file.

Moreover, I'm concerned that this file is not arch-aware.  It makes assumptions like `int16 == short`, and I think these kinds of mappings need to be detected for the current architecture that rubinius is compiled on.

So we need a solution to this.  One possible solution would be generating the file as it says it is, taking the arch in mind at build time.  Another solution would be adding more `Rubinius.primitive`s, so that we have both `pointer_write_int16` and `pointer_write_short` and they both do the right thing on the C level.

Please advise.

**Comment by brixen** [comment]
@jemc I honestly can't remember if this file was generated. It was added in this commit 6a7ce6812e5a3afcca9f4f71f18d329ae538aafa so if it was generated, maybe @mitchellh had a script to do that.

As for the sizes of types, we have all that here https://github.com/rubinius/rubinius/blob/705a3d5181a7a4d8ba4bffd777401cc44a73afac/kernel/platform/ffi.rb so you should be able to define the methods you want. If you need primitives to do this, you can add them.

**Comment by mitchellh** [comment]
I did generate most of that commit but I haven't had that script in a long time. Sorry for not bringing it in then :(

**Comment by brixen** [comment]
@mitchellh no worries, thanks for clarifying.

@jemc you could edit out the comment and we'll maintain it by hand. Alternatively, you can write a script to generate it and check that in. Feel free to write the methods you need.
