### ISSUE TITLE
Kernel.chomp specs

### ISSUE THREAD

**Issue by jc00ke** [rubinius/rubinius#3265]
Porting from rubyspec/rubyspec#23

http://gist.github.com/437039
- [ ] Pull out shared specs
- [ ] Review specs

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
