### ISSUE TITLE
Incompatible implementation of Process::Status

### ISSUE THREAD

**Issue by sodabrew** [rubinius/rubinius#3268]
This is a spin-off from eventmachine/eventmachine#551 wherein I am trying to get unit tests running clean for all Rubies that Eventmachine supports, including Rubinius.

Ruby MRI has a C implementation of Process::Status and jams instance values into the class.
http://rxr.whitequark.org/mri/ident?i=rb_last_status_set

``` C
  rb_last_status_set(int status, rb_pid_t pid)
  {
      rb_thread_t *th = GET_THREAD();
      th->last_status = rb_obj_alloc(rb_cProcessStatus);
      rb_iv_set(th->last_status, "status", INT2FIX(status));
      rb_iv_set(th->last_status, "pid", PIDT2NUM(pid));
  }
```

Eventmachine uses similar code to construct the Process::Status result for EM.system and EM.popen, which does not work with the Rubinius Process::Status https://github.com/rubinius/rubinius/blob/master/kernel/common/process.rb#L523-584

I hacked up my Eventmachine locally and got it working with this adjustment, but it fails on MRI because the (nonexistent)initialize for Process::Status wants 0 arguments.

``` C
 static VALUE t_get_subprocess_status (VALUE self, VALUE signature)
 {
        VALUE proc_status = Qnil;

        int status;
        pid_t pid;

        if (evma_get_subprocess_status (NUM2ULONG (signature), &status)) {
                if (evma_get_subprocess_pid (NUM2ULONG (signature), &pid)) {
                        proc_status = rb_obj_alloc(rb_cProcStatus);
+                       VALUE argv[2];
+                       argv[0] = INT2FIX(pid);
+                       argv[1] = INT2FIX(status);
+                       rb_obj_call_init(proc_status, 2, argv);
                        rb_iv_set(proc_status, "status", INT2FIX(status));
                        rb_iv_set(proc_status, "pid", INT2FIX(pid));
                }
        }

        return proc_status;
 }
```

Open question: should Rubinius change its definition of Process::Status to match the way MRI does it, or should Eventmachine test its Ruby engine and construct Process::Status accordingly?

**Comment by YorickPeterse** [comment]
My opinion would be "Yes, we need to change our stuff". We can make the arguments optional, which should keep compatibility with existing code. @brixen any further thoughts on this?

**Comment by brixen** [comment]
Where are the specs that cover this behavior?

**Comment by YorickPeterse** [comment]
@brixen Searching in our specs I can't seem to find anything that tests `Process::Status` itself (that is, initializing it and such), only a bunch of specs that test some of its methods.

My question in this would be: what would we test? In MRI this class doesn't have an `#initialize` method so besides just creating an instance there's no much to test. I suppose at minimum we could have something along the lines of the following:

```ruby
describe 'Process::Status#initialize' do
  it 'initializes a new Process::Status instance' do
    Process::Status.new.kind_of?(Process::Status).should == true
  end
end
```

**Comment by brixen** [comment]
I'd suggest something more like this:

```ruby
Process::Status.new.should be_an_instance_of(Process::Status)
```

Which looks tautological but if this shows the difference in behavior from MRI, it should be sufficient.

**Comment by YorickPeterse** [comment]
Ah, I wasn't aware we had that matcher. I'll see what I can do.

**Comment by brixen** [comment]
Can we confirm that this is fixed on master?

**Comment by sodabrew** [comment]
Will compile and test this evening / tomorrow.

**Comment by sodabrew** [comment]
We're partway there. I still needed to make this change to eventmachine:

Does this suggest that you need `pid=` and `status=` methods, or is it something deeper?

``` diff
diff --git a/ext/rubymain.cpp b/ext/rubymain.cpp
index e594b5f..d2467ca 100644
--- a/ext/rubymain.cpp
+++ b/ext/rubymain.cpp
@@ -408,8 +408,8 @@ static VALUE t_get_subprocess_status (VALUE self, VALUE signature)
        if (evma_get_subprocess_status (NUM2ULONG (signature), &status)) {
                if (evma_get_subprocess_pid (NUM2ULONG (signature), &pid)) {
                        proc_status = rb_obj_alloc(rb_cProcStatus);
-                       rb_iv_set(proc_status, "status", INT2FIX(status));
-                       rb_iv_set(proc_status, "pid", INT2FIX(pid));
+                       rb_iv_set(proc_status, "@status", INT2FIX(status));
+                       rb_iv_set(proc_status, "@pid", INT2FIX(pid));
                }
        }
```

**Comment by brixen** [comment]
@sodabrew that diff suggests that our `rb_iv_set` is not correct (eg it's not accepting the ivar name without the `@`).

**Comment by brixen** [comment]
@sodabrew sorry, to answer your actual question, I see no reason to assume that change implies that there exist setter methods. But that should be verified with MRI (eg with `Process::Status#respond_to?` or `Process::Status.instance_method_defined?`)

**Comment by sodabrew** [comment]
I don't even get this. It's a Class object, and MRI explicitly _removes_ the new method!?
```
irb(main):001:0> p = Process::Status.new
NoMethodError: undefined method `new' for Process::Status:Class
irb(main):002:0>  Process::Status.class
=> Class
```
http://rxr.whitequark.org/mri/source/process.c#6687
``` C
     rb_cProcessStatus = rb_define_class_under(rb_mProcess, "Status", rb_cObject);
     rb_undef_method(CLASS_OF(rb_cProcessStatus), "new");
```

**Comment by brixen** [comment]
@sodabrew hold tight, let me write some C-API specs for this. Your diff above shouldn't be needed.

Are there other issues besides your diff?

**Comment by sodabrew** [comment]
Am testing this diff now:
``` diff
diff --git a/kernel/common/type.rb b/kernel/common/type.rb
index 7cef99f..8193ba3 100644
--- a/kernel/common/type.rb
+++ b/kernel/common/type.rb
@@ -418,10 +418,6 @@ module Rubinius
         name = name.to_sym
       end

-      unless name.is_ivar?
-        raise NameError, "`#{name}' is not allowed as an instance variable name"
-      end
-
       name
     end
```

**Comment by sodabrew** [comment]
No other issues with Process::Status.

**Comment by brixen** [comment]
@sodabrew `rb_iv_set` doesn't go through any kernel code, so that diff isn't relevant.

I have a C-API spec that shows Rubinius having the same behavior as MRI code like `rb_iv_set(proc_status, "pid", INT2FIX(pid));`. Will link you when I push it.

What does the failure / error look like that you're trying to fix?

**Comment by sodabrew** [comment]
Yep, I figured out that `rb_iv_set` lives in `vm/capi/object.cpp` :)

**Comment by brixen** [comment]
https://github.com/rubinius/rubinius/commit/ffd327fb5fedc4c911f11b21425b764b254ee34c

**Comment by sodabrew** [comment]
Oh! Ok, so then the problem is that _from Ruby_ you cannot `instance_variable_get('foo')` because it will complain. I tried this on process.rb:
```
     def pid
-      @pid
+      @pid || instance_variable_get('pid')
     end
```
but that fails becase:
```
irb(main):001:0> p = Process::Status.new
=> #<Process::Status:0x4644 @stopsig=nil @status=nil @pid=nil @termsig=nil>
irb(main):002:0> p.instance_variable_get('pid')
NameError: `pid' is not allowed as an instance variable name
```

**Comment by brixen** [comment]
Correct, you can't get an instance variable from Ruby without the `@` on the name. MRI uses that from C to make hidden instance variables. I don't understand why MRI hates Ruby so much. :(

**Comment by sodabrew** [comment]
Going back to eventmachine changes for a moment, even if I made this change:
``` diff
diff --git a/ext/rubymain.cpp b/ext/rubymain.cpp
index e594b5f..ae4e06f 100644
--- a/ext/rubymain.cpp
+++ b/ext/rubymain.cpp
@@ -408,8 +408,12 @@ static VALUE t_get_subprocess_status (VALUE self, VALUE signature)
        if (evma_get_subprocess_status (NUM2ULONG (signature), &status)) {
                if (evma_get_subprocess_pid (NUM2ULONG (signature), &pid)) {
                        proc_status = rb_obj_alloc(rb_cProcStatus);
+                       /* MRI Ruby uses hidden instance vars */
                        rb_iv_set(proc_status, "status", INT2FIX(status));
                        rb_iv_set(proc_status, "pid", INT2FIX(pid));
+                       /* Rubinius uses standard instance vars */
+                       rb_iv_set(proc_status, "@status", INT2FIX(status));
+                       rb_iv_set(proc_status, "@pid", INT2FIX(pid));
                }
        }
```
I would have the problem I brought up in #3271, which is the `status` value above has the exitstatus, term signal, and exit signal values together, but the Rubinius Process::Status expects them to be separated out. I could adjust eventmachine like this, but it would imply a Process::Status API going forward:
``` diff
diff --git a/ext/rubymain.cpp b/ext/rubymain.cpp
index e594b5f..748dd98 100644
--- a/ext/rubymain.cpp
+++ b/ext/rubymain.cpp
@@ -408,8 +408,20 @@ static VALUE t_get_subprocess_status (VALUE self, VALUE signature)
        if (evma_get_subprocess_status (NUM2ULONG (signature), &status)) {
                if (evma_get_subprocess_pid (NUM2ULONG (signature), &pid)) {
                        proc_status = rb_obj_alloc(rb_cProcStatus);
+
+                       /* MRI Ruby uses hidden instance vars */
                        rb_iv_set(proc_status, "status", INT2FIX(status));
                        rb_iv_set(proc_status, "pid", INT2FIX(pid));
+
+                       /* Rubinius uses standard instance vars */
+                       rb_iv_set(proc_status, "@pid", INT2FIX(pid));
+                       if (WIFEXITED(status)) {
+                               rb_iv_set(proc_status, "@status", INT2FIX(WEXITSTATUS(status)));
+                       } else if(WIFSIGNALED(status)) {
+                               rb_iv_set(proc_status, "@termsig", INT2FIX(WTERMSIG(status)));
+                       } else if(WIFSTOPPED(status)){
+                               rb_iv_set(proc_status, "@stopsig", INT2FIX(WSTOPSIG(status)));
+                       }
                }
        }
```

**Comment by sodabrew** [comment]
What if the W* family of macros were defined as Rubinius.primitive? Then we could do the bit twiddling of #3271 when the values are read, but retain the portability of using the system-provided C macros. In eventmachine, I would do the smaller diff above, setting both `pid` and `@pid`, `status` and `@status` regardless of Ruby engine.

**Comment by YorickPeterse** [comment]
@brixen Can we not modify `rb_iv_set` so that when it sets an instance variable without a `@` it secretly adds it anyway? So basically `rb_iv_set(foo, "bar", ...)` would be the same as `rb_ivar_set(foo, "@bar", ...)`?

**Comment by brixen** [comment]
@YorickPeterse no, we can't change `rb_iv_set` that way.

@sodabrew your suggestion to conform the use of proper instance variables in Rubinius to the MRI use of hidden instance variables seems the most reasonable, I think. You could do this in your diff:

```diff
diff --git a/ext/rubymain.cpp b/ext/rubymain.cpp
index e594b5f..ae4e06f 100644
--- a/ext/rubymain.cpp
+++ b/ext/rubymain.cpp
@@ -408,8 +408,12 @@ static VALUE t_get_subprocess_status (VALUE self, VALUE signature)
        if (evma_get_subprocess_status (NUM2ULONG (signature), &status)) {
                if (evma_get_subprocess_pid (NUM2ULONG (signature), &pid)) {
                        proc_status = rb_obj_alloc(rb_cProcStatus);
+#ifdef RUBINIUS
+                       /* Rubinius uses standard instance vars */
+                       rb_iv_set(proc_status, "@status", INT2FIX(status));
+                       rb_iv_set(proc_status, "@pid", INT2FIX(pid));
+#else
+                       /* MRI Ruby uses hidden instance vars */
                        rb_iv_set(proc_status, "status", INT2FIX(status));
                        rb_iv_set(proc_status, "pid", INT2FIX(pid));
+#endif
                }
        }
```

I don't like this sort of conditional in code, but it's the most clear in this case. Of course, you're going to need to account for this in a few places, I expect.

Alternatively, using the same approach, you could substitute a few getter/setter functions that wrap all this up. That's likely the cleanest form of this hack.

Aside from this hack, the only reasonable thing is to file a bug with MRI and force them to change to a proper function API or _gasp_ use Ruby.

**Comment by sodabrew** [comment]
Just a heads up, I'm busy at work this week but I will revisit this in a new PR ASAP.

**Comment by sodabrew** [comment]
Thinking back to https://github.com/rubinius/rubinius/issues/3268#issuecomment-69442167 and looking at tenderlove/psych#216, perhaps Rubinius _does_ need a way to set non-`@`-prefixed ivars from the Ruby side in order to implement hidden ivars...

**Comment by brixen** [comment]
@sodabrew there is no way to "hide" instance variables from Ruby code (the concept is nonsensical) and all MRI achieves in doing so is impossible APIs instead of natural, object-oriented APIs (in an explicitly object-oriented language).

So, no, we are not ever going to add a way to "hide" Ruby instance variables, especially not when the API should just use them.
 
The disparity of code here concerns me: https://github.com/eventmachine/eventmachine/pull/568/files#diff-ef3d88dd2ef3bba26caebaebba5143b5R416

The code in that diff would be cleaner by using my recommended approach of defining separate functions for this behavior. I will revisit your alternate Process::Status PR to see if I can get closer to MRI's implementation.

**Comment by brixen** [comment]
In general, the MRI C-API for Rubinius is deprecated, but that doesn't mean it will be going anywhere soon. Compatibility for C-extensions will continue to be evaluated on a case-by-case basis. However, C-extensions that depend on functions that examine or manipulate built-in MRI data structures will never be supported.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated.
