### ISSUE TITLE
Problem with gems with non-ASCII characters in gemspec

### ISSUE THREAD

**Issue by frzng** [rubinius/rubinius#3275]
With Rubinius 2.4.1, when I try to install latest stable Cucumber:

``` bash
rbx -S gem install cucumber -v '1.3.18'
```

I get the following:

```
ERROR:  Error installing cucumber:
    invalid gem: package is corrupt, exception while verifying: invalid byte sequence in US-ASCII (ArgumentError) in /opt/rbx-2.4.1/gems/cache/cucumber-1.3.18.gem
```

As you may know, author of Cucumber is Aslak Helles**ø**y and the `ø` character isn’t part basic ASCII. When I check out Cucumber 1.3.18, change Aslak’s surname to Helles**oe**y and build the gem manually it works.

We use Cucumber 1.3.17 now which we installed with Rubinius 2.2.10. The [gemspec for 1.3.17](https://github.com/cucumber/cucumber/blob/v1.3.17/cucumber.gemspec) also contains `ø` so this is probably something introduced recently.

Just to be clear, it works with MRI 2.1.5 and 2.2.0.

**Comment by hassan** [comment]
FWIW, I don't see this problem installing that Cucumber version on a Mac (10.9.5) with rbx-2.4.1 built with llvm 3.5.0.

What platform are you on and how did you build rbx?

**Comment by jc00ke** [comment]
I also was able to install cucumber on Xubuntu 14.10 using LLVM 3.4.2

```
 ~  rbx -S gem install cucumber -v '1.3.18'
Fetching: multi_test-0.1.1.gem (100%)
Successfully installed multi_test-0.1.1
Fetching: gherkin-2.12.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed gherkin-2.12.2
Fetching: cucumber-1.3.18.gem (100%)
Successfully installed cucumber-1.3.18
Parsing documentation for multi_test-0.1.1
Installing ri documentation for multi_test-0.1.1
Parsing documentation for gherkin-2.12.2
Installing ri documentation for gherkin-2.12.2
Parsing documentation for cucumber-1.3.18
Installing ri documentation for cucumber-1.3.18
Done installing documentation for multi_test, gherkin, cucumber after 87 seconds
3 gems installed
 ~  rbx -v
rubinius 2.4.1.n361 (2.1.0 eec1ad34 2014-12-27 3.4.2 JI) [x86_64-linux-gnu]
```

By chance, what does `echo $LANG` return?

**Comment by frzng** [comment]
```bash
$ cat /etc/redhat-release 
CentOS Linux release 7.0.1406 (Core) 
$ rpm -qi llvm-devel | grep '^Version' 
Version     : 3.4.2
$ echo $LANG 
en_US.UTF-8
$ rbx -v 
rubinius 2.4.1 (2.1.0 b332f133 2014-12-04 3.4.2 JI) [x86_64-linux-gnu]
```

**Comment by frzng** [comment]
Another strange thing happened which maybe make this issue irrelevant. We run into some issues today and I destroyed my Vagrant box to be sure that all developers on our project have the same state and that it works. After provisioning the fresh Vagrant box everything works just fine. The LLVM, OS version and other settings are exactly the same.

I don’t remember it precisely, but I think the Vagrant box I destroyed today actually experienced Rubinius upgrades which we compile ourselves. So there may have been some artefacts which caused this issue.

What do you think? Shall we close this or investigate further?

**Comment by mislav** [comment]
When LANG contains `UTF-8`, that's a locale directive that Ruby respects by setting `Encoding.default_external` to UTF-8, i.e. reading in external input and files as Unicode. This is essential when gemspecs contain non-ASCII characters. In this case, installing gems works for me.

However when `LANG=C`, Ruby will load in external input as ASCII and choke on any non-ASCII characters. I can reproduce this issue with:

```
$ LANG=C /opt/rubies/rbx-2.2.10/bin/gem install bundler -v1.6.9 --verbose
...
ERROR:  Error installing bundler:
        invalid gem: package is corrupt, exception while verifying: invalid byte sequence in US-ASCII
        (ArgumentError) in /opt/rubies/rbx-2.2.10/gems/cache/bundler-1.6.9.gem
```

This might seem like a RubyGems bug, but I have the same version of RubyGems (v2.2.2) in MRI and it doesn't exhibit the same problem. This only happens with Rubinius.

Ideally, gem installation process shouldn't be affected by LANG. The gemspecs should be read in as UTF-8 by default (if that's what the standard for publishing gems is), or at least respect the settings in the `Content-type` response headers when fetching gems from rubygems.org.

**Comment by jawshooah** [comment]
Setting `LANG=en_US.UTF-8`, `LANGUAGE=en_US.UTF-8`, and `LC_ALL=en_US.UTF-8` does not appear to be sufficient. [Relevant build failure.](https://travis-ci.org/bbatsov/rubocop/jobs/100991199)

**Comment by brixen** [comment]
@jawshooah this is the only one that looks Encoding related https://travis-ci.org/bbatsov/rubocop/jobs/100991199#L241 and doesn't appear related to installing a gem. Would you mind opening a new issue for your case?

**Comment by jawshooah** [comment]
@brixen [Done.](https://github.com/rubinius/rubinius/issues/3555)

**Comment by chuckremes** [comment]
Still exists in rubinius 3.70. Noted on FreeBSD12 which does not set LANG var by default. Set to "en_US.UTF-8" and rebuild to work around the problem.

**Comment by brixen** [comment]
The following must be set in the environment `LANG=en_US.UTF-8` when installing gems that have UTF-8 characters.
