### ISSUE TITLE
Using Kernel#load with wrapping breaks "top-level methods"

### ISSUE THREAD

**Issue by ngollan** [rubinius/rubinius#3276]
``` ruby
# anon_thing.rb
def helper_method
  puts "Found it!"
end

helper_method
```

``` ruby
# test.rb
load(
  File.join(File.dirname(__FILE__), 'anon_thing.rb'),
  true
)
```

Running `test.rb` in rbx (tried `rubinius 2.4.1.n7 (2.1.0 0a3aebab 2015-01-07 3.5.0 JI) [x86_64-linux-gnu]`) results in:

``` text
An exception occurred running test.rb:

undefined local variable or method `helper_method' on an instance of Object. (NameError)

Backtrace:

  Kernel(Object)#helper_method (method_missing) at kernel/delta/kernel.rb:78
                              Object#__script__ at anon_thing.rb:5
                            Kernel(Object)#load at kernel/common/kernel.rb:497
                              Object#__script__ at test.rb:2
               Rubinius::CodeLoader#load_script at kernel/delta/code_loader.rb:66
               Rubinius::CodeLoader.load_script at kernel/delta/code_loader.rb:152
                        Rubinius::Loader#script at kernel/loader.rb:645
                          Rubinius::Loader#main at kernel/loader.rb:799
```

In MRI it works as expected. Running without the wrapping also works in rbx.

**Comment by jemc** [comment]
So, looking at this, the difference here is that MRI will create a different `main` object to use when you specify `wrap=true`, while Rubinius is always using the same (constant `MAIN`).

You can see this by modifying your example as shown:
```ruby
# issue3276.rb
p [self, self.object_id]
load(
  File.join(File.dirname(__FILE__), 'issue3276_module.rb'),
  true
)
p [self, self.object_id]
```
```ruby
# issue3276_module.rb
p [self, self.object_id]
```
```ruby
# output with MRI 2.1.2
[main, 69835780739580]
[main, 69835782996080]
[main, 69835780739580]
```
```ruby
# output with rbx 2.4.1
[main, 336]
[main, 336]
[main, 336]
```

The Rubinius code that is responsible for this behavior is `CompiledCode#create_script` defined in `kernel/common/compiled_code.rb` (https://github.com/rubinius/rubinius/blob/master/kernel/common/compiled_code.rb#L184-L203).

When `wrap` is `true`, it sets up a new `ConstantScope` in a new anonymous `Module`, but the `__script__` method that comprises the toplevel script gets stored and evaluated in the same main object as all other toplevel code (the constant `MAIN`).

@brixen 
It looks like we need to evaluate what we would need to do to have multiple `main` objects in the VM.  Or at least a way to spawn a temporary object that acts like a `main` that we can throw away when `load(..., true)` is done.

**Comment by brixen** [comment]
There's an aspect of this that has nothing to do with #load. Running just `anon_thing.rb` directly exhibits different behavior, as I mentioned in IRC. The send for `helper_method` does not allow private methods, as can be seen with `rbx compile -B anon_thing.rb`.

Creating a different `main` when `wrap == true` is not a big deal.

**Comment by brixen** [comment]
Obviously, we need specs for both facets of this.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
