### ISSUE TITLE
Psych/papertrail (reify) causing: Tuple cannot be created via allocate()

### ISSUE THREAD

**Issue by jc00ke** [rubinius/rubinius#3279]
I'm testing this on ffd327fb5fedc4c911f11b21425b764b254ee34c

* clone calagator/calagator@479c68a7fe54ee4b968ada098997731722dc7677
* `bundle`
* `bundle exec rspec spec/models/venue_spec.rb:327`

failure output: https://gist.github.com/jc00ke/7cb0b1e0c40646717f1a

**Comment by andrewhavens** [comment]
I am running into this same issue, but I'm not using papertrail. Just Rails 4.2.0 and Guard. Here are my steps to reproduce:

```bash
gem install rails -v 4.2.0
rails new testapp
echo "gem 'guard'" >> Gemfile
bundle
guard init
bundle exec guard
```

Backtrace: https://gist.github.com/andrewhavens/b93b58378c33f392242f

**Comment by jemc** [comment]
@andrewhavens @jc00ke 
This is a known issue with psych `2.0.9` for all serialization/deserialization of all Hashes.  I recently pushed a fix to psych (https://github.com/tenderlove/psych/pull/218) that should have solved this problem for *most* cases - please update your psych version to at least `2.0.10`.

The only case that this remains unfixed for is if someone is using a *subclass* of Hash that they implicitly serialize/deserialize.  See this issue (https://github.com/tenderlove/psych/issues/220) and the longer discussion in this issue (https://github.com/tenderlove/psych/issues/216).

**Comment by andrewhavens** [comment]
@jemc Thanks! Ran `bundle update psych` (which installed 2.0.11) and the error went away.
