### ISSUE TITLE
config/routes.rb seems to be executed twice

### ISSUE THREAD

**Issue by lumrandir** [rubinius/rubinius#3283]
Hello.

I'm using rbx-2.4.1, rails-4.1.8 and devise 3.4.1. When I'm trying to start my app, it crashes with the ArgumentError: Invalid route name, already in use: 'new_user_session'.

This issue seems to be unrelated to devise, because when I remove devise_for from config/routes.rb it starts complaining about my custom routes. I tried to wrap the routes block in begin...rescue block and it was really executing twice.

Here is the full backtrace https://gist.github.com/lumrandir/b5c40055c50ed01955c7

**Comment by YorickPeterse** [comment]
This problem should be fixed by using Rails 4.2 or newer, so please update to that version. See https://github.com/rails/rails/pull/17782 and https://github.com/rubinius/rubinius/issues/3223 for more information.
