### ISSUE TITLE
gem update json errors with rbx-2.4.1

### ISSUE THREAD

**Issue by jzakiya** [rubinius/rubinius#3285]
Update the json gem on 2.4.1 produced the following errors.

https://gist.github.com/jzakiya/18158cf2a67256dc5f7a

**Comment by YorickPeterse** [comment]
This is the same problem as described in #3230, which is supposed to be fixed in the master branch (https://github.com/rubinius/rubinius/issues/3230#issuecomment-69401478). Closing this one in favour of the former issue.
