### ISSUE TITLE
Rubinius debugging support for RubyMine

### ISSUE THREAD

**Issue by os97673** [rubinius/rubinius#3290]
there is a request for RubyMine to support debugging with Rubinius (https://youtrack.jetbrains.com/issue/RUBY-14118)
I've evaluated what we have now (as far as I understand rubinius-debuggers code) and decided to document my finding here to have it for reference (especially taking into account that the Debuggin API is supposed to be reworked soon).

Setting/removing breakpoint: we have almost everything we need except ability to set "exceptional" breakpoint (breakpoint triggered on throwing particular exception).
Another problem is to how to translate file:line to executable.  ribinius-debugger uses method name to specify breakpoint, but for IDE it is much easier to specify breakpoint using file and line.

Stepping: 
- step-over (next): it looks like every implementation of debugger will have to repeat code which calculate place where to set temporary breakpoint which is rathe complicated and looks like very implementation-specific (thus if the implementation will be changed the code should be change too).  Imho it would be better to have something similar to "step into" which (as far as I understand) implemented in Rubinius.
- it would be nice to have "step out" which goes out of the current method/frame

**Comment by os97673** [comment]
Also if/when the API will be reworked it would be nice to have some place where we could check its usage (or public documentation)

**Comment by brixen** [comment]
@os97673 thanks for opening this!

> Also if/when the API will be reworked it would be nice to have some place where we could check its usage (or public documentation)

Could you please elaborate here, I'm not sure I understand what you need. Are you asking for a capabilities predicate or a version number or something like that?

**Comment by os97673** [comment]
> Also if/when the API will be reworked it would be nice to have some place where we could check its usage (or public documentation)

I meant that currently we can use rubinius-debugger as a reference to check usage of Debugging API,  and it looks like this is the only place to check the API, thus it would be nice to either have the gem rewritten to use a new version of API or have another place to use as a reference.  I.e. we need either debugger reference implementation or documentation for the API.
Have I been able to clarify this request for you?

**Comment by brixen** [comment]
@os97673 sure, that makes sense. The Rubinius::Console will be the reference and we'll have much better documentation.

**Comment by os97673** [comment]
> @os97673 sure, that makes sense. The Rubinius::Console will be the reference and we'll have much better documentation.

Great, looking forward for the new API

**Comment by enovajuan** [comment]
(old) API debug post, pretty interesting stuff: http://mon-ouie.github.io/posts/debugger.html - an item or two have changed from the time this was written, but its minor

**Comment by brixen** [comment]
In general, Rubinius enthusiastically supports experimentation and welcomes ideas for features that enhance developer ability to create amazing software.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to support more efforts around experimentation.
