### ISSUE TITLE
IRB Resizing Crashes with execvp(2) failed

### ISSUE THREAD

**Issue by Pugio** [rubinius/rubinius#3292]
HEAD Rubinius, OS X 10.9.4
When I rapidly resize my terminal window IRB crashes:

```Ruby
An exception occurred running /Users/shalevold/Documents/Coding/Rubinius/rubinius/staging/library/bin/irb.rb:

Unknown errno : execvp(2) failed (SystemCallError)

Backtrace:

2.0.0-p195 :001 >                        Kernel(Module)#` at kernel/common/kernel.rb:188
  { } in RbReadline._rl_get_screen_size at staging/gems/gems/rb-readline-0.5.2/lib/rbreadline.rb:1870
        RbReadline.retry_if_interrupted at staging/gems/gems/rb-readline-0.5.2/lib/rbreadline.rb:6905
         RbReadline._rl_get_screen_size at staging/gems/gems/rb-readline-0.5.2/lib/rbreadline.rb:1869
          RbReadline.rl_resize_terminal at staging/gems/gems/rb-readline-0.5.2/lib/rbreadline.rb:8830
         RbReadline.rl_sigwinch_handler at staging/gems/gems/rb-readline-0.5.2/lib/rbreadline.rb:8841
       { } in RbReadline.rl_set_signals at staging/gems/gems/rb-readline-0.5.2/lib/rbreadline.rb:1665
                              Proc#call at kernel/bootstrap/proc.rb:20
                     Signal.run_handler at kernel/common/signal.rb:75
               Rubinius.received_signal at kernel/delta/rubinius.rb:215
                              Array#pop at kernel/common/array.rb:1042
         Rubinius::ThrownValue.register at kernel/common/throw_catch.rb:10
                  Kernel(RubyLex)#catch at kernel/common/throw_catch.rb:29
       RubyLex#each_top_level_statement at staging/gems/gems/rubysl-irb-2.1.0/lib/irb/ruby-lex.rb:232
                    IRB::Irb#eval_input at staging/gems/gems/rubysl-irb-2.1.0/lib/rubysl/irb/irb.rb:488
                       { } in IRB.start at staging/gems/gems/rubysl-irb-2.1.0/lib/rubysl/irb/irb.rb:397
                              Proc#call at kernel/bootstrap/proc.rb:20
            { } in Kernel(Module)#catch at kernel/common/throw_catch.rb:30
         Rubinius::ThrownValue.register at kernel/common/throw_catch.rb:8
                   Kernel(Module)#catch at kernel/common/throw_catch.rb:29
                              IRB.start at staging/gems/gems/rubysl-irb-2.1.0/lib/rubysl/irb/irb.rb:396
                      Object#__script__ at staging/library/bin/irb.rb:13
       Rubinius::CodeLoader#load_script at kernel/delta/code_loader.rb:66
       Rubinius::CodeLoader.load_script at kernel/delta/code_loader.rb:152
                Rubinius::Loader#script at kernel/loader.rb:655
                  Rubinius::Loader#main at kernel/loader.rb:809
```

I think I've identified the problem.
In vm/builtin/system.cpp#System::vm_backtick:615 , the parent tries to read from the error pipe (```errors[0]```) to see if the child sent an error code. The problem is that rb-readline uses a signal handler (which uses ``` `stty size` ``` to get the terminal size) to handle terminal resizes, and the rapid number of handler calls can sometimes call that read() to fail with EINTR.

The code doesn't handle this case, and assumes that when ```size != 0``` the child has failed, when in this case it's the parent read that's failed. In this case, ```error_no``` is never set and the returned exception has an unknown type. **See below the code for fixes.**

```C++
    int error_no;
    ssize_t size = read(errors[0], &error_no, sizeof(int));
    close(errors[0]);

    if(size != 0) {
      close(output[0]);
      Exception::errno_error(state, "execvp(2) failed", error_no);
      return NULL;
    }
```

I'd welcome suggestions on how to write a spec to catch this, but I've tested two possible solutions:

1. Handle read() failure by raising the proper exception (in this case EINTR). This works fine for rb-readline, as it's set up to catch EINTRs in Kernel#` and retry, but it doesn't fit well with the following code, which, when reading from the child processes output pipe, catches EINTRs and retries.

This would look like:
```C++
    int error_no;
    ssize_t size = read(errors[0], &error_no, sizeof(int));
    close(errors[0]);

    if(size != 0) {
      close(output[0]);
      if(size < 0) {
        Exception::errno_error(state, "reading child errors", errno, read(2));
     } else {
      Exception::errno_error(state, "execvp(2) failed", error_no);
     }
      return NULL;
    }
```

It just seems weird to have EINTR be thrown only in the case of reading from errors[0], but be handled internally when trying to read from output[0]. For that reason, I'd propose something that mirrors the handling code for reading from output[0]:

2.
```C++
    int error_no;
    for(;;) {
      ssize_t size = read(errors[0], &error_no, sizeof(int));

      if(size != 0) {     // either we read errors or read() errored
        std::cout << "MAN!" << std::endl;
        if (size > 0) {
          Exception::errno_error(state, "execvp(2) failed", error_no);
        } else {
          if (errno == EAGAIN || errno == EINTR) {
            if(state->check_async(calling_environment)) {
              continue;
            }
          } else {
            Exception::errno_error(state, "reading child errors", errno, "read(2)");
          }
        }

        close(errors[0]);
        close(output[0]);
        return NULL;
      }

      close(errors[0]);
      break;
    }
```

It's more verbose, but seems to correctly cover all cases correctly. I would like to refactor the nested ifs, but I can't think of a better way at the moment that still checks with ```check_async```.

**Comment by brixen** [comment]
This looks like the same issue as #3288.

**Comment by brixen** [comment]
Actually, this does not look related to #3288 after all. That issue appears to be that `infocmp` is not available and rb-readline uses it.

**Comment by Pugio** [comment]
Ahh good. It wasn't immediately obvious to me why #3288 would have been the same.
Suggestions for getting this merged in?

**Comment by brixen** [comment]
I'll push a patch today. I was investigating it on FreeBSD because I thought it was the same issue. Then I was investigating a way to avoid using the error pipe, but I think I'll keep that mechanism.
