### ISSUE TITLE
Split Ruby build dependencies into distinct steps

### ISSUE THREAD

**Issue by brixen** [rubinius/rubinius#3293]
The current build system relies on Ruby. This dependency significantly limits our ability to make the build process simpler in general and friendly for packaging systems.

There are several places where Ruby is a critical dependency, but all can be removed from the build by relying on artifacts instead of processing them every time a build is run:
1. Parsing instruction definitions and generating interpreter and JIT code.
2. Parsing C++ files and generating _primitive_ code.
3. Computing the dependencies for the C/C++ files.
4. Compiling the Ruby kernel files.

A gem (rubinius-instructions) has been made for the first one. The other steps can also easily be isolated.

Once the above parts are separated, the two remaining primary build components are:
1. The configure script
2. The blueprint / daedalus component that runs the build commands for vendored libraries and VM code.

These two pieces need to be rewritten in bash / sh. Bash is acceptable, sh is preferable.

The remaining Rake tasks can be retained, and the four components above can be integrated as new Rake tasks to generate the required artifacts that can be used for normal development builds and release builds.

This ticket is intended as an overview and to keep track of any necessary subordinate tickets.

**Comment by YorickPeterse** [comment]
When redoing the build system one feature I'd like to see is being able to reconfigure/recompile Rubinius _without_ manually having to call `configure` with all the options again. That is, whenver you run `./configure ....` all the options are saved in a file. Running something like `rake reconfigure` would just re-run the command. This can be useful when you have a lot of options set, e.g.:

   ./configure --cc=clang --cxx=clang++ --without-vendor-libsodium --without-vendor-zlib --prefix=~/.rubies/rbx-git

**Comment by andre-richter** [comment]
Maybe I could help on this one, but I'd need more detailed instructions.
What is the rubinius-instructions gem supposed to do? Does it compute something, or will it be a container for pre-computed results?

**Comment by brixen** [comment]
In general, Rubinius enthusiastically supports experimentation and welcomes ideas for features that enhance developer ability to create amazing software.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to support more efforts around experimentation.
