### ISSUE TITLE
Keyword arguments are not passed to parent class when calling super without arguments

### ISSUE THREAD

**Issue by jirutka** [rubinius/rubinius#3295]
#### Example

``` ruby
class Panthera
  def initialize(name: 'Panthera')
    @name = name
  end

  def to_s
    "name: '#{@name}'"
  end
end

class Tigris < Panthera
  def initialize(name: 'Tiger')
    super  # <-- HERE!
  end
end

puts Tigris.new(name: 'My Tiger')
puts Tigris.new
```
#### Expected output:

```
name: 'My Tiger'
name: 'Tiger'
```

Tested on MRI 2.1.2, MRI 2.2.0, JRuby 9.0.0.0.pre1.
#### Actual output:

```
name: ''
An exception occurred running script.rb:

method 'initialize': given 1, expected 1 (ArgumentError)

Backtrace:

                 Tigris#initialize at script.rb:13
                 Object#__script__ at script.rb:18
  Rubinius::CodeLoader#load_script at kernel/delta/code_loader.rb:66
  Rubinius::CodeLoader.load_script at kernel/delta/code_loader.rb:152
           Rubinius::Loader#script at kernel/loader.rb:645
             Rubinius::Loader#main at kernel/loader.rb:799
```

Tested on rubinius 2.5.0 (2.1.0 50777f41 2015-01-17 3.5.1 JI) [x86_64-darwin13.4.0].

**Comment by brixen** [comment]
@jirutka thanks for reporting this. It should be a ridiculous amount of fun figuring out all the edge-cases here, like how a keyword object is split into separate Hashes based on the types of keys. Any chance you'd be able to add some specs for this behavior? See eg https://github.com/rubinius/rubinius/blob/master/spec/ruby/language/method_spec.rb and https://github.com/rubinius/rubinius/blob/master/spec/ruby/language/block_spec.rb

**Comment by andrew-aladev** [comment]
```
class A
  def fit q = 1, w = 1, a: 1
    puts a
  end
end

class B < A
  def fit q = 1, w = 1, a: 1
    super q, w, a: a
  end
end

class C < A
  def fit q = 1, w = 1, a: 1
    super q, w, a
  end
end

class D < A
  def fit q = 1, w = 1, a: 1
    super
  end
end

B.new.fit
C.new.fit
D.new.fit
```

I've debuged `GenericArguments::call` a bit. We are failing here:
```
// Too many arguments
if(mcode->keywords && !RP && !KP && E > O) return false;
```

```
B.new.fit:
ololo method: fit, N: 0, M: 0, T: 3, O: 2, RP: 0, KP: 0, E: 0
ololo method: fit, N: 3, M: 0, T: 3, O: 2, RP: 0, KP: 1, E: 2

C.new.fit
ololo method: fit, N: 0, M: 0, T: 3, O: 2, RP: 0, KP: 0, E: 0
ololo method: fit, N: 3, M: 0, T: 3, O: 2, RP: 0, KP: 0, E: 3
method 'fit': given 3, expected 3 (ArgumentError)

D.new.fit
ololo method: fit, N: 0, M: 0, T: 3, O: 2, RP: 0, KP: 0, E: 0
ololo method: fit, N: 3, M: 0, T: 3, O: 2, RP: 0, KP: 0, E: 3
method 'fit': given 3, expected 3 (ArgumentError)
```

`C.new.fit` and `D.new.fit` are the same.

So we can see that super was called with arguments, but named parameter was passed as usual. We need to teach `super` how to bypass named parameters.

**Comment by brixen** [comment]
@andrew-aladev thanks for looking at this!

In [this gist](https://gist.github.com/brixen/82860dbc998676ec86f365e108016a69), you can see the bytecode that the Rubinius bytecode compiler emits for keyword arguments, as well as for `super` (which is called `zsuper` in MRI, basically, super that automatically includes all the arguments passed to this method)

I _think_ it would be possible to either 1. change the `zsuper` instruction or 2. use some bytecode and specifically pass all the arguments with `super` via bytecode instead of using the `zsuper` instruction at all.

The quickest, least intrusive approach would be to try to use bytecode and `super` instruction instead of the `zsuper` instruction when keywords are passed to the method.

If you want to start looking into this, the bytecode compiler is in https://github.com/rubinius/rubinius-code.

**Comment by andrew-aladev** [comment]
Today I've fixed `zsuper` instruction. I will add a special test into `spec/ruby/language/super_spec.rb` and create a PR tomorrow.

**Comment by brixen** [comment]
@andrew-aladev awesome! Excited to see what you're working on.

**Comment by glebm** [comment]
Has this been fixed in the latest release? Because i18n-tasks test suite now passes!
https://travis-ci.org/glebm/i18n-tasks/jobs/331206230

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
