### ISSUE TITLE
Random::DEFAULT is missing

### ISSUE THREAD

**Issue by godfat** [rubinius/rubinius#3296]
MRI/JRuby has this, and unfortunately, it does not seem to make much sense to have this in Rubinius given how Rubinius implements random. At first I just want to assign it with `Thread.current.randomizer` or `Thread.main.randomizer`, but a `Rubinius::Randomizer` is not a `Random`.

Any idea how we could add this, or just don't define it? I could probably just use `Random.seed` in my code, but MRI does not provide this method. Perhaps we should just ask MRI implements `Random.seed` instead?

**Comment by godfat** [comment]
Oops, I misread the code. There's no `Random.seed` defined in Rubinius.

**Comment by brixen** [comment]
@godfat I don't see a problem adding this constant. AFAIK, it's just an instance of Random. Is there some reason you see adding it would be a problem?

**Comment by godfat** [comment]
@brixen Since `Rubinius::Randomizer` is stored inside a thread local, I would guess it's not thread safe. Setting `Random::DEFAULT` would mean it's shared amongst all the threads. Also, what `Rubinius::Randomizer` should the `Random` instance refer to? The one from main thread, or a whole new one? This might also take some memory which most people might never use.

**Comment by eugenk** [comment]
Is there any news on this? We are using `Random::DEFAULT` indirectly via an external gem in our tests now and Rubinius not having this constant makes the tests fail.

**Comment by eugenk** [comment]
I've worked around it in our test suite, but the question remains: Any news on this?

**Comment by godfat** [comment]
Sorry, I don't have anything new to share.

**Comment by brixen** [comment]
@godfat @eugenk I don't see any evidence that MRI synchronizes calls to the object that `Random::DEFAULT` points to so Ruby implicitly doesn't make any concurrency guarantees about this object. This is similar to an Array instance or any number of other Ruby core library classes.

The simplest solution for Rubinius is probably just to assign an instance of Random to `Random::DEFAULT`. Could someone open a PR for this?
