### ISSUE TITLE
Regular Expression does not match all Extended ASCII Characters

### ISSUE THREAD

**Issue by ErnstA** [rubinius/rubinius#3300]
On MRI the test examples below pass but on Rubinius one fails (as indicated below).
With the range up to \xfd it still works but for \xfe and \xff it fails!

```
require 'spec_helper'
describe 'https://github.com/rubinius/rubinius/issues/2916' do

 #     Failure/Error: expect(match_data[0]).to eq "OK2"
 #     expected: "OK2"
 #         got: "O"
 it "should find token OK2" do
    str = "* OK2 "
    regex = /[^\x80-\xfe ]+/ni
    str.index(regex,2)
    match_data = $~
    expect(match_data[0]).to eq "OK2"
  end

  it "should find token OK3" do
    str = "* OK3 "
    regex = /[^\x80-\xfd ]+/ni
    str.index(regex,2)
    match_data = $~
    expect(match_data[0]).to eq "OK3"
  end
end
```

One Ruby standard library fails because of this. See #2916

**Comment by ErnstA** [comment]
I have never done maintenance work on Rubinius and do not know how the existing specs need to be run.
Tried:

cd ~/.rvm/src/rbx-head/spec/ruby/core/regexp/*
gem install mspec
rspec escape_spec.rb
Missing or uninitialized constant: SpecGuard::RUBY_NAME

There are some specs for extended ASCII:
~/.rvm/src/rbx-head/spec/ruby/core/regexp$ grep xf * -ir
shared/new_ascii.rb:    a = "(?:[\x8E\xA1-\xFE])"
shared/new_ascii.rb:    Regexp.send(@method, /\xff/n).encoding.should == Encoding::ASCII_8BIT
shared/quote.rb:    str = "\xff".force_encoding "us-ascii"
shared/quote.rb:    Regexp.send(@method, "\xff").encoding.should == Encoding::ASCII_8BIT
shared/new_ascii_8bit.rb:    a = "(?:[\x8E\xA1-\xFE])"
shared/new_ascii_8bit.rb:      Regexp.send(@method, "\3762").should == /#{"\xfe2"}/
shared/new_ascii_8bit.rb:    Regexp.send(@method, /\xff/n).encoding.should == Encoding::ASCII_8BIT

Do they pass?

**Comment by tmornini** [comment]
Which version of Rubinius are you running?

**Comment by brixen** [comment]
@ErnstA the known-passing specs are run with `bin/mspec ci`. So, to run the Regexp specs, you can do `bin/mspec ci core/regexp`.

I see that you're trying to run the specs in your .rvm directory. That's probably going to be more pain than you want. Instead, work in a git clone:

```
$ git clone https://github.com/rubinius/rubinius
$ cd rubinius
$ ./configure
$ rake
# Rubinius is built and all  the CI specs run
$ bin/mspec ci core/regexp
```

When you make edits to Rubinius files, run `rake build` to rebuild. Then you can run `bin/mspec` again.

If you want to run _all_ the Regexp specs, including ones that are tagged because they do not pass yet, you can run `bin/mspec core/regexp`.

**Comment by ErnstA** [comment]
@tmornini the regex problem occurs with 
rubinius 2.2.10 (2.1.0 bf61ae2e 2014-06-27 JI) [i686-linux-gnu]
and
rubinius 2.5.0.n25 (2.1.0 af7eb1b4 2015-01-25 3.4 JI) [i686-linux-gnu]

**Comment by ErnstA** [comment]
@brixen thanks for the help. I will not be able to spend time on this before the weekend.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
