### ISSUE TITLE
Syntax error using keyword arguments

### ISSUE THREAD

**Issue by heftig** [rubinius/rubinius#3301]
`eval "def a b:; c []; end"` works in both MRI 2.2.0 and Rubinius 2.5.1.

`eval "def a b:\n c []; end"` works in MRI but causes a syntax error in Rubinius.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
