### ISSUE TITLE
2.5.2 fails to build itself

### ISSUE THREAD

**Issue by heftig** [rubinius/rubinius#3302]
When attempting to build Rubinius using Rubinius 2.5.2, the build hangs after displaying `Running 198 tasks using 4 parallel threads`. Rake seems to be stuck in an infinite loop.

When using Rubinius 2.5.1 as system Ruby, the build completes.

**Comment by YorickPeterse** [comment]
Are you trying to build 2.5.2 into the same directory as the version you're using for the build? I believe that usually gives some problems. If so, try building into a different directory.

**Comment by heftig** [comment]
Necessarily the prefix is the same (/usr), since it's supposed to be a replacement. Since the prefix is set to a different directory than the source, the build system sets itself up to use a staging directory under the source.

Install uses DESTDIR so the products get redirected to yet another staging directory for packaging (/usr is not writable, anyway). Rubinius is packaged up from there. A packaged Rubinius is used to provide /usr/bin/ruby for the build.

When the system Rubinius providing /usr/bin/ruby is 2.5.1, 2.5.1 and 2.5.2 build successfully. If it is 2.5.2, neither builds due to the above problem.

**Comment by brixen** [comment]
I know what the issue is, will push a fix shortly.

**Comment by kyledrake** [comment]
I believe I may have some flavor of this, it hangs on the rake command:

```
Building native extensions.  This could take a while...
Installed rubysl-zlib (2.0.1)
Installed rb-readline (0.5.2)
Running 1 tasks using 3 parallel threads
1: GN vm/test/runner.cpp
1: CXX vm/test/runner.cpp
Build time: 34.497000179 seconds
1: LD vm/test/runner
Running 652 tests............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................OK!
bin/mspec ci :ci_files  -t bin/rbx -d --background
rubinius 2.5.2.c85 (2.1.0 e8a24276 2015-02-23 3.5.0 JI) [x86_64-linux-gnu]
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

This was run on master with commit e8a242769ba0cf2cfd373ec578541f12ebf840bd

**Comment by jemc** [comment]
@kyledrake 
I think your problem is different - it looks like your installation is hanging during tests, not build.  Is it consistently hanging for you?

**Comment by kyledrake** [comment]
It seemed to be hanging with no CPU activity. 2.5.1 does not appear to have
the same issue, but I didn't try 2.5.2, I tried HEAD, so I'll try 2.5.2
tomorrow and see if it works.
