### ISSUE TITLE
PTY: difference from between MRI 2.1 and RBX 2.4.1

### ISSUE THREAD

**Issue by johnmcconnell** [rubinius/rubinius#3305]
http://ruby-doc.org/stdlib-2.1.0/libdoc/pty/rdoc/PTY.html#method-c-open

```ruby
PTY.open
```
should be valid ruby code according to those specs.
Right now, RBX shows:
```
An exception occurred evaluating command line code:

method 'open': given 0, expected 1 (ArgumentError)

Backtrace:

                        Zeus.setup_dummy_tty! at /Users/aeberlin/.gem/rbx/2.1.0/gems/zeus-0.15.4/lib/zeus.rb:29
                       { } in Zeus.boot_steps at /Users/aeberlin/.gem/rbx/2.1.0/gems/zeus-0.15.4/lib/zeus.rb:59
                                    Proc#call at kernel/bootstrap/proc.rb:20
                  { } in Kernel(Module)#catch at kernel/common/throw_catch.rb:30
               Rubinius::ThrownValue.register at kernel/common/throw_catch.rb:8
                         Kernel(Module)#catch at kernel/common/throw_catch.rb:29
                              Zeus.boot_steps at /Users/aeberlin/.gem/rbx/2.1.0/gems/zeus-0.15.4/lib/zeus.rb:56
                                      Zeus.go at /Users/aeberlin/.gem/rbx/2.1.0/gems/zeus-0.15.4/lib/zeus.rb:48
                     { } in Object#__script__ at -e:1
  Rubinius::BlockEnvironment#call_on_instance at kernel/common/block_environment.rb:53
                Kernel(Rubinius::Loader)#eval at kernel/common/eval.rb:176
                       Rubinius::Loader#evals at kernel/loader.rb:612
                        Rubinius::Loader#main at kernel/loader.rb:798
```

**Comment by jemc** [comment]
@johnmcconnell 
It could be that rubysl-pty (https://github.com/rubysl/rubysl-pty) just needs to be updated from MRI trunk - I could be wrong, but it doesn't look like there's anything rubinius-specific in its implementation (it's written as a C extension for the MRI C API).

**Comment by jemc** [comment]
Yeah, among the many changes to `pty.c` that have happened in MRI since `rubysl-pty` was last updated is that the arity of the `open` method as registered in `Init_pty` has changed from `0` to `-1`.  So the rubysl-pty gem just needs to be updated and it should "just work".

**Comment by johnmcconnell** [comment]
The pty library is being used from a rubygem? Are you saying I should issue a PR to the rubygem repo? with like an updated Gemfile.lock?

**Comment by jc00ke** [comment]
We gemified the stdlib, and we update the libraries from time-to-time. We'll get this one updated (over at rubysl/rubysl-pty#8) and then a simple `gem update rubysl-pty` or `bundle update` should take care of it.

**Comment by johnmcconnell** [comment]
Okay great! This is one of the reasons rbx does not currently work on zeus.
