### ISSUE TITLE
Revise Thread::Backtrace::Location#path

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3310]
By now I've already fucked this one up twice, first thinking it always returns the basename and then thinking it's just an alias. Per notes in https://bugs.ruby-lang.org/issues/10561 the difference between `path` and `absolute_path` is as following:

* `absolute_path` _always_ returns the full path to the file `caller_locations` was called from.
* `path` returns the _basename_ when `caller_locations` resides directly in the script being executed, otherwise it _also_ returns the full path to the file it resides in. In case `caller_locations` resides in a file in the current working directory then the path is _relative_, otherwise it's absolute.

An example:

```
$ cat /tmp/example/file.rb 
def foo
  return [
    caller_locations[0].path,
    caller_locations[0].absolute_path
  ]
end

p foo

$ cat /tmp/example/other_file.rb 
require_relative 'file'

$ ruby /tmp/example/file.rb 
["/tmp/example/file.rb", "/tmp/example/file.rb"]

$ ruby /tmp/example/other_file.rb 
["/tmp/example/file.rb", "/tmp/example/file.rb"]

$ cd /tmp/example/
$ ruby file.rb 
["file.rb", "/tmp/example/file.rb"]

$ ruby other_file.rb 
["/tmp/example/file.rb", "/tmp/example/file.rb"]
```

As you'd expect from Ruby this behaviour is confusing and currently implemented incorrectly in Rubinius.

**Comment by brixen** [comment]
@YorickPeterse where are the MRI tests defining this behavior?

**Comment by YorickPeterse** [comment]
@brixen They are located at https://github.com/ruby/ruby/blob/9dc51967ef97808eacc2a900742a16aac2bd090b/test/ruby/test_backtrace.rb#L167-L186, although they are incredibly painful to digest. I'm not even sure if they properly assert the behaviour I described.
