### ISSUE TITLE
Subtracting a 0-valued Bignum from a Fixnum raises a TypeError

### ISSUE THREAD

**Issue by benweint** [rubinius/rubinius#3316]
The following Ruby code raises an exception on rbx-2.5.0, but does not on MRI 2.2.0 or JRuby 1.7.16:

```
1 - (0x3FFFFFFFFFFFFFFF+1).coerce(0).first
```

On MRI and JRuby, this expression yields a value of 1. (The `(0x3FFFFFFFFFFFFFFF+1).coerce(0).first` bit is just the easiest way I could find to produce a `Bignum` object with a value of zero - there may be a simpler way.)

On Rubinius 2.5.0, I get the following exception:

```
TypeError: Tried to use non-reference value 0x1 as type Bignum (10)
``` 

System info:

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.9.5
BuildVersion:	13F34

$ ruby -v
rubinius 2.5.0 (2.1.0 50777f41 2015-01-17 3.5.0 JI) [x86_64-darwin13.4.0]
```

**Comment by YorickPeterse** [comment]
Backstory for this can be found here: https://github.com/newrelic/rpm/pull/197#issuecomment-74133249

**Comment by jemc** [comment]
Note that this happens for any usually-Fixnum integer put into the `coerce` (not just zero), and only happens when subtracting from a Fixnum (not when adding).

**Comment by jemc** [comment]
In C++, `Bignum::normalize` returns `Fixnum::from(val)` if the number is small enough to fit inside a Bignum, otherwise returns the original Bignum.  However, `Fixnum::sub` is assuming that it's dealing with a Bignum at that point (`as<Bignum>`).

I think knowing this, I can fix it.
