### ISSUE TITLE
Wrong PID calling `system` with a command that doesn't exist

### ISSUE THREAD

**Issue by robin850** [rubinius/rubinius#3334]
Hello,

there's a little disparity between MRI and Rubinius calling the `system` method passing a command that doesn't exist:

``` ruby
>> system("i_do_no_exist")

>> RUBY_ENGINE
=> "rbx"
>> $?.pid
=> nil

>> RUBY_ENGINE
=> "ruby"
>> $?.pid
=> 3005
```

There's no big deal here but this is pretty useful to get a handle on a `Process::Status` object. It looks like the offending line is [here](https://github.com/rubinius/rubinius/blob/40040f9956833ac13774d745e961c743eeeefcbb/vm/builtin/system.cpp#L831) ; I don't know whether `fork` is working unexpectedly or if there is a missing check to avoid returning `nil` in such case.

Have a nice day!

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
