### ISSUE TITLE
Installing rbx-2.5.2 fails randomly while preinstalling 2.1.0 gems due to utilities::thread

### ISSUE THREAD

**Issue by nidev** [rubinius/rubinius#3359]
I'm very happy to know Rubinius and will try using Rubinius for my main one.

I tried to build rbx-2.5.2 with ruby-build from rbenv. I built it for two times. The first try was failed and the second one was successful and I finally got Rubinius. The failure was so ridiculous that I put 'randomly' in the title of this issue. I attach gists:[two piles of build logs](https://gist.github.com/nidev/21df2fabb4aa557ceb21), [config.rb and configure.log on failure](https://gist.github.com/nidev/68fb5bde6ec6dd963d53).

The point of the build failure is around line number 1905 of first log:

```text
(above omitted)
Installed rubysl-zlib (2.0.1)
Installed rb-readline (0.5.2)
utilities::thread: ~Condition: locked by another thread
rake aborted!
Command failed with status (): [/tmp/ruby-build.20150315230638.4558/rubini...] 
(below omitted)
```

I used this command to build Rubinius:
```shell
$ rbenv install rbx-2.5.2
```

I built Rubinius from:
```text
rbenv 0.4.0
ruby-build 20150303
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

uptime:
00:05:27 up  1:15,  1 user,  load average: 3.30, 2.56, 2.07

Linux yuuki-yuuna 4.0.0-1-mainline #1 SMP PREEMPT Wed Mar 4 10:48:18 JST 2015 x86_64 GNU/Linux
```
[/proc/cpuinfo](https://gist.github.com/nidev/de1a53745dae8b479939) is also attached.

While I was writing this issue, I tried 2 more times:
* 3rd try: failed (same error)
* 4th try: failed (same error)

I found 'utilities::thread: ~Condition: locked by another thread' message in vm/util/thread.hpp file. So It seemed that Ruby I used for building Rubinius is not responsible for this problem.

P.S. I rebooted my computer and tried to build two times and they were successful... :confused:

**Comment by YorickPeterse** [comment]
This looks like a race condition, so it can fail/succeed at any given time.

**Comment by nidev** [comment]
I corrected the title because compiling of actual 'Rubinius' was successful.

@YorickPeterse, I guessed so and I tried to reproduce it by using this shell script in the folder:

```shell
#!/bin/bash

echo " * This script tries to reproduce issue #3359"
echo " * After compiling Rubinius is done, rake will perform 'preinstalling 2.1.0 gems'."
echo " * The script will clean 'preinstalled' gems and re-do 'preinstalling'."

echo " 1. Cleanup"
rm -rf ./staging/gems/gems/*

echo " 2. Re-do preinstalling 2.1.0 gems"
DEV=1 rake build
```
(I didn't put DEV=1 environment variable. I did so to use GDB when it happens. Well, I did three times more but there was no failure.)

Does rakelib/preinstall_gems.rb utilize 'thread' to make installation faster?

**Comment by YorickPeterse** [comment]
The particular error occurs inside the Rubinius VM when it's trying to install a Gem. As such it's likely that this problem can also occur outside of the build process (e.g. when installing a Gem itself), it's not related to the Rake helper files themselves. @brixen made various changes related to threads, shutdown, etc, but these haven't been released yet. These changes _could_ solve the problem you're describing, though this particular problem could very well be unrelated.

**Comment by nidev** [comment]
@YorickPeterse, Thank you for your explanation. I was sticking to wrong point - Rake files. What can I do more to make this problem clearer? Just repeating certain routine doesn't seem helpful.

**Comment by YorickPeterse** [comment]
@nidev For now the build logs are adequate enough. Normally I'd suggest hooking up GDB and exporting its backtraces, but that's quite difficult to do during the installation process (since it's not running a single command you can attach to). What you could do is try to build from the master branch a few times to see if the error occurs there, though it's possible for it to only occur very rarely thus making it hard to reproduce.

**Comment by jemc** [comment]
I should add that I've seen this even when not compiling gems - I think it's a generic race condition within the VM related to some of the threading stuff that @brixen has been looking at.

**Comment by brixen** [comment]
In the logs, this `utilities::thread: ~Condition: locked by another thread` error occurs at the end of installing the pre-installed gems, so that rbx process is exiting. I'll audit where the Condition instances are getting destructed to see if I can determine the race condition.

**Comment by nidev** [comment]
@YorickPeterse Building from the master branch was successful. I did a few times but still, not 100% sure.

**Comment by jemc** [comment]
This is happening very regularly for me now with a particular Myco workload I'm running.

Here's the `thread apply all bt` output in `gdb`, in case it helps:
```
(gdb) thread apply all bt

Thread 8 (Thread 0x7fffea334700 (LWP 2115)):
#0  0x0000003f3520bca0 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
#1  0x000000000069bf0b in wait (mutex=..., this=0x17ed230)
    at /tmp/ruby-build.20150308134209.25932/rubinius-2.5.2/vm/util/thread.hpp:448
#2  become_dependent (cond=0x0, state=0x1d2f8b0, this=0x17ed200)
    at vm/world_state.hpp:98
#3  rubinius::SharedState::gc_dependent (this=<optimized out>, 
    state=state@entry=0x7fffea333ea0, call_frame=call_frame@entry=0x0)
    at vm/shared_state.cpp:278
#4  0x0000000000762f4c in gc_dependent (gct=..., call_frame=0x0, 
    this=0x7fffea333ea0)
    at /tmp/ruby-build.20150308134209.25932/rubinius-2.5.2/vm/state.hpp:151
#5  rubinius::ImmixMarker::perform (this=0x1d2f780, 
    state=state@entry=0x7fffea333ea0) at vm/gc/immix_marker.cpp:150
#6  0x0000000000763296 in rubinius::immix_marker_trampoline (
    state=0x7fffea333ea0) at vm/gc/immix_marker.cpp:19
#7  0x0000000000737646 in rubinius::Thread::execute_thread (
    state=state@entry=0x7fffea333ea0, vm=0x1d2f8b0) at vm/builtin/thread.cpp:276
#8  0x000000000073774e in rubinius::Thread::internal_thread (ptr=<optimized out>)
    at vm/builtin/thread.cpp:311
#9  0x0000003f35207ee5 in start_thread () from /lib64/libpthread.so.0
#10 0x0000003f34ef4b8d in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7fd0780 (LWP 2105)):
#0  0x0000003f34e35877 in raise () from /lib64/libc.so.6
#1  0x0000003f34e36f68 in abort () from /lib64/libc.so.6
#2  0x000000000069ab77 in rubinius::utilities::thread::fail (
    str=str@entry=0x10ac940 "~Condition: locked by another thread")
    at /tmp/ruby-build.20150308134209.25932/rubinius-2.5.2/vm/util/thread.hpp:38
#3  0x000000000069ce41 in ~Condition (this=0x17ed230, __in_chrg=<optimized out>)
    at /tmp/ruby-build.20150308134209.25932/rubinius-2.5.2/vm/util/thread.hpp:424
#4  ~WorldState (this=0x17ed200, __in_chrg=<optimized out>)
    at vm/world_state.hpp:9
#5  rubinius::SharedState::~SharedState (this=0x17eadb0, 
    __in_chrg=<optimized out>) at vm/shared_state.cpp:90
#6  0x000000000069d425 in rubinius::SharedState::discard (ss=0x17eadb0)
    at vm/shared_state.cpp:112
#7  0x00000000005c6fae in rubinius::Environment::~Environment (
    this=0x7fffffffd7c0, __in_chrg=<optimized out>) at vm/environment.cpp:116
#8  0x0000000000597db0 in main (argc=<optimized out>, argv=<optimized out>)
    at vm/drivers/cli.cpp:137
```

**Comment by brixen** [comment]
@nidev could you please try with 2.5.3?

**Comment by nidev** [comment]
@brixen I'll try soon. I was very glad to see 2.5.3 but was busy for job interviews.

**Comment by nidev** [comment]
I couldn't experience same problem again with 2.5.3. I tried to build rubinius 2.5.3 in ubuntu 32bit and gentoo 64bit for 5 times each, and failed to reproduce this issue again. :smile:

The build process was smoothly finished without any failures or hangups. In addition, I think with 2.5.3, issue #3366 should be cleared too. 

Thank you all for great job!

@brixen I close this issue.

**Comment by jemc** [comment]
Thanks, @brixen!  That was a nasty one.

**Comment by brixen** [comment]
@nidev great to hear, sorry it took a while to get to it.

**Comment by nidev** [comment]
@brixen I felt sorry that I couldn't provide any small patch for this time. Again, thank you so much. :smile:
