### ISSUE TITLE
Compiler error for splat operator followed by more arguments in case-when

### ISSUE THREAD

**Issue by maltoe** [rubinius/rubinius#3360]
Hi,

not sure if this qualifies as a bug, but at least this code used to work in MRI. Using rubinius 2.5.2.

```ruby
a = [1, 2]
case 3
when 3, *a
  puts 'works'
when *a, 3
  puts 'compiler error, but works in MRI'
end
```

System information:

```sh
$ ruby -v
rubinius 2.5.2 (2.1.0 7a5b05b1 2015-01-30 3.0 JI) [x86_64-linux-gnu]
$ rbenv -v
rbenv 0.4.0-98-g13a474c
$ uname -a
Linux xyz 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux
```

[Gist with stacktrace](https://gist.github.com/maltoe/b43657ffb88f5f178340)

Otherwise, thanks for this great product!

**Comment by jemc** [comment]
@maltoe 
Thanks for reporting this!  I think I have a fix that works, but I'm not that familiar with this behavior of `case`/`when` and I want to make sure it's done right.  Would you mind writing a few specs in `spec/ruby/language/case_spec.rb` to demonstrate a normal case and some edge cases for the behavior (which you probably understand better than I do at the moment).

**Comment by maltoe** [comment]
In fact, I too have no real clue what is a "normal" case here, I just stumbled across this weird behaviour. Digging into it, it only got more interesting. See the PR, where only the latter two test cases fail. It seems like somehow the variable expansion is messed up when it is followed by additional values (yet for two values it works with a single splat...).
