### ISSUE TITLE
Thread#pid would be a helpful addition

### ISSUE THREAD

**Issue by kwleland** [rubinius/rubinius#3365]
This way we can log long running thread pids as they are created and check up on them with the top command (H option).  If you have a thread that is in danger of using a whole core you can find it early as you are scaling.

Jruby has this FWIW, MRI does not but then again MRI threads don't scale that well so the need is less.

**Comment by jemc** [comment]
So, the corresponding system call for this is [gettid](http://linux.die.net/man/2/gettid).

For `getpid`, this is an easy FFI call (`Rubinius::FFI::Platform::POSIX.getpid`), but for `gettid` we are not this lucky.  In the above documentation link for gettid, it says: 
> Glibc does not provide a wrapper for this system call; call it using [syscall(2)](http://linux.die.net/man/2/syscall).

This means, we need to do the FFI equivalent of the following C pseudosnippet:
```c
#include <sys/types.h>
#include <sys/syscall.h>

pid_t thread_pid = syscall(SYS_gettid);
```
(where `SYS_gettid` is a number defined in the `sys/syscall.h` header)

So, to support this with FFI, we'd need to "read" the `sys/syscall.h` header at compile time and get that number for whatever platform we're on, then stuff that number somewhere accessible from Ruby space.

It seems then that the best way to implement this would be as a `Rubinius.primitive` in `thread.cpp`/`thread.hpp`.

**Comment by jemc** [comment]
Looking at this a bit more, calling `gettid` gives the pid of the calling thread, but what we actually want here is the pid of any *given* and it seems there is no safe, portable way to get the pid of an arbitrary `pthread_t` in POSIX.

The only way we'd be able to implement this is to make Thread store its pid when created for later access. I'm not comfortable making this call to add it though, as adding to the storage overhead of Threads has performance implications (more to allocate means spinning up threads will be slower). Unless there is actually a "lazy" way to get the value that I'm not seeing, the decision to add this would need to be weighed against the extra storage overhead.
