### ISSUE TITLE
UncaughtThrowError

### ISSUE THREAD

**Issue by nepalez** [rubinius/rubinius#3374]
Is it right to [raise] `ArgumentError` by the `#throw` method instead of more specialized `UncaughtThrowError` as MRI 2+ does?

[raise]: https://github.com/rubinius/rubinius/blob/58d397733b6ec1ae003b296ba4ab27a65e8629dc/kernel/common/throw_catch.rb#L37

**Comment by YorickPeterse** [comment]
Do you happen to know in what Ruby version `UncaughtThrowError` was added?

**Comment by nepalez** [comment]
Nope. I've tested it under MRI 2.0+ only.

When started testing with Rubinius and JRuby found that they complain on unknown constant.

**Comment by YorickPeterse** [comment]
Seeing how https://eval.in/312523 throws an error for the constant not being defined my guess is that this was added in 2.0. If so then we'll need to change our `throw` to be compatible with this.

**Comment by nepalez** [comment]
Yes, it was 2.0
http://svn.ruby-lang.org/cgi-bin/viewvc.cgi/trunk/ChangeLog?view=markup&pathrev=48468
(see 4-th message from the beginning)

**Comment by nepalez** [comment]
Tis is strange, but I found it in the [changelog for 2.2.0] only
(but both under 2.0 and 2.1 my tests passes)

[changelog for 2.2.0]: https://github.com/ruby/ruby/blob/ca6b174078fa15f33655be704d9409fdbc4f9929/doc/ChangeLog-2.2.0#L354

**Comment by tak1n** [comment]
I think this is ruby 2.2.0 specific behaviour.
When trying to access the constant `UncaughtThrowError` for ruby versions < 2.2.0 I get an error.

https://gist.github.com/tak1n/c02d5bbd371583e9ea61

**Comment by tak1n** [comment]
Thx for reporting this.

Closing in favor of #3264
