### ISSUE TITLE
CodeTools::CompileError on rspec-expectations-3.2.1 (on Travis)

### ISSUE THREAD

**Issue by e2** [rubinius/rubinius#3375]
I thought I'd report this:

```
CodeTools::CompileError:
       Error trying to compile /home/travis/.rvm/gems/rbx-2.5.2/gems/rspec-expectations-3.2.1/lib/rspec/matchers/built_in/equal.rb
```

I'm testing rbx-head locally and I don't get this. Feel free to close this if it's known/fixed/etc.

Here's the line in the build log (on Travis): https://travis-ci.org/celluloid/celluloid/jobs/58606387#L579

**Comment by YorickPeterse** [comment]
Could you provide a way for us to reproduce this?

**Comment by e2** [comment]
@YorickPeterse - you can try reconstructing the same setup from the Travis log linked above. I think the essential things are:
- the exact matching Rubinius version (whatever Travis uses)
- the same gems (rspec mostly, and probably rspec-expectations-3.2.1)
- the same ENV vars Travis uses (though I believe there aren't related settings for Rubinius, unlike JRuby).

Since I can't upgrade to rbx-head on Travis, if this doesn't "go away", I'll try to downgrade rspec-expectations to 3.2.0. If I have any more info, I'll update this issue.

**Comment by YorickPeterse** [comment]
Reverse engineering how to reproduce this is exactly what I wanted to avoid. Just having a clone command and whatever is needed to run the tests would help tremendously.

**Comment by jemc** [comment]
I can't reproduce this locally, but part of the problem with visibility here is that `CompilerError` here is precipitated by another exception, but the 'parent' exception only prints in the Rubinius backtrace printer (preceded by `Caused by:`).

This code load is the result of autoload - probably for `RSpec::Matchers::BuiltIn::Be` - so it is resolved while running specs, causing the error to happen and be printed with rspec's custom backtrace printer, which does not know about 'parent' exceptions.

We could know more about how to proceed if you (1) come up with a way to reproduce locally without waiting in Travis queues or (2) try adding `require 'rspec/matchers/built_in/be'` to the toplevel of one of your files to avoid waiting for the autoload and be sure the exception prints with the normal rubinius exception printer.

**Comment by e2** [comment]
> try adding require 'rspec/matchers/built_in/be' to the toplevel of one of your files

I'd be glad to.

Are there any options I can pass/set for Rubinius to help track this down? I don't mind a performance drop at all here - and reproducing the issue may be way too hard or time consuming.

**Comment by jemc** [comment]
You could also try setting `$DEBUG = true` at the top of one of your files.  This will be sure we can at least see the precipitating exception when it is raised even if for some reason we still don't get the normal Rubinius exception printer (like, because of `rake`'s custom printer, for example).

**Comment by e2** [comment]
Unfortunately, with `$DEBUG=true` I'm getting:
```
Exception: `NoMethodError' kernel/bootstrap/thread.rb:431 - undefined method `message' on nil:NilClass.
```

I don't know how the bootstrap thing works in RBX (I'm using RVM).

**Comment by jemc** [comment]
That's odd... try adding `Thread.abort_on_exception = true` to the toplevel as well.

**Comment by e2** [comment]
@jemc - same thing.

There are multiple things happening in multiple threads. Killing threads is also happening, though... (might be the cause, but all RSpec code is run from the main thread). I'll be working towards removing all calls to Thread#kill, so if that's the cause, this may never occur.

(This may also be the reason for the failure for `$DEBUG`- where the exception becomes nil).

I'll update this issue if it reoccurs again. Meanwhile, I'll assume it's caused by `Thread#kill` - you can close this issue if you like.

Let me know if there's anything else I can setup on my side to be better if this occurs again (I'd like to get `$DEBUG=1` working though - for other issues maybe).

**Comment by YorickPeterse** [comment]
This particular issue might be related to (or the same as) the one discussed in https://github.com/rubinius/rubinius/issues/2934.

**Comment by e2** [comment]
Thanks @YorickPeterse - I'll keep that in mind. If I somehow get this consistently on a desktop (and not on Travis), I'll take a shot at creating something that reproduces the issue.

Be aware that Travis boxes often have 32 cores ... which may be why this can occur there more often than on "average" desktops.

**Comment by YorickPeterse** [comment]
@e2 Is it possible for you to try to run the tests using https://github.com/rubinius/rubinius/commit/b57399f8f44c9afbe5b2785abd85943a8f46ddd3?

**Comment by e2** [comment]
@YorickPeterse - it's up to Travis to pick up this version (it didn't occur locally). All I can do is remove the workaround is see if appears again. 

I'll let you know if I encounter this - so feel free to close this if you consider it fixed.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
