### ISSUE TITLE
error: 'this' pointer cannot be null in well-defined C++ code

### ISSUE THREAD

**Issue by d4rky-pl** [rubinius/rubinius#3377]
Error during compilation: https://gist.github.com/d4rky-pl/9f197f9dbfa7db5e5845 , 

OS X Yosemite 10.10.3, llvm 3.5.1 from homebrew

**Comment by YorickPeterse** [comment]
This has already been fixed in 50aa7356e3c750fadb6665508e66d2f6923c7529.
