### ISSUE TITLE
Segfaults, missing constants, and unusual errors from autoload grinder

### ISSUE THREAD

**Issue by headius** [rubinius/rubinius#3378]
The following scripts reproduce a number of problems in Rubinius: https://gist.github.com/headius/f22ac44bc23bd221e100

While running this, it takes a variable amount of time to arrive at one of two conclusions (I've seen so far):

1. Missing constant, but with an unusual error (I'd expect it to be #<Module:...>::Foo... just ::Foo is *very* different).

```
An exception occurred running blah.rb:

Missing or uninitialized constant: ::Foo (NameError)

Backtrace:

      Module#const_missing at kernel/common/module.rb:652
       #<Module:0x8550>.go at (eval):4
  { } in Object#__script__ at blah.rb:11
                 Proc#call at kernel/bootstrap/proc.rb:20
            Thread#__run__ at kernel/bootstrap/thread.rb:396
```

2. Segfault in GC: https://gist.github.com/headius/70d17716d1e2f5e2ae70

The segfault seems to be pretty consistent...I've seen it maybe 10% of the time and it always seems to be in the same place.

Neither of these happen on JRuby or MRI.

Worth mentioning that this script runs _much_ slower on Rubinius (as compared to JRuby 1.7.19 and MRI 2.2), and I'm not sure how that might change the outcome.

**Comment by jemc** [comment]
@headius - Due to the way you're using the `$namespace` variable here, I also wonder if thread-safety of global variable access is also coming in to play.

**Comment by headius** [comment]
@jemc That's certainly possible too. I'd welcome a better test case. Ultimately, though, it *does* seem to be picking up the right module (i.e. the global is not returning nil), but the constant is just not there.

**Comment by brixen** [comment]
Unable to repro any issues with this on master. MRI 2.2.2p95 does segfault running it, however. https://gist.github.com/brixen/e74eeff668bbbcf866a7
