### ISSUE TITLE
`rubinius-2.2.10.tar.bz2` changed its checksum

### ISSUE THREAD

**Issue by mislav** [rubinius/rubinius#3380]
The resource at official download location for `rubinius-2.2.10.tar.bz2` changed its checksum.

We have this definition for `rbx-2.2.10` in ruby-build:

```
install_package "rubinius-2.2.10" "http://releases.rubini.us/rubinius-2.2.10.tar.bz2#2a3e6b71f27073b8d83b9592b05523af70bc147ddcd0673bffae55b4167c9d81" rbx
```

When 2.2.10 got released, "2a3e6b71f27073b8d83b9592b05523af70bc147ddcd0673bffae55b4167c9d81" was its SHA2, and based on that and we mirrored it to ruby-build's official CloudFront mirror:

```
curl -sL http://dqw8nmjcqpjn7.cloudfront.net/2a3e6b71f27073b8d83b9592b05523af70bc147ddcd0673bffae55b4167c9d81 | shasum -a 256 -b
2a3e6b71f27073b8d83b9592b05523af70bc147ddcd0673bffae55b4167c9d81 *-
```

However, since the official download changed its checksum to "3cb1a6ab2eba19b6dc84734666bb17a34332d247641b1a88b4c9324c69347780". I have diffed the contents of our cached archive and the latest one and it turns out there was a single whitespace change in `.bundle/config`:

```diff
diff --git a/.bundle/config b/.bundle/config
index a85cd57..8b7add1 100644
--- a/.bundle/config
+++ b/.bundle/config
@@ -1,2 +1,2 @@
----
+---
 BUNDLE_NO_PRUNE: true
```

It's not visible here, but a single space was removed after the YAML opening `---`.

There's nothing I expect you to "fix". I'm going to update the SHA2 in ruby-build. I just wanted to let you know that there was a snafu in your publishing process where a tarball got republished.

/cc @postmodern

**Comment by YorickPeterse** [comment]
According to S3 headers the last modified date is still `Thu, 03 Jul 2014 16:01:16 GMT`, meaning this change would've been around for a while now. @brixen did we end up re-publishing 2.2.10, or was that another release (I can't remember)?

**Comment by mislav** [comment]
Yeah, we didn't catch the change for a long time because ruby-build kept serving the original archive from our own mirror. We added 2.2.10 to ruby-build on Jul 2nd https://github.com/sstephenson/ruby-build/pull/595

Again, not a huge deal, but I just wanted to give a heads-up that Rubinius' release process might need guards against re-publishing already pushed tarballs.

**Comment by brixen** [comment]
@mislav we won't be republishing, sorry about the confusion on 2.2.10. Also, it shouldn't be supported. It's almost a year old. I'd much rather people complain they can't install it than being able to install it and using a year-old Rubinius version.
