### ISSUE TITLE
SSL cetificate error during ./configure

### ISSUE THREAD

**Issue by chaitanyav** [rubinius/rubinius#3383]
Fetching gems...
     ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
     ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
     ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
     ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
     ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
     ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
     ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
     ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
     ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
     ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
     ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
     ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
     ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
     ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
    ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
     ....
    Unable to download required gems.

This is happening on the when running configure on https://github.com/ruby/ruby.git

**Comment by YorickPeterse** [comment]
This is either a problem with the Ruby you're using to configure Rubinius, or your network. The only thing `configure` does relating to SSL is enabling it, we don't set any custom options whatsoever. I'm closing this as there's sadly nothing we can do here as far as I can tell.

**Comment by brixen** [comment]
@chaitanyav you can grab a release tarball which has all the needed gems included: 

http://releases.rubini.us/rubinius-2.5.3.tar.bz2

Unpack the tarball, cd to the rubinius-2.5.3 directory and run eg `bundle install --local && ./configure && rake build`. You don't need to install Rubinius to use it, but if you do want to install, pass `--prefix=/path/to/install` to configure.

**Comment by chaitanyav** [comment]
@brixen ,Got it

I dont get any errors on configure from the tarball
Verifying gems...

    Setting up gems...
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/runtime/gems/rubinius-ast-2.3.2'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/runtime/gems/rubinius-compiler-2.3.1'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/runtime/gems/rubinius-melbourne-2.3.1.0'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/runtime/gems/rubinius-processor-2.3.0'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/runtime/gems/rubinius-toolset-2.3.1'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/ffi2-generators-0.1.1'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-etc-2.0.3'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-fileutils-2.0.3'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-mkmf-2.0.1'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-shellwords-2.0.0'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-date-2.0.9'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-delegate-2.0.1'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-digest-2.0.3'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-fcntl-2.0.4'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-monitor-2.0.0'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-openssl-2.2.1'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-optparse-2.0.1'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-stringio-2.0.0'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-strscan-2.0.0'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-tempfile-2.0.1'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-thread-2.0.3'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-tmpdir-2.0.1'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-uri-2.0.0'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-yaml-2.1.0'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/rubysl-zlib-2.0.1'
    Unpacked gem: '/Users/nagachaitanyavellanki/Downloads/rubinius-2.5.3/bootstrap/gems/psych-2.0.10'

    Writing configuration files...
    ------------------------------------------------------------------
