### ISSUE TITLE
Two errors (and fixes) when compiling v2.5.3

### ISSUE THREAD

**Issue by ff2000** [rubinius/rubinius#3384]
```
=== 1 ===
vm/builtin/jit.cpp:44:55: error: member access into incomplete type 'rubinius::Configuration'
    return Integer::from(state, state->shared().config.jit_threshold_compile);
[and some more places]

=== 2 ===
vm/signal.cpp:112:34: error: use of undeclared identifier 'RBX_LLVM_VERSION'
    function("llvm version: %s", RBX_LLVM_VERSION);
                                 ^
1 error generated.
```

```diff
=== patch ===
diff --git a/vm/builtin/jit.cpp b/vm/builtin/jit.cpp
index 4963ab0..c4d48d7 100644
--- a/vm/builtin/jit.cpp
+++ b/vm/builtin/jit.cpp
@@ -1,6 +1,7 @@
 #include "builtin/block_environment.hpp"
 #include "builtin/jit.hpp"
 #include "builtin/list.hpp"
+#include "configuration.hpp"
 
 #include "ontology.hpp"
 
diff --git a/vm/signal.cpp b/vm/signal.cpp
index 25729dd..9f1b190 100644
--- a/vm/signal.cpp
+++ b/vm/signal.cpp
@@ -109,7 +109,9 @@ namespace rubinius {
     function("ruby version: %s", RBX_RUBY_VERSION);
     function("release date: %s", RBX_RELEASE_DATE);
     function("build revision: %s", RBX_BUILD_REV);
+#if ENABLE_LLVM
     function("llvm version: %s", RBX_LLVM_VERSION);
+#endif
     function("jit status: %s",
         CBOOL(signal_thread_->shared().env()->state->globals().jit.get()->enabled())
         ? "enabled" : "disabled");

======
```
(I hope it's OK to post the patch here. I currently want to get things running and forking/PR takes some time. Nevertheless if you wish so I will create a PR later)

This is compilation with LLVM turned off as I only have 3.6.0 installed and rubinius restricts to <=3.5.0.
Are there plans to support llvm-3.6.0/upcoming 3.7.0? What needs to be done in rubinius?

**Comment by jemc** [comment]
Regarding plans for supporting new versions of LLVM - yes, it's very high on our list of priorities, but it's not trivial.  New versions of LLVM have removed the JIT we use, so we must port our existing codebase to the new MCJIT.  There is an ongoing branch with this work: https://github.com/rubinius/rubinius/pull/3367

I'll take a look at your patches, thanks.

**Comment by jemc** [comment]
Thanks for reporting and patching!

**Comment by YorickPeterse** [comment]
@ff2000 In case you are on Arch Linux there's an llvm35 package that you can use to install LLVM 3.5, this will replace the existing "llvm" (3.6) package though.

**Comment by ff2000** [comment]
Hey, thx for merging!
I am on Gentoo, it would be easy to install llvm-3.5.0, but I need 3.6.0 because of clang for compilation. I will have a look at manually installing llvm-3.5.0 + rubinius in $HOME, so I don't have to mess with system llvm.
