### ISSUE TITLE
Rubinius Time issues with timezone changes on Europe/Lisbon and Europe/Istanbul

### ISSUE THREAD

**Issue by fmfdias** [rubinius/rubinius#3385]
Hi everyone,

While playing around with rubinius, I noticed that Time#new, Time#mktime and Time#local failed the 'handles years from 0 as such' test on spec/ruby/core/time/shared/time_params.rb. It was weird because the tests weren't failing on rubinius test system. I asked @ruipserra if these issues were happening to him, and he confirmed it. Soon after we confirmed that this is an issue related to our Timezone (Europe/Lisbon).

You can check the issue while running:

```
TZ='Europe/Lisbon' bin/mspec ci core/time
```

The date failing, 1912/01/01, represents the date where the timezone being used in Portugal changed.
After a quick C refresh (last time I've touch it was > 10 years ago) and some hours of debugging trying to track down where this was happening and found out that the cause of it is C mktime.

I checked out [IANA TZData europe source file](https://github.com/eggert/tz/blob/master/europe) and confirmed that the timezone change is there and also found 2 other cases that seem similar, Europe/Istanbul on 1910/10/01 and Europe/Amsterdam on 1940/05/16.

I tested these 2 cases and while it fails Europe/Istanbul it works correctly for Europe/Amsterdam on my local environment.

You can run [this](https://gist.github.com/fmfdias/a95b0d912bcb597e993b) to check it out.

Since mktime depends on the system you run it, I also tried to check the behavior on an Ubuntu machine, and while the error is different, they still fail. In this case, it only fails until you create another time object. When you try to create the date again, you get the correct value.

```
$ TZ='Europe/Lisbon' rbx
rbx-2.5.3 :001 > Time.new(1912,1,1)
 => 1911-12-31 23:23:28 -0036
rbx-2.5.3 :002 > Time.new(1912,1,1)
 => 1911-12-31 23:23:28 -0036
rbx-2.5.3 :003 > Time.new(1911,1,1)
 => 1911-01-01 00:00:00 -0036
rbx-2.5.3 :004 > Time.new(1912,1,1)
 => 1912-01-01 00:36:32 +0000
rbx-2.5.3 :005 > Time.new(1912,1,1)
 => 1912-01-01 00:36:32 +0000
```

Once more, this behavior doesn't happen for 'Europe/Amsterdam'

I wrote some C gists that prove that C mktime is showing this same behavior on each of the systems.
You can check them out here:
[Ubuntu glibc](https://gist.github.com/fmfdias/5c7c36726ff3cce12ead)
[OSX libc](https://gist.github.com/fmfdias/66aee626cf0d174a6de4)

I opened a [bug report](https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1437534) for ubuntu glibc. I'm planning to do the same for Apple libc but still didn't found the place where to open bug reports for Apple opensource projects :/

I don't know what might the best solution for Rubinius, if it's waiting for this issue to get fixed on these systems, if it's building it's own time library or if there's an easy fix for it. I would like to help out more, but I don't have much time available and my C is very very rusty.

**OSX System (Yosemite 10.10.3)**

rubinius 2.5.3 (2.1.0 2482b093 2015-05-01 3.5.1 JI) [x86_64-darwin14.3.0]
local build of current master

Darwin Filipes-MBP-2.home 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64 

rubinius chruby

**Ubuntu System (Ubuntu 12.04.5 LTE)**

rubinius 2.5.3 (2.1.0 2482b093 2015-04-28 3.4 JI) [x86_64-linux-gnu]

Linux shtrubymac 3.2.0-60-generic #91-Ubuntu SMP Wed Feb 19 03:54:44 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

rvm 1.25.27

Thanks

**Comment by YorickPeterse** [comment]
Sadly I think the only option is for us to wait for libc authors to fix this :/

**Comment by fmfdias** [comment]
Hi @YorickPeterse, Sorry for the late reply...

The bug report at Apple was opened a few days later, but still no reply. Will keep it posted here. Let's see what they say/do.

Cheers

**Comment by brixen** [comment]
This doesn't seem like an issue Rubinius can fix.
