### ISSUE TITLE
rubinius is missing fiddle

### ISSUE THREAD

**Issue by ff2000** [rubinius/rubinius#3387]
MRI ships fiddle as a replacement for DL. Rubinius does not ship this Module. It is needed by sup (which I want to test with rubinius, because performance with MRI is - suboptimal - sometimes ;))

```
An exception occurred running /home/franz/src/rubinius/gems/bin/sup:

no such file to load -- fiddle (LoadError)
```
There seems to be a seperate module called fiddle [1], which has nothing to do with the stdlib module, but hides that one unfortunately...

***
[1] https://github.com/bsm/fiddle

**Comment by brixen** [comment]
MRI added Fiddle despite there being a useful and widely used FFI available. You may want to look at converting sup to use FFI instead.

We may eventually add Fiddle, but it's very low priority at this point. If you want to send a PR to RubySL, that would be a great help.

I'll open an issue there to track this.
