### ISSUE TITLE
Threads coming and going still hang the gc (but takes much longer)

### ISSUE THREAD

**Issue by kwleland** [rubinius/rubinius#3396]
Thread recycling test program => https://gist.github.com/kwleland/4e788b9a091423118d21
hangs with 200 percent CPU utilization ie 2 of 8 cores, after 2 hours on linux.

rbx version => rubinius 2.5.3.c43 (2.1.0 52c28496 2015-05-11 3.4.2 JI) [x86_64-linux-gnu]

The gdb thread bt is => https://gist.github.com/kwleland/f1619d74e1ee769108ab

Thread 50 is doing a finalizer
Thread 1 is doing wait_till_alone  in stop_the_world

**Comment by kwleland** [comment]
result of gdb:  p *state    

$2 = {<rubinius::Lockable> = {mutex_ = {<rubinius::Lock> = {_vptr.Lock = 0x1790ff0, locking_thread_ = 0x0, lock_file_ = 0x13969af "", 
        lock_line_ = 0}, <rubinius::utilities::thread::Mutex> = {native_ = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 2, __spins = 0, 
            __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 16 times>, "\002", '\000' <repeats 22 times>, __align = 0}, 
        owner_ = 140150060295968}, <No data fields>}}, shared_ = @0x1c28570, roots_ = {<LinkedList> = {head_ = 0x0, count_ = 0}, lock_ = {lock_ = 0}}, name_ = 
    "rbx.ruby.main", variable_root_buffers_ = {<LinkedList> = {head_ = 0x7fff8a40a400, count_ = 3}, <No data fields>}, root_buffers_ = {<LinkedList> = {head_ = 0x0, 
      count_ = 0}, <No data fields>}, locked_objects_ = std::vector of length 0, capacity 8, run_state_ = rubinius::ManagedThread::eAlone, 
  kind_ = rubinius::ManagedThread::eRuby, metrics_ = {type = rubinius::metrics::eRubyMetrics, m = {ruby_metrics = {memory_young_bytes = 12582912, 
        memory_young_bytes_total = 66771304224, memory_young_objects = 0, memory_young_objects_total = 957305917, memory_young_percent_used = 19, memory_immix_bytes = 0, 
        memory_immix_bytes_total = 1101569200, memory_immix_objects = 0, memory_immix_objects_total = 4217196, memory_immix_chunks = 0, memory_immix_chunks_total = 33, 
        memory_large_bytes = 280624, memory_large_bytes_total = 313424, memory_large_objects = 1415, memory_large_objects_total = 1416, memory_symbols_bytes = 0, 
        memory_code_bytes = 0, memory_jit_bytes = 0, memory_promoted_bytes_total = 4134352592, memory_promoted_objects_total = 54194292, 
        memory_slab_refills_total = 16455662, memory_slab_refills_fails = 1503193, memory_data_objects_total = 0, memory_capi_handles = 12, 
        memory_capi_handles_total = 204, memory_inflated_headers = 29943, gc_young_count = 19769, gc_young_last_ms = 216, gc_young_total_ms = 1045521, 
        gc_young_lifetime = 3, gc_immix_count = 0, gc_immix_stop_last_ms = 0, gc_immix_stop_total_ms = 0, gc_immix_conc_last_ms = 115, gc_immix_conc_total_ms = 2912, 
        gc_large_count = 0, gc_large_sweep_last_ms = 0, gc_large_sweep_total_ms = 0}, finalizer_metrics = {objects_queued = 12582912, objects_finalized = 66771304224}, 
      jit_metrics = {methods_queued = 12582912, methods_compiled = 66771304224, methods_failed = 0, time_last_us = 957305917, time_total_us = 19}, console_metrics = {
        requests_received = 12582912, responses_sent = 66771304224}}, system_metrics = {io_read_bytes = 316, io_write_bytes = 167693, os_signals_received = 0, 
      os_signals_processed = 0, vm_inline_cache_resets = 837, vm_threads = 4151344, vm_threads_total = 4151344, locks_stop_the_world_last_ns = 255, 
      locks_stop_the_world_total_ns = 11732125708144}}, local_slab_ = {size_ = 0, start_ = {address_ = 0}, end_ = {address_ = 0}, current_ = {address_ = 0}, 
    allocations_ = 0}, os_thread_ = 140150060295968, id_ = 1}

**Comment by brixen** [comment]
This is working now on master. Will be releasing 2.5.8 shortly.
