### ISSUE TITLE
nil should be frozen

### ISSUE THREAD

**Issue by nirvdrum** [rubinius/rubinius#3401]
It looks like in MRI 2.2+, `nil` is now frozen.  I looked at making things match, but it creates problems in common/kernel.rb:175.  If `nil` is frozen, that line prevents extending it with a module, but that should be allowed.  I think it can be safely removed, since `object_extend` should catch any issues.  But I'd appreciate feedback from someone more familiar with things before proceeding.

**Comment by tak1n** [comment]
Closing in favor of #3264 

Thx for reporting, I'll repost your question in that issue so if I get to it or anyone else we can respond to it.
