### ISSUE TITLE
Subclass of array that overrides map & sort! can break sort_by

### ISSUE THREAD

**Issue by jeremyevans** [rubinius/rubinius#3416]
The following code raises `ArgumentError` on rbx, but works on MRI and JRuby:

```ruby
class A < Array
  def map(&block) A.new(super) end
  def sort!(order) sort_by{|a| a} end
end
A.new([1,2,3]).sort!(:foo)
```

This causes parts of the mail gem to not work on rbx:

https://github.com/mikel/mail/blob/2.6.3/lib/mail/parts_list.rb
https://travis-ci.org/jeremyevans/roda/jobs/64445320

This is apparently a problem in rbx 2.5.5 (according to Travis), but it also occurs with rbx 2.2.9.  I believe the problem is here: https://github.com/rubinius/rubinius/blob/master/kernel/common/enumerable.rb#L293

**Comment by jc00ke** [comment]
Reminiscent of #301 & #2015. I've been meaning to submit a PR to `mail` regarding that... if it would only compose instead of inherit. Hopefully I can manage some time soon for that PR.

**Comment by brixen** [comment]
This is a bug in mail. `ri Array#sort!`.

**Comment by jeremyevans** [comment]
FWIW, Mail actually switched to using composition instead of inheritance for this back in August of last year, it just hasn't made it into a release yet (https://github.com/mikel/mail/commit/9261582d449c2467820df003cc22201c637a9b71). I figured you may want to make rbx more compatible with ruby, but I guess the situation is rare enough that it isn't worth the effort to support it.

**Comment by brixen** [comment]
@jeremyevans the practice of overriding a method in a subclass and breaking the contract is common in Ruby. It's a blatant violation of LSP, which is well-established in industry for many years. It is not that it's not worth the effort to support it. It's _bad_ for Ruby as a programming language.

**Comment by jeremyevans** [comment]
@brixen I agree with you that it's a bad idea to violate LSP as mail was doing.  It's not that MRI and JRuby are doing it right and rbx is doing is wrong, it's that MRI and JRuby operate one way (`sort_by` does not call `sort!` internally), and rbx operates a different way.
