### ISSUE TITLE
Interrupt Codes (ctrl-c, USR2, QUIT) not working on 2.5.3-2.5.5

### ISSUE THREAD

**Issue by kayakyakr** [rubinius/rubinius#3418]
Since upgrading to rubinius 2.5.5, my interrupts have not been working. This means that ctrl-c in development and any of the interrupts in production just get swallowed by something that changed.

I finally had some time today to hunt down the culprit, and it's a change between 2.5.2 and 2.5.3.

The key versions are:
rails 4.1
puma 2.11
rbx 2.5.5

Signals in 2.5.2 do still work.

**Comment by brixen** [comment]
@kayakyakr could you provide more info, please. See the following gist for booting a Rails 4.2.1 app with puma 2.11.3 and rbx 2.5.5 https://gist.github.com/brixen/4ff7f11663bb3267b748

Perhaps gist your Gemfile.lock and gist of your terminal with what commands your ran and what the output was.

**Comment by brixen** [comment]
@kayakyakr also, please explain what you mean by "interrupts in production". What is an "interrupt", what is generating it, etc.

**Comment by kayakyakr** [comment]
Ah ha. I found the gem collision that is causing the issues, something with the new forking code. Issue happening with a stripped version of websocket-rails. Going to break that down and see if it's an issue with websocket-rails itself or if it's a problem with one of the required gems.

**Comment by kayakyakr** [comment]
Also, by interrupts I mean the USR2 and QUIT codes used in production to stop and restart a server.

**Comment by kayakyakr** [comment]
Looks like EventMachine is the problem. I don't know enough about the two pieces of software to find the point of collision.

Here is a demonstration project:
https://github.com/kayakyakr/rbxtest

**Comment by kayakyakr** [comment]
There might be a few other gems that are colliding in some way. I'm also having this issue on another project that does not use EventMachine. When I get back, go through the gems in the other project one-by-one.

Ubuntu 14.04, for the record.

**Comment by kayakyakr** [comment]
https://gist.github.com/kayakyakr/8bd9acdc683004060261

The gem list with rails 4.2. Unable to ctrl-c exit a server.

**Comment by brixen** [comment]
@kayakyakr thanks for the test repo. I reproduce the issue on 14.04 but not OS X. Looking into it.

**Comment by brixen** [comment]
@kayakyakr I have a fix for this but it involves breaking some pretty fundamental assumptions in the VM so may not land for a day or two. The fix does not strictly require reworking signal handling, but this sort of latent, lurking bug will likely repeat, so I'm fixing it now.

**Comment by kayakyakr** [comment]
Working on 2.5.7. Has an odd thing where, after I've done a few rails commands I get ```^CSegmentation fault (core dumped)```.

Not sure where my system is storing logs, didn't provide any details of the rest.

**Comment by brixen** [comment]
@kayakyakr could you check `/tmp/rbx-<username>.log` and gist the segv info.
