### ISSUE TITLE
Unable to build on Mac OS X 10.10.3

### ISSUE THREAD

**Issue by arthurcolle** [rubinius/rubinius#3429]
Build time: 246.472152 seconds
1: LD vm/vm
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMInstrumentation.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMArchive.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMLinker.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMIRReader.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMBitReader.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMAsmParser.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMDebugInfo.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMOption.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMipo.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMVectorize.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMBitWriter.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMTableGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMSystemZCodeGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMSystemZAsmParser.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMSystemZDesc.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMSystemZInfo.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMSystemZAsmPrinter.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMHexagonCodeGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMHexagonAsmPrinter.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMHexagonDesc.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMHexagonInfo.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMNVPTXCodeGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMNVPTXDesc.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMNVPTXInfo.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMNVPTXAsmPrinter.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMBlazeDisassembler.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMBlazeCodeGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMBlazeDesc.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMBlazeAsmPrinter.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMBlazeAsmParser.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMBlazeInfo.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMCppBackendCodeGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMCppBackendInfo.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMSP430CodeGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMSP430Desc.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMSP430Info.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMSP430AsmPrinter.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMXCoreDisassembler.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMXCoreCodeGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMXCoreDesc.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMXCoreInfo.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMXCoreAsmPrinter.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMipsDisassembler.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMipsCodeGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMipsAsmParser.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMipsDesc.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMipsInfo.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMipsAsmPrinter.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMARMDisassembler.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMARMCodeGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMARMAsmParser.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMARMDesc.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMARMInfo.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMARMAsmPrinter.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMAArch64Disassembler.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMAArch64CodeGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMAArch64AsmParser.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMAArch64Desc.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMAArch64Info.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMAArch64AsmPrinter.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMAArch64Utils.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMPowerPCCodeGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMPowerPCDesc.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMPowerPCAsmPrinter.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMPowerPCAsmParser.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMPowerPCInfo.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMSparcCodeGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMSparcDesc.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMSparcInfo.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMX86Disassembler.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMX86AsmParser.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMX86CodeGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMSelectionDAG.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMAsmPrinter.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMX86Desc.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMX86Info.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMX86AsmPrinter.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMX86Utils.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMCDisassembler.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMCParser.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMInterpreter.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMCJIT.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMJIT.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMCodeGen.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMObjCARCOpts.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMScalarOpts.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMInstCombine.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMTransformUtils.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMipa.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMAnalysis.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMRuntimeDyld.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMExecutionEngine.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMTarget.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMMC.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMObject.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMCore.a'
clang: error: no such file or directory: '/Users/arthur/anaconda/lib/libLLVMSupport.a'
Error: clang++ -o vm/vm vm/artifacts/accessor_primitives.cpp.o vm/artifacts/arguments.cpp.o vm/artifacts/bytecode_verification.cpp.o vm/artifacts/call_frame.cpp.o vm/artifacts/compiled_file.cpp.o vm/artifacts/config_parser.cpp.o vm/artifacts/console.cpp.o vm/artifacts/dispatch.cpp.o vm/artifacts/environment.cpp.o vm/artifacts/exception.cpp.o vm/artifacts/exception_point.cpp.o vm/artifacts/ffi.cpp.o vm/artifacts/ffi_util.cpp.o vm/artifacts/fiber_data.cpp.o vm/artifacts/fiber_stack.cpp.o vm/artifacts/global_cache.cpp.o vm/artifacts/helpers.cpp.o vm/artifacts/instructions.cpp.o vm/artifacts/internal_threads.cpp.o vm/artifacts/invoke_primitives.cpp.o vm/artifacts/jit_primitives.cpp.o vm/artifacts/linkedlist.cpp.o vm/artifacts/lock.cpp.o vm/artifacts/machine_code.cpp.o vm/artifacts/marshal.cpp.o vm/artifacts/method_primitives.cpp.o vm/artifacts/metrics.cpp.o vm/artifacts/object_memory.cpp.o vm/artifacts/ontology.cpp.o vm/artifacts/oop.cpp.o vm/artifacts/park.cpp.o vm/artifacts/shared_state.cpp.o vm/artifacts/signal.cpp.o vm/artifacts/stack_variables.cpp.o vm/artifacts/state.cpp.o vm/artifacts/symbol_table.cpp.o vm/artifacts/type_info.cpp.o vm/artifacts/unwind_info.cpp.o vm/artifacts/vm.cpp.o vm/artifacts/vm_thread_state.cpp.o vm/builtin/artifacts/access_variable.cpp.o vm/builtin/artifacts/alias.cpp.o vm/builtin/artifacts/array.cpp.o vm/builtin/artifacts/atomic.cpp.o vm/builtin/artifacts/autoload.cpp.o vm/builtin/artifacts/basic_object.cpp.o vm/builtin/artifacts/bignum.cpp.o vm/builtin/artifacts/block_as_method.cpp.o vm/builtin/artifacts/block_environment.cpp.o vm/builtin/artifacts/byte_array.cpp.o vm/builtin/artifacts/call_custom_cache.cpp.o vm/builtin/artifacts/call_site.cpp.o vm/builtin/artifacts/call_unit.cpp.o vm/builtin/artifacts/call_unit_adapter.cpp.o vm/builtin/artifacts/channel.cpp.o vm/builtin/artifacts/character.cpp.o vm/builtin/artifacts/class.cpp.o vm/builtin/artifacts/compact_lookup_table.cpp.o vm/builtin/artifacts/compiled_code.cpp.o vm/builtin/artifacts/constant_cache.cpp.o vm/builtin/artifacts/constant_scope.cpp.o vm/builtin/artifacts/constant_table.cpp.o vm/builtin/artifacts/data.cpp.o vm/builtin/artifacts/dir.cpp.o vm/builtin/artifacts/encoding.cpp.o vm/builtin/artifacts/exception.cpp.o vm/builtin/artifacts/executable.cpp.o vm/builtin/artifacts/ffi_pointer.cpp.o vm/builtin/artifacts/fiber.cpp.o vm/builtin/artifacts/find_object.cpp.o vm/builtin/artifacts/fixnum.cpp.o vm/builtin/artifacts/float.cpp.o vm/builtin/artifacts/fsevent.cpp.o vm/builtin/artifacts/heap_dump.cpp.o vm/builtin/artifacts/immediates.cpp.o vm/builtin/artifacts/integer.cpp.o vm/builtin/artifacts/io.cpp.o vm/builtin/artifacts/iseq.cpp.o vm/builtin/artifacts/jit.cpp.o vm/builtin/artifacts/list.cpp.o vm/builtin/artifacts/location.cpp.o vm/builtin/artifacts/logger.cpp.o vm/builtin/artifacts/lookup_table.cpp.o vm/builtin/artifacts/method_table.cpp.o vm/builtin/artifacts/module.cpp.o vm/builtin/artifacts/mono_inline_cache.cpp.o vm/builtin/artifacts/native_function.cpp.o vm/builtin/artifacts/native_method.cpp.o vm/builtin/artifacts/object.cpp.o vm/builtin/artifacts/pack.cpp.o vm/builtin/artifacts/packed_object.cpp.o vm/builtin/artifacts/poly_inline_cache.cpp.o vm/builtin/artifacts/proc.cpp.o vm/builtin/artifacts/randomizer.cpp.o vm/builtin/artifacts/regexp.cpp.o vm/builtin/artifacts/respond_to_cache.cpp.o vm/builtin/artifacts/stat.cpp.o vm/builtin/artifacts/string.cpp.o vm/builtin/artifacts/symbol.cpp.o vm/builtin/artifacts/system.cpp.o vm/builtin/artifacts/thread.cpp.o vm/builtin/artifacts/thread_state.cpp.o vm/builtin/artifacts/thunk.cpp.o vm/builtin/artifacts/time.cpp.o vm/builtin/artifacts/tuple.cpp.o vm/builtin/artifacts/unpack.cpp.o vm/builtin/artifacts/variable_scope.cpp.o vm/builtin/artifacts/weakref.cpp.o vm/capi/artifacts/array.cpp.o vm/capi/artifacts/bignum.cpp.o vm/capi/artifacts/capi.cpp.o vm/capi/artifacts/class.cpp.o vm/capi/artifacts/complex.cpp.o vm/capi/artifacts/data.cpp.o vm/capi/artifacts/encoding.cpp.o vm/capi/artifacts/enumerator.cpp.o vm/capi/artifacts/exception.cpp.o vm/capi/artifacts/file.cpp.o vm/capi/artifacts/fixnum.cpp.o vm/capi/artifacts/float.cpp.o vm/capi/artifacts/gc.cpp.o vm/capi/artifacts/globals.cpp.o vm/capi/artifacts/handle.cpp.o vm/capi/artifacts/handles.cpp.o vm/capi/artifacts/hash.cpp.o vm/capi/artifacts/integer.cpp.o vm/capi/artifacts/io.cpp.o vm/capi/artifacts/kernel.cpp.o vm/capi/artifacts/marshal.cpp.o vm/capi/artifacts/module.cpp.o vm/capi/artifacts/mutex.cpp.o vm/capi/artifacts/numeric.cpp.o vm/capi/artifacts/object.cpp.o vm/capi/artifacts/proc.cpp.o vm/capi/artifacts/range.cpp.o vm/capi/artifacts/rational.cpp.o vm/capi/artifacts/regexp.cpp.o vm/capi/artifacts/string.cpp.o vm/capi/artifacts/struct.cpp.o vm/capi/artifacts/symbol.cpp.o vm/capi/artifacts/thread.cpp.o vm/capi/artifacts/time.cpp.o vm/capi/artifacts/util.cpp.o vm/drivers/artifacts/cli.cpp.o vm/gc/artifacts/baker.cpp.o vm/gc/artifacts/code_manager.cpp.o vm/gc/artifacts/debug.cpp.o vm/gc/artifacts/finalize.cpp.o vm/gc/artifacts/gc.cpp.o vm/gc/artifacts/heap.cpp.o vm/gc/artifacts/immix.cpp.o vm/gc/artifacts/immix_marker.cpp.o vm/gc/artifacts/inflated_headers.cpp.o vm/gc/artifacts/managed.cpp.o vm/gc/artifacts/mark_sweep.cpp.o vm/gc/artifacts/object_mark.cpp.o vm/gc/artifacts/root.cpp.o vm/gc/artifacts/walker.cpp.o vm/gc/artifacts/write_barrier.cpp.o vm/instruments/artifacts/rbxti.cpp.o vm/instruments/artifacts/tooling.cpp.o vm/llvm/artifacts/autotypes.cpp.o vm/llvm/artifacts/detection.cpp.o vm/llvm/artifacts/disassembler.cpp.o vm/llvm/artifacts/inline.cpp.o vm/llvm/artifacts/inline_block.cpp.o vm/llvm/artifacts/inline_primitive.cpp.o vm/llvm/artifacts/jit_block.cpp.o vm/llvm/artifacts/jit_builder.cpp.o vm/llvm/artifacts/jit_compiler.cpp.o vm/llvm/artifacts/jit_context.cpp.o vm/llvm/artifacts/jit_inline_block.cpp.o vm/llvm/artifacts/jit_inline_method.cpp.o vm/llvm/artifacts/jit_memory_manager.cpp.o vm/llvm/artifacts/jit_method.cpp.o vm/llvm/artifacts/jit_runtime.cpp.o vm/llvm/artifacts/jit_util.cpp.o vm/llvm/artifacts/method_info.cpp.o vm/llvm/artifacts/passes.cpp.o vm/llvm/artifacts/state.cpp.o vm/llvm/artifacts/types.cpp.o vm/missing/artifacts/crypt.c.o vm/missing/artifacts/setproctitle.c.o vm/missing/artifacts/string.cpp.o vm/missing/artifacts/windows.cpp.o vm/util/artifacts/file.cpp.o vm/util/artifacts/logger.cpp.o vm/util/artifacts/murmur_hash3.cpp.o vm/util/artifacts/random.c.o vm/util/artifacts/sha1.c.o vm/util/artifacts/siphash.c.o vm/util/artifacts/spinlock.cpp.o vm/util/artifacts/strftime.c.o vm/util/artifacts/time64.c.o vm/util/artifacts/timer.cpp.o vm/util/artifacts/timing.c.o vm/util/artifacts/utf8.c.o vm/util/artifacts/vsnprintf.c.o vendor/double-conversion/libdoubleconversion.a vendor/libffi/.libs/libffi.a vendor/libtommath/libtommath.a vendor/oniguruma/./libonig.a vendor/udis86/libudis86/.libs/libudis86.a  -lm   /Users/arthur/anaconda/lib/libLLVMInstrumentation.a /Users/arthur/anaconda/lib/libLLVMArchive.a /Users/arthur/anaconda/lib/libLLVMLinker.a /Users/arthur/anaconda/lib/libLLVMIRReader.a /Users/arthur/anaconda/lib/libLLVMBitReader.a /Users/arthur/anaconda/lib/libLLVMAsmParser.a /Users/arthur/anaconda/lib/libLLVMDebugInfo.a /Users/arthur/anaconda/lib/libLLVMOption.a /Users/arthur/anaconda/lib/libLLVMipo.a /Users/arthur/anaconda/lib/libLLVMVectorize.a /Users/arthur/anaconda/lib/libLLVMBitWriter.a /Users/arthur/anaconda/lib/libLLVMTableGen.a /Users/arthur/anaconda/lib/libLLVMSystemZCodeGen.a /Users/arthur/anaconda/lib/libLLVMSystemZAsmParser.a /Users/arthur/anaconda/lib/libLLVMSystemZDesc.a /Users/arthur/anaconda/lib/libLLVMSystemZInfo.a /Users/arthur/anaconda/lib/libLLVMSystemZAsmPrinter.a /Users/arthur/anaconda/lib/libLLVMHexagonCodeGen.a /Users/arthur/anaconda/lib/libLLVMHexagonAsmPrinter.a /Users/arthur/anaconda/lib/libLLVMHexagonDesc.a /Users/arthur/anaconda/lib/libLLVMHexagonInfo.a /Users/arthur/anaconda/lib/libLLVMNVPTXCodeGen.a /Users/arthur/anaconda/lib/libLLVMNVPTXDesc.a /Users/arthur/anaconda/lib/libLLVMNVPTXInfo.a /Users/arthur/anaconda/lib/libLLVMNVPTXAsmPrinter.a /Users/arthur/anaconda/lib/libLLVMMBlazeDisassembler.a /Users/arthur/anaconda/lib/libLLVMMBlazeCodeGen.a /Users/arthur/anaconda/lib/libLLVMMBlazeDesc.a /Users/arthur/anaconda/lib/libLLVMMBlazeAsmPrinter.a /Users/arthur/anaconda/lib/libLLVMMBlazeAsmParser.a /Users/arthur/anaconda/lib/libLLVMMBlazeInfo.a /Users/arthur/anaconda/lib/libLLVMCppBackendCodeGen.a /Users/arthur/anaconda/lib/libLLVMCppBackendInfo.a /Users/arthur/anaconda/lib/libLLVMMSP430CodeGen.a /Users/arthur/anaconda/lib/libLLVMMSP430Desc.a /Users/arthur/anaconda/lib/libLLVMMSP430Info.a /Users/arthur/anaconda/lib/libLLVMMSP430AsmPrinter.a /Users/arthur/anaconda/lib/libLLVMXCoreDisassembler.a /Users/arthur/anaconda/lib/libLLVMXCoreCodeGen.a /Users/arthur/anaconda/lib/libLLVMXCoreDesc.a /Users/arthur/anaconda/lib/libLLVMXCoreInfo.a /Users/arthur/anaconda/lib/libLLVMXCoreAsmPrinter.a /Users/arthur/anaconda/lib/libLLVMMipsDisassembler.a /Users/arthur/anaconda/lib/libLLVMMipsCodeGen.a /Users/arthur/anaconda/lib/libLLVMMipsAsmParser.a /Users/arthur/anaconda/lib/libLLVMMipsDesc.a /Users/arthur/anaconda/lib/libLLVMMipsInfo.a /Users/arthur/anaconda/lib/libLLVMMipsAsmPrinter.a /Users/arthur/anaconda/lib/libLLVMARMDisassembler.a /Users/arthur/anaconda/lib/libLLVMARMCodeGen.a /Users/arthur/anaconda/lib/libLLVMARMAsmParser.a /Users/arthur/anaconda/lib/libLLVMARMDesc.a /Users/arthur/anaconda/lib/libLLVMARMInfo.a /Users/arthur/anaconda/lib/libLLVMARMAsmPrinter.a /Users/arthur/anaconda/lib/libLLVMAArch64Disassembler.a /Users/arthur/anaconda/lib/libLLVMAArch64CodeGen.a /Users/arthur/anaconda/lib/libLLVMAArch64AsmParser.a /Users/arthur/anaconda/lib/libLLVMAArch64Desc.a /Users/arthur/anaconda/lib/libLLVMAArch64Info.a /Users/arthur/anaconda/lib/libLLVMAArch64AsmPrinter.a /Users/arthur/anaconda/lib/libLLVMAArch64Utils.a /Users/arthur/anaconda/lib/libLLVMPowerPCCodeGen.a /Users/arthur/anaconda/lib/libLLVMPowerPCDesc.a /Users/arthur/anaconda/lib/libLLVMPowerPCAsmPrinter.a /Users/arthur/anaconda/lib/libLLVMPowerPCAsmParser.a /Users/arthur/anaconda/lib/libLLVMPowerPCInfo.a /Users/arthur/anaconda/lib/libLLVMSparcCodeGen.a /Users/arthur/anaconda/lib/libLLVMSparcDesc.a /Users/arthur/anaconda/lib/libLLVMSparcInfo.a /Users/arthur/anaconda/lib/libLLVMX86Disassembler.a /Users/arthur/anaconda/lib/libLLVMX86AsmParser.a /Users/arthur/anaconda/lib/libLLVMX86CodeGen.a /Users/arthur/anaconda/lib/libLLVMSelectionDAG.a /Users/arthur/anaconda/lib/libLLVMAsmPrinter.a /Users/arthur/anaconda/lib/libLLVMX86Desc.a /Users/arthur/anaconda/lib/libLLVMX86Info.a /Users/arthur/anaconda/lib/libLLVMX86AsmPrinter.a /Users/arthur/anaconda/lib/libLLVMX86Utils.a /Users/arthur/anaconda/lib/libLLVMMCDisassembler.a /Users/arthur/anaconda/lib/libLLVMMCParser.a /Users/arthur/anaconda/lib/libLLVMInterpreter.a /Users/arthur/anaconda/lib/libLLVMMCJIT.a /Users/arthur/anaconda/lib/libLLVMJIT.a /Users/arthur/anaconda/lib/libLLVMCodeGen.a /Users/arthur/anaconda/lib/libLLVMObjCARCOpts.a /Users/arthur/anaconda/lib/libLLVMScalarOpts.a /Users/arthur/anaconda/lib/libLLVMInstCombine.a /Users/arthur/anaconda/lib/libLLVMTransformUtils.a /Users/arthur/anaconda/lib/libLLVMipa.a /Users/arthur/anaconda/lib/libLLVMAnalysis.a /Users/arthur/anaconda/lib/libLLVMRuntimeDyld.a /Users/arthur/anaconda/lib/libLLVMExecutionEngine.a /Users/arthur/anaconda/lib/libLLVMTarget.a /Users/arthur/anaconda/lib/libLLVMMC.a /Users/arthur/anaconda/lib/libLLVMObject.a /Users/arthur/anaconda/lib/libLLVMCore.a /Users/arthur/anaconda/lib/libLLVMSupport.a -L/Users/arthur/anaconda/lib  -lz -lpthread -lm
rake aborted!
Error compiling
/Users/arthur/Downloads/rubinius-2.5.5/rakelib/vm.rake:240:in `block in <top (required)>'
Tasks: TOP => install => build:build => vm/vm
(See full trace by running task with --trace)

**Comment by arthurcolle** [comment]
Additional info:

1) rbx -v 
This is a compilation/build issue so I get: `zsh: command not found: rbx`

2) uname -a
Darwin colle-mac 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

I followed the instructions on rubini.us to build on Yosemite 10.10 and I got this output:
https://gist.github.com/arthurcolle/f4c472de4090cb2de4a9

**Comment by brixen** [comment]
You should be using `llvm-config` pointed to the `llvm-config` for your version of LLVM.

If you are using chruby, you can install a binary on OS X easily with Homebrew:

```
$ brew update
$ brew tap rubinius/apps
$ brew install rubinius
```

This will copy the Rubinius 2.5.5 release (or whatever is current at the time) into `~/.rubies` for use with chruby. Otherwise, it's a keg-only Homebrew install that you can choose to link.
