### ISSUE TITLE
Heroku Cedar-14 deployment

### ISSUE THREAD

**Issue by arthurcolle** [rubinius/rubinius#3430]
Per https://github.com/rubinius/rubinius/issues/3210, I tried to use this line to push to heroku:
`ruby "2.1.0", engine: 'rbx', engine_version: '2.3.0'`

I got these errors:
Is their copy of these gems corrupted, or does it have something to do with Rubinius? Thanks

https://gist.github.com/arthurcolle/5052201f0234f932c5ff

**Comment by arthurcolle** [comment]
@brixen I saw that you maintain Heroku/RBX support from another thread.

I changed the engine_version to 2.4.0 and it also gave me the same errors. 

https://gist.github.com/arthurcolle/35a9d9146c1ee1bb8585

**Comment by YorickPeterse** [comment]
Can you try using the latest version of Rubinius (2.5.5) instead of 2.3/2.4?

**Comment by brixen** [comment]
@arthurcolle current stable is 2.5.5. If you cannot use it, please open an issue for why not.

**Comment by arthurcolle** [comment]
Indeed it worked when I used 2.5.5, I actually used the rbx-2.5.5 binary locally and it was working but based on the previous comments of what people were using I just went with those, Heroku's pages do not document Rubinius support at all.

**Comment by brixen** [comment]
@arthurcolle I build the binaries used by Heroku with every release. We try to make sure it Just Works, but there's been some pains getting that process smoothed out. Unfortunately, I can't help with Heroku's documentation.

**Comment by arthurcolle** [comment]
No worries, I ♡ Heroku

**Comment by hubrix** [comment]
-----> Ruby app detected
-----> Compiling Ruby/Rack
 !
 !     An error occurred while installing Ruby ruby-2.1.0-rbx-2.5.8
 !     For supported Ruby versions see https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
 !     Note: Only the most recent version of Ruby 2.1 is supported on Cedar-14
 !     Command: 'set -o pipefail; curl -L --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 -O http://binaries.rubini.us/heroku/cedar-14/ruby-2.1.0-rbx-2.5.8.tar.bz2' failed unexpectedly:
 !     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
 !     Dload  Upload   Total   Spent    Left  Speed
 !     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 !     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 !     curl: (22) The requested URL returned error: 404 Not Found
 !
 !     Push rejected, failed to compile Ruby app

**Comment by chuckremes** [comment]
@hubrix Install the latest Rubnius release and that warning will disappear.

**Comment by hubrix** [comment]
we tried 3.10 and got clang errors on building native extensions
2.5.7 seems to work ok

**Comment by brixen** [comment]
@hubrix it seems your comment that I saw in email isn't showing here. I believe the clang errors are fixed in 3.16 but I have to build a Heroku binary for you to be able to test that. Now that we are using the 14.04 dist on Travis, we should be able to build the Heroku binary on release so we're not lagging on it.

I may be able to get the binary built today, but if not, it will be within a couple days.

**Comment by brixen** [comment]
@hubrix 3.16 should be working on Heroku https://blooming-chamber-2721.herokuapp.com
