### ISSUE TITLE
LICENSE still refers to 2014

### ISSUE THREAD

**Issue by chrisseaton** [rubinius/rubinius#3438]
The Rubinius license file still says `Copyright (c) 2007-2014`, but of course a lot of the code was written in 2015. When Truffle imports Rubinius code we are adding the license file as a header to all source files, but this now looks odd because we're saying 2014 on something that was clearly written in 2015 - but that's the license and we can't modify it.

To make this clear, we're adding a line in our README that explains this.

**Comment by jemc** [comment]
Thanks!
