### ISSUE TITLE
rbx-2.5.5 can't read xml text value in psql db column that rbx-2.2.10 could

### ISSUE THREAD

**Issue by ryan2johnson9** [rubinius/rubinius#3445]
I'm using Rails 4.1.6 with rbx 2.5.7 and psql db

I have a text field where xml strings are stored. I do not know why, but looking at these strings in pgadmin3 I see that they start with `---` or `--- |` or `--- |+` then following this is the xml. (these prefixes seem to have been added automatically)

When I use rbx 2.2.10 - I can retrieve all of these fields easily through a rails console.

When I switch to rbx 2.5.5 the value returned for the ones which have a prefix with a `|` is a blank string, even though there is a long xml there, as I can see with pgadmin3. I have also tried rbx-2.5.7 to no avail.

Here are some examples:

example value which can be read by both 2.2.10 and 2.5.5

```
--- "<?xml version=\"1.0\" encoding=\"UTF-8\"?>..."
```

in rails console returns

```
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>..."
```

example values which return blank string in rails console for 2.5.5:

```
--- |
<?xml version="1.0" encoding="UTF-8"?>...
```

and

```
--- |+
<?xml version="1.0" encoding="UTF-8"?>...
```

If I switch back to rbx 2.2.10 then it all works fine.

Any idea what the issue is - I don't even know why the `---`'s are there.

**Comment by YorickPeterse** [comment]
Not sure if I'm understanding the ticket correctly, but did you perhaps also update any Gems?

**Comment by ryan2johnson9** [comment]
Good question, I was wondering that myself.
`rbx-2.2.10@gemset_A`
works
`rbx-2.5.7@gemset_B`
fails.

When I list the gems for the individual gemset, i.e. excluding the global ones inherited ([using this technique](http://stackoverflow.com/questions/12307217/rvm-list-all-gems-in-current-gemset-ignoring-global-default)), I only get one difference.

rubinius-profiler (2.0.1) is in gemset_B and not in gemset_A at all

Of course there are a lot more differences when I use the simple `gem list`, but as far as I can tell I did not update any gems.

**Comment by ryan2johnson9** [comment]
The prefixed characters,`--- |` etc, that I can see through pgadmin3 may be a red herring.

I tried saving xml strings to that field when using rbx-2.5.7. Sometimes the prefix was `---` and one time it was `--- |` but every one of the fields was readable by rails console using rbx-2.5.7. However, if I switch back to rbx-2.2.10 and save an xml string, then try to read with rbx-2.5.7 in rails console I get the blank string.

Not sure if this is relevant, but i checked the encoding of the xml string before saving and it was `#<Encoding:ASCII-8BIT>`. Loading the saved string from console and checking the encoding shows `#<Encoding:UTF-8>`

To illustrate this problem I would make 2 apps, one in rbx-2.2.10 and one in rbx-2.5.5 (or .7) which shared the same database and had a button which saved a simple xml string to a db as a field in a basic model and another button to load and display these. If this is indeed a problem with rubinius then what we would see would be that the rbx-2.5.7 would display blank strings for anything saved by the rbx-2.2.10 app, but the rbx-2.2.10 app would be able to read all entries without problem. Perhaps I will get time to do this soon, but I've never done something like that before.

**Comment by brixen** [comment]
@ryan2johnson9 could you gist your Gemfile and Gemfile.lock?

**Comment by ryan2johnson9** [comment]
@brixen : 
[Gemfile] (https://gist.github.com/ryan2johnson9/b2e314de7f9611646c58)
[Gemfile.lock](https://gist.github.com/ryan2johnson9/cc6ea4d2249c840ca1fc)

**Comment by YorickPeterse** [comment]
@ryan2johnson9 Are the Gem versions also identical in both gemsets (excluding rubysl/rubinius Gems)?

**Comment by ryan2johnson9** [comment]
@YorickPeterse yes indeed they are

**Comment by ryan2johnson9** [comment]
I have got around this by using a script which writes the xml string to a file and I run this with  rbx2.2.10, then I change to rbx-2.5.7 and run a nother scrip which reads from this file and updates the attribute in the db. This has solved my personal problem.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
