### ISSUE TITLE
Matrix math is 2x slower that MRI

### ISSUE THREAD

**Issue by y8** [rubinius/rubinius#3447]
I'm trying to get more or less stable readings from my cheap ultrasonic range sensor, to measure a level of the water in my well. 

Sensor is constantly producing range readings, at rate about 7Hz, and writes readings to the CVS file. 

There a lot of noise in the data, so I've decided to use Kalman Filter. Filtering involves a lot of matrix math. You can watch this [video](https://www.udacity.com/course/artificial-intelligence-for-robotics--cs373) (Lesson 2), where this filter is explained. 

You can find my implementation [here](https://gist.github.com/y8/fea3892507db7bf3d1d0). There a very poor model of process, so output is still affected by measurement errors. 

Download the sample CSV file and run the filter: 

`ruby filter.rb 2015-06-22.csv`

It will output filtered CSV, and the total runtime. 

My tests results with different rubies:

```
; Runtime: 4.33
; ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]

; Runtime: 9.24
; rubinius 2.5.5 (2.1.0 433d9b8c 2015-05-15 3.5.1 JI) [x86_64-darwin14.4.0]

; Runtime: 10.82
; jruby 1.7.20.1 (1.9.3p551) 2015-06-10 d7c8c27 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_67-b01 +jit [darwin-x86_64]
```

As you can see, rbx and jruby are way slower than MRI.

[Here](https://gist.github.com/y8/d211a0b48002e2941c1f) the `benchmark/ips` for my Kalman filter implementation:

```
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]
Calculating -------------------------------------
              kalman   787.000  i/100ms
-------------------------------------------------
              kalman      8.024k (± 5.6%) i/s -     80.274k

rubinius 2.5.5 (2.1.0 433d9b8c 2015-05-15 3.5.1 JI) [x86_64-darwin14.4.0]
Calculating -------------------------------------
              kalman       283 i/100ms
-------------------------------------------------
              kalman     5026.3 (±15.5%) i/s -      48959 in  10.034451s

jruby 1.7.20.1 (1.9.3p551) 2015-06-10 d7c8c27 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_67-b01 +jit [darwin-x86_64]
Calculating -------------------------------------
              kalman       184 i/100ms
-------------------------------------------------
              kalman    11554.6 (±19.1%) i/s -     109296 in   9.975000s

jruby 9.0.0.0.pre1 (2.2.0p0) 2015-01-20 d537cab Java HotSpot(TM) 64-Bit Server VM 24.65-b04 on 1.7.0_67-b01 +jit [darwin-x86_64]
Calculating -------------------------------------
              kalman     6.000  i/100ms
-------------------------------------------------
              kalman      5.646k (±18.7%) i/s -     48.456k
```

**Comment by brixen** [comment]
It looks like most of the time is Array, not math _per se_.

[A histogram of the methods where most method calls originate](https://gist.github.com/brixen/f7e32e82667b40ffce06#file-gistfile1-txt).
[A profile](https://gist.github.com/brixen/f7e32e82667b40ffce06#file-gistfile2-txt).

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.
