### ISSUE TITLE
Regression in v2.5.7 vs v2.5.5: catching SIGINT and SIGTERM.

### ISSUE THREAD

**Issue by clonezone** [rubinius/rubinius#3455]
Given the program `catch-signal`:

```ruby
#!/usr/bin/env rbx

begin
    sleep 60
rescue SignalException => error
    puts "Got #{error}."
end

puts 'Done.'
```

running this with v2.5.5:

```
> ./catch-signal
^C
Got Thread has been interrupted.
Done.
```

with v2.5.7:
```
> ./catch-signal
^C
An exception occurred running ./catch-signal

Thread has been interrupted (Interrupt)

Backtrace:

  { } in Rubinius::Loader#signals at kernel/loader.rb:100
                        Proc#call at kernel/bootstrap/proc.rb:20
               Signal.run_handler at kernel/common/signal.rb:75
         Rubinius.received_signal at kernel/delta/rubinius.rb:215
```

Back to v2.5.5:

```
> ./catch-signal &
> kill %1
Got SIGTERM.                                                                                                                                         
Done.
>
```

And again with v2.5.7:

```
> ./catch-signal &
> kill %1
>
```

i.e. there's no output at all.

**Comment by jemc** [comment]
I believe a decision was made recently by other devs to not support `rescue SignalException` in order to improve other aspects of the threading model.

If you need this behavior, you'll have to make a case as to why you can't use actual signal traps in your application instead and how the benefits of supporting `rescue SignalException` outweigh the benefits of dropping support for it.

**Comment by clonezone** [comment]
Define "signal trap".

**Comment by jemc** [comment]
@clonezone - see [Signal.trap](http://ruby-doc.org/core-2.2.0/Signal.html#method-c-trap).

**Comment by brixen** [comment]
@clonezone please see https://github.com/rubinius/rubinius/commit/2928b6dd49ac4f734d4dd3b11a437322b3909ecb and https://github.com/rubinius/rubinius/commit/e32baa3128ce0e807cb224ca614e2df099ae013f for an explanation of the issues and mechanics of signal handling.

If you want to handle SIGTERM in your application, define a signal handler as follows:

```ruby
Signal.trap :TERM do
  puts "received SIGTERM, exiting..."
  exit 0
end

puts "I'm demonstrating how to properly handle OS signals..."
puts "Hit ^C now"

# pause execution indefinitely so that there is not a race to receive and
# handle the signal
sleep
```
Running this in the terminal gives:

```
$ ruby signal_handler.rb
I'm demonstrating how to properly handle OS signals...
Hit ^C now
^CAn exception occurred running signal_handler.rb

Thread has been interrupted (Interrupt)

Backtrace:

  { } in Rubinius::Loader#signals at kernel/loader.rb:100
                        Proc#call at kernel/bootstrap/proc.rb:20
               Signal.run_handler at kernel/common/signal.rb:75
         Rubinius.received_signal at kernel/delta/rubinius.rb:215
```

**Comment by clonezone** [comment]
I've got something that works now based upon this.

Thanks all.

**Comment by jemc** [comment]
Great!
