### ISSUE TITLE
Can't use Rubocop with Rubinius

### ISSUE THREAD

**Issue by wkoszek** [rubinius/rubinius#3457]
I'm wiring my Objective-C build to Travis-Ci and my Ruby build is fine, while my Rubinius build is failing:

https://travis-ci.org/wkoszek/macb/jobs/70179506
https://travis-ci.org/wkoszek/macb/jobs/70179507

Repo:
git clone https://github.com/wkoszek/macb.git

**Comment by brixen** [comment]
@wkoszek looks like there's a problem with RDoc parsing rubocop files that we'll need to fix. For now, you could disable generating rdoc and ri with gem installs. Unless your project is actually using them during CI, that's a huge waste of resources.

**Comment by jemc** [comment]
I'm able to `gem install rubocop` with rbx master.
```
 bin/rbx --version
rubinius 2.5.7.c40 (2.1.0 a292fce8 2015-07-07 3.5.0 JI) [x86_64-linux-gnu]
```
```
 bin/gem install rubocop
Fetching: ruby-progressbar-1.7.5.gem (100%)
Successfully installed ruby-progressbar-1.7.5
Fetching: ast-2.0.0.gem (100%)
Successfully installed ast-2.0.0
Fetching: parser-2.2.2.6.gem (100%)
Successfully installed parser-2.2.2.6
Fetching: astrolabe-1.3.0.gem (100%)
Successfully installed astrolabe-1.3.0
Fetching: powerpack-0.1.1.gem (100%)
Successfully installed powerpack-0.1.1
Fetching: rainbow-2.0.0.gem (100%)
Successfully installed rainbow-2.0.0
Fetching: rubocop-0.32.1.gem (100%)
Successfully installed rubocop-0.32.1
Parsing documentation for ruby-progressbar-1.7.5
Installing ri documentation for ruby-progressbar-1.7.5
Parsing documentation for ast-2.0.0
Installing ri documentation for ast-2.0.0
Parsing documentation for parser-2.2.2.6
Installing ri documentation for parser-2.2.2.6
Parsing documentation for astrolabe-1.3.0
Installing ri documentation for astrolabe-1.3.0
Parsing documentation for powerpack-0.1.1
Installing ri documentation for powerpack-0.1.1
Parsing documentation for rainbow-2.0.0
Installing ri documentation for rainbow-2.0.0
Parsing documentation for rubocop-0.32.1
Installing ri documentation for rubocop-0.32.1
Done installing documentation for ruby-progressbar, ast, parser, astrolabe, powerpack, rainbow, rubocop after 30 seconds
7 gems installed
```

It sounds like we just need to do a release so that Travis can use the latest version (unless something more subtle is going on here).

**Comment by YorickPeterse** [comment]
@jemc This might be an OS X (Travis) issue. I vaguely recall we had similar problems with RDoc in the distant past, but I believe that was due to the JIT (which has since been resolved).

**Comment by brixen** [comment]
@wkoszek I just realized your build is running `rubinius 2.2.6 (2.1.0 68d916a5 2014-03-10 JI) [x86_64-darwin13.1.0]` That's a version released over a year ago. The most recent release is 2.5.7. I see you've updated your `.travis.yml` to use `rbx-2`, so I'm assuming this is a problem with Travis or RVM.

**Comment by brixen** [comment]
@wkoszek sorry, it's finally registered that this is OS X and I need to build a binary for Travis. Once I do that, you can re-run your build and hopefully it will pull the latest version.

**Comment by wkoszek** [comment]
@brixen from the repo you'll see I started with rbx-2 since Travis advertises that. I spotted big version difference. I tried rbx-2.5.7, but Travis couldn't find it. So I reverted back to rbx-2. Weird thing is this:

https://travis-ci.org/wkoszek/macb/jobs/70180677

So looks like it succeeds sometimes. After README.md update, it failed once again:

https://travis-ci.org/wkoszek/macb/jobs/70181528

**Comment by brixen** [comment]
@wkoszek yeah, it's definitely an issue with 2.2.6. I've just pushed a build of 2.5.7 and I'm testing a fork of your project. I'll ping you once it's building correctly.

Sorry about the confusion, I completely did not grok that you were testing on OS X.

**Comment by wkoszek** [comment]
@brixen no worries. I agree it's confusing that Travis starts OSX on "objective-c", not on "osx" setting (which is a part of "multios"). This is my 1st project on Travis using OSX, and it uses Xcode.

Once it works, I'll migrate.

**Comment by brixen** [comment]
@wkoszek ok, this looks a lot better https://travis-ci.org/brixen/macb/jobs/70251810.

You shouldn't need to do anything more than restart your build. Let us know if you have further issues.

**Comment by wkoszek** [comment]
Other than:

warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Inspecting 1 file

Looks much better:

https://travis-ci.org/wkoszek/macb/jobs/70181528
