### ISSUE TITLE
Range#bsearch range is off by one

### ISSUE THREAD

**Issue by heftig** [rubinius/rubinius#3458]
`Range#bsearch` ignores the last element:
```
$ ruby -v -e 'p (1..5).bsearch { |i| i >= 5 }'
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
5
```
```
$ rbx  -v -e 'p (1..5).bsearch { |i| i >= 5 }'
rubinius 2.5.7 (2.1.0 d4fdeaad 2015-06-17 3.5.2 JI) [x86_64-linux-gnu]
nil
```

Similarly, for `1...5` the last included element `4` is missed.

Also, once this is fixed, maybe `Array#bsearch` should defer to `Range#bsearch` in order to share code?
```ruby
def bsearch
  return to_enum :bsearch unless block_given?
  index = (0...size).bsearch { |i| yield at(i) }
  index ? at(index) : nil
end
```

**Comment by heftig** [comment]
heftig@4afda40f adds a failing spec for this issue.

**Comment by YorickPeterse** [comment]
I added the specs in 9aa7833c1a0a2e3cd2a363441eb18b97489f182d but sadly I can't quite just figure out how to make things work. Looking at the behaviour of `Range#bsearch` and `Array#bsearch` we can't merge them as both work quite differently (the same appears to be the case for the MRI implementation).
