### ISSUE TITLE
Possible segmentation fault in the pg Gem

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3462]
Using the script from #3461 I now bumped into a segmentation fault in the pg Gem. GDB logs: https://gist.github.com/YorickPeterse/badd558a8799585a8ff3

Sadly I have no standalone way to reproduce this just yet.

**Comment by YorickPeterse** [comment]
Another GDB log which seems to describe a similar crash from the same script: https://gist.github.com/YorickPeterse/38b615002b061f3c09d5

**Comment by YorickPeterse** [comment]
And another one: https://gist.github.com/YorickPeterse/37d509f2e7428e4222ca

This fails with the following console output:

```
An exception occurred running populate_queue.rb

 (Aws::SQS::Errors::SignatureDoesNotMatch)

Backtrace:

 Seahorse::Client::Plugins::RaiseResponseErrors::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/plugins/raise_response_errors.rb:15
                    Aws::Plugins::ParamConverter::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/aws-sdk-core/plugins/param_converter.rb:21
       Seahorse::Client::Plugins::ResponseTarget::Handler#call at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/plugins/response_target.rb:21
                        Seahorse::Client::Request#send_request at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/request.rb:70
              { } in Aws::SQS::Client#define_operation_methods at /home/yorickpeterse/.gem/rbx/2.1.0/gems/aws-sdk-core-2.1.7/lib/seahorse/client/base.rb:207
                                      { } in Object#__script__ at populate_queue.rb:56
                                           Kernel(Object)#loop at kernel/common/kernel.rb:511
                                      { } in Object#__script__ at populate_queue.rb:51
                                                     Proc#call at kernel/bootstrap/proc.rb:20
                                                Thread#__run__ at kernel/bootstrap/thread.rb:352
row number 2443 is out of range 0..-939522665
row number 2443 is out of range 0..-939522665
row number 2443 is out of range 0..-939522665
row number 2443 is out of range 0..-939522665
row number 2444 is out of range 0..-939522665
row number 2444 is out of range 0..-939522665
row number 2444 is out of range 0..-939522665
utilities::thread: ~Condition: locked by another thread
```

**Comment by YorickPeterse** [comment]
And _another_ one: https://gist.github.com/YorickPeterse/b4d59ccafe66b81ee09f

**Comment by brixen** [comment]
In general, the MRI C-API for Rubinius is deprecated, but that doesn't mean it will be going anywhere soon. Compatibility for C-extensions will continue to be evaluated on a case-by-case basis. However, C-extensions that depend on functions that examine or manipulate built-in MRI data structures will never be supported.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated.
