### ISSUE TITLE
JIT crash in the AWS grinder

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3464]
Another crash I experienced when running the script from #3461: https://gist.github.com/YorickPeterse/2d485203986dc227ccf2

This appears to be a JIT crash, though I'm not sure if the origin of the crash is in the JIT or if that is simply a byproduct of something else breaking first.

**Comment by brixen** [comment]
The Rubinius JIT is being rewritten from the ground up. To support this effort, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler infrastructure
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to work extensively on making the JIT extremely good.
