### ISSUE TITLE
Thread safety for ThreadGroup#add

### ISSUE THREAD

**Issue by godfat** [rubinius/rubinius#3467]
Previous discussion: https://github.com/rubinius/rubinius/commit/00c04b92b91f89d99d50a0197bcc9ea39a1b1bf5

Actually this was a long story... I am not sure where to start,
and I also forgot some details. At the time I was using ThreadGroup#add,
I proposed ThreadGroup locals: https://bugs.ruby-lang.org/issues/10658

If we got that, then I probably don't have to use ThreadGroup#add at all.
So it's thread safe or not would no longer be relevant, at least in this use case.

But since we don't have that, currently I am manipulating ThreadGroup manually,
therefore thread safety in ThreadGroup#add would be relevant.
It failed here: https://travis-ci.org/godfat/pork/jobs/71427711
(p.s. old Rubinius and MRI and JRuby all passed)

The failing code was:
https://github.com/godfat/pork/blob/pork-1.3.1/lib/pork/more/should.rb#L17
extracted here:
``` ruby
def execute mode, stat=Stat.new, *args
  thread = Thread.current
  original_group, group = thread.group, ThreadGroup.new
  original_stat = thread[:pork_stat]
  group.add(thread) # HERE
  thread[:pork_stat] = stat
  super(mode, stat, *args)
ensure
  thread[:pork_stat] = original_stat
  original_group.add(thread)
end
```

I am not sure if I am ok with simply wrapping a mutex around it,
because this might only be required on Rubinius, and I could
understand why Rubinius didn't make it thread safe, assuming
it's somehow an internal API...

I am really running into many ThreadGroup issues. I guess
there are too few people using it, and indeed I can't think
of other use cases for it, and I only need it for using
the `should` method along with parallel testings.
Well, how many people could run tests in parallels anyway...?
I guess this is simply not important enough :(

**Comment by godfat** [comment]
Great, thank you!

**Comment by brixen** [comment]
@godfat no problem, thanks for letting us know about your issue.
