### ISSUE TITLE
Missing method: TCPServer#local_address (and class Addrinfo?)

### ISSUE THREAD

**Issue by godfat** [rubinius/rubinius#3468]
Here's MRI:

```
> ruby -vrsocket -e'p TCPServer.new(0).local_address'
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
#<Addrinfo: 0.0.0.0:37808 TCP>
```

Here's JRuby:

```
> jruby -vrsocket -e'p TCPServer.new(0).local_address'
jruby 1.7.20.1 (1.9.3p551) 2015-06-10 d7c8c27 on OpenJDK 64-Bit Server VM 1.8.0_45-b14 +jit [linux-amd64]
#<Addrinfo: 0:0:0:0:0:0:0:0:48859>
```

Discovered by:
https://travis-ci.org/godfat/rest-core/jobs/63995780

Should I add a spec to RubySpec..? Or is it merged into Rubinius now?

**Comment by YorickPeterse** [comment]
Since this deals with the Socket library this should be submitted to https://github.com/rubysl/rubysl-socket instead.

**Comment by YorickPeterse** [comment]
Ah, and it already exists there: https://github.com/rubysl/rubysl-socket/issues/7 and https://github.com/rubysl/rubysl-socket/pull/9.

**Comment by godfat** [comment]
Excellent. Sorry for the noise.
