### ISSUE TITLE
Implicit `super` call fails with double splat

### ISSUE THREAD

**Issue by robin850** [rubinius/rubinius#3471]
Hello,

There's a tiny bug when calling `super` without explicitly specifying the argument using the double splat:

~~~ruby
class Foo
  def foo(**options)
  end
end

class Bar < Foo
  def foo(**options)
    super
  end
end

Bar.new.foo
~~~

will raise:

~~~
method 'foo': given 1, expected 1 (ArgumentError)
~~~

Have a nice day.

**Comment by YorickPeterse** [comment]
Probably the same problem as described in #3295.

**Comment by YorickPeterse** [comment]
Closing as a duplicate of #3363
