### ISSUE TITLE
Scheduling Features for Threads

### ISSUE THREAD

**Issue by kwleland** [rubinius/rubinius#3473]
It would be helpful to be able to adjust thread scheduling

1.) policy  eg SCHED_FIFO
2.) core affinity
3.) priority

for a running thread. 

Of course this would only apply for OS's (such as Linux) that have the needed system call support.

Motivation:  I find that I can't always parallelize all the work and have one(two) thread(s) that provides a service that supports a ton of user threads.  In that case I would like the one (or two) thread(s) to have its own core(s) and the user threads to be corralled only to the other cores.  In this way I won't lose time to context switching on the relatively more sensitive (and higher priority) thread(s).

**Comment by brixen** [comment]
In general, Rubinius enthusiastically supports experimentation and welcomes ideas for features that enhance developer ability to create amazing software.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to support more efforts around experimentation.
