### ISSUE TITLE
OpenSSL isn't available anymore to build against on OSX 10.11 El Capitan

### ISSUE THREAD

**Issue by lloeki** [rubinius/rubinius#3478]
Therefore OpenSSL is now a third-party dependency, so this is how I built rbx:

```
brew tap homebrew/versions
brew install llvm35 openssl
# since I use rbenv/ruby-build, using configure --with-lib-dir and --with-include-dir looks like the following
RUBY_CONFIGURE_OPTS="--with-lib-dir=$(brew --prefix openssl)/lib --with-include-dir=$(brew --prefix openssl)/include" rbenv install rbx-2.5.8
```

`ruby-build` will probably [make things easier in the future](https://github.com/sstephenson/ruby-build/issues/797) and ruby-install may be unaffected (IIRC unconditionally uses brew anyway, but not sure), yet those using the source directly may be in for a surprise nonetheless.

**Comment by YorickPeterse** [comment]
Other than updating the installation guide (which is in https://github.com/rubinius/rubinius.github.io) I'm not sure what we can do regarding openssl no longer being installed by default.

**Comment by lloeki** [comment]
Nothing much, really :-) I'm just reporting this to save people time (it's very non-obvious especially since the libs are still there and the header locations are hard to find).

The only thing besides doc may be adding a `--with-openssl-dir=` to configure, making things slightly easier and incidentally identical to Ruby's one.

**Comment by YorickPeterse** [comment]
OK, in that case I'll be closing this issue. If you'd like to you can add a note about this to https://github.com/rubinius/rubinius.github.io/blob/master/doc/en/getting-started/requirements.markdown.

**Comment by brixen** [comment]
@lloeki have you considered using our Homebrew binary so you don't have to worry about building?

```
brew update
brew tap rubinius/apps
brew install rubinius
```

If this option doesn't work well for you, I'd love to hear why so hopefully we can fix it. Ideally, people won't need to build from source.

**Comment by lloeki** [comment]
@brixen I confirm this works, yet it doesn't integrate well with rbenv. My rubies are in `~/.rbenv/versions`, this way `gem install` doesn't make a mess in `/usr/local/bin` (not the case of those rubinius binaries, but it is for brew's ruby), especially when multiple versions of ruby are side by side and you regularly hop between them.

**Comment by brixen** [comment]
@lloeki the Homebrew recipe works with chruby and it could work with rbenv. Would you be interested in doing a PR to have it copy stuff to the rbenv dirs if you have rbenv enabled?

**Comment by jc00ke** [comment]
Is it possible to pass options into `brew install`? Looks like we hardcode the path [here](https://github.com/rubinius/homebrew-apps/blob/54ef94bbea3b84f0e7e20a8cb2d9a3292b15cf92/rubinius-2.5.8.rb#L18)

**Comment by brixen** [comment]
@jc00ke we just need to handle the chruby and rbenv cases separately, no need to pass anything in. It can copy in for both chruby and rbenv, depending on which (or both) are present.

**Comment by mislav** [comment]
As far as rbenv & ruby-build are concerned, I've just released a new ruby-build version that adds definitions for Rubinius 2.6 through 2.9 and transparently solves the Homebrew openssl linking issue https://github.com/rbenv/ruby-build/pull/857. If Homebrew openssl is not available, the latest version of OpenSSL will automatically be built for Mac. This is the same approach that we take for MRI installs as well.

**Comment by brixen** [comment]
Thanks @mislav, that sounds awesome. :heart:

**Comment by brixen** [comment]
@mislav unsure if you have a policy about what versions you support in rbenv, but one note about this: I'd recommend only supporting the latest Rubinius release and possibly one prior (in case the release is borked). I'm happy to add an auto-PR to rbenv from our deploy process if you wish. Possibly even just adding a "latest" to rbenv that we can modify (similar to how our https://github.com/rubinius/homebrew-apps/blob/master/rubinius.rb works).

The benefits of this approach are:

1. Reduced work for the rbenv team.
2. More clarity from rbenv for developers installing Rubinius via rbenv.
3. Better communication from Rubinius via rbenv for developers using rbenv.
4. Helpful pressure to use the latest Rubinius.

ICYMI, you can read about our [versioning scheme](http://rubinius.com/2015/09/22/major-minor-maximize-delivering-features-minimize-trouble/) and [release process](http://rubinius.com/2015/09/23/distributed-coding-distributed-releases/).

**Comment by mislav** [comment]
> I'd recommend only supporting the latest Rubinius release and possibly one prior

I get what you're coming from, but that goes against our versioning policy in ruby-build. We prefer to add a version using a specific release number (such as 2.9.0) and keep it that way basically forever. This also plays well with rbenv. If "latest" meant different versions at different times, it would be confusing to predict which actual version do you have installed and in use right now.

**Comment by brixen** [comment]
@mislav that's cool, I appreciate you explaining your policy on this.

The four items I listed are still relevant. Since it's your work, if the load is acceptable, it's all good. But the volume of Rubinius releases will be an order of magnitude higher (the version post and release post explain why). As I said, I'm happy to automatically send you a PR from our deploy process if that would help.

From my perspective as an implementer, one of the most frustrating things is having a component in our delivery pipeline that makes the user's experience worse. When Ruby installers don't advertise the latest release and developers are still installing a year-old version of Rubinius, we aren't able to give them the value that we are trying to deliver. A month-old version of Rubinius is typically very old.

So, if you can help improve 2-4 above, even a little, it would be greatly appreciated.

**Comment by mislav** [comment]
> As I said, I'm happy to automatically send you a PR from our deploy process if that would help.

That would be great. Also, some information which LLVM version is a specific release compatible with would also be great. We're kinda "requiring" LLVM 3.5 for rbx 2.5–2.10, but I'm pretty sure some of those releases would also be compatible with LLVM 3.6—only I'm not sure which ones exactly.

**Comment by lloeki** [comment]
> When Ruby installers don't advertise the latest release and developers are still installing a year-old version of Rubinius, we aren't able to give them the value that we are trying to deliver

To wit: a bad sort on my part led me to think I was installing the latest (2.5.something) rbx, when in fact I was trying and failing to install 2.2.10 or something. Entirely my fault, but I was stumped and even opened an issue upstream, losing everyone's time along with my own.

A simple notice (maybe triggered by some hypothetical "deprecate" function call inside the ruby-build file) when installing with rbenv/ruby-build that "this version is deprecated upstream" would have steered me clear.

**Comment by brixen** [comment]
@mislav RE dependencies like LLVM version, I'm looking at building that into our configure / build script, so you could run eg `./build --deps` and it will list all the expected dependencies for that platform. Also, there's a hard break between LLVM 3.5 and 3.6 because in 3.6, they removed the JIT APIs we use. I'm not going to support both APIs so once 3.6+ support is in Rubinius, 3.5 won't be usable.

If you have suggestions on how better to communicate to projects like rbenv, let me know.
