### ISSUE TITLE
Wrong result from proxy'd method (using method_missing) after JIT  

### ISSUE THREAD

**Issue by sshao** [rubinius/rubinius#3483]
Originally caught on rbx-1.8.7 + ActiveRecord, but reproducible on master without ActiveRecord:

``` ruby
class A
  def self.===(object)
    object.is_a?(self)
  end
end

class Proxy
  instance_methods.each { |m| undef_method m unless m =~ /(^__|^nil\?$|^send$|proxy_)/ }

  def initialize(c)
    @target = c
  end

  def method_missing(method, *args, &block)
    @target.send(method, *args, &block)
  end
end

a_obj = A.new
p_obj = Proxy.new(a_obj)

puts "Before A#=== is jitted:"
puts "A === a_obj: #{A === a_obj}" # returns true
puts "A === p_obj: #{A === p_obj}" # returns true

while !A.method(:===).executable.jitted? do
  A === a_obj
end

puts "\nAfter A#=== is jitted:"
puts "A === a_obj: #{A === a_obj}" # returns true -- ok
puts "A === p_obj: #{A === p_obj}" # returns false -- wrong
```

``` shell
$ ruby -v
rubinius 2.5.8.c16 (2.1.0 32b4d39f 2015-07-31 3.5.1 JI) [x86_64-darwin13.4.0]
$ ruby repro.rb 
Before A#=== is jitted:
A === a_obj: true
A === p_obj: true

After A#=== is jitted:
A === a_obj: true
A === p_obj: false
```

I'm already working on this one.

**Comment by packrat386** [comment]
There's a way to reproduce both a good and a bad jit 

https://gist.github.com/packrat386/705000a226a28cf2f223

**Comment by brixen** [comment]
The Rubinius JIT is being rewritten from the ground up. To support this effort, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler infrastructure
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to work extensively on making the JIT extremely good.
