### ISSUE TITLE
2.5.8 fails rake's test suite

### ISSUE THREAD

**Issue by tmornini** [rubinius/rubinius#3486]
```
Expected "rbx: vm/linkedlist.cpp:38: void LinkedList::remove(LinkedList::Node*): Assertion `!head_->prev()' failed.\n" to be empty.
```

```
https://travis-ci.org/ruby/rake/jobs/76136658
```

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
