### ISSUE TITLE
Process.fork appears to be broken when used within Fiber.

### ISSUE THREAD

**Issue by ioquatix** [rubinius/rubinius#3487]
With the following test case:

```
pid = nil

$stderr.puts "I'm parent #{Process.pid}"

Fiber.new do
    pid = fork do
        $stderr.puts "I'm forked #{Process.pid}"
        exit(2)
    end
end.resume

puts "Hello from #{Process.pid}"

Process.waitpid(pid) if pid
```

I get the following behaviour:

```
^_^ > rvm use default
Using /Users/samuel/.rvm/gems/ruby-2.1.2
^_^ > ruby test.rb   
I'm parent 81016
Hello from 81016
I'm forked 81017
^_^ > rvm use rbx    
Using /Users/samuel/.rvm/gems/rbx-2.5.2
^_^ > ruby test.rb
I'm parent 81122
Hello from 81122
I'm forked 81123
Hello from 81123
```

In the case of rbx, it appears that somehow the forked process resumes at the end of the fiber. Even after reading through the rubinius code it's not immediately obvious how this happens.

Thanks for all your hard work on Rubinius.

**Comment by brixen** [comment]
I think the title of this issue may be misleading. Fork appears to work fine, but I'm guessing you expect `exit(2)` to immediately terminate the child process (which would seem like a reasonable thing to expect).

**Comment by ioquatix** [comment]
exit(2) by definition shouldn't exit the child process, it raises SystemExit. It's more concerning that Kernel::exit! doesn't, and also that somehow the process resumes execution out of the `Fiber#resume` call.

**Comment by ioquatix** [comment]
This might be considered slightly more shocking behaviour:

```
> rvm use ruby
Using /Users/samuel/.rvm/gems/ruby-2.2.3
^_^ > ruby test.rb 
I'm parent pid=85908 in thread #<Thread:0x007fd8708c0410>
I'm fiber pid=85908 in thread #<Thread:0x007fd8708c0410>
I'm exiting fiber pid=85908 in thread #<Thread:0x007fd8708c0410>
Hello from 85908 in thread #<Thread:0x007fd8708c0410>
I'm forked 85909 in thread #<Thread:0x007fd8708c0410>
^_^ > rvm use rbx
Using /Users/samuel/.rvm/gems/rbx-2.5.2
^_^ > ruby test.rb
I'm parent pid=86014 in thread #<Thread:0x154 id=1 run>
I'm fiber pid=86014 in thread #<Thread:0x154 id=1 run>
I'm exiting fiber pid=86014 in thread #<Thread:0x154 id=1 run>
Hello from 86014 in thread #<Thread:0x154 id=1 run>
I'm forked 86015 in thread #<Thread:0x154 id=1 run>
Hello from 86015 in thread #<Thread:0x154 id=1 run>
Child has run amok!
^_^ > cat test.rb 

pid = nil

$stderr.puts "I'm parent pid=#{Process.pid} in thread #{Thread.current}"

Fiber.new do
	$stderr.puts "I'm fiber pid=#{Process.pid} in thread #{Thread.current}"
	pid = fork do
		$stderr.puts "I'm forked #{Process.pid} in thread #{Thread.current}"
		exit!(2)
	end
	$stderr.puts "I'm exiting fiber pid=#{Process.pid} in thread #{Thread.current}"
end.resume

puts "Hello from #{Process.pid} in thread #{Thread.current}"

if pid == nil
	$stderr.puts "Child has run amok!"
end

Process.waitpid(pid) if pid
```

**Comment by ioquatix** [comment]
It doesn't make sense to me that the child process could somehow exit the `Fiber#resume` call and end up hitting `if pid == nil`. I simply can't comprehend how this is happening.

**Comment by ioquatix** [comment]
By the way dude, thanks for looking into this promptly :) I just wanted to support rbx with my gem `process-group`.

**Comment by brixen** [comment]
A couple possibly related commits: 2928b6dd49ac4f734d4dd3b11a437322b3909ecb, 14b60c279a90db2011c498e68a16537265645f16, 5cd5e885cebbb69b1f129413519fc3537f4e431a, e32baa3128ce0e807cb224ca614e2df099ae013f

The exit in the Fiber may not exit the thread the fiber is running on. This is just off the top of my head. I'll need to look into it.

**Comment by ioquatix** [comment]
Please feel free to use the specs in `process-group` they will give you a good idea if the issue is fixed or not. Although, I don't recommend you run it all because the child processes go nuts, just run one like the fork_spec.

**Comment by ioquatix** [comment]
This appears to still be an issue :)

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
