### ISSUE TITLE
Enhance method/constant cache invalidation tracking

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3488]
Currently there's the VM option `ic.debug` that can be used to display when method/constant caches are being invalidated. There are a few problems with this option:
1. It controls printing of both method _and_ constant cache (well, global serial increases to be exact) invalidations.
2. Because it's set as a VM option there will be a lot of noise generated by code loaded during boot (e.g. RubyGems). For many users this won't be useful.
3. To the best of my knowledge we don't expose any interface to Ruby to see where invalidations happen.

To solve this I'd like to propose 2 changes:
1. Two VM options to control printing of method/constant cache invalidations separately (e.g. `-Xmethod_cache.debug` and `-Xconstant_cache.debug`)
2. A Ruby interface similar to the profiler (used by the above option)

I envision the Ruby interface would look something like this:

``` ruby
require 'rubinius/cache-tracer' # or whatever we'd call it

results = Rubinius::CacheTracer.trace do
  # some code here
end

results.each do |result|
  p result.location # => #<Rubinius::Location 0x00......>
  p result.type # => :constant
  p result.receiver # => #<Object 0x0 ...>
  p result.method => # :extend
end
```

For global tracing there would be `Rubinius::CacheTracer.start` and `Rubinius::CacheTracer.stop`, which would be used by the block form.

There is one tricky thing here: would tracing samples be collected thread-local, or globally? If they were to be collected globally (probably the easiest) we should _at least_ include the thread IDs/Objects in the result entries. This would allow application code to filter out traces from certain threads.

Issue that inspired this request: https://gitlab.com/gitlab-org/gitlab-ce/issues/2343

**Comment by YorickPeterse** [comment]
Another interesting feature would be the ability to run the tracer in the background using some sort of firehose like setup. That is, a block is invoked in the background every time a certain cache is busted. This would allow applications to log these events as they occur _without_ slowing down the application itself. Example mockup:

```ruby
Rubinius::CacheTracer.background do |event|
  event.type # => :method_cache_invalidation
  event.receiver # => #<Object 0x0 ...>
  event.method # => :extend

  send_to_newrelic_or_whatever(event)
end
```

**Comment by jemc** [comment]
Something to keep in mind while designing is that I think we want to eventually break the Ruby-specific behaviors of constant and method caching out of the core VM (generic language platform), making those caching primitives generic enough to be useful to other languages.  These Ruby-specific behaviors (like integration with `method_missing` and `const_missing`) would be lifted to a higher layer, which could potentially be written in Ruby itself, giving the additional benefit that tracing hooks like you're asking for could be easier to implement because the objects are already in Ruby-space.

**Comment by YorickPeterse** [comment]
@jemc This is largely already the case. There's `Rubinius.inc_global_serial` which is called in a bunch of places in the kernel code. In theory this tracer could hook into this method, but then it would only be invoked from within Ruby (and not any C++ code that might also increment the serial).

**Comment by brixen** [comment]
In general, Rubinius enthusiastically supports experimentation and welcomes ideas for features that enhance developer ability to create amazing software.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to support more efforts around experimentation.
