### ISSUE TITLE
Arity not consistent on rbx vs. CRuby, JRuby

### ISSUE THREAD

**Issue by bf4** [rubinius/rubinius#3491]
e.g. https://travis-ci.org/rails-api/active_model_serializers/jobs/77546313 in https://github.com/rails-api/active_model_serializers/pull/1004 where 

``` ruby
class Foo
  def my_method(name)
    # something
  end
end
```

has an arity of 1 on CRuby and JRub and rbx

whereas

``` ruby
class Foo
  alias :my_method, :send
end
```

has an arity of -1 on CRuby and JRuby, but appears to have an arity of -2 on rbx

(note: details may be inexact as I haven't been able to install rbx on any of my machines for a long while. So, just trying to be helpful)

This is a new rbx-only failure on this PR. Previously it was https://github.com/rails-api/active_model_serializers/pull/1004#issuecomment-121141494

Rbx is a drop-in replacement for CRuby except when it isn't :)

**Comment by benlovell** [comment]
```
irb(main):006:0> RUBY_ENGINE
=> "rbx"
irb(main):007:0> class Foo
irb(main):008:1> def meth(a); end
irb(main):009:1> end
=> :meth
irb(main):010:0> Foo.new.method(:meth).arity
=> 1
irb(main):011:0> class Foo
irb(main):012:1> alias :meth :send
irb(main):013:1> end
=> Foo
irb(main):014:0> Foo.new.method(:meth).arity
=> -2
irb(main):015:0> Foo.new.method(:send).arity
=> -2
```

**Comment by benlovell** [comment]
Oh, and JRuby

```
irb(main):001:0> RUBY_ENGINE
=> "jruby"
irb(main):002:0> class Foo
irb(main):003:1> def meth(a); end
irb(main):004:1> end
=> :meth
irb(main):005:0> Foo.new.method(:meth).arity
=> 1
irb(main):006:0> class Foo
irb(main):007:1> alias :meth :send
irb(main):008:1> end
=> nil
irb(main):009:0> Foo.new.method(:meth).arity
=> -1
```

**Comment by tak1n** [comment]
Send is defined here: https://github.com/rubinius/rubinius/blob/master/kernel/common/kernel.rb#L771

```
~ ❯❯❯ chruby 2.2.3
~ ❯❯❯ irb
irb(main):001:0> class Foo
irb(main):002:1> def method1(a, *args)
irb(main):003:2> end
irb(main):004:1> end
=> :method1
irb(main):005:0> Foo.new.method(:method1).arity
=> -2
irb(main):006:0> exit
~ ❯❯❯ chruby rbx
~ ❯❯❯ irb
irb(main):001:0> class Foo
irb(main):002:1> def method1(a, *args)
irb(main):003:2> end
irb(main):004:1> end
=> :method1
irb(main):005:0> Foo.new.method(:method1).arity
=> -2
irb(main):006:0> exit
```

Not sure anymore how primitives work exactly and whether we can affect this through the primitive.

**Comment by jemc** [comment]
@tak1n Primitives are created through code generation, and you can find them in the C++ area of the source by searching for the corresponding "magic comment" which marks a C++ method declaration in a class header as a primitive for code generation.

For example, here is the "magic comment" for the `object_send` primitive:
https://github.com/rubinius/rubinius/blob/dbd33a6dadd407041fcafa6651986ae02551f3ee/vm/builtin/object.hpp#L184

And here is the implementation of that marked C++ method (`Object::private_send_prim`):
https://github.com/rubinius/rubinius/blob/dbd33a6dadd407041fcafa6651986ae02551f3ee/vm/builtin/object.cpp#L563-L565

**Comment by tak1n** [comment]
Thx, for this refresher :)

**Comment by YorickPeterse** [comment]
Am I correct in understanding that rails-api apparently has some form of dependency on `Object#send` having an arity of -1? Or is this something only used in the test suite? Is there a way we can perhaps remove that dependency?

The reason MRI returns an arity of -1 is because it basically has the signature `send(*args)`, though it's defined in the C code. In Rubinius we instead have the signature `send(method, *args)` as it removes the need for code such as `method = args.shift`.

I'd argue that depending on the specific arity here is a bad idea. MRI effectively mimics the requirement of a single argument by manually raising `ArgumentError` if no arguments are passed to `Object#send` (https://github.com/ruby/ruby/blob/d5ec9ec308dccaeea2a723e070a98df4159183de/vm_eval.c#L909-L911). Rubinius in turn simply specifies at least 1 required argument. As a result of this depending on the arity to determine the correct amount of arguments to pass doesn't actually work reliably for `Object#send`. Thus depending on this is a bad idea.

Also because of this I'm strongly in favour of _keeping_ our `Object#send` as it is. After all we're just using Ruby here instead of replicating its behaviour in C/C++/Java/whatever.

**Comment by bf4** [comment]
@YorickPeterse I guess it's a philosophical question on some level.  If Rbx prefers to define send with a different arity, how do you think I should test that a class has the 'read_attribute_for_serialization' interface, since I'm not interested in behavior.  Is checking the arguments (arity) too strict, you think?  Or check >= 1 instead?

**Comment by YorickPeterse** [comment]
@bf4 Why does the test specifically test the arity of `send`? Can you not use a method of which the arity is consistent across implementations (e.g. a method specifically defined for the purpose of the test)?

**Comment by bf4** [comment]
@YorickPeterse because that's how Rails defines it in [ActiveModel::Serialization](https://github.com/rails/rails/blob/4-2-stable/activemodel/lib/active_model/serialization.rb#L125-L141)

```ruby
      # Hook method defining how an attribute value should be retrieved for
      # serialization. By default this is assumed to be an instance named after
      # the attribute. Override this method in subclasses should you need to
      # retrieve the value for a given attribute differently:
      #
      #   class MyClass
      #     include ActiveModel::Serialization
      #
      #     def initialize(data = {})
      #       @data = data
      #     end
      #
      #     def read_attribute_for_serialization(key)
      #       @data[key]
      #     end
      #   end
      alias :read_attribute_for_serialization :send
```

**Comment by bf4** [comment]
BTW, here's the current implementation in [`ActiveModel::Serializer::Lint::Tests`](https://github.com/rails-api/active_model_serializers/blob/1f08865a10bb06648efc170768c8c9937d441f45/lib/active_model/serializer/lint.rb#L30-L48)

```ruby
    # Passes if the object responds to <tt>read_attribute_for_serialization</tt>
    # and if it requires one argument (the attribute to be read).
    # Fails otherwise.
    #
    # <tt>read_attribute_for_serialization</tt> gets the attribute value for serialization
    # Typically, it is implemented by including ActiveModel::Serialization.
    def test_read_attribute_for_serialization
      assert_respond_to resource, :read_attribute_for_serialization, 'The resource should respond to read_attribute_for_serialization'
      actual_arity = resource.method(:read_attribute_for_serialization).arity
      if defined?(::Rubinius)
        #  1 for def read_attribute_for_serialization(name); end
        # -2 for alias :read_attribute_for_serialization :send for rbx because :shrug:
        assert_includes [1, -2], actual_arity, "expected #{actual_arity.inspect} to be 1 or -2"
      else
        # using absolute value since arity is:
        #  1 for def read_attribute_for_serialization(name); end
        # -1 for alias :read_attribute_for_serialization :send
        assert_includes [1, -1], actual_arity, "expected #{actual_arity.inspect} to be 1 or -1"
      end
    end
```

**Comment by YorickPeterse** [comment]
Can you not do something like the following?:

```ruby
aliased = resource.method(:read_attribute_for_serialization).arity
actual = Object.instance_method(:send).arity

assert_equals(aliased, actual)
```

You can then add a similar test for the case where `read_attribute_for_serialization` delegates to something other than `Object#send`. In this particular case the actual arity value is irrelevant, as long as it matches the arity of the original method.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
