### ISSUE TITLE
Each iterator behaves differently on MRI 2.x and JRuby vs. rbx-2.5.8 when you modify an array during the iteration

### ISSUE THREAD

**Issue by dblock** [rubinius/rubinius#3494]
![each](https://cloud.githubusercontent.com/assets/542335/9579510/40eb61ac-4fc1-11e5-8184-a29e9b0769ea.gif)

```
letters = ['a']

letters.each do |letter|
  puts letter
  letters << 'b' if letters.count == 1
end
```

**Comment by YorickPeterse** [comment]
Please try the latest version of Rubinius (2.5.8), 2.2.10 is well over a year old.

**Comment by dblock** [comment]
Same problem with 2.5.8.

**Comment by benlovell** [comment]
For a little context:

>It is undefined behavior of iterators if the block modifies iterating
>object.  It may crash or fall in to infinite loop.
>matz.

http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/23633

If you'll put aside the sad reflection that parts of our _official_ language specification are spread disparately across ages old issue tracker posts.

**Comment by dblock** [comment]
I do think iterators should reliably continue iterating where they left off without looking ahead, it's like a staircase, if someone adds a step when you're on the last step you can't jump off :) I am actually digging through rubinius code to see if I can fix this. No promises.

**Comment by YorickPeterse** [comment]
@dblock I'd start with making sure that the snippet is supposed to work on MRI. That is, if it's expected behaviour or just left up to the implementation. We've (apparently) rejected this in the past due to it being undefined: https://github.com/rubinius/rubinius/issues/547

**Comment by dblock** [comment]
Interestingly this behavior has changed on HEAD? This passes right now:

``` ruby
  it "iterates over elements appended during iteration" do
    a = [1]
    all = []
    a.each do |el|
      a << 2 if el == 1
      all << el
    end
    all.should == [1, 2]
  end
```

**Comment by dblock** [comment]
It used to work similarly to MRI, specs were removed in https://github.com/rubinius/rubinius/commit/406a6651c3331254302359089eb7df3d834bd4e0

**Comment by brixen** [comment]
Mutating collections while iterating them is unsupported.
