### ISSUE TITLE
In MRI, WeakRef is a subclass of Delegator, but in Rubinius it isn't

### ISSUE THREAD

**Issue by chrisseaton** [rubinius/rubinius#3495]
`WeakRef` being a subclass of `Delegator` is described in the Ruby documentation and is also detectable at runtime with `.subclass` or modifications to `Delegator`.

I guess that this may be because Rubinius implements `WeakRef` in core, where `Delegator` is part of the standard library so not available at that point.

**Comment by brixen** [comment]
@chrisseaton is there some code that you've encountered that depends on WeakRef subclassing Delegator?

**Comment by chrisseaton** [comment]
No. I was going through the documentation for `WeakRef` thinking about codifying it into more specs and noticed this discrepancy.

**Comment by brixen** [comment]
@chrisseaton thanks for reporting this. If we get code in the wild that is realistically dependent on WeakRef subclassing Delegator, we'll probably just have to pull Delegator into core. Until then, I'm not inclined to support bad programming practices (eg Delegator should be transparent to clients of WeakRef properly using the WeakRef API).
