### ISSUE TITLE
Rubinius won't compile in RVM on Yosemite (error in rake)

### ISSUE THREAD

**Issue by ashmoran** [rubinius/rubinius#3497]
Sorry if this is already documented, I went round in circles a few times until I figured out the LLVM 3.5/3.6 issue, but I can't find this problem anywhere. On OS X 10.10.5, RVM head ("rvm 1.26.11 (master)"), I get this compile failure:

    % rvm install rbx-head -C --llvm-config=/usr/local/opt/llvm35/bin/llvm-config-3.5
    rbx-head - #removing src/rbx-head - please wait
    Checking requirements for osx.
    Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
    Requirements installation successful.
    ruby-2.2.3@rubinius - #regenerating binstubs - please wait
    HEAD is now at 70ba66f Expand $PID in Metrics filename.
    From git://github.com/rubinius/rubinius
     * branch            master     -> FETCH_HEAD
    Already up-to-date.
    git checkout master
    Copying from repo to src path...
    ruby-2.2.3@rubinius - #bundle install - please wait
    rbx-head - #configuring - please wait
    rbx-head - #compiling - please wait
    Error running '/Users/ashmoran/.rvm/wrappers/ruby-2.2.3@rubinius/rake install --trace',
    showing last 15 lines of /Users/ashmoran/.rvm/log/1441288133_rbx-head/rake.log
    /Users/ashmoran/.rvm/gems/ruby-2.2.3@rubinius/bin/ruby_executable_hooks:15:in `eval': /Users/ashmoran/.rvm/rubies/ruby-2.2.3/bin/rake:4: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '(' (SyntaxError)
    exec "$bindir/ruby" -x "$0" "$@"
                            ^
    	from /Users/ashmoran/.rvm/gems/ruby-2.2.3@rubinius/bin/ruby_executable_hooks:15:in `<main>'

I get the same error with and without the `-C` option.

Is there anything I can do to work around the problem or help diagnose it?

**Comment by YorickPeterse** [comment]
We can not help you with RVM specific problems. Instead either use something like chruby/ruby-install or compile from source.

**Comment by brixen** [comment]
@ashmoran as was stated by @YorickPeterse, we don't develop RVM and cannot help you with errors. RVM has had so many breaking errors for years that we highly recommend people not use it. In your case above, it appears that `ruby_executable_hooks` is trying to execute a SHELL script as Ruby.

To avoid issues like RVM, we are trying to improve binary building. If you are on OS X, we have a Homebrew package already built that automatically works with chruby.

```
$ brew update
$ brew tap rubinius/apps
$ brew install rubinius
```

If you need binaries for other platforms, let us know which platform and we'll see if we can either help the package developers for that platform or build a binary (like these http://binaries.rubini.us/index.txt).

**Comment by ashmoran** [comment]
@YorickPeterse – sorry, I didn't release it was an RVM issue. It's something like a year or two since I wrote any real code so I'm not familiar with the current tools and Rubies and I didn't understand the error.

@brixen Thanks! I just did `rvm implode` and now have Rubinius 2.5.8 happily installed :-)

**Comment by brixen** [comment]
@ashmoran woot! `rvm implode` is my favorite RVM command! :)

**Comment by dblock** [comment]
I opened https://github.com/rvm/rvm/issues/3542.
