### ISSUE TITLE
Nanoseconds as zeroes in file modification time

### ISSUE THREAD

**Issue by majioa** [rubinius/rubinius#3502]
It seems that in `rubinius` nanosecond in modification time of a file are absent, I got the following part of log from `travis-ci`:

    000000000-Wed Sep  9 16:55:57 2015
    000000000-Wed Sep  9 16:55:57 2015

Here at the beginning 9 zeroes are nanoseconds of file modifications time. So I can use the time properly ....

**Comment by jc00ke** [comment]
```
➜ rubinius (master) stat -c "%y" README
2015-07-30 14:09:39.919141064 -0700
```

rbx
```
>> File.new("README")
>> f.mtime
=> 2015-07-30 14:09:39 -0700
>> f.mtime.nsec
=> 0
```

mri
```
>> File.new("README")
>> f.mtime
=> 2015-07-30 14:09:39 -0700
>> f.mtime.nsec
=> 919141064
```

**Comment by andre-richter** [comment]
This also affects atime and ctime!
I dug a bit into it, and it is a bit more complex than it seems at first glance.
Currently, rbx does not seem to support nanosecond members of struct stat (which were introduced in linux 2.6).

Here's the MRI patch that introduced them:
https://github.com/ruby/ruby/commit/a070c4fbe3cff184d224d1abb8a3101e3c11fc48

**Comment by andre-richter** [comment]
Started implementing a fix:
https://github.com/rubinius/rubinius/compare/2.2...andre-richter:2.2

Works on my machine, but couldn't test for the other Unixes which have different struct stat layouts.
```ruby
#!/usr/bin/env ruby

f = File.new(File.expand_path($0))
puts f.atime.nsec
puts f.mtime.nsec
puts f.ctime.nsec
```

```bash
andre@andre-desktop:~ (master)*$ ruby nsec.rb 
215014365
631056465
631056465
andre@andre-desktop:~ (master)*$ rubinius/bin/rbx nsec.rb 
215014365
631056465
631056465
```
Not sure if there is more to do somewhere else. What about https://github.com/rubinius/rubinius/blob/master/rakelib/platform.rake#L135-L164 ?

Do we need the timespec structs providing the nanoseconds there too?

**Comment by YorickPeterse** [comment]
@andre-richter Yes, if it's possible we should expose these new fields in platform.rake as well.

**Comment by andre-richter** [comment]
@YorickPeterse For now I surrender with the platform.rake stuff. Couldn't find a quick solution how to nest structs with FFI struct generators.

Will post a pull request for the rest, though. Also fixed File#utime which was related.

**Comment by andre-richter** [comment]
Maybe someone wants to check it on OSX beforehand.

**Comment by YorickPeterse** [comment]
@andre-richter Travis runs on OS X, so any obvious errors should pop up there.

**Comment by tak1n** [comment]
OS X specs are failing on travis ci for https://github.com/rubinius/rubinius/pull/3515

https://travis-ci.org/rubinius/rubinius/builds/85695115

**Comment by andre-richter** [comment]
Hmm, this will be hard to check for me since I don't have access to OSX atm.

In Travis the timespecs are found:
```
Checking for struct stat has member st_atimespec: found!
Checking for struct stat has member st_mtimespec: found!
Checking for struct stat has member st_ctimespec: found!
```

Therefore I suppose retrieving the usecs (https://github.com/rubinius/rubinius/commit/97b8fb37797c833ffb3f42fb4e3e71af07448468) should work on OSX.

Maybe there's something not working when setting them (https://github.com/rubinius/rubinius/commit/4de8eb50cf8b3eb7c888087295ed802d015722cd)?

**Comment by andre-richter** [comment]
http://stackoverflow.com/a/18404059
Seems to be a limitation of HFS+, which has a one second granularity.

Where to go from here? Remove the millisecond checks by reverting the spec?

**Comment by tak1n** [comment]
Not sure if we can reliable support os x here.
Maybe don't add the struct members if we are on os x for now?

**Comment by YorickPeterse** [comment]
Since pretty much everybody on OS X will be using HFS/HFS+ I suppose the best solution is to not use the new struct members on OS X.

**Comment by andre-richter** [comment]
The structs are fine and supported by OSX. OSX just returns 0 for the usec part when calling `stat` since HFS(+) doesn't support it.
In this case, it's the new specs I wrote which don't comply with a OSX/HFS environment.

**Comment by YorickPeterse** [comment]
In that case we should be able to add a simple operating system guard like so:

```ruby
platform_is_not :darwin do
  nano second specs here
end
```

**Comment by tak1n** [comment]
Also we should look what MRI does in this case, if they return 0 we can just return 0 either and as @YorickPeterse said use a spec guard here.
