### ISSUE TITLE
Array#sample sometimes returns duplicate results (when # of sampled items is 1/4 or less of array size)

### ISSUE THREAD

**Issue by alexdowad** [rubinius/rubinius#3506]
From `ri Array.sample`:

```
The elements are chosen by using random and unique indices into the array in
order to ensure that an element doesn't repeat itself unless the array already
contained duplicate elements.
```

When the number of sampled elements is 1/4 or less of the total array size, `rubinius/kernel/common/array.rb:1378-1390` attempts to use a faster method of selecting the random elements. Unfortunately, this faster code is buggy and can select the same element twice (or even more than twice).

The problem is that when it "spins" (tries selecting a new random element after finding the one it picked was a duplicate), it doesn't reset `j` to zero. The entire loop starting from line 1378 should be retried, with `j` reset to zero, every time it "spins".

**Comment by alexdowad** [comment]
Thanks @brixen!

**Comment by brixen** [comment]
@alexdowad no problem! Thanks for catching it. It's hard to test random behavior, although, in this case we could perhaps use a non-random rng fixture object as the second argument.
