### ISSUE TITLE
Rubinius reported it was installed successfully, but RVM could not find proper installation,

### ISSUE THREAD

**Issue by pedrorolo** [rubinius/rubinius#3508]
I am getting this with the current rvm version:

$ rvm install rbx
rbx-2.5.2 - #removing src/rbx-2.5.2.......
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.10/x86_64/rbx-2.5.2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Updating certificates in '/usr/local/etc/openssl/cert.pem'.
Requirements installation successful.
ruby-2.2.3-stable@rubinius - #regenerating binstubs............................-
rbx-2.5.2 - #downloading rubinius-2.5.2, this may take a while depending on your connection...
rbx-2.5.2 - #extracting rubinius-2.5.2 to /Users/pedro/.rvm/src/rbx-2.5.2......|
ruby-2.2.3-stable@rubinius - #bundle install..
rbx-2.5.2 - #configuring...
$LANG was empty, setting up LANG=en_US, if it fails again try setting LANG to something sane and try again.
rbx-2.5.2 - #compiling.....
Rubinius reported it was installed successfully, but RVM could not find proper installation,
please check why '/Users/pedro/.rvm/rubies/rbx-2.5.2/bin/rbx' was not created,
maybe here '/Users/pedro/.rvm/log/rbx-2.5.2/rake.log',
also make sure to report an error here 'https://github.com/rubinius/rubinius/issues'
about not returning non zero status in case of errors.

there's no rbx available in the end.

**Comment by YorickPeterse** [comment]
We can not help you with any RVM (or other version manager) related problems. Please try installing without RVM (e.g. by using Homebrew binaries or by building from source) to see if that works. When doing so make sure you're also using the latest version (2.5.8) instead of 2.5.2.
