### ISSUE TITLE
Statically allocating unmodified string literals

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3509]
Currently all strings, including literals, are allocated on the fly. For example, this will allocate a string for every iteration:

``` ruby
loop { 'Ruby' }
```

A more realistic example is the following:

``` ruby
some_list.map do |value|
  {'some_key' => value}
end
```

Here every iteration would allocate a String for the Hash key, a Hash and whatever comes along with a Hash. In both cases (and many other real world scenarios) these Strings are not modified, or at least very rarely.

MRI offers a workaround by calling `.freeze` on a String, turning it into an immutable statically allocated String. The obvious downside of this approach is having to call `.freeze` (or use the `f` suffix) on every darn String.

The solution I propose (and I'm just throwing this over the fence so I don't forget about it) is some heuristic that:
1. Determines if a String _literal_ is used in a mutable way or not
2. If the String is not mutated it's allocated statically and re-used

Whether this can be done during compilation remains to be seen. While the compiler _can_ know if a method mutates any instance variables, it _doesn't_ know what any primitives might do. One solution to this would be to just statically allocate literals right off the bat and copy them whenever mutated. Because this would be a runtime check we can handle primitives mutating Strings.

A compile time check would be most ideal as it removes any runtime overhead. What we could do is the following:
1. If a String method mutates an instance variable, tag the method as a "mutator" 
2. if a String method calls a primitive, also tag it as a "mutator"
3. If a method is called that calls a mutator method, also tag the method as a mutator (recursive)
4. If a mutator method is called on a String, allocate it as usual (`push_literal` + `string_dup`), if not we can skip the `string_dup`)

Regardless of whether we go with handling this during compilation or during runtime (or maybe in the JIT?), it would in theory led to far fewer String allocations _without_ having to use `.freeze` or the `f` suffix.

**Comment by YorickPeterse** [comment]
It's worth mentioning that this would _only_ apply to string *literals*. Dynamically created strings (e.g. those using string interpolation) would still be allocated every time.

**Comment by YorickPeterse** [comment]
Also, any statically allocated string would have to be marked as frozen. Code that depends on new object IDs for string literals will probably break. Bluntly put: that's not our problem.

**Comment by YorickPeterse** [comment]
Some more examples:

```ruby
def inspect
  values = @nodes.map(&:inspect).join(', ') # ', ' statically allocated

  "NodeSet(#{values})" # dynamically allocated
end

if name.include?(':')        # ':' statically allocated
  ns, name = name.split(':') # ':' statically allocated
else
  ns = nil
end

text = '' # dynamically allocated (due to String#<<)

text_nodes.each do |node|
  text << node.text
end

text
```

**Comment by jemc** [comment]
I don't think we have any mechanisms currently in place capable of the kind of static analysis you're talking about here.  There may be something we can do with the JIT, though - I'm not sure.

I think getting the static analysis would be a quite difficult and expansive project, but if done right would have many other performance optimization implications than just this narrow case.  Deep static analysis of side effects would enable some pretty sophisticated optimizations, if it is possible/practical at all.

**Comment by YorickPeterse** [comment]
Another thing to consider: dynamic method dispatching using `Object#send`. For example, if the compiler were to handle this the following could lead to nasty issues:

    obj = 'foo'
    obj.send(:downcase!)

As such a runtime check _might_ be easier to implement.

**Comment by jemc** [comment]
Right, there's lots of evil (pronounced `eval`) ways to mutate a string in Ruby, or make previously "safe" methods unsafe by redefining them, and accounting for all cases statically pretty much requires total static-analysis knowledge of all code that could be executed in the system, which is pretty impractical/impossible in Ruby.

So even if you have assumed "safe" methods or other "safe" constructs, you have to have some runtime way to "bail out" of the safe path if somebody has mucked it up.  I think this makes the JIT or some other runtime-oriented solution a more likely candidate for this kind of optimization.

**Comment by YorickPeterse** [comment]
@jemc Yeah, `eval` & friends definitely make this hard to do statically. Doing this on runtime would more or less require re-writing of bytecode on the fly. Take for example this code:

```ruby
name = 'ruby'
name.upcase!
```

The method `String#upcase!` _can_ check if it's operating on a static string and dup itself if so, but it can't replace the contents of `name` with this new string. Doing this in the JIT means having to command the JIT for every method called on a String, which I imagine being quite expensive (definitely more so than not optimizing anything at all).

**Comment by YorickPeterse** [comment]
Another option would be for strings to share their underlying byte arrays. Once a string would be modified it would copy the byte array and replace the old one with the copy. This would still require String allocations, but only at a portion of the current memory cost. This would also require a way to map string literals to pre-allocated byte arrays.

In theory this solution could be used to optimize all strings, but it would require a way to pre-determine what byte array to use for a chunk of input. The overhead of figuring this out might outweigh the benefits.

**Comment by jemc** [comment]
I think a copy-on-write layer inside the core string implementation is definitely worth pursuing.

**Comment by brixen** [comment]
In general, Rubinius enthusiastically supports experimentation and welcomes ideas for features that enhance developer ability to create amazing software.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to support more efforts around experimentation.
