### ISSUE TITLE
Undefined method `tcp' on Socket

### ISSUE THREAD

**Issue by saizai** [rubinius/rubinius#3510]
https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/transport/session.rb#L70 requires Socket.tcp.

This raises an error in rbx-2.5.8: 

    kernel/delta/kernel.rb:78:in `tcp (method_missing)'

See https://github.com/net-ssh/net-ssh/issues/276

**Comment by YorickPeterse** [comment]
Please report standard library errors at the corresponding rubysl repository. I moved this over to https://github.com/rubysl/rubysl-socket/issues/11.
