### ISSUE TITLE
Trying to install rbx2.5.8 using rvm on el capitan without success

### ISSUE THREAD

**Issue by scerelli** [rubinius/rubinius#3511]
I'm trying to install `rbx-2.5.8` using rvm on osx `10.11 el capitan` but i'm getting this error:

``` Detected old configuration settings, forcing a clean build
  Checking for 'llvm-config': only LLVM 3.0-3.5 is supported
ABORT: unable to set up LLVM ```

Since now i did: 

1. `brew install lvm`
2. `rvm install rbx-2.5.8 --1.9  -- --llvm-config /usr/local/opt/llvm/bin/llvm-config`
2. `rvm install rbx-master --url https://github.com/rubinius/rubinius.git --branch master`

and all other things i found on the first page of google. anyone have an idea on how to proceed?

**Comment by YorickPeterse** [comment]
> Detected old configuration settings, forcing a clean build Checking for 'llvm-config': only LLVM 3.0-3.5 is supported ABORT: unable to set up LLVM

As the error states this means you're using an incompatible version of LLVM, most likely LLVM 3.6. Rubinius requires LLVM <= 3.5. Other than that we can't help with RVM specific problems.

**Comment by scerelli** [comment]
UPDATE: 

`brew install homebrew/versions/llvm35`
`rvm install rbx-2.5.8 --1.9  -- --llvm-config /usr/local/opt/llvm35/bin/llvm-config `

it's the same thing

**Comment by YorickPeterse** [comment]
As I already stated we can not help with RVM (or other version manager) related problems. Please try building from source instead. Should that fail please open a separate issue with the information as listed in the contributing guide (https://github.com/rubinius/rubinius/blob/master/CONTRIBUTING.md#submitting-issues).

**Comment by scerelli** [comment]
OK, many thanks

**Comment by brixen** [comment]
@scerelli you can install Rubinius directly with Homebrew as follows:

```
$ brew update
$ brew tap rubinius/apps
$ brew install rubinius
```

Alternatively, if I recall correctly, RVM has a command to mount a directory instead of building from source, so you could fetch the Homebrew binary directly or tell RVM to mount the directory that the Homebrew package installs.

**Comment by nielsonrolim** [comment]
It worked for me:

`brew update
brew install homebrew/versions/llvm35
rvm install rbx -- --llvm-config /usr/local/opt/llvm35/bin/llvm-config-3.5`
