### ISSUE TITLE
v_2_5_8 Fails to Build on 64b Debian

### ISSUE THREAD

**Issue by martinvahi** [rubinius/rubinius#3514]
ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine$ ls
    rubinius-2.5.8.tar.bz2
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine$ bunzip2 ./rubinius-2.5.8.tar.bz2 
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine$ tar -xf ./rubinius-2.5.8.tar 
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine$ ls
    rubinius-2.5.8  rubinius-2.5.8.tar
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine$ cd rubinius-2.5.8/
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine/rubinius-2.5.8$ ls
    AUTHORS          Gemfile            library   README                            SECURITY      vendor
    bin              Gemfile.installed  LICENSE   README.md                         security.pub  vm
    configure        Gemfile.lock       mspec     rubinius-build_tools.gemspec      spec
    CONTRIBUTING.md  gems_list.txt      Rakefile  rubinius-developer_tools.gemspec  THANKS
    debian           kernel             rakelib   rubinius.gemspec                  tools
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine/rubinius-2.5.8$ ./configure --help
    Could not find daedalus-core-0.5.0 in any of the sources
    Run `bundle install` to install missing gems.
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine/rubinius-2.5.8$ bundle install
    Fetching gem metadata from https://rubygems.org/..
    Fetching version metadata from https://rubygems.org/..
    Using rake 10.4.2
    Installing daedalus-core 0.5.0
    Installing redcard 1.1.0
    Installing rubinius-ast 2.3.2
    Installing rubinius-bridge 1.1.0
    Installing rubinius-compiler 2.3.1
    Installing rubinius-melbourne 2.3.1.0 with native extensions
    
    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    
        /opt/2dot7TiB_k8vaketas/ts2/mittevarundatav/_home/m_local/bin_p/Ruby/paigaldatult/v_2_2_3/bin/ruby -r ./siteconf20151009-21268-11e9xvr.rb extconf.rb
    
    make "DESTDIR=" clean
    
    make "DESTDIR="
    compiling melbourne.cpp
    compiling node_types.cpp
    compiling encoding_compat.cpp
    compiling visitor.cpp
    compiling var_table.cpp
    compiling symbols.cpp
    compiling grammar.cpp
    linking shared-object melbourne.so
    /usr/bin/ld: cannot find -lruby
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    Makefile:48: recipe for target 'melbourne.so' failed
    make: *** [melbourne.so] Error 1
    
    make failed, exit code 2
    
    Gem files will remain installed in /home/ts2/m_local/bin_p/Ruby/paigaldatult/v_x_x_x_kasutuses/gem_home/gems/rubinius-melbourne-2.3.1.0 for inspection.
    Results logged to /home/ts2/m_local/bin_p/Ruby/paigaldatult/v_x_x_x_kasutuses/gem_home/extensions/x86_64-linux/2.2.0/rubinius-melbourne-2.3.1.0/gem_make.out
    An error occurred while installing rubinius-melbourne (2.3.1.0), and Bundler cannot continue.
    Make sure that `gem install rubinius-melbourne -v '2.3.1.0'` succeeds before bundling.
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine/rubinius-2.5.8$ uname -a
    Linux s8lm1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine/rubinius-2.5.8$ date
    Fri Oct  9 00:24:22 EEST 2015
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine/rubinius-2.5.8$ ruby -v
    ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine/rubinius-2.5.8$ gem -v
    2.4.5.1
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine/rubinius-2.5.8$

**Comment by jemc** [comment]
It's actually failing to install the gems used to build rubinius - you haven't actually gotten to the rubinius build yet.  The important part here is: `/usr/bin/ld: cannot find -lruby`.

It looks like some part of your environment is broken for using the ruby you are building with (looks like `2.2.3` at `/opt/2dot7TiB_k8vaketas/ts2/mittevarundatav/_home/m_local/bin_p/Ruby/paigaldatult/v_2_2_3`).  Specifically, your MRI ruby has a shared library component that the linker cannot find.

You need to fix your environment before building C extensions in MRI ruby 2.2.3 (one of which - melbourne - is required for building rubinius).  Specifically, you need to make sure the following command works at identifying your ruby shared library for your MRI ruby 2.2.3 : `ldconfig -p | grep libruby`.

**Comment by martinvahi** [comment]
Thank You for the anser. 

However, I think that it is quite self-evident that people want to use the "standard ruby"([ruby-lang.org](https://www.ruby-lang.org) by compiling one's own version of it, which results a situation, where the various libraries that come with the "standard ruby" reside at some place other than the system global set of libraries. To keep things clean, none of the global settings should be affected by some self-compiled experiment like the self-compiled "standard ruby". If Rubinius build system is not able to use the libraries that are available globally and demands a match between the ruby at the PATH and the libraries that go with the ruby console application that is available at the PATH, then, if I classify things to be broken according to my subjective taste, which can be a bit extreme, the Rubinius build system should INFER the location of the necessary libraries without demanding any global setup. After all, 

    dirname `dirname \`which ruby\``

gives the de facto "RUBY_HOME", which in my case happens to be 

    /home/ts2/m_local/bin_p/Ruby/paigaldatult/v_x_x_x_kasutuses

The "standard ruby" has a "lib" folder at its deployment deliverables. In my case

    ls ` dirname \`dirname \\\`which ruby\\\`\` `/lib/

gives

    ruby  x86_64-linux

I tried that with the LD_LIBRARY_PATH, but that did not work out either. The results of my new try are:

    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine/rubinius-2.5.8$ LD_LIBRARY_PATH="/home/ts2/m_local/bin_p/Ruby/paigaldatult/v_x_x_x_kasutuses/lib/x86_64-linux:$LD_LIBRARY_PATH" bundle install
    Fetching gem metadata from https://rubygems.org/..
    Fetching version metadata from https://rubygems.org/..
    Using rake 10.4.2
    Using daedalus-core 0.5.0
    Using redcard 1.1.0
    Using rubinius-ast 2.3.2
    Using rubinius-bridge 1.1.0
    Using rubinius-compiler 2.3.1
    Installing rubinius-melbourne 2.3.1.0 with native extensions
    
    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    
        /opt/2dot7TiB_k8vaketas/ts2/mittevarundatav/_home/m_local/bin_p/Ruby/paigaldatult/v_2_2_3/bin/ruby -r ./siteconf20151009-7761-ue5w5t.rb extconf.rb
    
    make "DESTDIR=" clean
    
    make "DESTDIR="
    compiling melbourne.cpp
    compiling node_types.cpp
    compiling encoding_compat.cpp
    compiling visitor.cpp
    compiling var_table.cpp
    compiling symbols.cpp
    compiling grammar.cpp
    linking shared-object melbourne.so
    /usr/bin/ld: cannot find -lruby
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    Makefile:48: recipe for target 'melbourne.so' failed
    make: *** [melbourne.so] Error 1
    
    make failed, exit code 2
    
    Gem files will remain installed in /home/ts2/m_local/bin_p/Ruby/paigaldatult/v_x_x_x_kasutuses/gem_home/gems/rubinius-melbourne-2.3.1.0 for inspection.
    Results logged to /home/ts2/m_local/bin_p/Ruby/paigaldatult/v_x_x_x_kasutuses/gem_home/extensions/x86_64-linux/2.2.0/rubinius-melbourne-2.3.1.0/gem_make.out
    An error occurred while installing rubinius-melbourne (2.3.1.0), and Bundler cannot continue.
    Make sure that `gem install rubinius-melbourne -v '2.3.1.0'` succeeds before bundling.
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine/rubinius-2.5.8$ ls -l /home/ts2/m_local/bin_p/Ruby/paigaldatult/v_x_x_x_kasutuses/lib/x86_64-linux
    total 14076
    lrwxrwxrwx 1 ts2 ts2      16 Aug 30 08:54 libruby.so -> libruby.so.2.2.0
    lrwxrwxrwx 1 ts2 ts2      16 Aug 30 08:54 libruby.so.2.2 -> libruby.so.2.2.0
    -rwxr-xr-x 1 ts2 ts2 9083784 Aug 30 08:43 libruby.so.2.2.0
    -rw-r--r-- 1 ts2 ts2 5316750 Aug 30 08:40 libruby-static.a
    drwxr-xr-x 2 ts2 ts2    4096 Aug 30 08:54 pkgconfig
    drwxr-xr-x 5 ts2 ts2    4096 Aug 30 08:54 ruby
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine/rubinius-2.5.8$ which ruby
    /home/ts2/m_local/bin_p/Ruby/paigaldatult/v_x_x_x_kasutuses/bin/ruby
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine/rubinius-2.5.8$ uname -a
    Linux s8lm1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
    ts2@s8lm1:~/m_local/bin_p/Ruby/kompileerimine/rubinius-2.5.8$ 
    
Well, different people do have different taste, but my taste is to keep global settings to a minimum to avoid various collisions and that what can be inferred, should be inferred. May be I misunderstood something again, so corrections, educational comments, etc. are all welcome. :-)

**Comment by YorickPeterse** [comment]
@martinvahi Rubinius doesn't care where your Ruby is located in PATH, as long as the `ruby` executable _is_ in PATH and as long as any shared libraries & headers needed for building C extensions can be found. This is no different from installing anything else that depends on Ruby (e.g. a Gem). 

If your Ruby headers and the likes are installed in a location that is not available by default to compilers then you'll have to fix that, there's nothing we can do about this.

**Comment by martinvahi** [comment]
Sounds good, except that generally when I use 

    gem install gemname

then everything works just fine. :-)

**Comment by jemc** [comment]
Are you able to `gem install rubinius-melbourne`?

**Comment by martinvahi** [comment]
Well, thank You for Your answer, but unfortunately I had to switch from my previous Debian installation to "something else", which by chance happens to be [openSUSE](https://www.opensuse.org/) and I'm not able to run the tests to reproduce the symptoms of the flaw. However, I can offer You new symptoms under the same title :-D

    ts2@linux-0fiz:~/m_local/bin_p/Ruby/Rubinius/kompil$ ls -l -a
    total 14484
    drwxr-xr-x  3 ts2 users     4096 Oct 12 17:48 .
    drwxr-xr-x  4 ts2 users     4096 Oct 12 17:47 ..
    drwxr-xr-x 13 ts2 users     4096 Oct  5 02:33 rubinius-master
    -rw-r-----  1 ts2 users 14815087 Oct 12 17:46 rubinius-master.zip
    ts2@linux-0fiz:~/m_local/bin_p/Ruby/Rubinius/kompil$ cd rubinius-master/
    ts2@linux-0fiz:~/m_local/bin_p/Ruby/Rubinius/kompil/rubinius-master$ ls -l -a
    total 204
    drwxr-xr-x 13 ts2 users  4096 Oct  5 02:33 .
    drwxr-xr-x  3 ts2 users  4096 Oct 12 17:48 ..
    -rw-r--r--  1 ts2 users  6047 Oct  5 02:33 AUTHORS
    -rw-r--r--  1 ts2 users  2967 Oct  5 02:33 .autotest
    drwxr-xr-x  2 ts2 users  4096 Oct  5 02:33 bin
    drwxr-xr-x  2 ts2 users  4096 Oct  5 02:33 .bundle
    -rwxr-xr-x  1 ts2 users 54307 Oct  5 02:33 configure
    -rw-r--r--  1 ts2 users  5098 Oct  5 02:33 CONTRIBUTING.md
    drwxr-xr-x  4 ts2 users  4096 Oct  5 02:33 debian
    -rw-r--r--  1 ts2 users   123 Oct  5 02:33 .editorconfig
    -rw-r--r--  1 ts2 users   383 Oct  5 02:33 .gdbinit
    -rw-r--r--  1 ts2 users   178 Oct  5 02:33 Gemfile
    -rw-r--r--  1 ts2 users   441 Oct  5 02:33 Gemfile.installed
    -rw-r--r--  1 ts2 users   654 Oct  5 02:33 Gemfile.lock
    -rw-r--r--  1 ts2 users  2776 Oct  5 02:33 gems_list.txt
    -rw-r--r--  1 ts2 users  1127 Oct  5 02:33 .gitignore
    drwxr-xr-x  6 ts2 users  4096 Oct  5 02:33 kernel
    drwxr-xr-x  7 ts2 users  4096 Oct  5 02:33 library
    -rw-r--r--  1 ts2 users  1496 Oct  5 02:33 LICENSE
    drwxr-xr-x  5 ts2 users  4096 Oct  5 02:33 mspec
    -rw-r--r--  1 ts2 users  5094 Oct  5 02:33 Rakefile
    drwxr-xr-x  2 ts2 users  4096 Oct  5 02:33 rakelib
    -rw-r--r--  1 ts2 users  2350 Oct  5 02:33 README
    -rw-r--r--  1 ts2 users  2776 Oct  5 02:33 README.md
    -rw-r--r--  1 ts2 users   724 Oct  5 02:33 rubinius-build_tools.gemspec
    -rw-r--r--  1 ts2 users   644 Oct  5 02:33 rubinius-developer_tools.gemspec
    -rw-r--r--  1 ts2 users   620 Oct  5 02:33 rubinius.gemspec
    -rw-r--r--  1 ts2 users  1104 Oct  5 02:33 SECURITY
    -rw-r--r--  1 ts2 users  3861 Oct  5 02:33 security.pub
    drwxr-xr-x 12 ts2 users  4096 Oct  5 02:33 spec
    -rw-r--r--  1 ts2 users   324 Oct  5 02:33 THANKS
    drwxr-xr-x  4 ts2 users  4096 Oct  5 02:33 tools
    -rw-r--r--  1 ts2 users  1172 Oct  5 02:33 .travis.yml
    drwxr-xr-x 10 ts2 users  4096 Oct  5 02:33 vendor
    drwxr-xr-x 15 ts2 users  4096 Oct  5 02:33 vm
    ts2@linux-0fiz:~/m_local/bin_p/Ruby/Rubinius/kompil/rubinius-master$ nice -n20 ./configure --prefix=/home/ts2/m_local/bin_p/Ruby/Rubinius/vd_2015_10_12
    /opt/2dot7TiB_k8vaketas/ts2/mittevarundatav/_home/m_local/bin_p/Ruby/paigaldatult/v_2_2_3_clang/lib64/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
    	from /opt/2dot7TiB_k8vaketas/ts2/mittevarundatav/_home/m_local/bin_p/Ruby/paigaldatult/v_2_2_3_clang/lib64/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    	from ./configure:4:in `<main>'
    ts2@linux-0fiz:~/m_local/bin_p/Ruby/Rubinius/kompil/rubinius-master$ gem install bundler
    Fetching: bundler-1.10.6.gem (100%)
    Successfully installed bundler-1.10.6
    Parsing documentation for bundler-1.10.6
    Installing ri documentation for bundler-1.10.6
    Done installing documentation for bundler after 13 seconds
    1 gem installed
    ts2@linux-0fiz:~/m_local/bin_p/Ruby/Rubinius/kompil/rubinius-master$ nice -n20 ./configure --prefix=/home/ts2/m_local/bin_p/Ruby/Rubinius/vd_2015_10_12
    Could not find daedalus-core-0.5.0 in any of the sources
    Run `bundle install` to install missing gems.
    ts2@linux-0fiz:~/m_local/bin_p/Ruby/Rubinius/kompil/rubinius-master$ bundle install
    Fetching gem metadata from https://rubygems.org/..
    Fetching version metadata from https://rubygems.org/..
    Using rake 10.4.2
    Installing daedalus-core 0.5.0
    Installing redcard 1.1.0
    Installing rubinius-ast 2.3.2
    Installing rubinius-bridge 1.1.0
    Installing rubinius-compiler 2.3.1
    Using rubinius-melbourne 2.3.1.0
    Installing rubinius-processor 2.3.0
    Installing rubinius-toolset 2.3.1
    Installing rubinius-build_tools 2.0.0
    Using bundler 1.10.6
    Bundle complete! 5 Gemfile dependencies, 11 gems now installed.
    Use `bundle show [gemname]` to see where a bundled gem is installed.
    ts2@linux-0fiz:~/m_local/bin_p/Ruby/Rubinius/kompil/rubinius-master$ nice -n20 ./configure --prefix=/home/ts2/m_local/bin_p/Ruby/Rubinius/vd_2015_10_12
    ------------------------- WARNING -----------------------
    The specified prefix '/home/ts2/m_local/bin_p/Ruby/Rubinius/vd_2015_10_12' already exists.
    Installing Rubinius into an existing directory may
    overwrite existing unrelated files or cause conflicts
    between different versions of Rubinius files.
    ---------------------------------------------------------
    Checking clang: found
    Checking clang++: found
    
    Detected old configuration settings, forcing a clean build
    The directory /home/ts2/m_local/bin_p/Ruby/Rubinius/vd_2015_10_12 already exists, installing to /home/ts2/m_local/bin_p/Ruby/Rubinius/vd_2015_10_12/rubinius/
      Checking for 'llvm-config': only LLVM 3.0-3.5 is supported
    ABORT: unable to set up LLVM
    
    Running 'configure' failed. Please check configure.log for more details.
    ts2@linux-0fiz:~/m_local/bin_p/Ruby/Rubinius/kompil/rubinius-master$ clang -v
    clang version 3.8.0 (trunk 249969)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    InstalledDir: /home/ts2/m_local/bin_p/LLVM/vd_2015_10_11/vd_2015_10_11_installed/bin
    Found candidate GCC installation: /usr/lib64/gcc/x86_64-suse-linux/4.8
    Found candidate GCC installation: /usr/lib64/gcc/x86_64-suse-linux/4.9
    Selected GCC installation: /usr/lib64/gcc/x86_64-suse-linux/4.8
    Candidate multilib: .;@m64
    Selected multilib: .;@m64
    ts2@linux-0fiz:~/m_local/bin_p/Ruby/Rubinius/kompil/rubinius-master$ clang++ -v
    clang version 3.8.0 (trunk 249969)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    InstalledDir: /home/ts2/m_local/bin_p/LLVM/vd_2015_10_11/vd_2015_10_11_installed/bin
    Found candidate GCC installation: /usr/lib64/gcc/x86_64-suse-linux/4.8
    Found candidate GCC installation: /usr/lib64/gcc/x86_64-suse-linux/4.9
    Selected GCC installation: /usr/lib64/gcc/x86_64-suse-linux/4.8
    Candidate multilib: .;@m64
    Selected multilib: .;@m64
    ts2@linux-0fiz:~/m_local/bin_p/Ruby/Rubinius/kompil/rubinius-master$ uname -a
    Linux linux-0fiz 3.16.7-24-desktop #1 SMP PREEMPT Mon Aug 3 14:37:06 UTC 2015 (ec183cc) x86_64 x86_64 x86_64 GNU/Linux
    ts2@linux-0fiz:~/m_local/bin_p/Ruby/Rubinius/kompil/rubinius-master$ date
    Mon Oct 12 17:53:24 EEST 2015
    ts2@linux-0fiz:~/m_local/bin_p/Ruby/Rubinius/kompil/rubinius-master$

The LLVM was custom-built within the "past" 48h from the newest published development version of its sources.

**Comment by jemc** [comment]
Recent versions of LLVM have a different API that we don't support ([yet](https://github.com/rubinius/rubinius/pull/3367)).  We hope to support the new API soon, but we're not there yet.

This is documented at http://rubini.us/doc/en/getting-started/requirements/ where it states that LLVM `<= 3.5` is required.  Please downgrade your LLVM and try again.

**Comment by martinvahi** [comment]
Thank You for the answer. 

Since I can not run the tests to verify the absence of the symptoms that I reported at the start of this thread and given that the second set of symptoms would induce a feature request that would be too self-evident to be written down to an issue-tracker in the classical context, I say that despite the fact that the issues have NOT been resolved, the openness of the current bug report contributes to information noise in stead of being helpful. So, I thank You all for the kind help and answers and with that note I close that issue. :-/

P.S. The [Travis CI](https://travis-ci.org/) is free for open source GitHub projects and the [RedHat OpenShift](https://www.openshift.com/) offers a free VM with [Jenkins CI](https://jenkins-ci.org/), not that it would be a small job to write the tests... :-D

**Comment by jemc** [comment]
Note that we do have a [test suite that is run by Travis](https://travis-ci.org/rubinius/rubinius), so I'm not sure what the last part of your comment is about.
