### ISSUE TITLE
Run Rails application only with precompiled files

### ISSUE THREAD

**Issue by JoseExposito** [rubinius/rubinius#3523]
Hi all,

Following this guide (http://rubini.us/2011/03/17/running-ruby-with-no-ruby/) I managed to execute simple Ruby scripts by running the generated rbc files.

I'd like to do the same with my Rails application to be able to distribute it without distributing the source code. I compiled it with:
```
$ rbx compile -s '^.rb:.rbc' .
$ find . -name "*.rb" -type f -delete
```

But, after trying a lot of things, I'm not able to run it.

Is it possible to run a Rails app with Rubinius without distributing the source code?

Thank you very much in advance

**Comment by jc00ke** [comment]
As of now, no, it's not effectively possible. The "Caveats" section in that post should be heeded with respect to compiled files.

There are plans to introduce the ability to precompile apps to a binary format, but the work has not started quite yet.

**Comment by JoseExposito** [comment]
OK, thank you very much @jc00ke :)

**Comment by brixen** [comment]
@JoseExposito the work is actually started on this branch https://github.com/rubinius/rubinius/tree/codedb. Planning to get back to it soon.
