### ISSUE TITLE
Marshaling difference between Rubinius and other Rubies

### ISSUE THREAD

**Issue by philipmw** [rubinius/rubinius#3527]
A marshalled custom object fails to unmarshal on Rubinius 2.5.8, but it works on JRuby and MRI Ruby.

Minimal test case is here: https://github.com/philipmw/rubinius-issue-3527. Please refer to the README in that project.

An excerpt from that README:

 A _Promise_ object wraps an _InnerClass_ object and delegates all unrecognized method calls to it.  _Promise_ inherits from _BasicObject_, so it's effectively a transparent wrapper around _InnerClass_.

When marshaling on Rubinius, the _Promise_ object is called with `#__class__`.  By default, this method is delegated to _InnerClass_ like all others.  As a result, the marshal string looks like `InnerClass > InnerClass`, which fails when unmarshaling.

In contrast, in Rubies, the _Promise_ object knows its class name, the `#__class__` method is never called, so it does not get delegated to the inner class.  The marshal string looks like `Promise > InnerClass` and correctly unmarshals.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
