### ISSUE TITLE
Cannot create method `total` on a Array subclass

### ISSUE THREAD

**Issue by brauliobo** [rubinius/rubinius#3528]
The following code works on MRI and crashes on Rubinius
```ruby
class Results < Array
  attr_reader :total
  
  def initialize(total)
    @total = total
  end
end
r = Results.new(50)
r << 5
```

The backtrace:
```
irb(main):014:0> r = Results.new(50)
Rubinius::ObjectBoundsExceededError: Tuple::at_prim: index 0 out of bounds for size 0
        from kernel/bootstrap/array.rb:76:in `each'
        from kernel/common/enumerable.rb:232:in `each_with_index'
        from kernel/common/array.rb:889:in `inspect'
        from kernel/common/thread.rb:56:in `detect_recursion'
        from kernel/common/array.rb:888:in `inspect'
        from kernel/bootstrap/proc.rb:20:in `call'
        from kernel/common/kernel.rb:511:in `loop'
        from kernel/bootstrap/proc.rb:20:in `call'
        from kernel/common/throw_catch.rb:30:in `catch'
        from kernel/common/throw_catch.rb:8:in `register'
        from kernel/common/throw_catch.rb:29:in `catch'
        from kernel/bootstrap/proc.rb:20:in `call'
        from kernel/common/throw_catch.rb:30:in `catch'
        from kernel/common/throw_catch.rb:8:in `register'
        from kernel/common/throw_catch.rb:29:in `catch'
        from /home/braulio/.rbenv/versions/rbx-2.5.8/gems/gems/rubysl-irb-2.1.1/bin/irb:12:in `__script__'
        from kernel/common/kernel.rb:498:in `load'
        from /home/braulio/.rbenv/versions/rbx-2.5.8/bin/irb:23:in `__script__'
        from kernel/delta/code_loader.rb:66:in `load_script'
        from kernel/delta/code_loader.rb:152:in `load_script'
```

**Comment by YorickPeterse** [comment]
Rubinius uses `@total` as an instance variable itself for storing the size of an Array, you should not overwrite this when sub-classing Array. The only reason this works on MRI is because it stores all internal state outside of Ruby.

**Comment by YorickPeterse** [comment]
As an extra note, when overwriting `initialize` you'll have to make sure to properly call the parent `initialize` method, otherwise the internal state of the Array won't be set up properly.

**Comment by brauliobo** [comment]
Ok @YorickPeterse, thanks for this, maybe rubinius should use a prefix like `@_` for its internal variables?

Thanks for remembering me about the `super` call.

**Comment by jc00ke** [comment]
Using `@_` style variable names doesn't solve the problem, as you could just as easily overwrite that as well in your inherited class, and we're back to the same thing. In the past we've recommended composing the `Array`, not subclassing from it. Then you'll get your `#total` accessor and not break the underlying code.
