### ISSUE TITLE
OpenStruct do not respond to `[]`

### ISSUE THREAD

**Issue by brauliobo** [rubinius/rubinius#3529]
The following works on MRI and not on Rubinius:
```
>> a=OpenStruct.new
=> #<OpenStruct>
>> a['id']
=> nil
```

**Comment by brixen** [comment]
Thanks for reporting that, @brauliobo. The code for OpenStruct is in Ruby and is copied from MRI (see https://github.com/rubysl/rubysl-ostruct/blob/2.0/lib/rubysl/ostruct/ostruct.rb).

Would you have time to dig in and look at adding that method? We may need to update the code to a more recent version of MRI.

**Comment by jc00ke** [comment]
@brixen `#[]` exists already, [doesn't it](https://github.com/rubysl/rubysl-ostruct/blob/33e8f5db5e680de894ad059a527ede9b335a0453/lib/rubysl/ostruct/ostruct.rb#L195-L197)? Or is it somehow hitting that branch in `#method_missing`?

**Comment by rideliner** [comment]
It exists in the repository, but it is not in the gem.

**Comment by brixen** [comment]
Just pushed https://github.com/rubysl/rubysl-ostruct/releases/tag/v2.1.0. The example above works.

You can use this with your current Rubinius version but it takes a couple extra steps at the moment:

```
$ # select your rbx version in whatever your Ruby switcher is
$ gem uninstall rubysl-ostruct
$ # this should give a message like the following:
$ # ERROR:  While executing gem ... (Gem::InstallError)
$ #    rubysl-ostruct is not installed in GEM_HOME, try:
$ #	gem uninstall -i /Users/brianshirai/.rubies/rbx-2.5.8/lib/rubinius/2.5.8/gems rubysl-ostruct
$ # run the gem uninstall command shown
$ # then run the same command but change 'uninstall' to 'install', for example:
$ gem install -i /Users/brianshirai/.rubies/rbx-2.5.8/lib/rubinius/2.5.8/gems rubysl-ostruct
Fetching: rubysl-ostruct-2.1.0.gem (100%)
Successfully installed rubysl-ostruct-2.1.0
1 gem installed
```

**Comment by brixen** [comment]
@brauliobo try the steps above and let us know if you have further issues.

**Comment by brauliobo** [comment]
it works @brixen, thanks!

**Comment by brixen** [comment]
@brauliobo awesome, thanks again for reporting it.
