### ISSUE TITLE
Fasta benchmark doesn't seem to make any progress

### ISSUE THREAD

**Issue by chrisseaton** [rubinius/rubinius#3531]
This benchmark runs in about a second on other implementations of Ruby, but I can't see any evidence of it making progress at all on Rubinius 2.5.8, even if I let it run for hours. If I reduce the size of the constant (`100_000_000` to `100`) it does, so it may be not broken, it's just tens of thousands of times slower than MRI with this large parameter.

```ruby
# Copyright © 2004-2008 Brent Fulgham, 2005-2015 Isaac Gouy
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#   * Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
#
#   * Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#
#   * Neither the name of "The Computer Language Benchmarks Game" nor the name
#     of "The Computer Language Shootout Benchmarks" nor the names of its
#     contributors may be used to endorse or promote products derived from this
#     software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# The Computer Language Benchmarks Game

# http://benchmarksgame.alioth.debian.org/

# Contributed by Sokolov Yura

# Modified by Joseph LaFata

# http://benchmarksgame.alioth.debian.org/u32/program.php?test=fasta&lang=yarv&id=2

ALU =
   "GGCCGGGCGCGGTGGCTCACGCCTGTAATCCCAGCACTTTGG"+
   "GAGGCCGAGGCGGGCGGATCACCTGAGGTCAGGAGTTCGAGA"+
   "CCAGCCTGGCCAACATGGTGAAACCCCGTCTCTACTAAAAAT"+
   "ACAAAAATTAGCCGGGCGTGGTGGCGCGCGCCTGTAATCCCA"+
   "GCTACTCGGGAGGCTGAGGCAGGAGAATCGCTTGAACCCGGG"+
   "AGGCGGAGGTTGCAGTGAGCCGAGATCGCGCCACTGCACTCC"+
   "AGCCTGGGCGACAGAGCGAGACTCCGTCTCAAAAA"

def make_repeat_fasta(src, n)
    l = src.length
    s = src * ((n / l) + 1)
    s.slice!(n, l)
    output = ''
    0.step(s.length-1,60) {|x| output << s[x,60]; output << "\n"}
    output
end

loop do
  start = Time.now
  raise 'failed' unless make_repeat_fasta(ALU, 100_000_000).length == 101666667
  puts Time.now - start
end
```

Ping @nirvdrum who added this benchmark to bench9000.

**Comment by rideliner** [comment]
The bottleneck seems to be at `s[x,60]`.

**Comment by YorickPeterse** [comment]
@rideliner What is that suspicion based on?

**Comment by rideliner** [comment]
Replacing `0.step(s.length-1,60) {|x| output << s[x,60]; output << "\n"}`
with `0.step(s.length-1,60) {|x| output << (' ' * 60); output << "\n"}`
significantly reduces the time taken.

**Comment by YorickPeterse** [comment]
@rideliner aren't the two lines doing vastly different things? Maybe I'm misreading the code (it's a bit confusing), but in one case it's slicing a string while in the other case it's creating a string containing 60 spaces.

**Comment by rideliner** [comment]
Yes, they are very different.
The first is repeatedly appending a 60 character slice of `s` to the output string.
The second is repeatedly creating an arbitrary 60 character string and appending it to the output string.

I've been running the first for the last half hour without any change.
The second finished instantly.

**Comment by ahmadsherif** [comment]
Encoding `ALU` to ASCII makes it work. By doing a quick profiling, `utf8_find_character_byte_index` in vm/util/utf8.c seems to be the culprit.

**Comment by ahmadsherif** [comment]
It seems that my conclusion wasn't very accurate after all. We just needed to optimize some spots for when a string contains ASCII characters only (and has an ASCII-compatible encoding). Right now RBX performs slightly better than MRI 2.3.0 on my machine for this benchmark, so closing as fixed.
