### ISSUE TITLE
`Method#parameters` fail with kwargs

### ISSUE THREAD

**Issue by adaedra** [rubinius/rubinius#3538]
Hello,

Problem:
`Method#parameters` outputs wrong on a method with defined kwargs.

Code sample:

``` ruby
def foo(a, b = nil, c:, d: nil)
end

puts "#{RUBY_ENGINE} #{RUBY_VERSION}"
p method(:foo).parameters
```

Ruby output

```
ruby 2.2.3
[[:req, :a], [:opt, :b], [:keyreq, :c], [:key, :d]]
```

Rubinius output

```
rbx 2.1.0
[[:req, :a], [:opt, :b], [:opt, :"_:1"]]
```

Versions:

```
ruby -v: rubinius 2.6 (2.1.0 cdcec7e8 2015-12-20 3.5.1 JI) [x86_64-darwin15.0.0]
chruby: 0.3.9
uname -a: Darwin localhost 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
```

**Comment by brixen** [comment]
@adaedra are there specs for this behavior?

**Comment by adaedra** [comment]
There doesn't seem to be specs relating to kwargs in `Method`.

**Comment by headius** [comment]
I added a few basic specs here: https://github.com/ruby/rubyspec/commit/df59b1f0e5a86f97c95cd5087ec9ac7ec470c233

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
