### ISSUE TITLE
FFI::Function doesn't work as expected if called from another thread

### ISSUE THREAD

**Issue by paddor** [rubinius/rubinius#3545]
Can't spawn a Thread from within an FFI::Function if the FFI::Function is called from another thread.

See [this gist](https://gist.github.com/paddor/53e2820e49df04b3eec0).

**Comment by paddor** [comment]
@ahmadsherif Thanks so much! I'll test it with the next Rubinius release.

**Comment by ahmadsherif** [comment]
@paddor  You're welcome :).
