### ISSUE TITLE
Random uncommon crash

### ISSUE THREAD

**Issue by brauliobo** [rubinius/rubinius#3547]
Happens infrequently on the test suite run. Not sure it is was already reported, sorry if it was.
```
llvm version: 3.5.0
--- end rubinius info ---
--- begin system backtrace ---
rbx() [0x6a5ba9]
/lib64/libpthread.so.0(+0xf130) [0x7f4bb6532130]
rbx(_ZN8rubinius6Object13write_barrierEPNS_12ObjectMemoryEPv+0x51) [0x714131]
rbx(_ZN8rubinius3jit17RuntimeDataHolder17run_write_barrierEPNS_12ObjectMemoryEPNS_6ObjectE+0x3f) [0x7bbd3f]
rbx(_ZN8rubinius9LLVMState3runEPNS_5StateE+0x743) [0x7c4323]
rbx(_ZN8rubinius14InternalThread3runEPv+0x8c) [0x5fc47c]
/lib64/libpthread.so.0(+0x7df3) [0x7f4bb652adf3]
/lib64/libc.so.6(clone+0x6d) [0x7f4bb51ce1ad]
--- end system backtrace ---
--- begin Ruby backtraces ---
--- Thread 1 backtrace ---
Array#== in kernel/common/array.rb:117 (+94)
__block__ in /mnt/jenkins/.rvm/rubies/rubinius-2.5.2.c96/gems/gems/rubysl-pathname-2.1.0/lib/rubysl/pathname/pathname.rb:504 (+0 inline)
/mnt/jenkins/local/jenkins/lib/jenkins/ruby.sh: line 16:  6571 Segmentation fault      bundle install -j2
Build step 'Execute shell' marked build as failure
```

**Comment by YorickPeterse** [comment]
The stacktrace seems to suggest you're using Rubinius 2.5.2, which is from January 2015. Is it possible to try the latest version?

**Comment by brixen** [comment]
@brauliobo please try https://github.com/rubinius/rubinius/releases/latest. There are 480 commits an master since 2.5.2 and there should no problem updating for you. There are a bunch of issues that have been fixed around threading.

**Comment by YorickPeterse** [comment]
Closing this due to the lack of feedback since and the Rubinius version in question being quite dated. Feel free to re-open if the problem persists on the latest version of Rubinius.
