### ISSUE TITLE
Changing license from BSD 3-clause to MPL 2.0

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3550]
We (Rubinius) would like to change the license from the [BSD 3-clause license](https://github.com/rubinius/rubinius/blob/6b35d17975333f3059913cc2ec4586df1cd07825/BSD_LICENSE) to the [MPL 2.0](https://github.com/rubinius/rubinius/blob/6b35d17975333f3059913cc2ec4586df1cd07825/LICENSE). Because the BSD license makes no mention of who owns the copyright to changes we're forced to request permission from all contributors regarding the license change.

The list of authors below is based on the contributors as listed in the GitHub API. The list of authors in Git consists out of a variety of valid, bullshit, or unused Emails; making it impossible to rely upon. Since Rubinius has been using GitHub since at least 2009 I'm fairly confident all contributors have a GitHub account.

Should you have contributed to Rubinius and are _not_ on the list below please send an Email to yorickpeterse+rubinius@gmail.com _or_ join the rubinius/rubinius Gitter channel and make a mention of this (Email is highly preferred as it's easier for me to keep track of).

I apologize for the noise this will introduce, but this is the most reliable way of contacting everybody. Contributors on the list below are adviced to reply and then unsubscribe from this issue (using the button on the right).
## Reason for Changing

The most important reason for switching to the MPL 2.0 is that it's more explicit in terms of who owns what, what happens to patents, and so forth. The BSD 3-clause license leaves far too much up to interpretation. In general it's a license we feel is better at protecting both the Rubinius project and its contributors.
## Contributors

If you're on the list below please reply with "OK" if you're OK with this license change and "not OK" if you're not OK with it. Should you not be OK with the change please do me a favour and provide a short explanation as to why.  You're also free to send said explanation to the above Email address.

Please refrain from posting any other comments on this issue as doing so makes it harder to keep track of things. Any comments other than "OK" or "not OK" will be removed.

If you happen to have access to this issue feel free to check-off your own username, but **please** still leave a comment saying you're OK with the change.

Note that due to GitHub limiting the amount of mentioned users to 50 I'll be splitting the list of usernames to 50 names per comment.

**Comment by YorickPeterse** [comment]
First batch:

* [ ] @abyx
* [ ] @adamwiggins
* [ ] @Aesthetikx
* [ ] @aevernon
* [ ] @agardiner
* [ ] @agrimm
* [ ] @ahmadsherif
* [ ] @akshayrawat
* [ ] @alexdowad
* [ ] @alfonsocora
* [ ] @alindeman
* [ ] @alvaropereyra
* [ ] @AndrewVos
* [ ] @antekpiechnik
* [ ] @anthropomorphic
* [ ] @Antti
* [ ] @anupnivargi
* [ ] @aquasync
* [ ] @argent-smith
* [ ] @arthurgeek
* [ ] @arthurschreiber
* [ ] @ashelly
* [ ] @ashmoran
* [ ] @audreyt
* [ ] @badosu
* [ ] @bakkdoor
* [ ] @balinterdi
* [ ] @bandresen
* [ ] @banister
* [ ] @baroquebobcat
* [ ] @be9
* [ ] @benburkert
* [ ] @benlangfeld
* [ ] @benlovell
* [ ] @benstiglitz
* [ ] @bjeanes
* [ ] @bjfish
* [ ] @bradediger
* [ ] @brainopia
* [ ] @brianmario
* [ ] @BRIMIL01
* [ ] @brixen
* [ ] @brynary
* [ ] @btakita
* [ ] @bterkuile
* [ ] @burningTyger
* [ ] @caarlos0
* [ ] @caiquanqing
* [ ] @carlosbrando
* [ ] @carlosgaldino

**Comment by YorickPeterse** [comment]
Second batch:

* [ ] @carols10cents
* [ ] @carsonmcdonald
* [ ] @celsodantas
* [ ] @cezarsa
* [ ] @chad
* [ ] @charliesome
* [ ] @charlietanksley
* [ ] @chickenkiller
* [ ] @chrisseaton
* [ ] @chuckremes
* [ ] @cldwalker
* [ ] @clee
* [ ] @CodeGnome
* [ ] @ConradIrwin
* [ ] @cpettitt
* [ ] @crafterm
* [ ] @crayz
* [ ] @cremes
* [ ] @ctoneal
* [ ] @cyfdecyf
* [ ] @cyndis
* [ ] @cypher
* [ ] @czarneckid
* [ ] @daikini
* [ ] @daneharrigan
* [ ] @DanielVartanov
* [ ] @danlucraft
* [ ] @davorb
* [ ] @dbussink
* [ ] @dgtized
* [ ] @diasjorge
* [ ] @dissolved
* [ ] @djwhitt
* [ ] @dkubb
* [ ] @dlt
* [ ] @dmacvicar
* [ ] @doudou
* [ ] @drbrain
* [ ] @drewolson
* [ ] @drnic
* [ ] @dtykocki
* [ ] @dubek
* [ ] @dudleyf
* [ ] @dwaite
* [ ] @ebenoist
* [ ] @ecoffey
* [ ] @edsrzf
* [ ] @emk
* [ ] @epall
* [ ] @eregon

**Comment by YorickPeterse** [comment]
* [ ] @evanphx
* [ ] @evtuhovich
* [ ] @fcheung
* [ ] @febuiles
* [ ] @flavio
* [ ] @fmfdias
* [ ] @franckverrot
* [ ] @frasca
* [ ] @FunkyFortune
* [ ] @fxn
* [ ] @gcapizzi
* [ ] @gensym
* [ ] @ghazel
* [ ] @Gibheer
* [ ] @gildo
* [ ] @godfat
* [ ] @goncalossilva
* [ ] @Gonzih
* [ ] @goyox86
* [ ] @gramos
* [ ] @grk
* [ ] @Groogy
* [ ] @guilleiguaran
* [ ] @gustavotemple
* [ ] @haines
* [ ] @halorgium
* [ ] @Haofei
* [ ] @headius
* [ ] @heftig
* [ ] @henrikhodne
* [ ] @herminiotorres
* [ ] @heronmedeiros
* [ ] @hosiawak
* [ ] @hurdlea
* [ ] @huy
* [ ] @i0rek
* [ ] @iainbeeston
* [ ] @ikataitsev
* [ ] @ileitch
* [ ] @inukshuk
* [ ] @IPGlider
* [ ] @jaggederest
* [ ] @jakedouglas
* [ ] @jamesotron
* [ ] @janogonzalez
* [ ] @jarib
* [ ] @jasonrclark
* [ ] @jaywhy
* [ ] @jbarnette
* [ ] @jbr

**Comment by YorickPeterse** [comment]
* [ ] @jc00ke
* [ ] @jcoglan
* [ ] @jcsherin
* [ ] @jdsiegel
* [ ] @jeffkreeftmeijer
* [ ] @jemc
* [ ] @jeremydurham
* [ ] @jeremyevans
* [ ] @jeremytregunna
* [ ] @jeremyz
* [ ] @jero5
* [ ] @jfirebaugh
* [ ] @jfredett
* [ ] @jgaskins
* [ ] @jgre
* [ ] @jimmycuadra
* [ ] @jish
* [ ] @jluxenberg
* [ ] @jmstacey
* [ ] @joevandyk
* [ ] @johnmuhl
* [ ] @jonforums
* [ ] @jonsmock
* [ ] @josh
* [ ] @jstorimer
* [ ] @jtdowney
* [ ] @julionc
* [ ] @justinmcp
* [ ] @justinweiss
* [ ] @kachick
* [ ] @kamal
* [ ] @kevinclark
* [ ] @khamutov
* [ ] @kodnin
* [ ] @krekoten
* [ ] @kronos
* [ ] @krsh
* [ ] @kubo
* [ ] @kwatch
* [ ] @kwleland
* [ ] @larskanis
* [ ] @leavengood
* [ ] @leocassarani
* [ ] @lest
* [ ] @lexmag
* [ ] @lgierth
* [ ] @lian
* [ ] @libc
* [ ] @Locke23rus
* [ ] @locks

**Comment by YorickPeterse** [comment]
* [ ] @lstoll
* [ ] @LTe
* [ ] @luislavena
* [ ] @mainej
* [ ] @malu
* [ ] @Mange
* [ ] @manveru
* [ ] @marcandre
* [ ] @marius
* [ ] @marnen
* [ ] @martinstannard
* [ ] @matthewd
* [ ] @mental
* [ ] @mernen
* [ ] @michaelklishin
* [ ] @mitchellh
* [ ] @mjackson
* [ ] @mkhl
* [ ] @mlangenberg
* [ ] @mlen
* [ ] @monkeylibre
* [ ] @mpalmer
* [ ] @mpapis
* [ ] @mthorn
* [ ] @mwunsch
* [ ] @nashby
* [ ] @nathansobo
* [ ] @nazgob
* [ ] @ndarilek
* [ ] @neelance
* [ ] @Nemo157
* [ ] @nevir
* [ ] @nexcastellan
* [ ] @ngollan
* [ ] @nibua-r
* [ ] @nirvdrum
* [ ] @obrok
* [ ] @oggy
* [ ] @p8
* [ ] @pager
* [ ] @parndt
* [ ] @pbevin
* [ ] @pcapriotti
* [ ] @pd
* [ ] @pedrodelgallego
* [ ] @pH14
* [ ] @pluskid
* [ ] @postmodern
* [ ] @practicingruby
* [ ] @presidentbeef

**Comment by YorickPeterse** [comment]
* [ ] @programble
* [ ] @pwnall
* [ ] @qmx
* [ ] @qqshfox
* [ ] @raggi
* [ ] @ragnard
* [ ] @razielgn
* [ ] @retnuh
* [ ] @rf-
* [ ] @rkh
* [ ] @rmg
* [ ] @rnicholson
* [ ] @robin850
* [ ] @roshats
* [ ] @r-stu31
* [ ] @rue
* [ ] @ruipserra
* [ ] @ryantm
* [ ] @ryoqun
* [ ] @santana
* [ ] @sbryant
* [ ] @schleyfox
* [ ] @schmidt
* [ ] @schmurfy
* [ ] @sdaubert
* [ ] @seanchas116
* [ ] @semmons99
* [ ] @seydar
* [ ] @sferik
* [ ] @shatterednirvana
* [ ] @shoe
* [ ] @skliew
* [ ] @slaught
* [ ] @slawosz
* [ ] @smtlaissezfaire
* [ ] @sodabrew
* [ ] @southerngs
* [ ] @Spakman
* [ ] @spastorino
* [ ] @splattael
* [ ] @srawlins
* [ ] @sshao
* [ ] @stass
* [ ] @steveklabnik
* [ ] @stormbrew
* [ ] @Stormwind
* [ ] @stouset
* [ ] @stuarthalloway
* [ ] @subwindow
* [ ] @szimek

**Comment by YorickPeterse** [comment]
* [ ] @tak1n
* [ ] @tamird
* [ ] @tarcieri
* [ ] @tchandy
* [ ] @technomancy
* [ ] @tenderlove
* [ ] @terceiro
* [ ] @thedarkone
* [ ] @timabdulla
* [ ] @tmm1
* [ ] @tokengeek
* [ ] @tonysidaway
* [ ] @troessner
* [ ] @tsion
* [ ] @txus
* [ ] @unleashed
* [ ] @utgarda
* [ ] @veganstraightedge
* [ ] @vic
* [ ] @vincentlu
* [ ] @vitaliy
* [ ] @vito
* [ ] @vjmp
* [ ] @vmg
* [ ] @voxik
* [ ] @vredniy
* [ ] @vvs
* [ ] @walski
* [ ] @warrenseen
* [ ] @wasnotrice
* [ ] @wayneeseguin
* [ ] @wilson
* [ ] @wrozka
* [ ] @wycats
* [ ] @xaviershay
* [ ] @xenda
* [ ] @yipdw
* [x] @YorickPeterse
* [ ] @yui-knk
* [ ] @zaeleus
* [ ] @zankich
* [ ] @zenspider
* [ ] @zerowidth
* [ ] @zimbatm
* [ ] @zzak

**Comment by heftig** [comment]
OK

**Comment by chrisseaton** [comment]
OK

**Comment by jasonrclark** [comment]
OK

**Comment by henrikhodne** [comment]
OK

**Comment by tamird** [comment]
OK

**Comment by jeremytregunna** [comment]
:+1:

**Comment by musybite** [comment]
OK

**Comment by rf-** [comment]
OK

**Comment by mitchellh** [comment]
OK

**Comment by gcapizzi** [comment]
Ok

**Comment by justinweiss** [comment]
OK

**Comment by jfirebaugh** [comment]
OK

**Comment by joevandyk** [comment]
Ok

**Comment by clee** [comment]
OK

**Comment by jaggederest** [comment]
OK

**Comment by justinmcp** [comment]
OK

**Comment by IPGlider** [comment]
OK

**Comment by programble** [comment]
OK

**Comment by tsion** [comment]
OK

**Comment by lexmag** [comment]
OK

**Comment by parndt** [comment]
OK

**Comment by luislavena** [comment]
OK

**Comment by ghazel** [comment]
Ok

**Comment by locks** [comment]
OK

**Comment by lgierth** [comment]
OK

**Comment by tmm1** [comment]
OK

**Comment by practicingruby** [comment]
OK

**Comment by jbarnette** [comment]
OK

**Comment by jemc** [comment]
OK

**Comment by pager** [comment]
OK

**Comment by dissolved** [comment]
OK

**Comment by zerowidth** [comment]
OK

**Comment by tenderlove** [comment]
OK

**Comment by walski** [comment]
OK

**Comment by dwaite** [comment]
OK

**Comment by thedarkone** [comment]
OK

**Comment by pcapriotti** [comment]
OK

**Comment by alindeman** [comment]
OK

**Comment by rmg** [comment]
OK :+1:

**Comment by semmons99** [comment]
OK

**Comment by yui-knk** [comment]
OK

**Comment by jeremydurham** [comment]
OK

**Comment by kubo** [comment]
OK

**Comment by mpalmer** [comment]
OK

**Comment by jc00ke** [comment]
OK

**Comment by sferik** [comment]
OK

**Comment by shatterednirvana** [comment]
OK

**Comment by postmodern** [comment]
OK

**Comment by jluxenberg** [comment]
Ok

**Comment by marcandre** [comment]
OK

**Comment by nevir** [comment]
OK

**Comment by sshao** [comment]
OK

**Comment by edsrzf** [comment]
OK

**Comment by steveklabnik** [comment]
I agree with relicensing my contributions.

**Comment by kwleland** [comment]
OK

**Comment by drewolson** [comment]
Agreed.

**Comment by nathansobo** [comment]
:+1:

**Comment by Antti** [comment]
OK

**Comment by technomancy** [comment]
OK

**Comment by zaeleus** [comment]
OK

**Comment by brainopia** [comment]
+1

**Comment by mernen** [comment]
OK

**Comment by ConradIrwin** [comment]
OK

**Comment by jish** [comment]
OK

**Comment by jtdowney** [comment]
OK

**Comment by julionc** [comment]
OK

**Comment by pedrodelgallego** [comment]
OK

**Comment by ebenoist** [comment]
OK :+1:

**Comment by mwunsch** [comment]
OK

**Comment by fmfdias** [comment]
OK

**Comment by timabdulla** [comment]
ok

**Comment by seanchas116** [comment]
OK

**Comment by benburkert** [comment]
OK

**Comment by jaywhy** [comment]
OK

On Sunday, January 3, 2016, Yorick Peterse <notifications@github.com> wrote:

>
>    - @evanphx <https://github.com/evanphx>
>    - @evtuhovich <https://github.com/evtuhovich>
>    - @fcheung <https://github.com/fcheung>
>    - @febuiles <https://github.com/febuiles>
>    - @flavio <https://github.com/flavio>
>    - @fmfdias <https://github.com/fmfdias>
>    - @franckverrot <https://github.com/franckverrot>
>    - @frasca <https://github.com/frasca>
>    - @FunkyFortune <https://github.com/FunkyFortune>
>    - @fxn <https://github.com/fxn>
>    - @gcapizzi <https://github.com/gcapizzi>
>    - @gensym <https://github.com/gensym>
>    - @ghazel <https://github.com/ghazel>
>    - @Gibheer <https://github.com/Gibheer>
>    - @gildo <https://github.com/gildo>
>    - @godfat <https://github.com/godfat>
>    - @goncalossilva <https://github.com/goncalossilva>
>    - @Gonzih <https://github.com/Gonzih>
>    - @goyox86 <https://github.com/goyox86>
>    - @gramos <https://github.com/gramos>
>    - @grk <https://github.com/grk>
>    - @Groogy <https://github.com/Groogy>
>    - @guilleiguaran <https://github.com/guilleiguaran>
>    - @gustavotemple <https://github.com/gustavotemple>
>    - @haines <https://github.com/haines>
>    - @halorgium <https://github.com/halorgium>
>    - @Haofei <https://github.com/Haofei>
>    - @headius <https://github.com/headius>
>    - @heftig <https://github.com/heftig>
>    - @henrikhodne <https://github.com/henrikhodne>
>    - @herminiotorres <https://github.com/herminiotorres>
>    - @heronmedeiros <https://github.com/heronmedeiros>
>    - @hosiawak <https://github.com/hosiawak>
>    - @hurdlea <https://github.com/hurdlea>
>    - @huy <https://github.com/huy>
>    - @i0rek <https://github.com/i0rek>
>    - @iainbeeston <https://github.com/iainbeeston>
>    - @ikataitsev <https://github.com/ikataitsev>
>    - @ileitch <https://github.com/ileitch>
>    - @inukshuk <https://github.com/inukshuk>
>    - @IPGlider <https://github.com/IPGlider>
>    - @jaggederest <https://github.com/jaggederest>
>    - @jakedouglas <https://github.com/jakedouglas>
>    - @jamesotron <https://github.com/jamesotron>
>    - @janogonzalez <https://github.com/janogonzalez>
>    - @jarib <https://github.com/jarib>
>    - @jasonrclark <https://github.com/jasonrclark>
>    - @jaywhy <https://github.com/jaywhy>
>    - @jbarnette <https://github.com/jbarnette>
>    - @jbr <https://github.com/jbr>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubinius/rubinius/issues/3550#issuecomment-168557264>.
>


-- 
Jason Yates
jaywhy@gmail.com

**Comment by vito** [comment]
OK

**Comment by carsonmcdonald** [comment]
OK

**Comment by godfat** [comment]
OK

**Comment by jfredett** [comment]
OK

**Comment by aevernon** [comment]
OK

**Comment by ndarilek** [comment]
OK

**Comment by srawlins** [comment]
OK

**Comment by smtlaissezfaire** [comment]
OK

**Comment by bjeanes** [comment]
OK

**Comment by ctoneal** [comment]
OK

**Comment by guilleiguaran** [comment]
OK

**Comment by jeremyevans** [comment]
OK

**Comment by cldwalker** [comment]
OK

**Comment by krekoten** [comment]
OK

**Comment by ecoffey** [comment]
OK

**Comment by kevinclark** [comment]
OK 😁👍

--

**Comment by jgaskins** [comment]
OK

**Comment by sodabrew** [comment]
OK

**Comment by pluskid** [comment]
OK

**Comment by alexdowad** [comment]
OK

**Comment by ryantm** [comment]
OK

**Comment by carols10cents** [comment]
OK

**Comment by mthorn** [comment]
OK

**Comment by dudleyf** [comment]
OK

**Comment by jdsiegel** [comment]
OK

**Comment by epall** [comment]
OK

**Comment by schmidt** [comment]
OK

**Comment by michaelklishin** [comment]
OK

**Comment by oggy** [comment]
OK

**Comment by Mange** [comment]
OK

**Comment by be9** [comment]
OK

**Comment by skliew** [comment]
OK

**Comment by larskanis** [comment]
OK

**Comment by roshats** [comment]
OK

**Comment by abyx** [comment]
OK

**Comment by mkhl** [comment]
OK

**Comment by i0rek** [comment]
OK

**Comment by nibua-r** [comment]
OK

**Comment by jbr** [comment]
OK

**Comment by jstorimer** [comment]
OK

**Comment by chad** [comment]
OK

**Comment by akshayrawat** [comment]
OK

**Comment by agardiner** [comment]
OK

**Comment by stass** [comment]
OK

**Comment by dainmiller** [comment]
OK

**Comment by brianmario** [comment]
OK

**Comment by p8** [comment]
OK

**Comment by splattael** [comment]
OK

**Comment by fxn** [comment]
OK

**Comment by Gonzih** [comment]
OK

**Comment by lest** [comment]
OK

**Comment by dubek** [comment]
OK

**Comment by voxik** [comment]
OK

**Comment by Nemo157** [comment]
OK

**Comment by iainbeeston** [comment]
OK

**Comment by gildo** [comment]
Ok

**Comment by jimmycuadra** [comment]
OK

**Comment by razielgn** [comment]
OK

**Comment by leocassarani** [comment]
OK

**Comment by ngollan** [comment]
OK

**Comment by flavio** [comment]
OK

**Comment by cypher** [comment]
OK

**Comment by tokengeek** [comment]
OK

**Comment by kronos** [comment]
OK

**Comment by grk** [comment]
OK

**Comment by dbussink** [comment]
OK

**Comment by libc** [comment]
OK

**Comment by inukshuk** [comment]
OK

**Comment by balinterdi** [comment]
OK

**Comment by fcheung** [comment]
OK

**Comment by ileitch** [comment]
OK

**Comment by burningTyger** [comment]
OK

**Comment by unleashed** [comment]
OK

**Comment by diasjorge** [comment]
OK

**Comment by chickenkiller** [comment]
OK

**Comment by cyndis** [comment]
OK

**Comment by goyox86** [comment]
OK

**Comment by mpapis** [comment]
OK

**Comment by ahmadsherif** [comment]
OK

**Comment by zimbatm** [comment]
OK

**Comment by neelance** [comment]
OK

**Comment by wrozka** [comment]
OK

**Comment by aquasync** [comment]
OK

**Comment by adamwiggins** [comment]
OK

**Comment by janogonzalez** [comment]
OK

**Comment by ruipserra** [comment]
OK

**Comment by benlovell** [comment]
OK

**Comment by jeffkreeftmeijer** [comment]
OK

**Comment by dtykocki** [comment]
OK

**Comment by tchandy** [comment]
OK

**Comment by retnuh** [comment]
OK

**Comment by benlangfeld** [comment]
OK

**Comment by LTe** [comment]
OK

**Comment by troessner** [comment]
Ok!

**Comment by haines** [comment]
OK

**Comment by hosiawak** [comment]
OK

**Comment by malu** [comment]
OK

**Comment by benstiglitz** [comment]
OK

**Comment by anupnivargi** [comment]
OK

**Comment by robin850** [comment]
OK

**Comment by pd** [comment]
OK

**Comment by nirvdrum** [comment]
OK

**Comment by alfonsocora** [comment]
OK

**Comment by charlietanksley** [comment]
OK

**Comment by evtuhovich** [comment]
OK

**Comment by terceiro** [comment]
OK

**Comment by stuarthalloway** [comment]
OK

**Comment by bandresen** [comment]
OK

**Comment by alvaropereyra** [comment]
OK

**Comment by schmurfy** [comment]
OK

**Comment by cpettitt** [comment]
OK

**Comment by czarneckid** [comment]
OK

**Comment by bjfish** [comment]
OK

**Comment by txus** [comment]
OK

**Comment by vitaliy** [comment]
OK

**Comment by shoe** [comment]
OK

**Comment by carlosgaldino** [comment]
OK

**Comment by wayneeseguin** [comment]
好的！

**Comment by lstoll** [comment]
OK

**Comment by obrok** [comment]
OK

**Comment by goncalossilva** [comment]
👍

**Comment by gustavotemple** [comment]
OK

**Comment by bakkdoor** [comment]
OK

**Comment by ragnard** [comment]
OK

**Comment by evanphx** [comment]
OK

**Comment by kachick** [comment]
OK

**Comment by szimek** [comment]
OK

**Comment by wasnotrice** [comment]
OK

**Comment by kamal** [comment]
OK

**Comment by vmg** [comment]
OK

**Comment by yipdw** [comment]
OK

**Comment by danlucraft** [comment]
OK

**Comment by sdaubert** [comment]
OK

**Comment by stouset** [comment]
OK

**Comment by gensym** [comment]
OK

**Comment by jonsmock** [comment]
OK

**Comment by themgt** [comment]
OK

**Comment by marnen** [comment]
OK

**Comment by jeremyz** [comment]
OK

**Comment by marius** [comment]
OK

2016-01-04 1:17 GMT+01:00 Yorick Peterse <notifications@github.com>:

**Comment by mjackson** [comment]
OK

**Comment by spastorino** [comment]
OK

**Comment by rnicholson** [comment]
OK

**Comment by FunkyFortune** [comment]
OK

**Comment by raggi** [comment]
OK

**Comment by ashmoran** [comment]
OK

**Comment by Spakman** [comment]
OK

**Comment by caarlos0** [comment]
OK

**Comment by dmacvicar** [comment]
OK

**Comment by badosu** [comment]
OK

**Comment by febuiles** [comment]
OK

**Comment by crafterm** [comment]
OK

**Comment by Haofei** [comment]
ok

On Sun, Jan 3, 2016 at 8:02 PM, Ryan Mulligan <notifications@github.com>
wrote:

> OK
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubinius/rubinius/issues/3550#issuecomment-168576029>.
>



-- 
名无の小人

**Comment by nashby** [comment]
OK

**Comment by tak1n** [comment]
ok

**Comment by jcoglan** [comment]
OK

**Comment by eregon** [comment]
OK

**Comment by vredniy** [comment]
OK

**Comment by presidentbeef** [comment]
OK

**Comment by schleyfox** [comment]
OK

**Comment by antekpiechnik** [comment]
OK

**Comment by dgtized** [comment]
OK

**Comment by qmx** [comment]
OK

**Comment by djwhitt** [comment]
Ok

**Comment by pwnall** [comment]
OK

**Comment by johnmuhl** [comment]
ok

**Comment by caiquanqing** [comment]
OK

**Comment by arthurgeek** [comment]
Ok

**Comment by xaviershay** [comment]
ok

**Comment by jakedouglas** [comment]
OK

**Comment by CodeGnome** [comment]
OK

**Comment by mlen** [comment]
OK

**Comment by BRIMIL01** [comment]
OK

**Comment by qqshfox** [comment]
OK

**Comment by zankich** [comment]
OK

**Comment by rkh** [comment]
OK

**Comment by jcsherin** [comment]
OK

**Comment by sbryant** [comment]
OK

**Comment by Locke23rus** [comment]
OK

**Comment by utgarda** [comment]
OK

**Comment by ashelly** [comment]
OK

**Comment by emk** [comment]
OK

**Comment by celsodantas** [comment]
OK

**Comment by slawosz** [comment]
OK

**Comment by agrimm** [comment]
OK

**Comment by franckverrot** [comment]
OK

**Comment by arthurschreiber** [comment]
Ok

**Comment by argent-smith** [comment]
Ok

**Comment by mainej** [comment]
OK

**Comment by jamesotron** [comment]
OK

**Comment by martinstannard** [comment]
OK

--
  Martin Stannard
  mstannard@gmail.com
 
 
 
On Tue, 12 Jan 2016, at 08:30 AM, James Harton wrote:
> OK


> —
> Reply to this email directly or view it on GitHub[1]. 


>  


Links:

  1. https://github.com/rubinius/rubinius/issues/3550#issuecomment-170695921

**Comment by stormbrew** [comment]
OK

**Comment by baroquebobcat** [comment]
OK

**Comment by ikataitsev** [comment]
OK

**Comment by vic** [comment]
OK

**Comment by manveru** [comment]
OK

**Comment by khamutov** [comment]
OK

**Comment by davorb** [comment]
OK

**Comment by nexcastellan** [comment]
OK

**Comment by tamird** [comment]
OK

**Comment by bradediger** [comment]
OK

**Comment by daikini** [comment]
OK

**Comment by chuckremes** [comment]
OK

**Comment by jarib** [comment]
OK

**Comment by zzak** [comment]
OK

**Comment by vvs** [comment]
@vvs OK

**Comment by ryoqun** [comment]
OK

**Comment by charliesome** [comment]
OK

**Comment by dkubb** [comment]
OK

**Comment by kodnin** [comment]
OK

**Comment by doudou** [comment]
@doudou OK

**Comment by veganstraightedge** [comment]
OK

**Comment by rue** [comment]
OK

**Comment by mitchellh** [comment]
OK

**Comment by DanielVartanov** [comment]
OK

**Comment by pbevin** [comment]
OK

**Comment by krsh** [comment]
OK

**Comment by audreyt** [comment]
OK

**Comment by anthropomorphic** [comment]
OK

**Comment by heronmedeiros** [comment]
OK

**Comment by brynary** [comment]
OK

**Comment by frasca** [comment]
OK

**Comment by cezarsa** [comment]
OK

**Comment by drbrain** [comment]
Per my email (attached in comments above) you need to ask @engineyard if they are OK with the license change for the commits with my name during my employment there.

If you find code contributed by me that is was not committed during my employment with @engineyard please re-ping me so I can properly confirm/deny (I'm unsure if there is any).

**Comment by pH14** [comment]
OK

**Comment by zacts** [comment]
OK

**Comment by warrenseen** [comment]
OK

**Comment by gustavotemple** [comment]
OK

**Comment by zacts** [comment]
OK

**Comment by Groogy** [comment]
OK

**Comment by dmacvicar** [comment]
OK

**Comment by bterkuile** [comment]
OK

**Comment by caiquanqing** [comment]
OK

**Comment by LTe** [comment]
OK

**Comment by davorb** [comment]
OK
