### ISSUE TITLE
Lacks code of conduct

### ISSUE THREAD

**Issue by agrimm** [rubinius/rubinius#3551]
Neither the rubinius/rubinius git repository, nor published versions of rubinius.com have a code of conduct. The closest thing is an announcement in [November 2014](http://rubinius.com/2014/11/10/rubinius-3-0-part-1-the-rubinius-team/) that there will be one, plus an unpublished [code of conduct](https://github.com/rubinius/rubinius.github.io/blob/master/_includes/code-of-conduct.html).

**Comment by YorickPeterse** [comment]
@brixen is working on the new website which will contain the CoC. A copy of the current WIP can be found at http://rubinius.com/code-of-conduct/.

**Comment by agrimm** [comment]
Is the code of conduct itself considered finished, or is it still being worked on?

**Comment by YorickPeterse** [comment]
@agrimm As far as I'm aware said CoC is considered to be finished, it's merely the layout and such that's being worked on.

**Comment by jc00ke** [comment]
rubinius/rubinius.github.io#55

**Comment by agrimm** [comment]
If the code of conduct itself is ready, then ship it. Don't delay it until the new website is ready.

**Comment by jc00ke** [comment]
While there might not be a link from other pages, it's there, shipped: http://rubinius.com/code-of-conduct/
