### ISSUE TITLE
Builds using LLVM > 3.5

### ISSUE THREAD

**Issue by jzakiya** [rubinius/rubinius#3553]
The latest version I have been able to build, using RVM or by hand with source, has been 2.5.2.d
I am using PCLOS, which uses LLVM 3.7.
I just tried to install RBX-3.2 using RVM, and as expected it didn't compile because it says it needs LLVM 3.0-3.5.  See below.

------------------------------ Deprecation notice ------------------------------
Support for compilers other than clang/clang++ is deprecated and will be
removed soon. If your platform does not have support for clang/clang++,
please notify us.
--------------------------------------------------------------------------------

Detected old configuration settings, forcing a clean build
  Checking for 'llvm-config': only LLVM 3.0-3.5 is supported
ABORT: unable to set up LLVM

So, when will RBX support LLVM 3.7+?

**Comment by jc00ke** [comment]
The changes to the JIT system in 3.6 need to be addressed first, so my guess is it'll be a while. If you can get 3.5 installed and still have issues installing Rubinius, please let us know.

**Comment by brixen** [comment]
@jzakiya the work for LLVM 3.6+ support is on the mcjit branch. It should get finished soon. In the meantime, if your platform doesn't have packages for LLVM 3.5 (FYI, you'll need to run `./configure --llvm-config=path/to/your/llvm-config-3.5`), then you could use our Docker image for now: http://rubinius.com/packages#docker.

**Comment by majioa** [comment]
+1 to address to JIT system in 3.6, please fix it.
