### ISSUE TITLE
Issue with Enumerable

### ISSUE THREAD

**Issue by ioquatix** [rubinius/rubinius#3554]
When using `to_enum`, yield with multiple args is not handled correctly?

```ruby
class Bob
	def foo(*args)
		return to_enum(:foo, *args) unless block_given?
		
		paths = []
		
		3.times do
			yield args.shift, args.shift
		end
	end
end

bob = Bob.new
things = bob.foo(1, 2, 3, 4, 5, 6)

things.each do |thing|
	puts thing.inspect
	# Correct behavior:
	# MRI: gives 1, 3, 5
	# RBX: gives 1, 3, 5
end

puts things.first.inspect
# Odd behavior:
# MRI: [1, 2]
# RBX: 1
```

**Comment by ioquatix** [comment]
After reviewing this issue I found that the problem is with `Enumerable::next`. It doesn't work correctly for the base case. This monkey patch fixes the issue:

```ruby
module Enumerable
	def first(n=1)
		return __take__(n) unless n == 1
		each { |*obj| return *obj }
		nil
	end
end
```

**Comment by ioquatix** [comment]
So, basically the problem is to do with `|*obj|`. I took a look in the code and it might affect other functions too, e.g. `cycle`.

**Comment by brixen** [comment]
@ioquatix thanks for reporting this. Do you know if there is a spec that describes this behavior?

**Comment by ioquatix** [comment]
I have no idea where to look for an official spec but I assume that the behaviour should match MRI? The above code is a basic outline of what a spec might look like, but as I said there are other methods, e.g. `cycle` that are affected.

**Comment by ioquatix** [comment]
Okay, here is an example of the issue with count:

```ruby
#!/usr/bin/env ruby

class Bob
    def foo(*args)
        return to_enum(:foo, *args) unless block_given?

        paths = []

        3.times do
            yield args.shift, args.shift
        end
    end
end

bob = Bob.new
things = bob.foo(1, 2, 3, 4, 5, 6)

puts things.count([1, 2])
# MRI: gives 1
# RBX: gives 0
```

**Comment by ioquatix** [comment]
Here is an example showing `slice_before` is broken:

```ruby
#!/usr/bin/env ruby

class Bob
    def foo(*args)
        return to_enum(:foo, *args) unless block_given?

        paths = []

        3.times do
            yield args.shift, args.shift
        end
    end
end

bob = Bob.new
things = bob.foo(1, 2, 3, 4, 5, 6)

more = things.slice_before do |a, b|
	a == 3 and b == 4
end.to_a

puts more.inspect
# MRI: [[[1, 2]], [[3, 4], [5, 6]]]
# RBX: [[1, 3, 5]]
```

There are potentially more functions, someone which better access and knowledge than me should probably do a complete audit.

**Comment by ioquatix** [comment]
This is awesome you guys fixed these issues really quickly. If someone has time it might be worth figuring out if any other methods have the same issue. I just glanced through the documentation and found these examples.

**Comment by jsyeo** [comment]
@ioquatix thanks for reporting them. Yep, you're right. I think there are more `Enumberable` methods that have this problem with enumerables that yields multiple values. I will get back to them this weekend when I have the time.

Since the issues that you have reported are fixed and merged, I will close this issue.

**Comment by ioquatix** [comment]
Thanks so much for your effort.
