### ISSUE TITLE
"Invalid byte sequence in US-ASCII" when LANG, etc. set to en_US.UTF-8

### ISSUE THREAD

**Issue by jawshooah** [rubinius/rubinius#3555]
RuboCop's `rbx-2` build has been failing for quite some time, and upon trying to patch it up, I discovered what appears to be a bug in Rubinius.

Even with `LANG=en_US.UTF-8`, `LANGUAGE=en_US.UTF-8`, and `LC_ALL=en_US.UTF-8`, I'm seeing an `invalid byte sequence in US-ASCII` error. [Relevant lines from recent build failure](https://travis-ci.org/bbatsov/rubocop/jobs/100991199#L241-L245).

**Comment by brixen** [comment]
RubyCop isn't testing on Rubinius.
