### ISSUE TITLE
Exception running specs on rubinius-3.4 on Ubuntu 14.04

### ISSUE THREAD

**Issue by AnwarShah** [rubinius/rubinius#3560]
I was installing rubinius 3.4 on Ubuntu 14.04. All things went good, but the tests are failing.

**Edit:** replaced previous inline paste with a link to a gist below.

https://gist.github.com/brixen/5e47c5e23d6e9f323972

**Comment by YorickPeterse** [comment]
Please provide the details of `config.rb` and the likes (as stated in the CONTRIBUTING guide at https://github.com/rubinius/rubinius/blob/master/CONTRIBUTING.md#submitting-issues).

**Comment by AnwarShah** [comment]
`config.rb` file's content is given in [the gist here](https://gist.github.com/AnwarShah/eafcfdfbaacacddcd7ee)

**Comment by brixen** [comment]
@AnwarShah I put your inline paste into a gist so the ticket is easier to read.

Could you please run this and gist the results `bin/mspec ci spec/ruby/optional/capi/bignum`?

**Comment by AnwarShah** [comment]
@brixen Thanks for the reply and help. I've run the command and the output is [here is this gist](https://gist.github.com/AnwarShah/facf5298dab88edd9c4c)

**Comment by brixen** [comment]
@AnwarShah ah ok, thanks, that looks helpful. It seems possible that a C++ exception is being thrown when calling from the C-API code and that will cause an abort when trying to unwind through the C stack.

**Comment by AnwarShah** [comment]
@brixen Any recommended solution for this?

**Comment by brixen** [comment]
@AnwarShah well, it's puzzling that it's aborting for you but not when the specs run on Travis on 12.04. I'll need to change the way `rb_dbl2big` handles values like Nan and Infinity so that C++ exceptions aren't being raised.

I'll try to get a patch tomorrow for you to test when you have time.

**Comment by brixen** [comment]
@AnwarShah if by chance you're interested in looking into this yourself, we need to test for Nan and Infinity in `rb_dbl2big` the same way we test in `Bignum::from_double`, but raise an exception in `rb_dbl2big` with `rb_raise` instead.

**Comment by YorickPeterse** [comment]
@andre-richter what's the reason for closing this issue? As far as I can tell no fix is there just yet.

**Comment by andre-richter** [comment]
I absolutely can't explain how this happened.
Haven't even been logged in at github today.

Changing my password right now!

**Comment by brixen** [comment]
@AnwarShah I added the fix I mention in this commit https://github.com/rubinius/rubinius/commit/e265a22ae15caeabe38eed190b80c607739ca9fa. Could you please build and test master as follows:

```
$ git clone https://github.com/rubinius/rubinius
$ cd rubinius
$ ./configure
$ rake
```

**Comment by AnwarShah** [comment]
@brixen I'll update you soon by trying this. Thanks

**Comment by AnwarShah** [comment]
@brixen I've manually patched that single file and tried using `./configure` and `rake` command (without cloning master). [This is the output](https://gist.github.com/AnwarShah/4e2fb433aec2683b39fd) given.

**Comment by AnwarShah** [comment]
@brixen After failing above attempt, I clone the repository using `--depth 1`. However, It still failing, though with only 2 errors. [Here is the gist](https://gist.github.com/AnwarShah/83f2837b6eb36ba344c9) of the output

**Comment by brixen** [comment]
@AnwarShah thanks for checking. The other failures were fixed. So, that's good. The two failures you are seeing are because your platform is 32bit. Both failures result from assumptions in the specs that the platform is 64bit. I'll update those two specs to make them work on 32bit.

I'm curious, do you have a requirement to use 32bit? We will likely be supporting only 64bit in the future, but I still haven't decided for sure. I'm curious to hear from people why they are using 32bit.

**Comment by AnwarShah** [comment]
@brixen Sounds great! Hope it will be fixed.

I actually switched to 64bit few months ago. But, Now needed to use 32bit again for a modem issue. I have an old modem, which doesn't have 64bit driver for Linux. Even 32bit driver is removed from latest kernel. It's a binary only driver.

I'm thinking of dumping that modem permanently. But, in the meanwhile, I must use 32bit at least for few more days.

**Comment by brixen** [comment]
@AnwarShah ah, ok, it's always interesting to hear. We won't be dropping 32bit support in the next few days and I'm still open to supporting it if we can do so without too much work. Some of the stuff I want to do in the object memory would benefit a lot from a 64bit word in the object header, but we can still support it with a more costly overhead on 32bit. Anyway, I think these specs should be fix. Could you build master and test?

**Comment by AnwarShah** [comment]
@brixen Great! It builds successfully with that fix! Thanks. It outputs -- 

```
Finished in 434.842057 seconds

2194 files, 20605 examples, 154900 expectations, 0 failures, 0 errors
```

**Comment by brixen** [comment]
@AnwarShah awesome! Thanks for taking the time to let us know about the issues.
