### ISSUE TITLE
Booting GitLab is around 2x slower than MRI

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3571]
Booting GitLab on MRI 2.1.7 (the version GitLab currently uses) takes about 11-12 seconds (as measured using `time -f '%E' rails r ''`. 

On Rubinius the timings are as following:
- cold bootup (boot without the `~/.rbx` directory existing): ~50 seconds
- regular bootup: ~25 seconds

Profiler output (`rbx -Xprofile -S rails r ''`): https://gist.github.com/YorickPeterse/0715ced873746ea8e2ef

**Comment by YorickPeterse** [comment]
Having looked into the code of `Array#==` I can't find anything that stands out as being bad on its own, instead it looks more like a collection of things leading to this method performing as it currently does. Some of the things we would have to improve for this method (that I can think of):

* `Rubinius::Tuple` access (better Ruby code, specialized instructions, maybe JIT specific bits)
* Incrementing counters, e.g. `some_fixnum += 10`. Right now this uses the usual approach of `push_local -> push_int -> send_stack :+ -> set_local` but in theory we could use something like `increment_local 0, 10`; though this would only work for Fixnums
* Reducing mirror overhead (e.g. `Mirror.reflect`)
* Improving thread recursion detection

**Comment by YorickPeterse** [comment]
As an added note I'm OK with GitLab booting up a little bit slower, but 2x is going to lead to a lot of developers constantly complaining about the bootup being so slow.

**Comment by jemc** [comment]
As I understand it, bootup time for large applications is one of the problems that [the `codedb` branch](https://github.com/rubinius/rubinius/tree/codedb) is intended to solve.

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.
