### ISSUE TITLE
First GitLab request is extremely slow

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3573]
Booting up GitLab CE and using my local database results in the first request taking around 137 seconds. Quickly scanning through the Rails logs seems to indicate a lot of time being spent in rendering views (or running code present in said views). Since GitLab uses HAML I wouldn't be surprised if it's partially to blame.

**Comment by YorickPeterse** [comment]
Having said that, subsequent requests load in a much more reasonable time. For example, requesting the index page of gitlab-org/gitlab-ce locally takes around 2.6 seconds. It's possibly the JIT might need some extra crutches to handle GitLab for the first request.

**Comment by YorickPeterse** [comment]
Profiler output of the first request to /gitlab-org/gitlab-ce: https://gist.github.com/YorickPeterse/41bb9196012717f1a12d

Output of the second request to the same page: https://gist.github.com/YorickPeterse/bf16fcd5288f79629971

**Comment by jc00ke** [comment]
I notice our app takes a long time on first request (even on MRI) and we use ERB. I believe a lot of the slowness comes from SASS. Does GitLab use SASS too?

**Comment by YorickPeterse** [comment]
@jc00ke Yes, the stack is the pretty standard SASS + HAML stack.

**Comment by benlovell** [comment]
https://github.com/sass/sassc-rails is faster and has (so far) worked out OK for me.

**Comment by brixen** [comment]
@YorickPeterse do you know if files could be getting lazily loaded during that first request? Is Autoload (or Rails autoloading hack) in use?

**Comment by YorickPeterse** [comment]
@brixen It's quite possible a lot of stuff is being loaded on the first request. GitLab itself doens't use autoloading explicitly, only the class autoloading Rails itself provides.

**Comment by brixen** [comment]
In order to make performance work as efficient and effective as possible, the focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Once these core capabilities are properly functioning, it will be possible to create a how-to guide to examining and fixing performance issues.
