### ISSUE TITLE
Kernel#rand with an exclusive Range should not call Range#max

### ISSUE THREAD

**Issue by mlarraz** [rubinius/rubinius#3586]
MRI:
```ruby
rand(0...1.0) # => some positive float less than 1
```

RBX 3.11:
```ruby
rand(0...1.0)
# =>
# TypeError: cannot exclude non Integer end value
#	from kernel/common/range.rb:198:in `max'
#	from kernel/common/random.rb:69:in `random_range'
#	from kernel/common/random.rb:36:in `random'
#	from kernel/common/kernel.rb:721:in `rand'
```

Note that ```(0...1.0).max``` raises this error in both implementations, so that behavior is correct.

This is not just a theoretical concern. Currently the [rubocop](https://github.com/bbatsov/rubocop) suite fails on Rubinius due exclusively to this issue:
https://travis-ci.org/bbatsov/rubocop/jobs/104055842
https://github.com/bbatsov/rubocop/blob/master/spec/rubocop/cop/rails/pluralization_grammar_spec.rb#L56

**Comment by jemc** [comment]
Fixed in fa397f821d96bfe2384ae9c4aa6a53b76c4993d0
Released in [`v3.12`](https://github.com/rubinius/rubinius/releases/tag/v3.12)!
