### ISSUE TITLE
Array#product with block modifying self

### ISSUE THREAD

**Issue by jkr2255** [rubinius/rubinius#3587]
# Issue
In MRI (tested on 2.0.0 - 2.3.0), `Array#product` with block doesn't modify `self` and can be used for frozen arrays, but Rubinius modifies original array, and fails to run on frozen arrays due to this behavior.

In [reference manual of MRI (Japanese edition)](http://docs.ruby-lang.org/ja/2.3.0/method/Array/i/product.html), `Array#product` with block does return `self`, but unmodified.

# reproduction code
```rb
arr = [1,2,3].freeze
arr.product([4,5,6]){ 1 }
# MRI can do this, while Rubinius raises RuntimeError
```

# environment
* Rubinius 3.5 (2.2.0 2016-01- 2016-01-25 3.4.2 JI) [x86_64-linux-gnu] ; Installed from rbenv
* Linux localhost.localdomain 3.10.0-327.3.1.el7.x86_64 #1 SMP Wed Dec 9 14:09:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by YorickPeterse** [comment]
This seems pretty nasty as non-bang methods typically aren't supposed to modify `self`.

**Comment by YorickPeterse** [comment]
Seems this method does more crazy things such as [modifying arguments in-place](https://github.com/rubinius/rubinius/blob/fa397f821d96bfe2384ae9c4aa6a53b76c4993d0/kernel/common/array.rb#L1118).

**Comment by andre-richter** [comment]
There's more to fix here. Unfrozen and blocks is bogus, too:

```ruby
arr = [1,2]

puts arr.product([4,5]){ 1337 }.inspect
puts arr.product([4,5]){ |x| x*2 }.inspect
puts arr.product([4,5]){ |x| puts "hi #{x}" }.inspect
```

```bash
MRI:
[1, 2]
[1, 2]
hi [1, 4]
hi [1, 5]
hi [2, 4]
hi [2, 5]
[1, 2]

rbx: **explodes**
```
Result of the block must not appended to the array, only yield to it and return self.

[From the ruby feature request:](https://bugs.ruby-lang.org/issues/3021)
`I suggest that Array#product(&block) yields to the block and returns self.`
