### ISSUE TITLE
Changing license from BSD 3-clause to MPL 2.0: Extra Notification

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3598]
To reduce the amount of notifications sent out whenever replying to https://github.com/rubinius/rubinius/issues/3550 I'll be using this issue to ping contributors regarding the license change.

To the contributors on the list below, please reply to the above issue _or_ send me an Email (following the instructions in said issue). Thank you.

Script to check who has not yet replied:

``` javascript
$('.task-list-item input[type="checkbox"]:not(:checked)').map(function(i, el) { return $(el).next()[0].innerText; });
```

**Comment by YorickPeterse** [comment]
* @Aesthetikx
* @AndrewVos
* @anthropomorphic
* @audreyt
* @banister
* @brynary
* @btakita
* @bterkuile
* @carlosbrando
* @cezarsa
* @crayz
* @cyfdecyf
* @DanielVartanov
* @dlt
* @drbrain
* @drnic
* @frasca
* @Gibheer
* @gramos
* @Groogy
* @halorgium
* @headius
* @herminiotorres
* @heronmedeiros
* @hurdlea
* @huy
* @jero5
* @jgre
* @jmstacey
* @jonforums
* @josh
* @krsh
* @kwatch
* @leavengood
* @matthewd
* @mental
* @mitchellh
* @mlangenberg
* @monkeylibre
* @pbevin
* @pH14
* @r-stu31
* @rue
* @santana
* @seydar
* @southerngs
* @Stormwind
* @subwindow
* @tarcieri
* @tonysidaway

**Comment by YorickPeterse** [comment]
* @vincentlu
* @vjmp
* @warrenseen
* @wilson
* @wycats
* @xenda
* @zenspider

**Comment by burningTyger** [comment]
At least one of the people mentioned above is banned from "participation in any forum or space, online or in-person, that is primarily devoted to the Rubinius project". What does that mean for the license change? Also, I actually disagree with banning people.

**Comment by YorickPeterse** [comment]
@burningTyger 

> What does that mean for the license change? 

I have Emailed Charles in the past (I emailed all above users that had an Email on their GitHub profile) but have not yet gotten a reply. If need be I'll find other methods to contact them.

> Also, I actually disagree with banning people.

We don't. The reasoning for this can be found in http://rubinius.com/2016/01/15/banning-mr-nutter-for-repeated-harassment.

Having said all that, this issue is not the place to discuss anything as I want to use solely to ping people, hence it was locked in the first place. Please move the discussion to the Gitter channel.

To clarify for any other contributors: do **not** reply here as this only increases the amount of GitHub notifications being sent out and I don't want to spam contributors any more than necessary.

**Comment by YorickPeterse** [comment]
I'm still awaiting a response from the following contributors:

@Aesthetikx @AndrewVos @anthropomorphic @audreyt @banister @brynary @btakita @bterkuile @carlosbrando @cezarsa @crayz @cyfdecyf @dlt @drbrain @drnic @frasca @Gibheer @gramos @Groogy @halorgium @headius @herminiotorres @heronmedeiros @hurdlea @huy @jero5 @jgre @jmstacey @jonforums @josh @krsh @kwatch @leavengood @matthewd @mlangenberg @monkeylibre @pH14 @r-stu31 @santana @seydar @southerngs @Stormwind @subwindow @tarcieri @tonysidaway @vincentlu @vjmp @warrenseen @wilson @wycats @xenda @zenspider

To said contributors, please see issue #3550 and leave a comment in said issue.

**Comment by YorickPeterse** [comment]
The following people still have non spec code on HEAD and have yet to reply:

@Aesthetikx @Gibheer @Stormwind @btakita @carlosbrando @halorgium @jero5 @matthewd @pH14 @seydar @southerngs @subwindow @tarcieri @tonysidaway @wilson @wycats @headius
