### ISSUE TITLE
Symbol Garbage Collection

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3599]
Extracting this feature from https://github.com/rubinius/rubinius/issues/3264 as it's one that probably needs quite some thought/work/changes. Rails already stated that at some point they'll depend on Symbols being GC'd. MRI does some hack where certain `to_sym` methods return Symbols that can be collected, but I think we can just collect any non literal Symbols and be done with it.

**Comment by brixen** [comment]
In general, Rubinius enthusiastically supports experimentation and welcomes ideas for features that enhance developer ability to create amazing software.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to support more efforts around experimentation.
