### ISSUE TITLE
Update parser for another heredoc literal

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3602]
The parser should be updated to allow _another_ heredoc literal: `<<~`.

Extracted from https://github.com/rubinius/rubinius/issues/3559
Redmine ticket: https://bugs.ruby-lang.org/issues/9098

**Comment by tomkadwill** [comment]
Hi @YorickPeterse, are you happy if I take a look at this? I'm a new contributor, is there any timeline for this feature?

**Comment by YorickPeterse** [comment]
@tomkadwill Knock yourself out, there's no deadline whatsoever :)

**Comment by brixen** [comment]
@tomkadwill thanks for taking a look at this! Please hop into the Gitter channel if you have any questions.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
