### ISSUE TITLE
Add support for Encoding::IBM037

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3603]
The only reference I can find to this encoding in Redmine is this commit: https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/53124. This encoding is aliased as `Encoding::EBCDIC_CP_US`.

Extracted from https://github.com/rubinius/rubinius/issues/3559

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
