### ISSUE TITLE
IO#advise no longer raises Errno::ENOSYS in cases where it was detected at build time but not available at runtime

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3605]
Redmine ticket: https://bugs.ruby-lang.org/issues/11806

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
