### ISSUE TITLE
Add support for Module#deprecate_constant

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3606]
Redmine ticket: https://bugs.ruby-lang.org/issues/11398

I'm not sure how we'd tag a constant as deprecated in our current system, or how useful it is in the first place.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
