### ISSUE TITLE
Thread#name, Thread#name= are added to handle thread names

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3609]
Redmine ticket: https://bugs.ruby-lang.org/issues/11251

Notes from what I found: 
- `pthread_setname_np` on OSX only allows setting the name of the calling thread from what I could find.
- ASCII incompatible names should raise an ArgumentError
- Names are stored inside a thread as well as being used to set the OS thread name
- If a name is longer than 16 characters (the maximum length for POSIX thread names) only the first 16 characters are used for the native thread. Calling `Thread#name` however _does_ return the full name (so basically we'd just store/read from an instance variable when calling `Thread#name`)

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
