### ISSUE TITLE
Array#inspect doesn't raise error even if its content returns a string which is not compatible with Encoding.default_external as inspected result

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3610]
Redmine ticket: https://bugs.ruby-lang.org/issues/11801

**Comment by YorickPeterse** [comment]
This can be reproduced using:

```ruby
o = Object.new

def o.inspect
  'abc'.encode(Encoding::UTF_32LE)
end

p [o].inspect
```

**Comment by tak1n** [comment]
As I'm currently in the process of implementing that the question which raises is what does CRuby use for encoding if the array contains multiple elements of different non compatible encoding.

Trying to extract that out of the c code in the mentioned redmine ticket.

What I could come up for now:

```ruby
o  = Object.new
o2 = Object.new

def o.inspect
  'abc'.encode(Encoding::UTF_16BE)
end

def o2.inspect
  'def'.encode(Encoding::UTF_16LE)
end

p Encoding.default_external
p [o, o2].inspect
p [o, o2].inspect.encoding
```

CRuby:

```
#<Encoding:UTF-8>
"[abc, def]"
#<Encoding:US-ASCII>
```

Rbx:

```
#<Encoding:UTF-8>
"[abc, def]"
#<Encoding:UTF-16BE>
```

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
