### ISSUE TITLE
Hash#inspect doesn't raise error even if its content returns a string which is not compatible with Encoding.default_external as inspected result

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3611]
Redmine ticket: https://bugs.ruby-lang.org/issues/11801

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
