### ISSUE TITLE
Add rb_define_class_id_under to the C API and update rb_define_class_under to raise a TypeError for a superclass mismatch

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3613]
This function is the same as `rb_define_class_under` except the name should be an `ID` instead of a `const char *`.

**Comment by YorickPeterse** [comment]
From the 2.3 changelog:

> rb_define_class_id_under() now raises a TypeError exception when the class is already defined but its superclass does not match the given superclass, as well as definitions in ruby level.

**Comment by YorickPeterse** [comment]
@ahmadsherif Does our `rb_define_class_id_under` / `rb_define_class_under` raise TypeError in the case mentioned above?

**Comment by ahmadsherif** [comment]
@YorickPeterse It does through `rubinius::Helpers::open_class` which in turn calls `rubinius::Helpers::check_superclass`.

**Comment by YorickPeterse** [comment]
@ahmadsherif Ah OK.
