### ISSUE TITLE
Add rb_timespec_now and rb_time_timespec_new to the C API

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3614]
Redmine ticket: https://bugs.ruby-lang.org/issues/11558

**Comment by YorickPeterse** [comment]
`rb_time_timespec_new` was added in df6783d594c2419575d0031f086b0affa04ce331.

**Comment by brixen** [comment]
In general, the MRI C-API for Rubinius is deprecated, but that doesn't mean it will be going anywhere soon. Compatibility for C-extensions will continue to be evaluated on a case-by-case basis. However, C-extensions that depend on functions that examine or manipulate built-in MRI data structures will never be supported.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated.
