### ISSUE TITLE
Regexp/String: Updated Unicode version from 7.0.0 to 8.0.0

### ISSUE THREAD

**Issue by YorickPeterse** [rubinius/rubinius#3615]
Ruby 2.3 applied this, unsure how this affects us. Noting it here so we don't lose track of it.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
