### ISSUE TITLE
Process.clock_gettime and related Process::CLOCK_* not yet implemented

### ISSUE THREAD

**Issue by smarr** [rubinius/rubinius#3618]
I was trying to execute code that uses `Process.clock_gettime(Process::CLOCK_MONOTONIC, :nanosecond)` on rbx 3.14, but this does not yet seem to be implement.

My current work around is to use `Time.new`, which is fine for the amount of precision I need. So, not urgent, just wanted to document it.

**Comment by brendon** [comment]
I'm having trouble testing Rails 5.2.2 against `rbx-3.107`

Per: https://travis-ci.org/mixonic/ranked-model/jobs/465731591

```
NameError:
  uninitialized constant Process::CLOCK_MONOTONIC
# ./gemfiles/vendor/bundle/rbx/2.3/gems/activesupport-5.2.2/lib/active_support/subscriber.rb:111:in `now'
```

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
