### ISSUE TITLE
Rubinius is slow to execute a big and trivial case-when statement

### ISSUE THREAD

**Issue by mame** [rubinius/rubinius#3620]
Hello,

MRI adopts "jump table"-like optimization for case-when statement if all clauses have trivial immediate values such as Integer and Symbol.  How about implementing this optimization in Rubinius?

~~~
100000.times do
  case 1000
  when 0
  when 1
  when 2
  ...
  when 999
  end
end
~~~

~~~
$ time ruby -v t.rb
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

real    0m0.082s
user    0m0.068s
sys     0m0.012s
~~~

~~~
# time ruby -v t.rb
rubinius 3.14 (2.2.2 a7ba16db 2016-01-28 3.4.2 JI) [x86_64-linux-gnu]

real    0m2.311s
user    0m2.240s
sys     0m0.064s
~~~

(I'm using rubinius/docker.)

Thank you for your consideration,

**Comment by jemc** [comment]
Something to watch out for:

You can't make this kind of optimization with `Fixnum` if the `===` method is overwritten for `Fixnum`, for example.

**Comment by mame** [comment]
Sure.  Whenever MRI evaluates such a case statement, it checks if `===` is redefined or not.

**Comment by brixen** [comment]
@mame thanks for the suggestion.

This optimization would go in the compiler, not in Rubinius itself, so https://github.com/rubinius/rubinius-code would be a more appropriate place for a PR.

The bigger issue is that there are many possible optimizations and without any information about how common such a case statement is, it's hard to know whether to prioritize it.

Alternatively, if someone worked on it and opened a PR, it would be easy to evaluate it. But without a PR, we have to close tickets like this that are not actionable (*possible* work is not actually actionable) or they just languish as noise in the issues list. Periodically, we go through and clean them up, but we need to be more disciplined about it.

Please open a PR on the other repository if you want to make progress on this.

**Comment by mame** [comment]
@brixen, I see, thank you for your reply.  I'm sorry I didn't know rubinius repository structure and policy.  

This issue is critical in a program that I'm creating now (It is not published yet.  I plan to publish it in a few months).  I found Rubinius (and [JRuby 9k](https://github.com/jruby/jruby/issues/3672)) much slower than MRI, so I just wanted to inform a possible improvement to you.

Thank you,

**Comment by brixen** [comment]
@mame I hope you let us know when you publish your program. The diagnostics and performance tooling we're working on should make it easy to both see and analyze behavior like this, so hopefully someone will use that to make an improvement.

**Comment by mame** [comment]
@brixen Sure!

**Comment by YorickPeterse** [comment]
I created an issue in the rubinius-code repository for this so we won't lose track of it: https://github.com/rubinius/rubinius-code/issues/2

**Comment by mame** [comment]
@brixen FYI: I published [my program and benchmark result](https://github.com/mame/optcarrot).  Enjoy!

**Comment by brixen** [comment]
@mame thanks for letting us know!
