### ISSUE TITLE
Rubinius 3.10 and 2.58 builds fail on heroku

### ISSUE THREAD

**Issue by hubrix** [rubinius/rubinius#3623]
## Problem

-----> Ruby app detected
-----> Compiling Ruby/Rack
 !
 !     An error occurred while installing Ruby ruby-2.1.0-rbx-2.5.8
 !     For supported Ruby versions see https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
 !     Note: Only the most recent version of Ruby 2.1 is supported on Cedar-14
 !     Command: 'set -o pipefail; curl -L --fail --retry 3 --retry-delay 1 --connect-timeout 3 --max-time 30 -O http://binaries.rubini.us/heroku/cedar-14/ruby-2.1.0-rbx-2.5.8.tar.bz2' failed unexpectedly:
 !     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
 !     Dload  Upload   Total   Spent    Left  Speed
 !     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 !     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 !     curl: (22) The requested URL returned error: 404 Not Found
 !
 !     Push rejected, failed to compile Ruby app

## How to Reproduce

set ruby to ruby-2.1.0-rbx-2.5.8 and deploy to heroku

**Comment by jc00ke** [comment]
That's a very old version of Rubinius... can you post the `ruby` line to your `Gemfile`?

**Comment by CyberLeo** [comment]
Here is the failing ruby line:
`ruby "2.1.0", :engine => "rbx", :engine_version => "2.5.8"`

This works:
`ruby "2.1.0", :engine => "rbx", :engine_version => "2.5.7"`

This fails while building native extensions with 'make: clang: Command not found':
`ruby "2.2.0", :engine => "rbx", :engine_version => "3.10"`

I did not see any other heroku builds available.

**Comment by brixen** [comment]
@hubrix 3.16 should be working on Heroku https://blooming-chamber-2721.herokuapp.com
