### ISSUE TITLE
Errors using Marshal.load

### ISSUE THREAD

**Issue by asppsa** [rubinius/rubinius#3628]
## Problem

When using `Marshal.load` to load certain marshalled data structures, I am seeing `ArgumentError` exceptions and occasional segfaults.  I do not have the issue in 3.14; from my tests it seems to have started with 3.15.  I've tested 3.19, but not git master.
## How to Reproduce

The following script usually produces the issue for me.  Sometimes I have to run it more than once.

``` ruby
100.times do
  marshalled = Marshal.dump((1..100).map{ "hi" })
  Marshal.load(marshalled)
end
```
## Configuration Details
- Output of `rbx -v`: `rubinius 3.19 (2.2.2 1cc41ddc 2016-02-27 3.5.2 JI) [x86_64-linux-gnu]`
- Output of `uname -a`: `Linux managua 4.1.19-1-lts #1 SMP Sun Mar 6 09:23:49 CET 2016 x86_64 GNU/Linux`
- Distribution name (in case of Linux/BSD): Archlinux
  - NB. I have also had the same problem on Debian 8

I've not tried building from source (have used ruby-build), so I don't have the following:
- Contents of `config.rb` (as a Gist link): 
- Contents of `configure.log` (as a Gist link):
## Stack Trace

The error is not always the same, so I've included a couple of different examples.  I've also included a gdb log showing a segfault.

https://gist.github.com/asppsa/5f97af3a55950a7841be

**Comment by brixen** [comment]
@asppsa could you `export RBXOPT=-Xint` and try running your repro?

**Comment by asppsa** [comment]
@brixen, I can confirm that using this option makes the problem go away on rbx-3.19

**Comment by asppsa** [comment]
If it helps, I'm using LLVM 3.5.2, as distributed by Archlinux

**Comment by brixen** [comment]
@asppsa it's not likely the version of LLVM that you're using but more likely an issue with the JIT handling some particular code shape. If you are interested in digging into it a bit, there are some JIT specs under `spec/jit/` that you may be able to use as an example. If you want to work on it, hop in the Gitter channel and chat us up. Otherwise, I'll try making a repro as a JIT spec but I probably won't get to it until after merging the stw branch.

**Comment by asppsa** [comment]
I can no longer reproduce this error on RBX 3.29.  I guess it got fixed!

**Comment by brixen** [comment]
@asppsa the JIT is currently disabled by default so I'm going to re-open this and double check when I re-enable the JIT. I'm just finish up the call site inline cache rewrite and will be working on the JIT right now, so I should either be able to repro this or it will be fixed.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
