### ISSUE TITLE
support for 2.2 quoted symbol in hash {'abc':5}

### ISSUE THREAD

**Issue by mfazekas** [rubinius/rubinius#3630]
## Problem

rbx 3.1 doesn't support {'abc':5}

this was new feature introduced in 2.2 
https://github.com/ruby/ruby/blob/v2_2_0/NEWS#L19-L20

## How to Reproduce

```ruby
rbx-3.1 :001 > {'abc':5}
SyntaxError: expecting tASSOC: (irb):1:7
	from /Users/boga/.rvm/rubies/rbx-3.1/runtime/gems/rubinius-melbourne-2.3.1.0/lib/rubinius/melbourne.rbc:48:in `syntax_error'
	from /Users/boga/.rvm/rubies/rbx-3.1/runtime/gems/rubinius-melbourne-2.3.1.0/lib/rubinius/melbourne.rbc:52:in `parse_string'
	from /Users/boga/.rvm/rubies/rbx-3.1/runtime/gems/rubinius-compiler-2.3.1/lib/rubinius/compiler/stages.rbc:241:in `parse'
	from /Users/boga/.rvm/rubies/rbx-3.1/runtime/gems/rubinius-compiler-2.3.1/lib/rubinius/compiler/stages.rbc:207:in `run'
	from /Users/boga/.rvm/rubies/rbx-3.1/runtime/gems/rubinius-compiler-2.3.1/lib/rubinius/compiler/compiler.rbc:359:in `run'
	from /Users/boga/.rvm/rubies/rbx-3.1/runtime/gems/rubinius-compiler-2.3.1/lib/rubinius/compiler/compiler.rbc:303:in `compile_eval'
	from /Users/boga/.rvm/rubies/rbx-3.1/runtime/gems/rubinius-compiler-2.3.1/lib/rubinius/compiler/compiler.rbc:315:in `construct_block'
```

## Configuration Details

* Output of `rbx -v`: rubinius 3.1 (2.1.0 d8e5c64a 2016-01-04 3.5.1 JI) [x86_64-darwin14.5.0]
* Output of `uname -a`:
* Distribution name (in case of Linux/BSD):
* Contents of `config.rb` (as a Gist link):
* Contents of `configure.log` (as a Gist link):

## Stack Trace

n/a

**Comment by mfazekas** [comment]
i'm a bit confused seems i should be trying 3.3 sorry. https://github.com/rubinius/rubinius/issues/3600

**Comment by brixen** [comment]
@mfazekas we need to find better ways to communicate the latest release but note that can find it here https://github.com/rubinius/rubinius/releases/latest and at the top of http://rubinius.com. The latest release right now is 3.19.
