### ISSUE TITLE
Rake aborted on FreeBSD 10.3-RELEASE

### ISSUE THREAD

**Issue by papilip** [rubinius/rubinius#3647]
## Problem
Unable to compile rubinus, `after mkdir -p runtime/core` rake aborted

## How to Reproduce
In a fresh FReeBSD install
```
sudo pkg install llvm35
git clone https://github.com/rubinius/rubinius.git
cd rubinus
./configure --prefix=/home/deploy/.rubies/rbx-3.29 --llvm-config=/usr/local/llvm35/bin/llvm-config
rake
```

## Configuration Details
* Output of `rbx -v`: never installed
* Output of `uname -a`: FreeBSD myserver 10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25 02:10:02 UTC 2016     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
* Distribution name (in case of Linux/BSD): FreeBSD 10.3
* Contents of `config.rb` (as a Gist link): https://gist.github.com/papilip/073b20a088cefd11d3b00b4945f40e29#file-config-rb
* Contents of `configure.log` (as a Gist link): https://gist.github.com/papilip/073b20a088cefd11d3b00b4945f40e29#file-configure-log

## Stack Trace
https://gist.github.com/papilip/073b20a088cefd11d3b00b4945f40e29#file-rake
https://gist.github.com/papilip/073b20a088cefd11d3b00b4945f40e29#file-rake-trace

## Comment
This is the same error with all versions of rubinus tested from 2.5 to 2.9

**Comment by brixen** [comment]
This should be fixed by 4b2a14b3.

**Comment by papilip** [comment]
@brixen Can you send me the command for compile rbx ? I can’t compile in my freebsd server or the vagrant file

**Comment by brixen** [comment]
@papilip 

```
$ git clone https://github.com/rubinius/rubinius
$ cd rubinius
$ bundle
$ ./configure
$ rake build
```

When `rake build` completes, `bin/rbx` will be the executable. You can add `/path_to_clone/bin/rbx` and `/path_to_clone/gems/bin` to PATH to run directly, or see the `--prefix` option for configure to set an install location. Use `rake install` instead of `rake build` if your configure with a prefix.
