### ISSUE TITLE
Can't use Gtk3 gem

### ISSUE THREAD

**Issue by GoldenKeyRiver** [rubinius/rubinius#3648]
## Problem

Gtk3 gem isn't working. 

## How to Reproduce

Install gtk3 and run any simple program.

## Configuration Details

* Output of `rbx -v`: rubinius 3.27 (2.2.2 628fe1c2 2016-04-15 3.5.2) [x86_64-linux-gnu]
* Output of `uname -a`: Linux PalladiumRiverPC 4.5.2-1-MANJARO #1 SMP PREEMPT Thu Apr 21 01:07:48 UTC 2016 x86_64 GNU/Linux
* Distribution name (in case of Linux/BSD): Manjaro Linux Gnome 15.12
* Contents of `config.rb` (as a Gist link): installed from pacman repository,
* Contents of `configure.log` (as a Gist link): installed from pacman repository,

## Stack Trace

Could not open library /usr/lib/rubinius/gems/gems/glib2-3.0.8/lib/glib2.so - /usr/lib/rubinius/gems/gems/glib2-3.0.8/lib/glib2.so: undefined symbol: CONST_ID (LoadError::InvalidExtensionError)

Backtrace:

  Rubinius::NativeMethod.load_extension at core/native_method.rb:26
     Rubinius::CodeLoader#load_library at core/code_loader.rb:672
          Rubinius::CodeLoader#require at core/code_loader.rb:130
          Rubinius::CodeLoader.require at core/code_loader.rb:227
  Kernel(Object)#gem_original_require (require) at core/kernel.rb:856
               Kernel(Object)#require at /usr/lib/rubinius/library/rubygems
                                         /core_ext/kernel_require.rb:55
                    Object#__script__ at /usr/lib/rubinius/gems/gems/glib2-3.0.8
                                         /lib/glib2.rb:115
          Rubinius::CodeLoader.require at core/code_loader.rb:233
  Kernel(Object)#gem_original_require (require) at core/kernel.rb:856
               Kernel(Object)#require at /usr/lib/rubinius/library/rubygems
                                         /core_ext/kernel_require.rb:55
                    Object#__script__ at /usr/lib/rubinius/gems/gems
                                         /gobject-introspection-3.0.8/lib
                                         /gobject-introspection.rb:17
          Rubinius::CodeLoader.require at core/code_loader.rb:233
  Kernel(Object)#gem_original_require (require) at core/kernel.rb:856
               Kernel(Object)#require at /usr/lib/rubinius/library/rubygems
                                         /core_ext/kernel_require.rb:55
                    Object#__script__ at /usr/lib/rubinius/gems/gems/gtk3-3.0.8
                                         /lib/gtk3.rb:17
          Rubinius::CodeLoader.require at core/code_loader.rb:233
  Kernel(Object)#gem_original_require (require) at core/kernel.rb:856
               Kernel(Object)#require at /usr/lib/rubinius/library/rubygems
                                         /core_ext/kernel_require.rb:55
                     Object#__script__ at rbnapigui.rb:1
      Rubinius::CodeLoader#load_script at core/code_loader.rb:505
      Rubinius::CodeLoader.load_script at core/code_loader.rb:590
               Rubinius::Loader#script at core/loader.rb:680
                 Rubinius::Loader#main at core/loader.rb:867

Caused by: Could not open library /usr/lib/rubinius/gems/gems/glib2-3.0.8/lib/glib2.so - /usr/lib/rubinius/gems/gems/glib2-3.0.8/lib/glib2.so: undefined symbol: CONST_ID (LoadError)

  Rubinius::FFI::DynamicLibrary#initialize at core/zed.rb:726
  Rubinius::NativeMethod.load_extension at core/native_method.rb:24
     Rubinius::CodeLoader#load_library at core/code_loader.rb:672
          Rubinius::CodeLoader#require at core/code_loader.rb:130
          Rubinius::CodeLoader.require at core/code_loader.rb:227
  Kernel(Object)#gem_original_require (require) at core/kernel.rb:856
               Kernel(Object)#require at /usr/lib/rubinius/library/rubygems
                                         /core_ext/kernel_require.rb:55
                    Object#__script__ at /usr/lib/rubinius/gems/gems/glib2-3.0.8
                                         /lib/glib2.rb:115
          Rubinius::CodeLoader.require at core/code_loader.rb:233
  Kernel(Object)#gem_original_require (require) at core/kernel.rb:856
               Kernel(Object)#require at /usr/lib/rubinius/library/rubygems
                                         /core_ext/kernel_require.rb:55
                    Object#__script__ at /usr/lib/rubinius/gems/gems
                                         /gobject-introspection-3.0.8/lib
                                         /gobject-introspection.rb:17
          Rubinius::CodeLoader.require at core/code_loader.rb:233
  Kernel(Object)#gem_original_require (require) at core/kernel.rb:856
               Kernel(Object)#require at /usr/lib/rubinius/library/rubygems
                                         /core_ext/kernel_require.rb:55
                    Object#__script__ at /usr/lib/rubinius/gems/gems/gtk3-3.0.8
                                         /lib/gtk3.rb:17
          Rubinius::CodeLoader.require at core/code_loader.rb:233
  Kernel(Object)#gem_original_require (require) at core/kernel.rb:856
               Kernel(Object)#require at /usr/lib/rubinius/library/rubygems
                                         /core_ext/kernel_require.rb:55
                     Object#__script__ at rbnapigui.rb:1
      Rubinius::CodeLoader#load_script at core/code_loader.rb:505
      Rubinius::CodeLoader.load_script at core/code_loader.rb:590
               Rubinius::Loader#script at core/loader.rb:680
                 Rubinius::Loader#main at core/loader.rb:867

**Comment by YorickPeterse** [comment]
This is a known issue. The gtk Gem (and various related Gems) use various MRI specific APIs we can't support in Rubinius. See the following issues for more information:

* https://github.com/rubinius/rubinius/issues/3257#issuecomment-68284381
* https://github.com/rubinius/rubinius/issues/1988
* https://github.com/ruby-gnome2/ruby-gnome2/issues/117
