### ISSUE TITLE
Unable to build HEAD on Ubuntu 16.04 with LLVM 3.6

### ISSUE THREAD

**Issue by jc00ke** [rubinius/rubinius#3652]
## Problem

Saw #3632 and thought I'd try building on my laptop

## How to Reproduce

```
$> sudo apt-get install -y llvm-3.6 llvm-3.6-dev clang-3.6
$> bundle
$> ./configure --llvm-config=llvm-config-3.6
$> rake build
```

## Configuration Details

* Output of `rbx -v`: `N/A`
* Output of `uname -a`: `Linux kendrick 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
* Distribution name: Ubuntu 16.04
* Contents of `config.rb`: [gist](https://gist.github.com/jc00ke/53fb94fc481778449c2de744ae5246de#file-config-rb)
* Contents of `configure.log`: [gist](https://gist.github.com/jc00ke/53fb94fc481778449c2de744ae5246de#file-configure-log)

## Build log

[gist](https://gist.github.com/jc00ke/53fb94fc481778449c2de744ae5246de#file-rake-build-log)

**Comment by jc00ke** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9975410-118866928_5-s1-v1.png?palette=1&width=246)

**Comment by brixen** [comment]
@jc00ke lol ❤️
