### ISSUE TITLE
Aborting with SIGSEGV; the sequel, twice-over.

### ISSUE THREAD

**Issue by digitalextremist** [rubinius/rubinius#3653]
Similar to #3322 except:
- Already using `resolv-replace`
- Already using `mysql2`

Identical to #2908 except:
- Not using `nokogiri`

Not sure how to reproduce or even interpret the backtrace.

```
rubinius 2.5.8 (2.1.0 bef51ae3 2015-07-14 3.4 JI) [x86_64-linux-gnu]
Linux --- 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Stacktrace & GDB output:
* https://gist.github.com/digitalextremist/64eff339a60a9119285b689f74f0caf0
* stacktrace.txt: https://gist.github.com/digitalextremist/64eff339a60a9119285b689f74f0caf0#file-stacktrace-txt
* gdb.txt: https://gist.github.com/digitalextremist/64eff339a60a9119285b689f74f0caf0#file-gdb-txt

Any help I could get on this would be *very* much appreciated. Moving a project over to `Rubinius` to try and escape jruby/jruby#3834 and make the platform cross-compatible.

**Comment by brixen** [comment]
@digitalextremist unfortunately, we are not working any longer on any Rubinius 2.x and there are a bunch of concurrency, GC, JIT issues that I've been tackling on the 3.x line. Currently, the JIT is disabled on the most recent 3.x release (3.30 as of right now), but it will be re-enabled very soon. If the JIT is critical to your application, I suggest trying 3.19, but note that you may experience random segvs with that version. If the JIT is not critical for you to at least work on the migration, please try 3.30 and continue updating to new versions as we release them.

**Comment by digitalextremist** [comment]
Thanks @brixen. I've temporarily solved this by running one of two `Ruby` server processes with `jRuby` and one with `Rubinius`; I will definitely try `3.x` for that.

**Comment by brixen** [comment]
@digitalextremist ok, keep me in the loop. Landed some profiler stuff yesterday and working on the JIT today, so hopefully we'll be cooking with gas soon. :)
