### ISSUE TITLE
Brew LLVM catch 22?

### ISSUE THREAD

**Issue by tmornini** [rubinius/rubinius#3655]
## Problem

As of release 3.30, I can no longer install as I have been able to up to release 3.29.

ruby-build says I need LLVM 3.5 if I have anything other than 3.5 installed with Brew.

If I install LLVM 3.5 with brew, then ruby-build reports that LLVM 3.6+ is required.

## How to Reproduce

```
~ $ rbenv install rbx-3.30

ERROR: Rubinius will not be able to compile using Apple's LLVM-based 
build tools on OS X. You will need to install LLVM 3.5 first.

TO FIX THE PROBLEM: Install Homebrew's llvm package with this
command: brew tap homebrew/versions ; brew install llvm35

BUILD FAILED (OS X 10.11.5 using ruby-build 20160426-20-g8dc4568)

ruby: system 
~ $ brew tap homebrew/versions ; brew install llvm35
==> Installing llvm35 from homebrew/versions
==> Downloading https://homebrew.bintray.com/bottles-versions/llvm35-3.5.1.el_capitan.bottle.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/llvm35-3.5.1.el_capitan.bottle.4.tar.gz
==> Pouring llvm35-3.5.1.el_capitan.bottle.4.tar.gz
==> Caveats
Extra tools are installed in /usr/local/opt/llvm35/share/clang-3.5

To link to libc++, something like the following is required:
  CXX="clang++-3.5 -stdlib=libc++"
  CXXFLAGS="$CXXFLAGS -nostdinc++ -I/usr/local/opt/llvm35/lib/llvm-3.5/include/c++/v1"
  LDFLAGS="$LDFLAGS -L/usr/local/opt/llvm35/lib/llvm-3.5/lib"

Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/tmornini/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/tmornini/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/llvm35/3.5.1: 1,532 files, 203.7M
ruby: system 
~ $ rbenv install rbx-3.30
Downloading rubinius-3.30.tar.bz2...
-> https://dqw8nmjcqpjn7.cloudfront.net/5294f406679d41160abe46ec1ff14b76c4353a75756227cc691108bb57f4bd16
Installing rubinius-3.30...

BUILD FAILED (OS X 10.11.5 using ruby-build 20160426-20-g8dc4568)

Inspect or clean up the working tree at /var/folders/z7/rq6vhb0s7299yt54gljf0f600000gn/T/ruby-build.20160518032204.39675
Results logged to /var/folders/z7/rq6vhb0s7299yt54gljf0f600000gn/T/ruby-build.20160518032204.39675.log

Last 10 log lines:
Your bundle is complete!
It was installed into ./vendor/bundle
Checking clang: found
Checking clang++: found

Detected old configuration settings, forcing a clean build
  Checking for 'llvm-config': only LLVM 3.6+ is supported
ABORT: unable to set up LLVM

Running 'configure' failed. Please check configure.log for more details.
```

## Configuration Details

* Output of `rbx -v`: n/a
* Output of `uname -a`: Darwin Toms-MacBook-Air.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
* Contents of `config.rb` (as a Gist link): I don't know where to find this
* Contents of `configure.log` (as a Gist link):I don't know where to find this

**Comment by brixen** [comment]
@tmornini unfortunately, this is an issue with ruby-build. It looks like it's trying to be helpful, but it's doing that in such a way that you are helpless. Instead of advising, it's dictating what you can do, even when you have better information, unless there is a way to tell it to ignore that, but I cannot help you with rbenv/ruby-build.

I suggest using ruby-install, which can install for rbenv. See https://github.com/postmodern/ruby-install#integration

I've started adding documentation to the Rubinius book. Here's the page on Getting Rubinius http://book.rubinius.com/part_i/getting_rubinius.html. I'm in the (very long) process of removing Ruby from the build system and making the dependencies more explicit per platform. Hopefully, problems like this won't be as common soon.
