### ISSUE TITLE
Data::finalize: object has invalid handle! during bundle install

### ISSUE THREAD

**Issue by thedrow** [rubinius/rubinius#3661]
## Problem

Got an error message during a bundle install regarding an invalid handle while finalizing an object.
## How to Reproduce

I cloned the [grape](https://github.com/ruby-grape/grape) framework's repository and typed bundle install.
## Configuration Details
- Output of `rbx -v`: rubinius 3.36 (2.2.2 f23df637 2016-06-05 3.6.2) [x86_64-darwin13.4.0]
- Output of `uname -a`: Darwin OmerK.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
- Distribution name (in case of Linux/BSD):
- Contents of `config.rb` (as a Gist link): https://gist.github.com/thedrow/35f087e4da332596d54839b5d0091a83 - I think that's it though not sure.
- Contents of `configure.log` (as a Gist link): No idea where to get that
## Stack Trace

https://gist.github.com/thedrow/bb9a37ac13ec26dd0794e551b602f849

**Comment by brixen** [comment]
This completes for me on Rubinius 3.64 with Bundler 1.11.2: https://gist.github.com/brixen/b3838c5c2616d07921585dc80f95776d

There are a number of concurrency issues with Bundler post 1.11.x, so please only use the Bundler version that is included with Rubinius. (See eg https://github.com/bundler/bundler/issues/5142).

Please re-open is you experience the issue on Rubinius 3.64 using the included version of Bundler.
