### ISSUE TITLE
Issue installing guard and running specs

### ISSUE THREAD

**Issue by brixen** [rubinius/rubinius#3663]
Tracking this issue here https://github.com/guard/listen/issues/400

**Comment by thedrow** [comment]
Why is the exception message for frozen hashes different?
In RBX it's "can't modify frozen instance of Hash" and in MRI Ruby it's "can't modify frozen Hash".
I agree the former is clearer but we should compatible with MRI Ruby IMO.

**Comment by brixen** [comment]
@thedrow we do not generally match MRI's verbiage for many reasons, but mostly because they are "non-executable" content and code should not be matching on arbitrary Strings when there are proper instances of classes (eg an RuntimeError, ArgumentError, etc). Something that exacerbates the problem you're seeing is MRI's very poor use of attributes on Exception classes to provide actual information in a way that can be computed (ie code can make proper OO method calls instead of random regexp matching Strings).

I have no intention of matching MRI Strings but I'm happy to support better OO APIs on Exception classes or elsewhere to support better code.
