### ISSUE TITLE
Logger does not get new fd appropriately. Log files to not compress.

### ISSUE THREAD

**Issue by digitalextremist** [rubinius/rubinius#3666]
This is a reminder ticket for something @brixen observed in a debugging situation, and which even I don't fully know the details of but promised to ticket. Feel free to change body of ticket as needed:

- [x] Logger does not get new fd appropriately. (fixed in https://github.com/rubinius/rubinius/commit/2932ba11bc83eabc09acc43ae3f79e6cae85dc86)
- [x] Log files to not compress. (fixed in https://github.com/rubinius/rubinius/commit/1b12831612315cbf7cf2a1cd757ffe48f13b80e4)

**Comment by brixen** [comment]
@digitalextremist should be good. Please re-open if I've overlooked something.
