### ISSUE TITLE
Segfault in one of our closed source gems

### ISSUE THREAD

**Issue by tak1n** [rubinius/rubinius#3668]
## Problem

When running the specs of one of our gems a segfault occurs.
## How to Reproduce

I will try to dig deeper and create a reproduction script.
## Configuration Details
- Output of `rbx -v`: `rubinius 3.29.c113 (2.2.2 d49a89ad 2016-06-07 3.8.0) [x86_64-linux-gnu]`
- Output of `uname -a`: `Linux benny-Lenovo-Y50-70 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- Contents of `config.rb` (as a Gist link): https://gist.github.com/tak1n/e80606922d865c657ebd3d86f9ac2590
- Contents of `configure.log` (as a Gist link): https://gist.github.com/tak1n/7b227cee15a916743f79155bd6dc586d
## Stack Trace

https://gist.github.com/tak1n/f3a8d1c69419cb93f2e6e0ff186083ca

**Comment by tak1n** [comment]
And another one: https://gist.github.com/tak1n/bbddf1bd5bc5e2850157656c43d14f36

**Comment by digitalextremist** [comment]
Is this still happening once you upgrade to `3.38`?

**Comment by tak1n** [comment]
Yep getting another segfault on `3.38`.

Segfault output: https://gist.github.com/tak1n/98c805f8e9735f7739ed35550cf784b5
LLDB debugging: https://gist.github.com/tak1n/7dae2023b78dcf2fb735afb796ac002d

**Comment by tak1n** [comment]
Not sure if this helps somehow: https://gist.github.com/tak1n/75a5d8e2468f196a2b17793e11325256

**Comment by brixen** [comment]
@tak1n unfortunately, without the source code, or access to a running instance, it's nearly impossible to help you debug this, and that means we can't do anything to close this issue.

What I suggest doing is building Rubinius from source using the `--debug-build` option for configure. Use chruby to set up the built version or use `--prefix` option for configure to install Rubinius where your program expects to find it. Then run the debug version you built under lldb. From that, you should have a usable backtrace that shows where the segfault is occurring.

If you have time to do these steps and have a backtrace where we can follow how the segfault is happening, please re-open the issue with that additional information.
