### ISSUE TITLE
Emitted profiler output isn't thread-safe

### ISSUE THREAD

**Issue by chuckremes** [rubinius/rubinius#3672]
## Problem

While working on some repro code for a lock contention issue, I noticed that the streamed profiler output was wrong.

## How to Reproduce

Execute this script:
```
require 'date'

Thread.abort_on_exception = true
threads = []
Iterations = 10_000

threads += (0..100).to_a.map do
  Thread.new do
    date = Date.today
    i = 0

    Iterations.times do
      date += 1
      date.to_s
      i += 1
    end

    raise "oops, was [#{i}] instead of [#{Iterations}]" if i < Iterations

    date
  end
end

p threads.size
threads.each { |thread| p thread.value }
```
Should execute like:
```
ruby -Xsystem.diagnostics.target='./t-diag.json' -Xsystem.profiler.target=diagnostics t.rb
```

## Configuration Details

* Output of `rbx -v`: 3.40
* Output of `uname -a`: darwin
* Distribution name (in case of Linux/BSD): OSX

## Stack Trace

Profiler/diagnostic output:
https://gist.github.com/chuckremes/9e8399f19c5bb6a036c30d9eec92b3c2

**Comment by chuckremes** [comment]
Can't reproduce anymore. As @brixen suggested on gitter, I must have had a second process running that was writing to the same file. Don't know how since I was running everything from the same terminal window but it's the only explanation that makes sense.

Closing until I can reliably reproduce this.

**Comment by brixen** [comment]
@chuckremes I'll still take a look. There is a config option `-Xsystem.profiler.subprocess=yes/no` that sets whether to run the profiler in a subprocess. The default is no. I'll add one for the diagnostics as well.
