### ISSUE TITLE
`Array.new` with huge value makes SIGSEGV

### ISSUE THREAD

**Issue by kachick** [rubinius/rubinius#3682]
## Problem

`Array.new` with huge value makes SIGSEGV

## How to Reproduce

```shell
rbx -e 'Array.new(2 ** 29)'
```

## Configuration Details

* Output of `rbx -v`: rubinius 3.3.c713 (2.3.1 f0373ac0 2016-07-21 3.6.2) [x86_64-darwin15.5.0]
* Output of `uname -a`: `Darwin MacBook-Pro-2.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64`

## Stack Trace

https://gist.github.com/kachick/835651bb018fd03c913d2bb4bf39af97

**Comment by brixen** [comment]
@kachick thanks for reporting, that was a nasty one. 😢 See the commit message for details.

**Comment by kachick** [comment]
Thanks for your investigation and fixed it! 😮  📝
