### ISSUE TITLE
PR for updated rvm install instructions for OSX?

### ISSUE THREAD

**Issue by jm3** [rubinius/rubinius#3687]
the README and the rvm defaults don't work on current OS X 10.11.6. just something like:

```bash
brew install llvm35
rvm install rbx -- --llvm-config /usr/local/opt/llvm35/bin/llvm-config-3.5
```

seems to do it. would you be open to me submitting a PR for that?

**Comment by chuckremes** [comment]
Rubinius needs LLVM 3.6, 3.7, or 3.8. It doesn’t compile with 3.5 anymore.

**Comment by brixen** [comment]
@jm3 this page in the Rubinius book has instructions for installing on various platforms: http://book.rubinius.com/part_i/getting_rubinius.html If you want to improve the, please send a PR there.

Note that we have no control over RVM and RVM has a very long history of breaking its support for installing Rubinius, so we do not recommend using RVM. The best alternatives right now are chruby and ruby-install, and we do recommend using them. We will not put RVM instructions in Rubinius documentation.
