### ISSUE TITLE
HOME environment variable (or HOMEDRIVE and HOMEPATH) must be set and point to a directory (RuntimeError)

### ISSUE THREAD

**Issue by allenzhao** [rubinius/rubinius#3688]
## Problem

I'm running bundler's rspec (script in https://github.com/bundler/bundler/blob/master/bin/rspec) and encountered this HOME variable RuntimeError. But when I run `ENV["HOME"]` in `irb` it gave me the perfect answer, which is `=> "/home/vagrant"`
## How to Reproduce

Installing rbx on trusty64 vagrant box using the script similar with provided [here](https://github.com/rubinius/docker). Then install the dependencies for bundler spec at [here](https://github.com/bundler/bundler/blob/master/DEVELOPMENT.md#development-setup). Then run the `bin/rspec` gives the above-mentioned error
## Configuration Details
- Output of `rbx -v`:
  rubinius 3.51 (2.3.1 b3a77ad4 2016-07-27 3.6.0) [x86_64-linux-gnu]
- Output of `uname -a`:
  Linux vagrant-ubuntu-trusty-64 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Distribution name (in case of Linux/BSD):
  Ubuntu Trusty 14.04
- Contents of `config.rb` (as a Gist link):
- Contents of `configure.log` (as a Gist link):
## Stack Trace

https://gist.github.com/allenzhao/f8f872f07f02eb21cebb50214d00df32

**Comment by brixen** [comment]
@allenzhao whether $HOME is defined in IRB really doesn't tell us anything about whether it's defined when that script runs.

You could start [at this point in the code](https://gist.github.com/allenzhao/f8f872f07f02eb21cebb50214d00df32#file-gistfile1-txt-L59) and check that $HOME is defined as you go up the stacktrace.

**Comment by brixen** [comment]
@allenzhao I realized when reviewing this issue that [in your gist](https://gist.github.com/allenzhao/f8f872f07f02eb21cebb50214d00df32#file-stack_trace_windows-L2) you show MRI on Windows exhibiting the same exception being raised at the same place in rbreadline. Given that, this doesn't appear to be a Rubinius issue.
