### ISSUE TITLE
Rubinius is working  in Windows 10 Bash

### ISSUE THREAD

**Issue by GoldenKeyRiver** [rubinius/rubinius#3690]
Rubinius 3.48 is working in Windows 10 Bash.
Some extensions when I try to update by gem command show "Cannot allocate memory - error forking - fork(2)". They are json and psych. 
gem-rehash have the same error. 

Simple methods are working.

**Comment by GoldenKeyRiver** [comment]
clang 3.8, llvm 3.8
Symlinks are needed to clang, clang++ and llvm-config to compilation. I'm using rbenv and mustn't install bundler before "rbenv install rbx-3.48" this is bugged.
Don't work: gem update --system

Rails can by installed. 

[Logs.zip](https://github.com/rubinius/rubinius/files/400253/Logs.zip)

**Comment by GoldenKeyRiver** [comment]
(Errno::EBADF) Bad file descriptor - fcntl(2) failed
Sometimes are that errors.

"rails new" is working.
"bundle install" have problems.

**Comment by brixen** [comment]
@GoldenKeyRiver this is awesome! Can you post a how-to in a gist and link here for getting set up to run on Windows bash.

**Comment by chuckremes** [comment]
Wow, great work! Are you going to push changes in a PR so other Windows folks (like me) can check it out?

**Comment by GoldenKeyRiver** [comment]
https://gorails.com/setup/windows/10
Tutorial for installation Rails on Windows.

sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev bison libncurses5-dev
All needed packages without llvm and clang.

https://github.com/bundler/bundler/issues/4599
Bundler issue on Windows 10 bash and solution. 

First install Ruby 2.3.1 without bundler and set global, next install rubinius. 

PostgreSQL isn't working, install binary on Windows. 

I have too slow computer to recompile it again and write tutorial.

**Comment by GoldenKeyRiver** [comment]
Sometimes is needed to restart Windows 10 Bash when was errors.

bundle install --local
It's only option to install gems for Rails, and gems like: sqlite, puma (3.5.0), sass-rails, uglifier, coffee-rails, jquery-rails, turbolinks, jbuilder must be installed manually.

sudo apt-get install libpq-dev
gem install pg
rails new [project] -d postgresql

gem install rake -v "11.2.2"
bundle install --local
"bundle exec rake db:migrate" (don't work - PostgreSQL and SQLite)

opalizoid@DESKTOP-MQER98A:~/Projects/depot$ bundle exec rake db:migrate
[Listen warning]:
  Listen will be polling for changes. Learn more at https://github.com/guard/listen#polling-fallback.
rake aborted!
NoMethodError: undefined method `start' on an instance of Thread.
core/zed.rb:1425:in `start (method_missing)'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/activesupport-5.0.0/lib/active_support/evented_file_update_checker.rb:90:in `boot!'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/activesupport-5.0.0/lib/active_support/evented_file_update_checker.rb:61:in `initialize'
core/alpha.rb:93:in `new'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/activesupport-5.0.0/lib/active_support/i18n_railtie.rb:59:in `initialize_i18n'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/activesupport-5.0.0/lib/active_support/i18n_railtie.rb:15:in `__script__'
core/proc.rb:20:in `call'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:45:in `run_load_hooks'
core/array.rb:72:in `each'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/railties-5.0.0/lib/rails/application/finisher.rb:65:in `__script__'
core/basic_object.rb:176:in `instance_exec'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `run_initializers'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/rubysl-tsort-2.0.1/lib/rubysl/tsort/tsort.rb:150:in `tsort_each'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/rubysl-tsort-2.0.1/lib/rubysl/tsort/tsort.rb:183:in `each_strongly_connected_component'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/rubysl-tsort-2.0.1/lib/rubysl/tsort/tsort.rb:219:in `each_strongly_connected_component_from'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/rubysl-tsort-2.0.1/lib/rubysl/tsort/tsort.rb:182:in `each_strongly_connected_component'
core/array.rb:72:in `tsort_each_node (each)'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/rubysl-tsort-2.0.1/lib/rubysl/tsort/tsort.rb:180:in `each_strongly_connected_component'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/rubysl-tsort-2.0.1/lib/rubysl/tsort/tsort.rb:148:in `tsort_each'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
/home/opalizoid/Projects/depot/config/environment.rb:5:in `__script__'
core/code_loader.rb:233:in `require'
core/kernel.rb:856:in `require'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/railties-5.0.0/lib/rails/application.rb:328:in `require_environment!'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/railties-5.0.0/lib/rails/application.rb:448:in `run_tasks_blocks'
core/proc.rb:20:in `call'
core/array.rb:72:in `each'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize (mon_synchronize)'
core/array.rb:72:in `each'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize (mon_synchronize)'
core/array.rb:72:in `each'
core/kernel.rb:577:in `load'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/bundler-1.12.5/exe/bundle:27:in `__script__'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/home/opalizoid/.rbenv/versions/rbx-3.48/gems/gems/bundler-1.12.5/exe/bundle:19:in `__script__'
core/kernel.rb:577:in `load'
/home/opalizoid/.rbenv/versions/rbx-3.48/bin/bundle:22:in `__script__'
core/code_loader.rb:505:in `load_script'
core/code_loader.rb:590:in `load_script'
core/loader.rb:679:in `script'
core/loader.rb:862:in `main'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

**Comment by brixen** [comment]
@GoldenKeyRiver very cool, thank you!

**Comment by brixen** [comment]
If there are specific issues running on Windows 10 Bash, please open individual tickets and we will try to address them if possible.
