### ISSUE TITLE
Needs -latomic to compile on Debian unstable

### ISSUE THREAD

**Issue by mvz** [rubinius/rubinius#3693]
## Problem

Linking `machine/test/runner.cpp` fails with `undefined reference to `__atomic_is_lock_free'` unless `-latomic` is set as an additional linker flag.`

## How to Reproduce

On Debian unstable:
* Run `./configure`
* Run `bundle exec rake`
* The build fails with the above error.
* Run `LDFLAGS=-latomic ./configure`
* Run `bundle exec rake`
* The build succeeds.

## Configuration Details

* Output of `rbx -v`:

  ```
  rubinius 3.56 (2.3.1 a9e6f6c4 2016-08-19 3.6.2) [x86_64-linux-gnu]
  ```

* Output of `uname -a`:

  ```
  Linux bean 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux
  ```
* Distribution name (in case of Linux/BSD): Debian (Unstable)
* Contents of `config.rb` (as a Gist link): https://gist.github.com/mvz/a58e4e836ba1013f74f10c28fa788dbb#file-config-rb
* Contents of `configure.log` (as a Gist link): https://gist.github.com/mvz/a58e4e836ba1013f74f10c28fa788dbb#file-configure-log

**Comment by brixen** [comment]
@mvz could you please check master HEAD?

**Comment by mvz** [comment]
@brixen it doesn't add `-latomic` to `config.rb`, and the `configure.log` contains:

```
[2016-08-30 08:11:53] clang++     -o rbx-configure-test rbx-configure-test.cpp  -fPIC -std=c++11  -Wl,--export-dynamic -lrt -lcrypt -ldl -lpthread-latomic  -lm  >>/home/matijs/tmp/software/rubinius/configure.log 2>&1
/usr/bin/ld: cannot find -lpthread-latomic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[2016-08-30 08:11:53] Compiling configure test program failed.
```

It looks like a space is missing.

After adding an extra space before `-latomic` in [this line](https://github.com/rubinius/rubinius/commit/0aa75c27418614b38a60084b774164e60b938350#diff-e2d5a00791bce9a01f99bc6fd613a39dR1381), `-latomic` appears in `config.rb` and the build succeeds.

**Comment by brixen** [comment]
@mvz ah, indeed, thanks for checking! I'll update.

**Comment by mvz** [comment]
Thanks, @brixen!

**Comment by brixen** [comment]
@mvz no problem! Thanks for reporting.
