### ISSUE TITLE
Private constants cannot be reopened

### ISSUE THREAD

**Issue by flash-gordon** [rubinius/rubinius#3697]
## Problem

Hey, I discovered a behavior inconsistent with mri/jruby regarding reopening a class/module referenced by a private constant.

## How to Reproduce

This is an easy part:
```ruby
module Foo
  module Bar
  end
  private_constant :Bar

  Bar # => Bar

  module Bar # => Private constant: Foo::Bar (NameError) on rbx, no error on MRI/JRuby
  end
end
```

## Configuration Details

```
$ rbx -v
rubinius 3.59 (2.3.1 f9c2dffa 2016-09-12 3.6.2) [x86_64-darwin16.0.0]
$ uname -a
Darwin MacBook-Pro-Nikita.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64
```

The bug was found in https://github.com/dry-rb/dry-types/pull/147

**Comment by flash-gordon** [comment]
❤️

**Comment by brixen** [comment]
@flash-gordon thanks again for reporting the issue. If you look at my commit message, you'll see my explanation for removing support for private constants. This fixes your immediate issue. If you have additional comments or feedback regarding support for private constants, please let us know.

**Comment by flash-gordon** [comment]
NP, yeah, I read that, it works for me as long as it doesn't raise an error, thank you :)

**Comment by brixen** [comment]
@flash-gordon cool. :)
