### ISSUE TITLE
Use newer version of rake

### ISSUE THREAD

**Issue by LTheGreats** [rubinius/rubinius#3704]

**Comment by brixen** [comment]
@LTheGreats would you want to give a pull-request (PR) for this one a try?

You'd need to look in [Gemfile](https://github.com/rubinius/rubinius/blob/master/Gemfile) for this line `gem "rake", "~> 10.0"` and figure out what `~>` means and how to change `10.0` to get the result you want. Then run `bundle update` and commit the changes to both Gemfile and Gemfile.lock.
