### ISSUE TITLE
ruby -S gem fails

### ISSUE THREAD

**Issue by segiddins** [rubinius/rubinius#3711]
*Edit: fixed Markdown formatting of list. -- @brixen*

Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

  I ran `ruby -S gem -v`

2. What behavior did you expect?

  I expected the rubygems version to be printed

3. What behavior did you get instead?

  I observed a stracktrace, since rbx tried to evaluate an executable as ruby code

4. What version of Rubinius?

  Output of `rbx -v`: 3.69

5. What version of operating system?

  Output of `uname -a`: `Darwin wireless-s0-no-150-2-229.uchicago.edu 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64`

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is N/A

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [x] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb. (if walked through the steps, never used lldb outside of an IDE before)
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by brixen** [comment]
@segiddins thanks for the report.

1. What version of ruby-build?
2. Are you also using rbenv, and if so, what version?
3. What is the output of `which gem`?

**Comment by segiddins** [comment]
1) ruby-build 20160913, but I manually created a definition for 3.69 by copying the latest one in the repo
2) n/a
3) `/Users/segiddins/.rubies/rbx-3.69/gems/bin/gem`, which is a binary instead of a ruby source file

**Comment by brixen** [comment]
@sandstrom could you paste the output of this command:

```
file `which gem`
```

There is something more wrong with this than just the fact that file is an executable, so trying to narrow that down. See eg:

```
$ which gem
/source/rubinius/rubinius/bin/gem
$ file `which gem`
/source/rubinius/rubinius/bin/gem: Mach-O 64-bit executable x86_64
$ rbx -S gem -v
2.6.6
```

**Comment by segiddins** [comment]
```
/Users/segiddins/.rubies/rbx-3.69/gems/bin/gem: Mach-O 64-bit executable x86_64
```

Also a Mach-O for me

**Comment by brixen** [comment]
@segiddins could you gist the output of `set` for your shell (assuming you're using bash or an act-alike; if other shell, I'm not sure the command)?

**Comment by segiddins** [comment]
https://gist.github.com/segiddins/3c67c36a740ce1c50340cf2e5db58816

**Comment by brixen** [comment]
Working on eliminating the Ruby dependency for building Rubinius and improving the packages available. Unsure when all that work may land.
