### ISSUE TITLE
`gem` command fails

### ISSUE THREAD

**Issue by AlexWayfer** [rubinius/rubinius#3713]
1. What command did you run?

  I ran `gem -v`

2. What behavior did you expect?

  I expected output of `gem` version

3. What behavior did you get instead?

  I observed [exception](https://gist.github.com/AlexWayfer/1fd216427cf124873e8636f1a1190558)

4. What version of Rubinius?

  Output of `rbx -v`: rubinius 3.69 (2.3.1 a57071c6 2016-11-17 3.9.0) [x86_64-linux-gnu]

5. What version of operating system?

  Output of `uname -a`: Linux Alex-ArchMainPC 4.8.10-1-ARCH #1 SMP PREEMPT Mon Nov 21 11:55:43 CET 2016 x86_64 GNU/Linux

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is Arch Linux

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [x] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [ ] Yes, I'm able to help debug, including running commands under lldb.
  - [x] No, I'm not able help debug or I don't have time to help.

**Comment by brixen** [comment]
@AlexWayfer I haven't seen this issue in a long time, but here are two possible causes: 1. be sure libyaml is installed; 2. if you are using chruby, delete all your gems under `~/.gem/rbx` and delete any previously installed Rubinius versions, then re-install Rubinius.

**Comment by AlexWayfer** [comment]
1. `libyaml` is installed.
```
~ $ pacaur -Qs libyaml
local/libyaml 0.1.7-1
    YAML 1.1 library
```
2. `~/.gem/rbx` doesn't exist.

I delete previously installed Rubinius versions:
```
$ rm -rf ~/.rbenv/versions/rbx-3.69
```
Then re-install Rubinius (`ruby-install` from [git](https://github.com/AlexWayfer/ruby-install/tree/update-rbx-dependencies-for-pacman)):
```
$ ./bin/ruby-install -i (rbenv root)/versions/rbx-3.69 rbx 3.69
```

Same issue.

------

About `ruby-install` from git:

1. [PR](https://github.com/postmodern/ruby-install/pull/286)

2. Environment:
```
$ pacaur -Qs llvm
local/clang 3.9.0-3
    C language family frontend for LLVM
local/lib32-llvm-libs 3.9.0-1
    Low Level Virtual Machine (runtime library)(32-bit)
local/llvm 3.9.0-3
    Low Level Virtual Machine
local/llvm-libs 3.9.0-3
    Low Level Virtual Machine (runtime libraries)
```

**Comment by brixen** [comment]
@AlexWayfer could you try building from a Rubinius clone following these steps:

```
$ git clone https://github.com/rubinius/rubinius
$ cd rubinius
$ bundle
$ ./configure --llvm-config=llvm-config-3.9
$ rake build
$ ./bin/gem -v
```

I'm assuming your llvm-config executable is named as above. If it is just `llvm-config`, you don't need the `--llvm-config` option.

**Comment by AlexWayfer** [comment]
@brixen No, it's just `llvm-config`:

```
~ $ llvm-config --version
3.9.0
```

Okay, let's try to build from source…

I have some errors and warnings while building (`bundle exec rake build`), but it doesn't stop… They look insignificant.

And… [The same issue](https://gist.github.com/AlexWayfer/99b357171c86a463ad765d5c5088ac8b) :(

**Comment by brixen** [comment]
@AlexWayfer ok, thanks for trying to build from a clone. Before we go further trying to debug this, have you tried this package? https://www.archlinux.org/packages/community/x86_64/rubinius/

**Comment by AlexWayfer** [comment]
@brixen I didn't know how to call `gem` command for this package. Now I found: `rbx gem`.

And… [The same issue](https://gist.github.com/AlexWayfer/f90f9abfe4ca931428feed7596adc851) :(

**Comment by brixen** [comment]
@AlexWayfer unfortunately, without access to your system, this is very hard to debug. Could you use a Vagrant box to try to repro this so I can use the same box to investigate it?

**Comment by AlexWayfer** [comment]
@brixen Oh, I never used Vagrant 😥 Can you provide links (?) to some instructions with which I can do this?

**Comment by brixen** [comment]
@AlexWayfer could you [check out this link](https://atlas.hashicorp.com/terrywang/boxes/archlinux) and here is the [Vagrant website](https://www.vagrantup.com). There may already be a vagrant package for Arch that you can use to get started, but I don't know this for sure.

**Comment by AlexWayfer** [comment]
Ok, so…

I have tried Arch Linux installation .ISO in VirtualBox and everything is fine.

Something wrong in my system 🙁

**Comment by AlexWayfer** [comment]
I removed some found-by-`ruby` folders and fix this problem 🙂 For distribution-package and git-repository.

```
~ $ sudo find / -name "ruby"
/home/alex/src/jruby-9.1.6.0/ # ...
/home/alex/src/rubinius-3.69/ # ...
/home/alex/.gem/ruby/ # ...
/usr/lib/ruby
```

Thanks for help. Sorry for wasting your time.

**Comment by brixen** [comment]
@AlexWayfer it was no waste of time at all. So, it seems like *possibly* what was happening is rubygems was loading a C-extension that wasn't the correct C-extension for Rubinius, Psych was catching the error and continuing, and then the process would ultimately fail with the missing Psych::Parser constant.

One thing I didn't suggest is running with `export RUBYOPT=-d` so that we could see the exceptions being raised. This probably would have shown which C-extension wasn't getting loaded and possibly why.

If you hit this issue again (or if someone else does), please try running with `export RUBYOPT=-d` and see if this gives more information that may be useful.
