### ISSUE TITLE
Deleting from array during enumeration differs from other rubies

### ISSUE THREAD

**Issue by segiddins** [rubinius/rubinius#3714]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

See https://gist.github.com/segiddins/2630075eee951b404198dc2471755844

1. What command did you run?

  I ran `rb.rb`

2. What behavior did you expect?

  I expected the same output as under MRI and JRuby

3. What behavior did you get instead?

  I observed that enumeration introduced a `nil` element that was never inserted into the collection

4. What version of Rubinius?

  Output of `rbx -v`: `rubinius 3.69 (2.3.1 a57071c6 2016-11-17 3.6.2) [x86_64-darwin16.1.0]`

5. What version of operating system?

  Output of `uname -a`: `Darwin wireless-s0-no-150-1-148.uchicago.edu 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64`

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is N/A

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [x] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by brixen** [comment]
Modifying a collection while iterating has been explicitly declared undefined Ruby behavior by matz. Rubinius doesn't support it. The alternative is to use something like `#delete_if`.
