### ISSUE TITLE
Build fails on FreeBSD 11.0 due to clang warnings

### ISSUE THREAD

**Issue by brixen** [rubinius/rubinius#3716]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

  *Note: opening this issue from a note in Rubinius Gitter from @wahjava 

  I ran `rake build`

2. What behavior did you expect?

  I expected the Rubinius build to complete successfully.

3. What behavior did you get instead?

  I observed that clang warns about unused flags during compilation and since -Werror is used, the warning causes the build to fail. http://pastebin.com/FfjtydVR

4. What version of Rubinius?

  Output of `rbx -v`: N/A

5. What version of operating system?

  Output of `uname -a`: Output not accessible, relevant info FreeBSD 11.0/amd64

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is FreeBSD 11.0

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.
  - [x] N/A

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by chuckremes** [comment]
I have clean builds working on FreeBSD12. The spec runs have some failures but the build itself succeeds and produces a working binary. This was tested with llvm 3.9.1 too.

Please reopen if you continue to see problems on freebsd11.
