### ISSUE TITLE
5x performance degredation from rbx 2.5.8 to rbx 3.69

### ISSUE THREAD

**Issue by PragTob** [rubinius/rubinius#3718]
1. What command did you run?

  I ran `ruby full_playout.rb` as well as `mcts_avg.rb`, one works with benchmark-ips the other with a self written benchmarking library. I ran both with 2.5.8 and 3.69 through RVM. Scripts available here: https://github.com/PragTob/rubykon /tree/master/benchmark

The script that switches these is available as well: https://github.com/PragTob/rubykon/blob/master/benchmark/benchmark.sh

2. What behavior did you expect?

  I expected rbx 3.69 to be about as fast as 2.5.8 or faster.

3. What behavior did you get instead?

  I observed that it got about 5 times slower. You can see results in [this gist](https://gist.github.com/PragTob/4f8d46805016fb6cca5e85ce7b62881d).

4. What version of Rubinius?

 As I said 3.69 (was most up to date when I installed last week) and 2.5.8

  Output of `rbx -v`:

```
tobi@speedy ~/github/rubykon $ rbx -v
rubinius 3.69 (2.3.1 a57071c6 2016-11-17 3.8.0) [x86_64-linux-gnu]
```

5. What version of operating system?

  Output of `uname -a`: `Linux speedy 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is Linux Mint 18 (based on Ubuntu 16.04)

7. How did you build your version of Rubinius?

  - [x] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

Why did I run all this? I wanted to make a redo of my benchmarks of ruby implementations from [last year](https://pragtob.wordpress.com/2015/11/30/benchmarking-a-go-ai-in-ruby-cruby-vs-rubinius-vs-jruby-vs-trufflegraal/) seeing how the implementations improved in the last year :)

**Comment by brixen** [comment]
@PragTob the just-in-time compiler (JIT) has been removed to make way for a new interpreter and JIT infrastructure. That is the reason you're seeing the performance degradation (and illustrates how important JIT is to making Ruby fast). The JIT was removed because it had a number of bugs and was too complicated, resulting in almost no contributors making improvements.

If you're interested in helping with the new interpreter and JIT, I can point you to some tasks to get started.

**Comment by PragTob** [comment]
@brixen the news that the JIT got removed from rubinius must have passed me by, will dig the blog to find a full blog post. Not really a JIT implementing person so probably no help from my side, but good luck in your endeavors! :)

**Comment by ShalokShalom** [comment]
Hi there. Is there still no JIT?
