### ISSUE TITLE
cannot compile 3.69 on OS X 10.12.1 with LLVM 3.9.1

### ISSUE THREAD

**Issue by schmurfy** [rubinius/rubinius#3722]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

```
bundle
./configure --prefix=[...] --llvm-config /usr/local/Cellar/llvm/3.9.1/bin/llvm-config
bundle exec rake install
```

2. What behavior did you expect?

  build successfully

3. What behavior did you get instead?

  The build fails, trace here: https://gist.github.com/schmurfy/4ecfa8e917cc74366fb75d7bae07daa6

4. What version of Rubinius?

I tried to compile 3.69, also tried with master with same result

5. What version of operating system?

OS X 10.12.1
ruby 2.3.1
llvm 3.9.1

6. What is your operating system distribution, if your operating system has more than one?

N/A

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [X] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [X] I built manually from a git clone.
  - [ ] I installed a binary.

I first noticed the error with ruby-build then tried on my local git copy with the same error

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [X] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [X] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

I tried to update to latest llvm with homebrew which solves some other errors I had previously but I still fail to compile.

**Comment by brixen** [comment]
@schmurfy thanks for opening this issue. Are you able to build successfully with LLVM 3.8? Are you able to run the Homebrew binary for 3.69?

**Comment by schmurfy** [comment]
I could not install it with homebrew, the tap listed in the install section on the website seems outdated and trying to tap it spew a lot of warning, an error and eventually fails ( from here: https://rubinius.com/install/ ).
Where do I find a working homebrew recipe ?

I just tried to compile 3.69 with llvm 3.8 and the result is the same: https://gist.github.com/schmurfy/5a645f80b6724ed66038a331e104a5f4 :(

**Comment by schmurfy** [comment]
I still can't compile it but I manage to get the binary by copying the rubinius.rb brew recipe locally instead of trying to use brew tap and brew install it.
