### ISSUE TITLE
Array#sample doesn't seem to sampling correctly

### ISSUE THREAD

**Issue by tompng** [rubinius/rubinius#3723]
The result of `[0,1,2,3].sample(3).first` seems to be biased.

I checked the randomness of Array#sample by running this code
```ruby
p 10000.times.map{[0,1,2,3].sample(3)[0]}.group_by{|a|a}.map{|a,b|[a,b.size]}.sort_by(&:first)
```
got `[[0, 2415], [1, 3333], [2, 2867], [3, 1385]]`
expected result is
`[[0, 2300~2700], [1, 2300~2700], [2, 2300~2700], [3, 2300~2700]]`

<hr>
1. What command did you run?

```sh
my-shell$ docker pull rubinius/docker
my-shell$ docker run -it rubinius/docker bash
docker-shell# rbx -v
rubinius 3.69 (2.3.1 a57071c6 2016-11-17 3.8.0) [x86_64-linux-gnu]
docker-shell# rbx -e "p 10000.times.map{[0,1,2,3].sample(3)[0]}.group_by{|a|a}.map{|a,b|[a,b.size]}.sort_by(&:first)"
[[0, 2415], [1, 3333], [2, 2867], [3, 1385]]
```

2. What behavior did you expect?
```ruby
% ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
% ruby -e "p 10000.times.map{[0,1,2,3].sample(3)[0]}.group_by{|a|a}.map{|a,b|[a,b.size]}.sort_by(&:first)"
[[0, 2490], [1, 2585], [2, 2473], [3, 2452]] # each should be 2300~2700
```

4. What version of Rubinius?
  Output of `rbx -v`: `rubinius 3.69 (2.3.1 a57071c6 2016-11-17 3.8.0) [x86_64-linux-gnu]`

5. What version of operating system?

  Output of `uname -a`: `Linux fc6d004976bf 4.4.39-moby #1 SMP Fri Dec 16 07:34:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by brixen** [comment]
Fixed by #3724.
