### ISSUE TITLE
Reproducible SEGV on release 3.69 when spawning subprocess from a Fiber

### ISSUE THREAD

**Issue by chuckremes** [rubinius/rubinius#3725]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

  I ran `...`
rbx crash-repro-2.rb

2. What behavior did you expect?

  I expected ...
... the command to echo a blank line to the terminal, sleep 5 seconds, and exit without error.

3. What behavior did you get instead?

  I observed ...
... a SEGV backtrace pointing to the spawn primitive. Here's a gist of the output:
https://gist.github.com/chuckremes/b88560500dfd5b2a291f3bd5328a86ea

4. What version of Rubinius?

  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

  Output of `rbx -v`:
rubinius 3.69.c9 (2.3.1 099c55c2 2017-01-09 3.8.0 D) [x86_64-darwin15.6.0]

5. What version of operating system?

  Output of `uname -a`:
Darwin GuestOSX 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is ...
N/A

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [x] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by brixen** [comment]
@chuckremes thanks for opening the issue. Is crash-repro-2.rb available?

**Comment by chuckremes** [comment]
Sorry for not including the repro. Duh!

Liunk to repro:  https://gist.github.com/chuckremes/cbf3caf628a9f3d5bb22a321aaf26ef5

git bisect gave me this result:

`44d5f8059634e94a0e2ac0f9de67ec2201774a72 is the first bad commit
commit 44d5f8059634e94a0e2ac0f9de67ec2201774a72
Author: Brian Shirai <brixen@gmail.com>
Date:   Sun Jun 26 10:08:40 2016 -0700

    Added Fiber#dispose and auto-cleanup of Fiber.
    
    A Fiber is composed of both managed (ie object memory) resources and unmanaged
    (ie pthread) resources. When a Fiber completes normally, the unmanaged
    resources can be reclaimed simply.
    
    When a Fiber that has not completed normally goes out of 'scope' (ie is no
    longer reachable from any reachable object), the garbage collector cannot
    simply reclaim the managed resources allocated to the Fiber because the Fiber
    composes native resources (ie the pthread instance). In this case, the Fiber's
    pthread invoke function needs to be forced to exit so that the pthread
    instance can be reclaimed.

:040000 040000 baf73a9118a8deb0cfa6ffc99d85110c30fa82ee 877e106245fc93acd201e94087a7099425aeb19d M	core
:040000 040000 f6075e3b9aeb02ae6aeb645600dc58cc73e7c6c0 0f1e0605142a22ed47791641377b53e0d70bcf7f M	machine
`

**Comment by brixen** [comment]
@chuckremes ah, I think I hit this working on #3706. I'll check your repro when I fix that one.

**Comment by chuckremes** [comment]
I made the repro code even smaller by eliminating the creation of a class and methods. A straight call to `Fiber.new { system("ls") }.resume` is enough to trigger the SEGV.

**Comment by chuckremes** [comment]
Alas, this bug prevents me from using rbx for any of my current work & play projects. Pretty much everything I do requires Fibers (celluloid). I have tried fixing it myself but have made no substantial progress.

**Comment by chuckremes** [comment]
(Belated) thank you for this fix.
