### ISSUE TITLE
Exception message from `Hash#fetch` is not interpolating key name

### ISSUE THREAD

**Issue by solnic** [rubinius/rubinius#3726]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

  I ran `{}.fetch(:foo)`

2. What behavior did you expect?

  I expected error message with interpolated key name

3. What behavior did you get instead?

  I observed an exception with message `KeyError: key #{key} not found`

4. What version of Rubinius?

  Output of `rbx -v`: `rubinius 3.69 (2.3.1 a57071c6 2016-11-17 3.9.1) [x86_64-darwin16.3.0]`

5. What version of operating system?

  Output of `uname -a`: `16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64`

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is `MacOS`

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [√] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [√] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [ ] Yes, I'm able to help debug, including running commands under lldb.
  - [√] No, I'm not able help debug or I don't have time to help.

**Comment by chuckremes** [comment]
Fixed by 58f85ba. Thanks for the report! New release coming soon will incorporate this fix.

**Comment by chuckremes** [comment]
Version 3.70 released includes this fix.

**Comment by solnic** [comment]
@chuckremes thanks, this was fast :)
