### ISSUE TITLE
UnboundMethod#source_location returns nil for attr_* methods

### ISSUE THREAD

**Issue by lucianolev** [rubinius/rubinius#3727]
1. What command did you run?

  - A script with the following code

```
class MyObject
  attr_accessor :attr_accessor_ivar
end

p MyObject.instance_method(:attr_accessor_ivar).source_location
```

2. What behavior did you expect?

- The same behavior as in MRI 2.3.3: A tuple with location of `attr_accessor` definition (second line of my script)

3. What behavior did you get instead?

  - `source_location` returned `nil`

4. What version of Rubinius?

- rubinius 3.69 (2.3.1 a57071c6 2016-11-17 3.7.0) [x86_64-linux-gnu]

5. What version of operating system?

  - Linux luciano-UX303LAB 4.2.0-42-generic # 49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

6. What is your operating system distribution, if your operating system has more than one?

  - Ubuntu 15.10

7. How did you build your version of Rubinius?

 - I used chruby.

8. Does this issue involve proprietary code?

  - No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - Yes, I'm able to help debug, including running commands under lldb.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
