### ISSUE TITLE
`Integer#bit_length` is missing

### ISSUE THREAD

**Issue by excelsior** [rubinius/rubinius#3728]
1. What command did you run?

  I ran `6174.bit_length` in the Ruby console.

2. What behavior did you expect?

  I expected `13` (`Math.log2(6174 + 1).ceil`), same as in MRI 2.3.

3. What behavior did you get instead?

  I observed the `NoMethodError` exception:

```
NoMethodError: undefined method `bit_length' on 6174:Fixnum
```

4. What version of Rubinius?

  Output of `rbx -v`:

```
rubinius 3.69 (2.3.1 a57071c6 2016-11-17 3.9.1) [x86_64-darwin16.3.0]
```

5. What version of operating system?

  Output of `uname -a`:

```
Darwin ice.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
```

6. What is your operating system distribution, if your operating system has more than one?

  N/A

7. How did you build your version of Rubinius?

  - [x] I used RVM.

8. Does this issue involve proprietary code?

  - [x] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.

**Comment by edumansky** [comment]
This issue also blocks db:migrate from working in Rails 5:

rake aborted!
NoMethodError: undefined method `bit_length' on 3095908001763421950:Fixnum.
core/zed.rb:1413:in `bit_length (method_missing)'
/Users/Ed/.rbenv/versions/rbx-3.72/gems/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:319:in `get_advisory_lock'
/Users/Ed/.rbenv/versions/rbx-3.72/gems/gems/activerecord-5.0.2/lib/active_record/migration.rb:1298:in `with_advisory_lock'

**Comment by chuckremes** [comment]
Would you like some help creating the fix for this issue? If it's truly as simple as you defined (Math.log...) then making a small pull request should be fairly easy. I can guide you through it if you would like.

**Comment by brixen** [comment]
There's a bug in `Math.log2` with Bignum that needs to be addressed. I'm pushing an implementation of `Fixnum.bit_length` and `Bignum.bit_length`, but that can be replaced with a better version when available.
