### ISSUE TITLE
UnboundMethod#source_location uses relative paths instead of absolute paths for core code

### ISSUE THREAD

**Issue by lucianolev** [rubinius/rubinius#3729]
1. What command did you run?

- A script with the following code
```
class MyObject
  def my_method; end
end
p MyObject.instance_method(:my_method).source_location
p Object.instance_method(:class).source_location
```

2. What behavior did you expect?

```
["/home/luciano/ruby-stm/workspace/workspace.rb", 486]
["core/alpha.rb", 113]
```

3. What behavior did you get instead?

```
["/home/luciano/ruby-stm/workspace/workspace.rb", 486]
["/home/luciano/.rubies/rbx-3.69/core/alpha.rb", 113]
```

4. What version of Rubinius?

- rubinius 3.69 (2.3.1 a57071c 2016-11-17 3.7.0) [x86_64-linux-gnu]

5. What version of operating system?

- Linux luciano-UX303LAB 4.2.0-42-generic # 49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

6. What is your operating system distribution, if your operating system has more than one?

- Ubuntu 15.10

7. How did you build your version of Rubinius?

- I used chruby.

8. Does this issue involve proprietary code?

- No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

- Yes, I'm able to help debug, including running commands under lldb.

**Comment by lucianolev** [comment]
I'm currently using the following ugly "patch"

```
class UnboundMethod
  alias_method :orig_source_location, :source_location

  def source_location
    unless orig_source_location.nil?
      file, linenum = orig_source_location
      unless Pathname.new(file).absolute?
        file = File.absolute_path(file, RbConfig::CONFIG['prefix'])
      end
      return file, linenum
    end
  end
end
```

I'm not sure at which level should I implement this to contribute a patch. If you can guide me, I can contribute a patch.

**Comment by chuckremes** [comment]
I can confirm the patch works. However, it uses `Pathname` which is not part of the core library. It's in the stdlib which we don't want polluting the core lib. Figure out how to replace it and we can probably accept a patch similar to this.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
