### ISSUE TITLE
macOS and RVM install issue due to llvm35 dependency

### ISSUE THREAD

**Issue by habovh** [rubinius/rubinius#3730]
## Description

When installing Rubinius (`rbx-3.7`) with `rvm`, it fails because `rvm` is forcing the `llvm35` dependency.
However, the `llvm35` brew formulae has been removed from homebrew repositories, and macOS Sierra does not even support `llvm35` at all. This results in an unsuccessful build due to unmatched dependecy.

According to [this older rvm issue](https://github.com/rvm/rvm/issues/3722), they found out that Rubinius was not building well on more recent `llvm` versions than 3.5.

I then opened [this issue](https://github.com/rvm/rvm/issues/3901) to report the problem when on macOS Sierra, but in order for them to be sure they can remove the `llvm`dependency lock, we actually need to know wether Rubinius can build correctly on more recent `llvm` versions.

Can you guys bring any help for this cross-project issue?

**Comment by habovh** [comment]
This issue is actually fixed on RVM head, but not currently released.

[This comment](https://github.com/rvm/rvm/issues/3901#issuecomment-276930896) actually suggests to update rvm from head and install rubinius again.

**Comment by habovh** [comment]
Reopening this issue as it is actually not fixed. Can a macOS Sierra (10.12) user confirm that building on this platform does not work because of LLVM?

Some investigation has been done over [here](https://github.com/rvm/rvm/issues/3901), but it is mostly regarding RVM itself.

**Comment by chuckremes** [comment]
I can confirm that Rubinius can be successfully built using llvm 3.8, 3.8.1, 3.9, and 3.9.1.

**Comment by habovh** [comment]
I have `llvm 3.9.1` installed through homebrew, but when I try tu build Rubinius 3.8 (same error for 3.7) I get the following error:

```
Jordan@JB-MBP ~/Repositories/rubinius [(HEAD detached at v3.8)]$ ./configure 
Checking clang: found
Checking clang++: found

Detected old configuration settings, forcing a clean build
  Checking for 'llvm-config': only LLVM 3.0-3.5 is supported
ABORT: unable to set up LLVM

Running 'configure' failed. Please check configure.log for more details.
```

Then I don't understand how can it successfully build with more recent LLVM version, the error message is pretty self-explanatory.

**Comment by habovh** [comment]
I actually figured out what the problem was.
Rubinius version naming is not conventional.
Actually, 3.70 is much more recent than 3.7. And that was my mistake, as I was desperately trying to install rbx 3.7 or 3.8, thinking that it was the same as 3.70 or 3.80 (as it generally is for almost every piece of software you can find).

Sorry for raising an unrelevant issue, however this confusion might be worth a warning on the README, as it is really unusual to see minor version going above 9.

Version `3.7.1` would make much more sense than `3.71`, but obviously renaming every tag would be a mess, that's something you have to specify right from the beginning...

**Comment by chuckremes** [comment]
Yes, we don't follow the major.minor.patch release naming scheme. Explanation is here:

https://book.rubinius.com/manuscript/versioning.html

**Comment by habovh** [comment]
That's fair enough, it was my mistake considering 3.7 as 3.70 and vice versa. Should I knew that, I would have avoided this issue. However it might help other doing the same mistake!

**Comment by brixen** [comment]
@habovh if you're curious to learn more about the Rubinius versioning scheme, this is a post that describes it https://github.com/rubinius/rubinius-archive/blob/cf54187d421275eec7d2db0abd5d4c059755b577/_posts/2015-09-22-major-minor-maximize-delivering-features-minimize-trouble.markdown. We use Medium now for the blog and I'm not planning to import the old posts, but if you're curious, you can see them at that archive.

For future reference, https://rubinius.com always has the current release listed in the menu header.

**Comment by habovh** [comment]
@brixen thanks for the link! I read @chuckremes's link yesterday so I eventually understood your choice regarding the versioning scheme.

But thanks anyway for the blog, it could come in handy and interesting should one need to know more about your versioning scheme!
