### ISSUE TITLE
Unable to resolve type 'socklen_t' in alpine linux with musl libc

### ISSUE THREAD

**Issue by SquallATF** [rubinius/rubinius#3732]
1. What command did you run?
  I ran `rbx -S gem install bundler`

2. What behavior did you expect?

  install bundler

3. What behavior did you get instead?

  ```
ERROR:  Loading command: install (Rubinius::FFI::TypeError)
        Unable to resolve type 'socklen_t'
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' on nil:NilClass.
 ```

4. What version of Rubinius?
 `rubinius 3.70 (2.3.1 58f85ba2 2017-01-24 3.8.1) [x86_64-linux-gnu]`

5. What version of operating system?
 `Linux magi06 4.4.45-0-virtgrsec #1-Alpine SMP Thu Jan 26 14:32:43 GMT 2017 x86_64 Linux`

6. What is your operating system distribution, if your operating system has more than one?
  `Alpine Linux 3.5.1`

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [x] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [ ] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [ ] Yes, I'm able to help debug, including running commands under lldb.
  - [x] No, I'm not able help debug or I don't have time to help.

**Comment by SquallATF** [comment]
`rbx.platform.typedef.socklen_t = uint`  is not generated in `runtime/platform.conf`
in musl libc `socklen_t` defined in `bits/alltypes.h`
```c
#if defined(__NEED_socklen_t) && !defined(__DEFINED_socklen_t)
typedef unsigned socklen_t;
#define __DEFINED_socklen_t
#endif
```
include by [`sys/socket.h`](http://git.musl-libc.org/cgit/musl/tree/include/sys/socket.h#n9) like this 
```c
#define __NEED_socklen_t
#define __NEED_sa_family_t
#define __NEED_size_t
#define __NEED_ssize_t
#define __NEED_uid_t
#define __NEED_pid_t
#define __NEED_gid_t
#define __NEED_struct_iovec

#include <bits/alltypes.h>
```

**Comment by SquallATF** [comment]
I found why `rbx.platform.typedef.socklen_t` not generated, because `socklen_t` defined as `unsigned`, but [types.rb#L23](../blob/master/library/ffi/generators/types.rb#L23) only define `"unsigned int" => :uint`

From the [C specification](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf), section 6.7.2:

>— unsigned, or unsigned int

Meaning that `unsigned`, when not specified the type, shall default to `unsigned int`. So writing `unsigned a` is the same as `unsigned int a` 
[via stackoverflow](http://stackoverflow.com/questions/41173499/what-does-unsigned-mean-when-its-all-by-itself/41173518#41173518)

**Comment by chuckremes** [comment]
Have you tried modifying types.rb to add a mapping from "unsigned" => :uint ? Does it work?

**Comment by SquallATF** [comment]
yes, it works, I have created a pull request.
