### ISSUE TITLE
rubinius 3.69 and rails 4.2.4/4.2.7 seg faults 

### ISSUE THREAD

**Issue by goodcode** [rubinius/rubinius#3733]
Hi there,

Apologies if this is the wrong place, but I believe the issue is in rubinius. Here is the full post:

http://stackoverflow.com/questions/42043769/rails-4-2-4-with-rubinius-and-puma-crashes-or-hangs-forever

Can someone please share a successful rails 4.2 and puma **production** setup, using rubinius? What versions did you use and what issues did you run into. Honestly this had to be an easy migration from a staging setup that uses MRI, to a production setup, using something that should give us higher performance. Now I'm feeling like the only person in the world that ever tried it...

**Comment by brixen** [comment]
Rubinius 4.x has a rewritten garbage collector, so this may no longer be an issue.
