### ISSUE TITLE
SIGBUS on FreeBSD12 when running VM specs

### ISSUE THREAD

**Issue by chuckremes** [rubinius/rubinius#3736]
Complete debugging steps are outlined below after the standard issue Q&A. There's also a gist of the backtrace from lldb below.

1. What command did you run?

  I ran `rake vm:test`

2. What behavior did you expect?

  I expected it to run 900+ tests and exit successfully.

3. What behavior did you get instead?

  I observed a SIGBUS.

4. What version of Rubinius?

  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

  Output of `rbx -v`:
rubinius 3.70.c28 (2.3.1 94953774 2017-01-26 3.9.1) [x86_64-freebsd12.0]

5. What version of operating system?

  Output of `uname -a`:
FreeBSD freebsd-12 12.0-CURRENT FreeBSD 12.0-CURRENT #0 r310361: Wed Dec 21 13:49:14 UTC 2016     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

6. What is your operating system distribution, if your operating system has more than one.
N/A

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [x ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [ x] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x ] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

Here's a gist pointing to the backtrace from lldb.

https://gist.github.com/chuckremes/1136c81579abbfccd55346e26503a234

Here's a list of steps I took to narrow down the issue:
After a vm test runs, it tears down the VM. Here's where things start going wrong:

1. We discard the VM instance. This call leads to a call to `delete vm` in its destructor.
https://github.com/rubinius/rubinius/blob/master/machine/test/test.hpp#L194

2. Now we `delete shared` which calls its destructor.
https://github.com/rubinius/rubinius/blob/master/machine/test/test.hpp#L195

3. In SharedState destructor, we call `delete om`
https://github.com/rubinius/rubinius/blob/master/machine/shared_state.cpp#L108

4. The Memory destructor first tries to free all objects
https://github.com/rubinius/rubinius/blob/master/machine/memory.cpp#L96

5. MarkSweepGC iterates through all objects to free them
https://github.com/rubinius/rubinius/blob/master/machine/memory/mark_sweep.cpp#L43

6. During the free, the diagnostics mechanism tracks the number of freed bytes.
To do so, in needs to get the object size which relies on a reference to a `vm` var.
https://github.com/rubinius/rubinius/blob/master/machine/memory/mark_sweep.cpp#L76

7. It calls an inline function which in turn tries to get `vm->memory`
https://github.com/rubinius/rubinius/blob/master/machine/memory/header.hpp#L921

8. The `vm->memory()` call calls `shared.memory()`. At this point lldb can't tell us the value of the ivar `shared` but the function call still worksConnection to 192.168.1.191 closed by remote host.ubinius/rubinius/blob/master/machine/vm.hpp#L282
Connection to 192.168.1.191 closed.
GuestOSX:stock-importer cremes$  to get its pointer to `om`
https://github.com/rubinius/rubinius/blob/master/machine/shared_state.hpp#L300

FreeBSD blows up at this point because `shared.memory()` refers to its canary value of 0x5a5a5a5a5a(etc) and raises a SIGBUS error. It's calling back into SharedState while we ent
ered its destructor in step 2.

**Comment by brixen** [comment]
@chuckremes could you please check if this is still an issue on master?

**Comment by chuckremes** [comment]
@brixen Hard to say now that I'm blocked by #3789. I'll close this for now and reopen if I run into it again.
