### ISSUE TITLE
[Question] Why two NilClass in nil.rb ?

### ISSUE THREAD

**Issue by Kendos-Kenlen** [rubinius/rubinius#3740]
I was reading Rubinius code and I was wondering, why is there 2 NilClass in [nil.rb](https://github.com/rubinius/rubinius/blob/master/core/nil.rb) ? Can't all the methods be in the same definition of NilClass ?

**Comment by brixen** [comment]
@Kendos-Kenlen thanks for noticing! To explain why it was that way, the Rubinius core library used to be split into different directories and that was an artifact of when I combined everything into a single directory.
