### ISSUE TITLE
Install failed with undefined reference to `__atomic_is_lock_free'

### ISSUE THREAD

**Issue by junaruga** [rubinius/rubinius#3741]
> Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

> Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

The terminal output is here.
https://gist.github.com/junaruga/cda6361372cf4f807a903eb9d60e9985

1. What command did you run?

  I ran `bundle exec rake`.

For detail,

```
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

$ bundle -v
Bundler version 1.14.6

$ clang --version
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ bundle --path vendor/bundle

$ bundle list
Gems included by the bundle:
  * bundler (1.14.6)
  * daedalus-core (1.3)
  * rake (12.0.0)
  * redcard (1.1.0)
  * rubinius-ast (3.8)
  * rubinius-bridge (2.2)
  * rubinius-code (3.0)
  * rubinius-compiler (3.10)
  * rubinius-instructions (3.0)
  * rubinius-melbourne (3.9)
  * rubinius-processor (3.3)
  * rubinius-toolset (3.0)

$ bundle exec ./configure --prefix=/usr/local/rbx-3.9dev

$ bundle exec rake
```

2. What behavior did you expect?

  I expected ... that rbx is installed by "bundle exec rake".

3. What behavior did you get instead?

  I observed ...

```
$ bundle exec rake
...
1: LD machine/test/runner
machine/test/artifacts/runner.cpp.o: In function `std::__atomic_base<unsigned long>::is_lock_free() const':
/usr/bin/../lib/gcc/x86_64-redhat-linux/6.3.1/../../../../include/c++/6.3.1/bits/atomic_base.h:354: undefined reference to `__atomic_is_lock_free'
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
Error: clang++ -o  ... -lm -Wl,--export-dynamic -lrt -lcrypt -ldl -lpthread  -lz -lLLVM-4.0 -L/usr/lib64
rake aborted!
Error compiling
...
```
4. What version of Rubinius?

  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

  Output of `rbx -v`:

HEAD of master branch.

```
commit 4628ce3730626df435089e6c705dc07ead7e32ab
Author: Brian Shirai <brixen@gmail.com>
Date:   Thu May 11 21:20:27 2017 -0700

    Fix nil.rb. Closes #3740.
```

5. What version of operating system?

Fedora 26.

  Output of `uname -a`:

```
$ uname -a
Linux unused-4-164.brq.redhat.com 4.10.6-200.fc25.x86_64 #1 SMP Mon Mar 27 14:06:23 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is ...

Fedora 26.

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [X] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [X] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [X] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by brixen** [comment]
@junaruga it looks like you may be hitting an issue involving a conflict between GCC and LLVM+Clang. See [this note](https://book.rubinius.com/manuscript/getting_rubinius.html#ubuntudebian).

While I've debugged this on Ubuntu/Debian, it's probably an issue on Redhat/Fedora as well. Would you be able to look into it?

**Comment by junaruga** [comment]
@brixen ok I will see the link, and let me try to look into it.

**Comment by brixen** [comment]
@junaruga closing this because it isn't a Rubinius issue. If you'd like a binary for your platform, please let me know what it is and I'll add it to my list. I'm working on a new binary build pipeline.

**Comment by junaruga** [comment]
Oh okay, my platform is Fedora (RPM base Linux). Fedora Project is kind of upstream of other RPM base linux distribution. I would be happy if it it supported.

**Comment by brixen** [comment]
@junaruga what version? The latest one?

**Comment by junaruga** [comment]
@brixen yes, latest one. Fedora 27. Thank you for the working.
