### ISSUE TITLE
Unsupported UncaughtThrowError#tag method

### ISSUE THREAD

**Issue by junaruga** [rubinius/rubinius#3742]
I got an error in `test-unit` test on `rbx3`.
https://github.com/test-unit/test-unit/pull/145#issuecomment-301211502

I want Rubinius to support the `UncaughtThrowError#tag`.

```
Error: test_assert_throw(Test::Unit::TestAssertions): NoMethodError: undefined method `tag' on an instance of UncaughtThrowError.
```

> Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

> Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

  I ran Travis `test-unit` test on `rubinius 3.77 (2.3.1 d8751792 2017-05-06 3.8.0) [x86_64-linux-gnu]`.

2. What behavior did you expect?

  I expected that the test was succeeded.

3. What behavior did you get instead?

  I observed that it is finished with the error.

4. What version of Rubinius?

  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

  Output of `rbx -v`:

Sorry I like to show you the result of `ruby --version`.

```
$ ruby --version
rubinius 3.77 (2.3.1 d8751792 2017-05-06 3.8.0) [x86_64-linux-gnu]
```

5. What version of operating system?

  Output of `uname -a`:

It is Ubuntu Trusty.

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is ...
Ubunbu.

7. How did you build your version of Rubinius?

  - [X] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [X] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [X] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

Thanks!

**Comment by brixen** [comment]
@junaruga thanks for reporting this issue.
