### ISSUE TITLE
Can't build on Debian Jessie

### ISSUE THREAD

**Issue by vzdor** [rubinius/rubinius#3743]
./configure --prefix=/home/vzdor/.rvm/rubies/rbx-3.77 --llvm-config /usr/bin/llvm-config-3.8 --cc=clang-3.8 --cxx=clang++-3.8
rake --trace

Is failing with:
...
** Invoke gems:melbourne (first_time)
** Execute gems:melbourne
/home/vzdor/rubinius/staging/bin/rbx ./extconf.rbc 
rake aborted!
Command failed with status (): [/home/vzdor/rubinius/staging/bin/rbx ./ext...]
/home/vzdor/.rvm/gems/ruby-2.3.4/gems/rake-12.0.0/lib/rake/file_utils.rb:66:in `block in create_shell_runner'
... 

If I run:
staging/bin/rbx
with ./extconf.rb argument or without, I get segmentation fault.
gdb backtrace for 3.77: https://gist.github.com/vzdor/a1529eba601d0a86127b75e4eae06d31

4. What version of Rubinius?
3.77 and master. I've tried different versions with RVM, as 3.71 and 3.60.

5. What version of operating system?
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

6. What is your operating system distribution, if your operating system has more than one?
Debian jessie with llvm and clang from backports.
libllvm3.5:amd64
libllvm3.8:amd64
llvm-3.8
llvm-3.8-dev
llvm-3.8-runtime
clang-3.8
libclang-common-3.8-dev
libclang1-3.8:amd64

7. How did you build your version of Rubinius?

  - [ x ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ x ] I built manually from a git clone.
  - [ ] I installed a binary.

9. Are you able to help us debug the issue?

  - [  ] Yes, I'm able to help debug, including running commands under lldb.
  - [ x ] No, I'm not able help debug or I don't have time to help.

**Comment by brixen** [comment]
@vzdor please see the note here [about mixing GCC and LLVM/Clang](https://book.rubinius.com/manuscript/getting_rubinius.html#ubuntudebian). The segv you are seeing is caused by this.
