### ISSUE TITLE
caller(range) throws NoMethodError

### ISSUE THREAD

**Issue by tamird** [rubinius/rubinius#3744]
Running `caller(1...1)` results in the stack trace:
```
NoMethodError: undefined method `+' on an instance of Range.
core/zed.rb:1413:in `+ (method_missing)'
core/kernel.rb:352:in `caller'
```

Looks like the implementation just doesn't support this: https://github.com/rubinius/rubinius/blob/v3.78/core/kernel.rb#L348:L352.

I'm not sure what Ruby API level RBX targets these days, but this signature has been documented at least since 2.0.0: https://ruby-doc.org/core-2.0.0/Kernel.html#method-i-caller.

**Comment by brixen** [comment]
@tamird thanks for opening the issue. It's just missing. Would you have time to add it? You need to detect a Range argument and compute start, end indexes. There are a number of examples of this in the Ruby core library code.
