### ISSUE TITLE
Numeric#step throws error when no limit is given

### ISSUE THREAD

**Issue by NightFeather** [rubinius/rubinius#3747]
> Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

> Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

https://gist.github.com/NightFeather/a1d696e6f63e7d1bb020381b818c6095

1. What command did you run?

  I ran `rbx -e 'p 2.step(by: 4).next'`

2. What behavior did you expect?

  I expected it outputs `2`

3. What behavior did you get instead?

  I observed an exception as the [gist](https://gist.github.com/NightFeather/a1d696e6f63e7d1bb020381b818c6095) shows

4. What version of Rubinius?

`rubinius 3.81 (2.3.1 2fb232dd 2017-06-09 4.0.0) [x86_64-linux-gnu]`

5. What version of operating system?

`Linux localhost 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux`

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is Antergos (Based on Arch Linux)

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [x] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

according to the https://github.com/ruby/ruby/blob/trunk/numeric.c#L2648

this patch should fix this
```
--- a/core/numeric_mirror.rb
+++ b/core/numeric_mirror.rb
@@ -58,10 +58,10 @@ module Rubinius
         raise ArgumentError, "step is given twice" if step && by
         raise ArgumentError, "step cannot be 0" if step == 0
 
-        limit ||= to
         step ||= by || 1
-       value = @object
         asc = step > 0
+        limit ||= to || (asc ? Float::INFINITY : -Float::INFINITY)
+         value = @object
         if value.kind_of? Float or limit.kind_of? Float or step.kind_of? Float
           return FloatValue(value), FloatValue(limit), FloatValue(step), asc, true
         else
```

**Comment by brixen** [comment]
@NightFeather thanks for the ticket and suggested patch. Would you have time to create a pull-request with a spec to cover this case and your suggested patch?

**Comment by NightFeather** [comment]
@brixen Sure. I've sent a pull request #3748 , please check.
