### ISSUE TITLE
Unexpected argument error with named parameter

### ISSUE THREAD

**Issue by andrew-aladev** [rubinius/rubinius#3754]
Let it be `test.rb`:
```
require "active_record"
require "active_record/migration"

ActiveRecord::Base.establish_connection({
  :adapter  => "postgresql",
  :host     => "127.0.0.1",
  :database => "postgres"
})

begin
  ActiveRecord::Migrator.up "migrations"
ensure
  ActiveRecord::Base.remove_connection
end
```

```
rvm use rbx-3.84
rvm gemset empty
gem install bundler && gem install activerecord && gem install pg
sudo rc-service postgresql-9.6 start
sudo -u postgres createuser -s $(whoami)
mkdir migrations
ruby test.rb
```

> ../active_record/connection_adapters/abstract/database_statements.rb:68
> method 'select_all': given 4, expected 4 (ArgumentError)

This could be fixed in activerecord by replacing:

`def select_all(arel, name = nil, binds = [], preparable: nil)`
`def select_all(arel, name = nil, binds = [], preparable = nil)`

This is not a solution, but we can see that named parameter is the actual problem.

**Comment by andrew-aladev** [comment]
I've tested it works perfect.

**Comment by brixen** [comment]
@andrew-aladev thanks again!
