### ISSUE TITLE
Can't install Rubinius using RVM on mac

### ISSUE THREAD

**Issue by adamthedeveloper** [rubinius/rubinius#3755]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

Here you go: [https://gist.github.com/adamthedeveloper/7432ec4970499ca7436c0c1cd962833d](https://gist.github.com/adamthedeveloper/7432ec4970499ca7436c0c1cd962833d)

1. What command did you run?

  I ran `rvm install rbx`
  I also tried `rvm install rubinius`

2. What behavior did you expect?

  I expected it to succeed just like MRI versions succeed.

3. What behavior did you get instead?

Here's an excerpt of the (unhelpful) output (llnk to full log above): 

checking for assert.h... yes
checking for openssl/ssl.h... yes
checking for OpenSSL_add_all_digests() in -lcrypto... no
checking for OpenSSL_add_all_digests() in -llibeay32... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/adammedeiros/.rvm/src/rbx-3.84/staging/bin/rbx
	--with-openssl-dir
	--without-openssl-dir
	--with-openssl-include
	--without-openssl-include=${openssl-dir}/include
	--with-openssl-lib
	--without-openssl-lib=${openssl-dir}/lib
	--with-kerberos-dir
	--without-kerberos-dir
	--with-kerberos-include
	--without-kerberos-include=${kerberos-dir}/include
	--with-kerberos-lib
	--without-kerberos-lib=${kerberos-dir}/lib
	--with-debug
	--without-debug
	--enable-debug
	--disable-debug
	--with-nsllib
	--without-nsllib
	--with-socketlib
	--without-socketlib
	--with-openssl-config
	--without-openssl-config
	--with-pkg-config
	--without-pkg-config
	--with-cryptolib
	--without-cryptolib
	--with-libeay32lib
	--without-libeay32lib
rake aborted!
Command failed with status (1): [/Users/adammedeiros/.rvm/src/rbx-3.84/stag...]

4. What version of Rubinius?

  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

  Output of `rbx -v`: I can't get far enough to run this.

5. What version of operating system?

  Output of `uname -a`: Darwin Adams-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is ... huh?

7. How did you build your version of Rubinius?
  It won't build - but I attempted to do so with RVM.
  - [ X] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?
  huh? I just want to build rubinius using RVM on my mac. Nothing magical or proprietary.

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [ ] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [ X] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by brixen** [comment]
@adamthedeveloper we cannot help with RVM issues, so to sort out whether this is a Rubinius issue or RVM issue, please [follow these instructions](https://book.rubinius.com/manuscript/getting_rubinius.html#building-from-source-code) for building source on macOS. In place of the tarball, you can substitute a git clone.

**Comment by adamthedeveloper** [comment]
I confirm that installing from source worked. Definitely must be RVM. Thanks for giving me some path forward.

**Comment by brixen** [comment]
@adamthedeveloper thanks for taking the time to test that! FYI, we've found over the years that [ruby-install](https://github.com/postmodern/ruby-install) and [chruby](https://github.com/postmodern/chruby) seem to be much more stable than RVM. Maybe those will work better for you.

**Comment by medols** [comment]
@adamthedeveloper can you try with this command? It worked here.

```
$ rvm install rbx-3.84 -C --with-lib-dir=$(brew --prefix openssl)/lib --with-include-dir=$(brew --prefix openssl)/include
```

**Comment by adamthedeveloper** [comment]
@medols That worked! Thanks for sharing that.
