### ISSUE TITLE
String#tr() does not work with non-ASCII UTF-8 characters

### ISSUE THREAD

**Issue by lihi1** [rubinius/rubinius#3757]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

  I ran `ruby test.rb`:

```
# encoding: UTF-8

puts "АБВ".tr "А-ЯЁ", "а-яё"
```

2. What behavior did you expect?

  I expected `абв`

3. What behavior did you get instead?

  I observed the following error:

```
              main # Rubinius::Loader at core/loader.rb:861
            script # Rubinius::Loader at core/loader.rb:679
       load_script . Rubinius::CodeLoader at core/code_loader.rb:590
       load_script # Rubinius::CodeLoader at core/code_loader.rb:505
        __script__ # Object at test.rb:3
                tr # String at core/string.rb:788
               tr! # String at core/string.rb:792
          tr_trans # String at core/string.rb:2557
         each_char # String at core/string.rb:476
   { } in tr_trans # String at core/string.rb:2564
               ord # String at core/string.rb:51

invalid byte sequence in UTF-8 (ArgumentError)

An exception occurred running test.rb
```

4. What version of Rubinius?

  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

  Output of `rbx -v`:

```
rubinius 3.85 (2.3.1 da2766ea 2017-09-24 3.8.0) [x86_64-linux-gnu]
```

5. What version of operating system?

  Output of `uname -a`:

```
Linux ubuntu-desktop 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is Ubuntu 14.04 LTS Trusty Tahr

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [x] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [X] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [ ] Yes, I'm able to help debug, including running commands under lldb.
  - [X] No, I'm not able help debug or I don't have time to help.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
