### ISSUE TITLE
Errno::ENOENT is not an Exception?

### ISSUE THREAD

**Issue by rickhull** [rubinius/rubinius#3760]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

  I ran `https://travis-ci.org/rickhull/dotcfg/jobs/287852731`

2. What behavior did you expect?

  I expected rake to succeed in a Rubinius environment

3. What behavior did you get instead?

  I observed 

# Running tests:
...F.....
Finished tests in 0.081645s, 110.2338 tests/s, 159.2266 assertions/s.
  1) Failure:
DotCfg::new::bad file path#test_0001_must raise [/home/travis/build/rickhull/dotcfg/test/dotcfg.rb:21]:
[Exception] exception expected, not
Class: <Errno::ENOENT>
Message: <"No such file or directory - failed to open file">
---Backtrace---
core/errno.rb:15:in `handle'
core/io.rb:88:in `open_with_mode'
core/io.rb:1660:in `sysopen'
core/file.rb:1188:in `initialize'
core/alpha.rb:93:in `new'
core/io.rb:1386:in `open'
/home/travis/build/rickhull/dotcfg/lib/dotcfg.rb:88:in `save'
/home/travis/build/rickhull/dotcfg/lib/dotcfg.rb:114:in `reset'
/home/travis/build/rickhull/dotcfg/lib/dotcfg.rb:37:in `initialize'
/home/travis/build/rickhull/dotcfg/test/dotcfg.rb:21:in `__script__'
---------------
9 tests, 13 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1)
core/proc.rb:20:in `call'
core/proc.rb:20:in `call'
core/array.rb:72:in `each'
/home/travis/.rvm/rubies/rubinius-3.86/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize (mon_synchronize)'
core/array.rb:72:in `each'
/home/travis/.rvm/rubies/rubinius-3.86/gems/gems/rubysl-monitor-2.0.0/lib/rubysl/monitor/monitor.rb:211:in `synchronize (mon_synchronize)'
core/array.rb:72:in `each'
/home/travis/.rvm/gems/rubinius-3.86@global/gems/rake-12.1.0/exe/rake:27:in `__script__'
core/kernel.rb:572:in `load'
core/block_environment.rb:147:in `call_on_instance'
core/kernel.rb:1132:in `eval'
/home/travis/.rvm/gems/rubinius-3.86/bin/ruby_executable_hooks:15:in `__script__'
core/code_loader.rb:505:in `load_script'
core/code_loader.rb:590:in `load_script'
core/loader.rb:679:in `script'
core/loader.rb:861:in `main'
Tasks: TOP => default => test
(See full trace by running task with --trace)
The command "rake" exited with 1.
Done. Your build exited with 1.

4. What version of Rubinius?

  Reported: 3.86
  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

  Output of `rbx -v`:

5. What version of operating system?

  Output of `uname -a`: Ubuntu 14.04.5 LTS

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is Ubuntu 14.04.5 LTS

7. How did you build your version of Rubinius?

  - [X] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [X] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [X] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by rickhull** [comment]
Here is the main problem:

`Failure:
DotCfg::new::bad file path#test_0001_must raise [/home/travis/build/rickhull/dotcfg/test/dotcfg.rb:21]:
[Exception] exception expected, not
Class: Errno::ENOENT
Message: <"No such file or directory - failed to open file">`

**Comment by rickhull** [comment]
```
irb(main):002:0> Errno::ENOENT
=> Errno::ENOENT
irb(main):003:0> Errno::ENOENT.class
=> Class
irb(main):004:0> Errno::ENOENT.superclass
=> SystemCallError
irb(main):005:0> Errno::ENOENT.superclass.superclass
=> StandardError
irb(main):006:0> Errno::ENOENT.superclass.superclass.superclass
=> Exception
irb(main):007:0>
```

**Comment by rickhull** [comment]
Rubinius succeeds when I don't consider Errno::ENOENT to be an Exception and instead test for it directly: https://travis-ci.org/rickhull/dotcfg/jobs/287858032

**Comment by chuckremes** [comment]
This is actually a bug in the version of minitest included with Rubinius. Its logic is INCORRECT for checking if the raised exception is a kind of the expected exception. It uses `instance_of?` for some reason. Anyway, later versions of Minitest have this fixed.

@brixen How does one update this for Rubinius now that the old minitest code is prebuilt into the `codedb` zip file? I installed a newer minitest gem but it still picks up the old one in codedb.

**Comment by brixen** [comment]
@chuckremes if you update `gems_list.txt` in master, I'm working on being able to build a new CodeDB from the bootstrap CodeDB. So when I push that, the build will update itself.
