### ISSUE TITLE
Provide rb_wait_for_single_fd

### ISSUE THREAD

**Issue by tamird** [rubinius/rubinius#3771]
Split from https://github.com/rubinius/rubinius/issues/3073 which was closed prematurely.

See https://github.com/brianmario/mysql2/pull/632/commits/9c191308a12f68058bb22124432906ba76298ad6.

**Comment by brixen** [comment]
In general, the MRI C-API for Rubinius is deprecated, but that doesn't mean it will be going anywhere soon. Compatibility for C-extensions will continue to be evaluated on a case-by-case basis. However, C-extensions that depend on functions that examine or manipulate built-in MRI data structures will never be supported.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated.
