### ISSUE TITLE
Thread.abort_on_exception spec fails on OSX for version 3.86

### ISSUE THREAD

**Issue by chuckremes** [rubinius/rubinius#3774]
1. What command did you run?

  I ran `./build.sh`

2. What behavior did you expect?

  I expected a clean spec run

3. What behavior did you get instead?

  I observed: https://gist.github.com/chuckremes/8098db9ce6eeafe1c2f0553654f0683b

4. What version of Rubinius?

3.86.c90

  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

5. What version of operating system?

  Output of `uname -a`:
OSX 10.12.6

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [x] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by brixen** [comment]
@chuckremes I rewrote those specs to use a script because turning on `Thread.abort_on_exception` for the main process has "interesting" consequences. Could you run the subscript and check the results? I'm wondering if the subprocess may not be running correctly. You can also check the Rubinius runtime log during the spec run to see whether the subscript executes.

**Comment by chuckremes** [comment]
Didn't see your question until now. Will rerun and check the runtime log.

**Comment by chuckremes** [comment]
Had to `git clean -fdx` and rebuild from scratch to pickup these changes. I can confirm the bug is fixed. Will close issue as solved.
