### ISSUE TITLE
rubinius is very slow

### ISSUE THREAD

**Issue by rg-3** [rubinius/rubinius#3775]
Rubinius is very slow to run the Pry test suite (https://travis-ci.org/pry/pry/builds/320414833). It can take up to 25-30 minutes. Is there a reason for this? I don't remember rubinius being as slow as it is now, although always a little slower. I see a lot of spam about pristine gems, too. Does that have an impact? Anything I can do to speed the process up?

**Comment by jc00ke** [comment]
Is the test suite slow when you run it locally on a cloned build? It looks like part of the problem might be how RVM is trying to install/update gems.

**Comment by brixen** [comment]
@r-obert the run you linked looks like it took ~8 min total to run the specs and the entire process took ~14 min. Do the tests subprocess a lot?

I'll take a look locally and see what I can discover.

**Comment by r-obert** [comment]
I ran the tests locally, and I saw:

```
Finished in 5 minutes 1 second (files took 4.65 seconds to load)
1144 examples, 1 failure, 4 pending
```

The specs do fork in a few places I'm sure, one of those failures seems to be where a spec forks. On 1.9.3, the same spec run I saw:

```
Finished in 6.74 seconds (files took 0.55246 seconds to load)
1174 examples, 0 failures, 1 pending
```

So there's a pretty big gap between the two 😞

**Comment by r-obert** [comment]
it also takes quite a while to start Pry itself, though it does start and function as normal (it seems):
```
time rbx -Ilib bin/pry -e 'exit'
rbx -Ilib bin/pry -e 'exit'  11.60s user 0.25s system 100% cpu 11.846 total
```

**Comment by brixen** [comment]
@r-obert I'm seeing the same thing with the start time. I ran a quick profile with `RBXOPT=-Xsystem.profiler.target=pry_prof.txt time rbx -S pry -e 'exit'` and got this:

```
Profile: thread: 1, samples: 10311, sample avg time: 0.00083384s, total time: 8.59772s

    %   Samples  Method
------------------------------------------------------------
  9.6       985  <anonymous module>.keywords_extra
  6.1       634  Integer(Fixnum)chr
  1.0       104  Array#include?
  0.6        65  Array#[]
  0.6        61  BasicObject(FalseClass)!
  0.6        57  Rubinius::Tuple#insert_at_index
  0.5        47  <anonymous module>.add_method
  0.4        42  Rubinius::MethodTable#each
  0.4        40  Hash::Item#initialize
  0.1        14  Array#map
  0.1         7  Rubinius::VariableScope#method_visibility
  0.0         5  Hash::Trie#add_key
  0.0         5  Hash#each
  0.0         4  Module#lookup_method
  0.0         2  String#modify!
  0.0         2  Module(Class)alias_method
  0.0         1  Object(Class)Float
  0.0         1  <anonymous module>.coerce_to_symbol
  0.0         1  Object(Class)Regexp
  0.0         1  Rubinius::<included module>(Module)attach_function
  0.0         1  <anonymous module>.add_typedef
  0.0         1  <anonymous module>.unprintable_chr
  0.0         1  Module(Class)alias_method
  0.0         1  Object(Class)String
  0.0         1  String#gsub!
```

**Comment by r-obert** [comment]
interesting

**Comment by brixen** [comment]
@r-obert looks like there are only a couple subprocess calls, so subprocess isn't the cause of the slowness. You can see these in the Rubinius log (located at `{$TMPDIR, /tmp}/rbx-<user>.log`), eg:

```
Dec 22 15:49:47 [53419] process: backtick: 53466: /source/rubinius/rubinius/bin/rbx -I /source/rubinius/rubinius/repros/pry/lib -e '      require "pry"
      Pry.input = StringIO.new("exit-all")
      Pry.start self, output: StringIO.new
      p defined?(Readline)
', ruby.main, /source/rubinius/rubinius/repros/pry/spec/integration/readline_spec.rb:37
```

Running the profile again, this time for the specs, I got this:

```
Profile: thread: 1, samples: 456508, sample avg time: 0.000878796s, total time: 401.178s

    %   Samples  Method
------------------------------------------------------------
  9.9     45185  String#replace
  9.8     44635  <anonymous module>.keywords_extra
  6.2     28530  Integer(Fixnum)chr
  2.6     11673  Rubinius::MethodTable#each
  1.2      5357  Array#map
  0.2       883  Hash::Item#initialize
  0.2       726  Hash::Trie#insert
  0.2       687  Hash::Trie#lookup
  0.1       487  String#upcase!
  0.1       262  Hash#[]=
  0.1       246  <anonymous module>.add_method
  0.1       230  String#[]
  0.0       126  Hash::Trie#add_item
  0.0        82  Rubinius::ByteArray#dup
  0.0        29  Hash::Item#insert
  0.0         9  <anonymous module>.stat
  0.0         7  Rubinius::VariableScope#method_visibility
  0.0         3  Rubinius::<included module>(Module)find_type
  0.0         1  <anonymous module>.find_type
  0.0         1  <anonymous module>.expand
  0.0         1  <anonymous module>.unprintable_chr
  0.0         1  <anonymous module>.toprint
  0.0         1  Object(Class)NestedLocalVariable
  0.0         1  Module#module_function
  0.0         1  Object(Class)Regexp
```

I'm seeing basically the same thing you are, so I'll dig into it a bit. BTW, the failure I see locally is this: `1) Hanami integration does not enter an infinite loop (#1471, #1621)`, is that what you're seeing?

**Comment by r-obert** [comment]
Yep, that's the same failure I see.

**Comment by eregon** [comment]
I'm also seeing a very slow startup for pry, with Rubinius 4.5:
```
$ time rbx -S pry -e 'exit'
rbx -S pry -e 'exit'  24.06s user 0.22s system 99% cpu 24.361 total
```
I tried the profiler command above but that didn't seem to produce any file.

**Comment by brixen** [comment]
@rg-3 you read my mind, I was just thinking that Rubinius has changed so much in the past year, it would be good to get a fresh start in 2020. Thanks for helping clean up the issues list. 👍

**Comment by rg-3** [comment]
No problem, i only recently discovered Github has a place for all your open issues so i closed the really old one's. I haven't tested rbx lately so i'm not sure if pry performs better or the same, and the current pry developers don't wanna invest in supporting rbx anymore.
