### ISSUE TITLE
rbx-3.90 build.sh SIGSEGV failure on Arch Linux

### ISSUE THREAD

**Issue by zacts** [rubinius/rubinius#3779]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

  I ran `./build.sh --prefix=/home/zacts/.rubies/rbx-3.90`

2. What behavior did you expect?

  I expected the build to succeed.

3. What behavior did you get instead?

  I observed a SIGSEGV build failure: https://gist.github.com/zacts/6ad1834efb9a35a198985b6255c9fac9

4. What version of Rubinius?

  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

  Output of `rbx -v`: N/A

5. What version of operating system?

  Output of `uname -a`:Linux emilybronte 4.14.13-1-ARCH #1 SMP PREEMPT Wed Jan 10 11:14:50 UTC 2018 x86_64 GNU/Linux`

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is the latest Arch Linux.

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [X] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [X] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [X] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by zacts** [comment]
I notice the same issue with the same setup above for rbx-3.89.

**Comment by zacts** [comment]
I also notice the same issue with the same setup above for rbx-3.88.

**Comment by brixen** [comment]
@zacts there is a Rubinius package for Arch, could you please try installing and running that to confirm that Rubinius does run on your install?

**Comment by zacts** [comment]
I installed the `rubinius-ruby` package via `pacman -S rubinius-ruby`. Now when I type `rbx --version` I get `rubinius 3.90 (2.3.1 273aea3e 2018-01-06 5.0.1) [x86_64-linux-gnu]`.

**Comment by brixen** [comment]
@zacts ok, good to know. Thanks for checking that.

Could you please try building with `./configure --debug-build && rake --trace` and put all the terminal output including that command into a gist?

**Comment by zacts** [comment]
https://gist.github.com/zacts/ad05c7993f53475822b7d07c25805868

**Comment by brixen** [comment]
@zacts see this line https://gist.github.com/zacts/ad05c7993f53475822b7d07c25805868#file-gistfile1-txt-L9989

Somehow it looks like the GNU C++ lib is getting mixed with the Clang one, which causes this segv. You can google for more info about it.

Also, see the note in the Rubinius book https://book.rubinius.com/manuscript/getting_rubinius.html#ubuntudebian about it. You may need to experiment for the correct build flags for your system.

If you're going to use Arch, I'd suggest just using the Arch Rubinius packages. The maintainer, @heftig, has done a tremendous job, and the packages will likely be available for a new Rubinius release before you even know there's a new release. 😄

**Comment by heftig** [comment]
FWIW we do not ship libc++, so Clang++ also builds against GCC's libstdc++.

**Comment by brixen** [comment]
@heftig as best I understand it, the problem exists in mixing the two.

If you can 100% guarantee that libc++ is nowhere on the system and cannot get in the mix, that should be sufficient.

If the two can possibly mix, anything that pulls in code from both (the C++ `basic_string::char_traits` appear particularly vulnerable to this) will likely SEGV.
