### ISSUE TITLE
bundle exec jekyll serve throws an exception on rbx-3.90 Arch Linux

### ISSUE THREAD

**Issue by zacts** [rubinius/rubinius#3780]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

  I ran `bundle exec jekyll serve`

2. What behavior did you expect?

  I expected jekyll to locally serve my blog.

3. What behavior did you get instead?

  I observed an exception: https://gist.github.com/zacts/a421f632b3ad3e10230f4dd72442237e.

4. What version of Rubinius?

  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

  Output of `rbx -v`: rubinius 3.90 (2.3.1 273aea3e 2018-01-06 5.0.1) [x86_64-linux-gnu]

5. What version of operating system?

  Output of `uname -a`: Linux emilybronte 4.14.13-1-ARCH #1 SMP PREEMPT Wed Jan 10 11:14:50 UTC 2018 x86_64 GNU/Linux

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is Arch Linux x86_64

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [X] I installed a binary (I installed the official `rubinius-ruby` Arch Linux package).

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [X] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [X] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

10. Note:

You may want to test this directly against my exact GitHub blog so that you can run the exact same versions of gems: https://github.com/zacts/zacts.github.io.

**Comment by zacts** [comment]
Note, I don't know if this is relevant, but I've recently switched my UNIX shell to mksh, the official Arch Linux package version.

**Comment by brixen** [comment]
@zacts thanks for opening the issue. Once Travis gets their builds working again, 3.92 should work for you.
