### ISSUE TITLE
Official Alpine Linux packaging

### ISSUE THREAD

**Issue by CpuID** [rubinius/rubinius#3786]
Hey @brixen 

Would you be open to official packaging for rubinius in the upstream Alpine Linux repositories? a la https://pkgs.alpinelinux.org/packages

I assume we can take the learnings from https://gist.github.com/brixen/ef849d23078ee3fc617c7f40ad3630bf and my (mostly) summarised version in https://gist.github.com/CpuID/6a1ecadf3045f0f2d76ca5d7d46ff3a6 to get there?

[Upstream package creation docs](https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package)

Thanks :)

**Comment by brixen** [comment]
@CpuID howdy! Yes, we would love that! I was just recently looking into how to do that. Any help would be most appreciated.

A couple things to note: the build system is a bit in flux. I'm trying really hard to remove Ruby as a build dependency, but it's not quite there yet. However, it should be possible to build from the tarball without additional file dependencies (but there are some build system dependencies like Ruby and some libraries that need to be installed).

What do you need from me?

**Comment by brixen** [comment]
@CpuID also, I should clarify, what do you think about building from the tarball instead of the git clone?

**Comment by CpuID** [comment]
@brixen for sure, yea I'd love to see a working implementation. I occasionally have cycles spare to get it implemented, but it'll be hit and miss. I can definitely test implementations when something is close to ready also. If I get free time I'lll try put together an 

I'm fine with using the tarball for builds, one less dependency (git) on systems like Alpine.

I have noticed the deprecation warnings re getting rid of the Ruby dependency, yet `build.sh` still calls `rake` :) Understandable, and fair enough.

I think the first step will be getting an `APKBUILD` file put together. Here's an [example of the ruby one for Alpine](https://git.alpinelinux.org/cgit/aports/tree/main/ruby/APKBUILD), and a [completely random but simpler one for another unrelated package](https://git.alpinelinux.org/cgit/aports/tree/testing/fdk-aac/APKBUILD)

**Comment by CpuID** [comment]
@brixen I think the main thing will be assistance when it comes to missing dependencies/dependency version issues etc when they arise also.

**Comment by CpuID** [comment]
[APKBUILD reference docs](https://wiki.alpinelinux.org/wiki/APKBUILD_Reference)

**Comment by CpuID** [comment]
@brixen taking a stab at this now, see how far I get.

Questions so far:

- how much do you think we should break out the subpackages list? [example for ruby](https://git.alpinelinux.org/cgit/aports/tree/main/ruby/APKBUILD#n31)
- what files/directories do we need explicitly from the build directory for a working installation? I assume a subset of `build` at a minimum?

**Comment by CpuID** [comment]
[first pass of an APKBUILD](https://gist.github.com/CpuID/06673ce079b49c3a49357f2798f94f37) with TODOs inline

Current state: for whatever reason `./configure` can't find clang when running under `abuild -r`, yet it runs fine from a `sh` shell... I wonder if the env vars aren't being fed in correctly for CXXFLAGS/LDFLAGS etc...

```
79067fe537b2:/host/aports/testing/rubinius/src/rubinius-3.100$ cat configure.log 
[2018-03-16 00:07:43] Configuring Rubinius...
[2018-03-16 00:07:43] Command line: "--libc libc.so"
[2018-03-16 00:07:43]*** ERROR ------------------------------ Deprecation notice ------------------------------
[2018-03-16 00:07:43]*** ERROR ---


'configure' is deprecated and will be removed in the future.
Use 'build.sh' to configure, build, package, and install Rubinius.


---
[2018-03-16 00:07:43]*** ERROR --------------------------------------------------------------------------------
[2018-03-16 00:07:43] Checking gcc:
[2018-03-16 00:07:43]  found
[2018-03-16 00:07:43] Checking clang++:
[2018-03-16 00:07:43]  found
[2018-03-16 00:07:43]*** ERROR ---
Unable to find clang C compiler. Support for compilers other than clang C
compiler was deprecated 1 Jun 2016 and has been removed. If your platform does
not support clang C compiler, please email contact@rubinius.com
```

**Comment by brixen** [comment]
@CpuID wow, thanks for working on this! 👍 As for splitting things up, you may want to take a look at the Arch packages. They are split so you can use Rubinius without clobbering a Ruby, which is the direction I want to go. They also pass in a bunch of env vars to set up the build, which may help you. If you know the paths, you could also use the `--cc` and `--cxx` configure options.

Are you working on this in a repo or just in a gist? If you need to host a repo, we could do that under the Rubinius org.

And yes, I'm highly motivated to get rid of the Ruby build dependency. It has cost us hundreds of hours of issues. Unfortunately, there are a couple major pieces I still need to replace (the scripts that generate the GC tracing functions and primitive glue functions, and the dependency calculations.)

Please keep dropping questions here or maybe try the Gitter chat channel. I'll try to respond as quickly as I can.

**Comment by CpuID** [comment]
@brixen just a gist right now + a local container for testing.

I think the next step will be a fork of https://github.com/alpinelinux/aports and come up with a branch ready to PR the `APKBUILD` back to live in the official Alpine repos. 211 outstanding PRs, hopefully it get's some attention when the time comes :)

I'm happy if you want to do that under the Rubinius org - did you want to do the fork and grant me contributor access to it? That would make sense for future updates etc also I expect.

Awesome - on Gitter now.

**Comment by CpuID** [comment]
Aha, the next issue to deal with, character sets (not the first time):

```
The -K command line option sets __ENCODING__ to Encoding::UTF_8 with -KU FAILED
Expected "US-ASCII"
 to equal "UTF-8"
```

**Comment by brixen** [comment]
@CpuID Is this something you're still interested in working on?

**Comment by brixen** [comment]
I plan to make Docker images available using Alpine as a base.
