### ISSUE TITLE
Puma/Sinatra app fails to start: classname is not a class

### ISSUE THREAD

**Issue by onli** [rubinius/rubinius#3787]
Rubunius seems to think that a class of mine is not a class, at least that is how I interpret [the stacktrace](https://gist.github.com/onli/bcbfcd904211a96323fd92682fd1650a). The class in question [is this](https://gist.github.com/onli/62c8c784e1478fd1fba39ebf4f8504fe), which `ruby -c benchmark.rb` confirmed to be correct - besides, it works with MRI. I'm aware that the issue is likely something deeper than just a code syntax misinterpretation - but this is not the first class the program is loading, and the others seem to load fine.

1. What command did you run?

  I ran `bundle exec puma -e development`

2. What behavior did you expect?

  I expected my sinatra application to be started

3. What behavior did you get instead?

  [This stacktrace](https://gist.github.com/onli/bcbfcd904211a96323fd92682fd1650a) of a TypeError.

4. What version of Rubinius?

  Output of `rbx -v`: rubinius 3.100.c2 (2.3.1 d08bd4e8 2018-03-16 3.9.1) [x86_64-linux-gnu]

5. What version of operating system?

  Output of `uname -a`: Linux Fallout 4.14.12-2 #1 SMP Sun Jan 7 22:35:18 CET 2018 x86_64 AMD Phenom(tm) II X6 1090T Processor AuthenticAMD GNU/Linux

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is funtoo, a fork of gentoo.

7. How did you build your version of Rubinius?

  - [x] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [x] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [ ] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by jc00ke** [comment]
Ruby/Rubinius already has a module defined called`Benchmark`. Try renaming your class, or nesting it under a namespace of your own.

`-c` will pass on MRI when only that file is checked, but I'm guessing it won't if you add `-rbenchmark`.

**Comment by onli** [comment]
Thanks, putting Benchmark into a module helped with this issue :) I'd like to kindly suggest that this difference to MRI might be cumbersome for others as well, and maybe that namespace could be freed - `Benchmark` can't be a too uncommon class name.

**Comment by jc00ke** [comment]
@onli can you share your new version? If you just switched from `class` to `module` then you're just adding methods to the existing `Benchmark` module.

As for your suggestion, it's better to organize one's code so that it doesn't conflict with other's, and this is a perfect example.

**Comment by brixen** [comment]
@onli thanks for opening the issue and @jc00ke for helping look into it.

The issue here is that Benchmark is provided by the stdlib and Rubinius is currently preferring the stdlib over `$LOAD_PATH` due to previous issues with trying to gemify stdlib and Bundler and RubyGems not respecting that. I've removed the stdlib gems, and the files are pre-compiled into the Rubinius CodeDB.

I'll revisit the load order resolution shortly. I do think @jc00ke has good advice about properly namespacing your own app's classes and not assuming that the global namespace under Object won't have a conflict. But in this case, I think fixing the load order resolution will be better overall, but it does impose an extra cost for resolving stdlib files.

**Comment by onli** [comment]
@jc00ke I wrapped a different module around it: https://gist.github.com/onli/f3d295667cc5288b720eb01f3c1c5754. Thanks for warning me about that though :)

@brixen I'm happy to head you consider fixing this at the core!

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
