### ISSUE TITLE
StringScanner does not accept [:symbol]

### ISSUE THREAD

**Issue by onli** [rubinius/rubinius#3788]
I'm using the gem [http-accept](https://rubygems.org/gems/http-accept/versions/1.7.0). This gem makes a scan with one of those regexpressions containing named subgroups, [here](https://github.com/ioquatix/http-accept/blob/0302c83a1e3acca3a8a69f4158dc2d707ce49348/lib/http/accept/languages.rb#L36), and then later tries to [access its result](https://github.com/ioquatix/http-accept/blob/0302c83a1e3acca3a8a69f4158dc2d707ce49348/lib/http/accept/languages.rb#L108) via `[:group]` - mri allows that since Ruby 2.1, see [here](https://ruby-doc.org/stdlib-2.1.0/libdoc/strscan/rdoc/StringScanner.html#method-i-5B-5D). But [in strscan](https://github.com/rubinius/ruby-stdlib/blob/bda4115d2212eb016d34cf4cdd53f4eef48e1d16/lib/rubysl/strscan/strscan.rb#L24) `[]` does not allow inputs that do not convert to integer, breaking the gem. 

I did not find a statement which API version you are targeting, but I thought it was above 2.1? If not, is there a way to make bundler aware which ruby API version rubinius supports?

1. What command did you run?

  I ran `bundle exec puma -e development`

2. What behavior did you expect?

  My sinatra/puma app that uses the http-accept gem to run

3. What behavior did you get instead?

  I observed [a stacktrace](https://gist.github.com/onli/45c34df6f3c12d3fb1ea1498b1b67e7c).

4. What version of Rubinius?

  Output of `rbx -v`: rubinius 3.100.c2 (2.3.1 d08bd4e8 2018-03-16 3.9.1) [x86_64-linux-gnu]

5. What version of operating system?

  Output of `uname -a`: Linux Fallout 4.14.12-2 #1 SMP Sun Jan 7 22:35:18 CET 2018 x86_64 AMD Phenom(tm) II X6 1090T Processor AuthenticAMD GNU/Linux

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is funtoo, a gentoo fork.

7. How did you build your version of Rubinius?

  - [x] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issue doesn't involve proprietary code.

(It does in the context of my application, but I think all the moving parts here are free)

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by brixen** [comment]
@onli the supported Ruby version is available in RUBY_VERSION and in the `-v` output, which should be 2.3.1. However, we fix issues as they are reported due to a combination of incomplete test coverage in MRI and constant, often subtle, changes.

Thanks for opening the issue. We'll take a look at it.

**Comment by brixen** [comment]
Rubinius will continue to maintain compatibility with the current stable version of MRI to the extent possible.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above, or for Ruby compatibility, are appreciated.
