### ISSUE TITLE
SIGSEGV on freebsd 11.1

### ISSUE THREAD

**Issue by chuckremes** [rubinius/rubinius#3789]
@brixen Fixing this one is a bit beyond my current capability. Here are the steps to reproduce.

1. Get a FreeBSD 11.1 vm image from here:
https://download.freebsd.org/ftp/releases/VM-IMAGES/11.1-RELEASE/amd64/Latest/

2. Install and run under your vm manager of choice (virtualbox?)

3. Image is likely missing lots of important packages. Once logged in, install these packages:
    % pkg install bash llvm50 llvm-devel git readline ruby25

4. Setup environment:
    % export LANG=C
    % export LC_ALL=en_US.UTF-8
    % export PATH=${PATH}:/usr/local/llvm50/bin

5. clone repository
    % git clone git@github.com:rubinius/rubinius.git

6. build
    % cd rubinius
    % ./build.sh --with-lib-dir /usr/local/lib --with-include-dir /usr/local/include

At the end of the build, it will run the `preinstall_gems.rb` file. Upon exiting this script, `build/rubinius/bin/rbx` with segfault. 

7. Now run under lldb to capture the crash:
    % lldb -f ./build/rubinius/bin/rbx -- build/scripts/preinstall_gems.rb 
    (lldb) r

Here is the backtrace I captured.

https://gist.github.com/chuckremes/b5cc05758212147481d6523e20ed68dd

Looks like it dies in the finalizer at line 269. If I'm reading this right, then some object on the `live_list` gets double-freed which causes the fault. It's trying to call the destructor on a `CompiledCode` instance (compiled_code.cpp:49) which calls a mutex destructor. Kaboom. Since you likely touched this code recently, there's a subtle bug here.

If you don't want to go through the effort of building a freebsd environment to reproduce this, I can provide you with remote access to my freebsd environment. Let me know in gitter.

**Comment by brixen** [comment]
I'm going to close any issues for platforms other than macOS or Ubuntu (CI running on Travis) in order to make more progress on completing Rubinius features. Then I want to make a drive to get packages built for all the major distributions and package managers.

If someone wants to take on fixing issues on other platforms in the meantime, that would be appreciated.

**Comment by chuckremes** [comment]
I'll _own_ getting (and keeping) Rubinius working on the various BSDs.
