### ISSUE TITLE
Rubinius::CodeLoader.require_compiled

### ISSUE THREAD

**Issue by medols** [rubinius/rubinius#3796]
1. What command did you run?

[Code example](https://gist.github.com/medols/a4a5e4729fd7650508cd0b541a33d0d3)

2. What behavior did you expect?

"require_compiled" should load the compiled file.

Is there any alternative?

3. What behavior did you get instead?

```undefined method `require_compiled' on Rubinius::CodeLoader```

"require_compiled" is missing since 3.87.

4. What version of Rubinius?

rbx-3.102

5. What version of operating system?

macOS High Sierra

6. What is your operating system distribution, if your operating system has more than one?

10.13.4

7. How did you build your version of Rubinius?

  - [*] I used RVM.

8. Does this issue involve proprietary code?

  - [*] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [*] Yes, I'm able to help debug, including running commands under lldb.

**Comment by brixen** [comment]
@medols code loading in Rubinius has been completely redone and that method is no longer supported. The new CodeDB facility will likely be able to support your use case, but what you need may not be implemented yet. Can you describe what you're doing now with `require_compiled`?

**Comment by brixen** [comment]
@medols could you [email me](mailto:brian@rubinius.com), I'd like to have a more detailed discussion about this.

**Comment by brixen** [comment]
In general, Rubinius enthusiastically supports experimentation and welcomes ideas for features that enhance developer ability to create amazing software.

The focus for Rubinius in the near term is on the following capabilities:

1. Instruction set
2. Debugger
3. Profiler
4. Just-in-time compiler
5. Concurrency
6. Garbage collector

Contributions in the form of PRs for any of the areas of focus above are appreciated. Once those core capabilities are more robust, it will be possible to support more efforts around experimentation.
