### ISSUE TITLE
-I doesn't work with directories ending with /

### ISSUE THREAD

**Issue by chrisseaton** [rubinius/rubinius#3797]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

  I ran `ruby -I foo/ -rbar`

2. What behavior did you expect?

  I expected it to load `bar` from `foo`.

3. What behavior did you get instead?

  I observed it crashing in `Rubinius::CodeLoader::Resource#search`.

  https://gist.github.com/chrisseaton/6b1a6c644262c93f04dd87dcfd9d40b3

  Is it because of this line?

 https://github.com/rubinius/rubinius/blob/eced203d53133650123dc944f758c5f8240b45cb/core/code_loader.rb#L71

  I can't see this instance variable set anywhere else. Is it perhaps supposed to be `dir` instead?

4. What version of Rubinius?

  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

  Output of `rbx -v`: `rubinius 3.104 (2.3.1 eced203d 2018-05-15 5.0.1) [x86_64-darwin17.5.0]`

5. What version of operating system?

  Output of `uname -a`: `Darwin Chriss-MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64`

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is macOS 10.13.4.

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [X] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [X] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [X] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by brixen** [comment]
Thanks!
