### ISSUE TITLE
Rubinius hangs while testing ranked-model on Rails 5.2

### ISSUE THREAD

**Issue by brendon** [rubinius/rubinius#3802]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

Check out `https://github.com/mixonic/ranked-model.git` branch `master` then:

`bundle`
`bundle exec appraisal install`
`bundle exec appraisal rails-5-2 rake`

2. What behavior did you expect?

  The tests should run green and return.

3. What behavior did you get instead?

  The tests run green but then the suite hangs right at the end. This is only observable with Rails 5.2.

See: https://travis-ci.org/mixonic/ranked-model/builds/403460110

Specifically:
https://travis-ci.org/mixonic/ranked-model/jobs/403460152
https://travis-ci.org/mixonic/ranked-model/jobs/403460191
https://travis-ci.org/mixonic/ranked-model/jobs/403460222

4. What version of Rubinius?

  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

`rubinius 3.105 (2.3.1 477d83b7 2018-05-28 6.0.1) [x86_64-darwin17.6.0]`

3.106 isn't available via ruby-build via home-brew yet.

5. What version of operating system?

`Darwin Brendons-MacBook-Pro.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64`

6. What is your operating system distribution, if your operating system has more than one?

N/A

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [x] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by brendon** [comment]
Hi @brixen, It hangs locally and needs to be killed. I think travis might just be killing it after a timeout?

Here's my local run with `RUBYOPT=-d`: https://gist.github.com/brendon/56943e8bdcd8ca9c215742304a83dcc4

You can see at the end where I'm killing it. I'm not sure about all the noise at the start :)

**Comment by brixen** [comment]
@brendon thanks again for opening the issue. It should be fixed in 387c488798d8b911f160d36278710474e526d73f. I'll tag a release as soon as CI finishes.

**Comment by brendon** [comment]
Thanks @brixen :) Glad you were able to figure that one out :D

Just on a side note, in my quest to upgrade the test suite for `ranked-model` I discovered that both `pg` and `mysql2` have pulled support and CI for Rubinius. They're both actually broken on Rubinius on their current latest releases. I'm not sure if you're aware of this, but I wanted to let you know just in case. It seems like these two gems would be good to keep compatible with Rubinius if Rails support is important going forward.

**Comment by brixen** [comment]
Thanks @brendon, I appreciate the heads up.
