### ISSUE TITLE
Missing Rubinius binaries for macOS 10.12 and 10.13

### ISSUE THREAD

**Issue by iriberri** [rubinius/rubinius#3805]
Hey there, from the Travis CI team!

I noticed from a Support request that there seem to be no Rubinius binaries available beyond macOS 10.11, according to:  http://rubinius-binaries-rubinius-com.s3-us-west-2.amazonaws.com/.

Is this on purpose, or could these be generated? Thank you! I'll also leave the debug questions answered.

1. What command did you run?

  I ran `rvm use rubinius-3.10 --install --binary --fuzzy`, which is the command Travis CI uses for a given Ruby version, in this case `rubinius-3.10`.

2. What behavior did you expect?

  I expected Rubinius 3.10 to be installed/found, but this command does only seem to work for build environments running macOS 10.11 or older.

3. What behavior did you get instead?

  The binary for this Rubinius version for my system couldn't be found. The terminal output of the `rvm use` command was: https://gist.github.com/iriberri/42d4fb176d42fe566b301ea7c73944b9

4. What version of Rubinius?

  N/A

5. What version of operating system?

  Output of `uname -a`: `Darwin Traviss-Mac-6.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`

6. What is your operating system distribution, if your operating system has more than one?

  N/A

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [x] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by brixen** [comment]
Rubinius builds some binaries as a convenience but none are guaranteed. If someone wants to contribute code or binary build resources, that would be appreciated.
