### ISSUE TITLE
Expected LocalJumpError but no exception was raised

### ISSUE THREAD

**Issue by nshigit** [rubinius/rubinius#3810]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

  I ran `mspec/lib/mspec/expectations/expectations.rb`

2. What behavior did you expect?

  I expected the building process pass the test.

3. What behavior did you get instead?

  I observed tests have 2 failures.
  2335 files, 21112 examples, 176040 expectations, 2 failures, 0 errors

4. What version of Rubinius?

  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

  Output of `rbx -v`: v
  rubinius 3.107 (2.3.1 387c4887 2018-07-15 3.6.2) [x86_64-linux-gnu]

5. What version of operating system?

  Output of `uname -a`: 
Linux vagrant 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is ...
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [v] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [v] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [v] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

ii  llvm-8                              1:8~svn351543-1~exp1~20190118144607.5      amd64        Modular compiler and toolchain technologies
ii  llvm-8-dev                          1:8~svn351543-1~exp1~20190118144607.5      amd64        Modular compiler and toolchain technologies, libraries and headers
ii  llvm-8-runtime                      1:8~svn351543-1~exp1~20190118144607.5      amd64        Modular compiler and toolchain technologies, IR interpreter
clang-8                             1:8~svn351543-1~exp1~20190118144607.5      amd64        C, C++ and Objective-C compiler

git clone https://github.com/rubinius/rubinius.git
cd rubinius 
git checkout tags/v3.107 -b v3.107 
./build.sh --prefix=$HOME/rubinius --llvm-config=/usr/bin/llvm-config-8 --cc=/usr/bin/clang-8 --cxx=/usr/bin/clang++-8

1)                                                                                         [66/1899]
Fiber#resume raises a LocalJumpError if the block includes a return statement FAILED
Expected LocalJumpError but no exception was raised ( was returned)
                main # Rubinius::Loader at core/loader.rb:852 (+90)
              script # Rubinius::Loader at core/loader.rb:667 (+343)
         load_script # Rubinius::CodeLoader at core/code_loader.rb:280 (+60)
                load # Rubinius::CodeLoader::Source(Rubinius::CodeLoader::Script) at 
        core/code_loader.rb:119 (+81)
          run_script # Rubinius::CodeLoader::Source(Rubinius::CodeLoader::Script) at 
        core/code_loader.rb:132 (+21)
          __script__ # Object at mspec/bin/mspec-ci:8 (+67)
                main . MSpecScript at mspec/lib/mspec/utils/script.rb:217 (+84)
                 run # MSpecCI at mspec/lib/mspec/commands/mspec-ci.rb:78 (+227)
             process . MSpec at mspec/lib/mspec/runner/mspec.rb:43 (+11)
               files . MSpec at mspec/lib/mspec/runner/mspec.rb:51 (+48)
                each # Array at core/array.rb:72 (+71)
        { } in files . MSpec at mspec/lib/mspec/runner/mspec.rb:57 (+88)
             protect . MSpec at mspec/lib/mspec/runner/mspec.rb:69 (+34)
       instance_eval # BasicObject(Object) at core/basic_object.rb:102 (+169)
        { } in files . MSpec at mspec/lib/mspec/runner/mspec.rb:57 (+10)
                load . Kernel at core/kernel.rb:578 (+49)
                load # Rubinius::CodeLoader at core/code_loader.rb:287 (+64)
                load # Rubinius::CodeLoader::Source(Rubinius::CodeLoader::CodeModule) at 
        core/code_loader.rb:119 (+81)
          run_script # Rubinius::CodeLoader::Source(Rubinius::CodeLoader::CodeModule) at 
        core/code_loader.rb:132 (+21)
          __script__ # Object at spec/ruby/core/fiber/resume_spec.rb:3 (+35)               [40/1899]
        with_feature # Object at mspec/lib/mspec/guards/feature.rb:43 (+138)
   { } in __script__ # Object at spec/ruby/core/fiber/resume_spec.rb:4 (+12)
            describe # Object at mspec/lib/mspec/runner/object.rb:11 (+47)
            describe . MSpec at mspec/lib/mspec/runner/mspec.rb:38 (+129)
             process # ContextState at mspec/lib/mspec/runner/context.rb:199 (+100)
                each # Array at core/array.rb:72 (+71)
      { } in process # ContextState at mspec/lib/mspec/runner/context.rb:200 (+9)
              repeat . MSpec at mspec/lib/mspec/runner/mspec.rb:238 (+15)
               times # Integer(Fixnum) at core/integer.rb:194 (+40)
       { } in repeat . MSpec at mspec/lib/mspec/runner/mspec.rb:239 (+1)
      { } in process # ContextState at mspec/lib/mspec/runner/context.rb:208 (+81)
             protect # ContextState at mspec/lib/mspec/runner/context.rb:179 (+48)
                all? # Enumerable(Array) at core/enumerable.rb:408 (+10)
                each # Array at core/array.rb:72 (+71)
         { } in all? # Enumerable(Array) at core/enumerable.rb:408 (+96)
      { } in protect # ContextState at mspec/lib/mspec/runner/context.rb:179 (+26)
             protect . MSpec at mspec/lib/mspec/runner/mspec.rb:69 (+34)
       instance_eval # BasicObject(Object) at core/basic_object.rb:102 (+169)
   { } in __script__ # Object at spec/ruby/core/fiber/resume_spec.rb:79 (+39)
              should # Object(Proc) at mspec/lib/mspec/expectations/should.rb:8 (+209)
           fail_with . SpecExpectation at 
        mspec/lib/mspec/expectations/expectations.rb:15 (+110)
                                                                                           [17/1899]
2)
Fiber#resume raises a LocalJumpError if the block includes a break statement FAILED
Expected LocalJumpError but no exception was raised ( was returned)
                main # Rubinius::Loader at core/loader.rb:852 (+90)
              script # Rubinius::Loader at core/loader.rb:667 (+343)
         load_script # Rubinius::CodeLoader at core/code_loader.rb:280 (+60)
                load # Rubinius::CodeLoader::Source(Rubinius::CodeLoader::Script) at 
        core/code_loader.rb:119 (+81)
          run_script # Rubinius::CodeLoader::Source(Rubinius::CodeLoader::Script) at 
        core/code_loader.rb:132 (+21)
          __script__ # Object at mspec/bin/mspec-ci:8 (+67)
                main . MSpecScript at mspec/lib/mspec/utils/script.rb:217 (+84)
                 run # MSpecCI at mspec/lib/mspec/commands/mspec-ci.rb:78 (+227)
             process . MSpec at mspec/lib/mspec/runner/mspec.rb:43 (+11)
               files . MSpec at mspec/lib/mspec/runner/mspec.rb:51 (+48)
                each # Array at core/array.rb:72 (+71)
        { } in files . MSpec at mspec/lib/mspec/runner/mspec.rb:57 (+88)
             protect . MSpec at mspec/lib/mspec/runner/mspec.rb:69 (+34)
       instance_eval # BasicObject(Object) at core/basic_object.rb:102 (+169)
        { } in files . MSpec at mspec/lib/mspec/runner/mspec.rb:57 (+10)
                load . Kernel at core/kernel.rb:578 (+49)
                load # Rubinius::CodeLoader at core/code_loader.rb:287 (+64)
                load # Rubinius::CodeLoader::Source(Rubinius::CodeLoader::CodeModule) at 
        core/code_loader.rb:119 (+81)
          run_script # Rubinius::CodeLoader::Source(Rubinius::CodeLoader::CodeModule) at 
        core/code_loader.rb:132 (+21)
          __script__ # Object at spec/ruby/core/fiber/resume_spec.rb:3 (+35)
        with_feature # Object at mspec/lib/mspec/guards/feature.rb:43 (+138)
   { } in __script__ # Object at spec/ruby/core/fiber/resume_spec.rb:4 (+12)
            describe # Object at mspec/lib/mspec/runner/object.rb:11 (+47)
            describe . MSpec at mspec/lib/mspec/runner/mspec.rb:38 (+129)
             process # ContextState at mspec/lib/mspec/runner/context.rb:199 (+100)
                each # Array at core/array.rb:72 (+71)
      { } in process # ContextState at mspec/lib/mspec/runner/context.rb:200 (+9)
              repeat . MSpec at mspec/lib/mspec/runner/mspec.rb:238 (+15)
               times # Integer(Fixnum) at core/integer.rb:194 (+40)
       { } in repeat . MSpec at mspec/lib/mspec/runner/mspec.rb:239 (+1)
      { } in process # ContextState at mspec/lib/mspec/runner/context.rb:208 (+81)
             protect # ContextState at mspec/lib/mspec/runner/context.rb:179 (+48)
                all? # Enumerable(Array) at core/enumerable.rb:408 (+10)
                each # Array at core/array.rb:72 (+71)
         { } in all? # Enumerable(Array) at core/enumerable.rb:408 (+96)
      { } in protect # ContextState at mspec/lib/mspec/runner/context.rb:179 (+26)
             protect . MSpec at mspec/lib/mspec/runner/mspec.rb:69 (+34)
       instance_eval # BasicObject(Object) at core/basic_object.rb:102 (+169)
   { } in __script__ # Object at spec/ruby/core/fiber/resume_spec.rb:84 (+39)
              should # Object(Proc) at mspec/lib/mspec/expectations/should.rb:8 (+209)
           fail_with . SpecExpectation at 
        mspec/lib/mspec/expectations/expectations.rb:15 (+110)

**Comment by brixen** [comment]
It's complicated to fix the specs that fail when the process is run as superuser. If someone wishes to open a PR, that would be appreciated.

Regarding the Fiber failures, I'm not certain that Rubinius will ever support raising the same exceptions as MRI. By definition, exceptions are raised when code doesn't work as expected, so _not_ raising an exception doesn't prevent valid code from running.
