### ISSUE TITLE
Publish md5 hash of releases

### ISSUE THREAD

**Issue by saizai** [rubinius/rubinius#3812]
Currently, Rubinius publishes sha512 hashes, e.g. https://github.com/rubinius/rubinius/releases/download/v3.107/rubinius-3.107.tar.bz2.sha512

Please also publish md5 hashes.

Purpose: rvm uses it: https://github.com/rvm/rvm/blob/master/config/md5

**Comment by brixen** [comment]
Rubinius will not be publishing md5 hashes. RVM should update to a modern hash function.
