### ISSUE TITLE
PSA: Rubinius seems unmaintained

### ISSUE THREAD

**Issue by eregon** [rubinius/rubinius#3813]
Specifically, it had [13 commits](https://github.com/rubinius/rubinius/graphs/contributors?from=2018-04-06&to=2019-04-06&type=c) in the last year, and just one commit since August 1, 2019.
![contributions](https://user-images.githubusercontent.com/168854/55683804-1f57b280-5944-11e9-8b7c-e06292c5ada0.png)

The latest release, 3.107, was on Jul 15, 2018 and is compatible with Ruby 2.3.1.
For comparison, MRI 2.3.x is [no longer supported](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/).

**Comment by brixen** [comment]
Closing because there is nothing actionable in this issue.
