### ISSUE TITLE
Readme: Implementation of functions

### ISSUE THREAD

**Issue by ShalokShalom** [rubinius/rubinius#3814]
Hi Brian

This article suggests that Rubinius impliments functions different as Standard Ruby:

https://medium.com/metalanguage/objects-are-for-interactions-functions-are-for-data-936e044cc729

This steems the question, why you mention several incompabilities, while this one not?

Thanks a lot for your hard work, greets :D

**Comment by brixen** [comment]
@ShalokShalom I'll document functions when they are usable.
