### ISSUE TITLE
machine/test/test_bignum.hpp: found (4611686018427387904 != 0)

### ISSUE THREAD

**Issue by medols** [rubinius/rubinius#3815]
Thank you for taking the time to let us know that you're having an issue with Rubinius. We apologize for the inconvenience.

Please respond to the following questions to help us fix the issue. Please leave the form contents in place. If a question isn't relevant, please respond with N/A.

Please include a link to a gist (https://gist.github.com/) for terminal output, including backtraces, rather than pasting them inline in the issue.

1. What command did you run?

  I ran `rake vm:test`

2. What behavior did you expect?

  I expected

https://github.com/rubinius/rubinius/blob/3f42a2d463ce94570301b518d49acf8741de8f6d/machine/test/test_bignum.hpp#L164

and

https://github.com/rubinius/rubinius/blob/3f42a2d463ce94570301b518d49acf8741de8f6d/machine/test/test_bignum.hpp#L165

to be fine.

3. What behavior did you get instead?

  I observed `sum` is a Fixnum because `TS_ASSERT(kind_of<Fixnum>(sum));` is correct

and produces a value mismatch

   `Error: Expected ((((intptr_t)1 << ((8 * sizeof(intptr_t)) - 0x1 - 1)) - 1)+1 == sum->to_native()), found (4611686018427387904 != 0)"`

4. What version of Rubinius?

  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

  Output of `rbx -v`: `rubinius 4.0.c10 (2.3.1 363b0e78 2019-05-15 3.6.2) [aarch64-linux-gnu]`

5. What version of operating system?

  Output of `uname -a`: `Linux 48504c8d87b0 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux`

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is `Ubuntu 16.04.6 LTS (Xenial Xerus)`

7. How did you build your version of Rubinius?

  - [ ] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [ ] I built manually from a tarball.
  - [x] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [x] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [x] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by medols** [comment]
#3818

**Comment by brixen** [comment]
@medols thanks.
