### ISSUE TITLE
Workaround for Rubinius on Travis

### ISSUE THREAD

**Issue by jc00ke** [rubinius/rubinius#3819]
I'd like to get Guard Puma [running on Travis again](https://travis-ci.org/jc00ke/guard-puma/jobs/557428209) against Rubinius. Is there a recommended way to run tests against Rubinius on Travis w/o using `rvm`? Not sure if something like [before_install](https://docs.travis-ci.com/user/customizing-the-build/#installing-a-second-programming-language) can be leveraged.

Thanks!

**Comment by brixen** [comment]
I've not had any success avoiding RVM on Travis in many years of trying.

The issue you are likely hitting is that Xenial (16.04) is now the default on Travis and we aren't building binaries for it yet. However, I'm fixing that now, so `rbx-4` should work on Xenial soon 🤞.

**Comment by brixen** [comment]
@jc00ke there are Xenial (16.04) binaries now, but RVM won't install them. It should be exactly as it was with Trusty, and RVM is obviously finding, downloading, etc. but fails https://travis-ci.org/rubinius/travis-canary/jobs/558292568

If you want to pursue figuring this out with Travis or RVM, that would be great. If not, we need to think about an alternative to Travis.

**Comment by brixen** [comment]
@jc00ke at one point, there was some work done to be able to use chruby instead of RVM on Travis. You may be able to look into that.

**Comment by brixen** [comment]
Closing this as it's unlikely to be resolved.
