### ISSUE TITLE
Rubinius 4.12 failed to build on OS X Catalina

### ISSUE THREAD

**Issue by slowpilot** [rubinius/rubinius#3829]
1. What command did you run?

  I ran `./build.sh`

2. What behavior did you expect?

  I expected successfull build

3. What behavior did you get instead?

  I observed inability to complete rake codedb:extensions. Everytime I try to run bin/rbx i'm getting [this](https://gist.github.com/slowpilot/e1aa202fffc59494b2978b45cbb26209)

4. What version of Rubinius?
  4.12

  *Note that we accept issue reports for the current release of Rubinius. That version can be found at https://rubinius.com/install/. If there is a reason that you cannot use the current version, other than not having installed the current version, please include that reason in your issue.*

  Output of `rbx -v`:
  [https://gist.github.com/slowpilot/e1aa202fffc59494b2978b45cbb26209](https://gist.github.com/slowpilot/e1aa202fffc59494b2978b45cbb26209)

5. What version of operating system?

  Output of `uname -a`: Darwin Air 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

6. What is your operating system distribution, if your operating system has more than one?

  My distribution is OS X Catalina

7. How did you build your version of Rubinius?

  - [+] I used RVM.
  - [ ] I used ruby-build.
  - [ ] I used ruby-install.
  - [+] I built manually from a tarball.
  - [ ] I built manually from a git clone.
  - [ ] I installed a binary.

8. Does this issue involve proprietary code?

  - [ ] Yes, this issue involves proprietary code that I cannot share.
  - [ ] Yes, this issue involves proprietary code, but I am able to share it under certain conditions.
  - [+] No, this issue doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  - [+] Yes, I'm able to help debug, including running commands under lldb.
  - [ ] No, I'm not able help debug or I don't have time to help.

**Comment by brixen** [comment]
@slowpilot I'm working on tracking down the cause of failures like this that look sporadic to me. Did you try building again after you got this failure?

**Comment by slowpilot** [comment]
Hi, @brixen, thanks for replying. Yes I did it many times with no any changes in effect. It fails on executing codedb cache file according to some basic tracing.

**Comment by brixen** [comment]
@slowpilot please try 4.14.

**Comment by slowpilot** [comment]
4.14 succeeded to build. Thanks
