### ISSUE TITLE
Suggestion: Fixing a typo in the README file.

### ISSUE THREAD

**Issue by ndregs** [rubinius/rubinius#3854]
While reviewing the code, I noticed the following:

- Fixing a typo in the README file.

This could be improved to enhance the project quality. Let me know your thoughts!

**Comment by jc00ke** [comment]
Hi @ndregs, we don't find these issues to be helpful or actionable since they lack detail, so please refrain from opening them. Also, please review our [Code of Conduct](https://book.rubinius.com/manuscript/code_of_conduct.html).
