### ISSUE TITLE
CSV is much slower than MRI

### ISSUE THREAD

**Issue by aubergene** [rubinius/rubinius#985]
*\* edited to require fastercsv in 1.8 as I forgot the standard CSV library in 1.8 is very slow

``` ruby
begin
  require "faster_csv"
  FasterCSV.build_csv_interface
rescue LoadError
  require "csv"
end

CSV.foreach('thirty-megs.csv') do |row|
end
```
# ruby 1.8.7 (2011-02-18 patchlevel 334) [i686-darwin10.7.0]

real    0m20.300s
user    0m20.118s
sys 0m0.117s
# ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-darwin10.7.0]

real    0m12.281s
user    0m11.952s
sys 0m0.159s
# rubinius 2.0.0dev (1.8.7 23af0f7b yyyy-mm-dd JI) [x86_64-apple-darwin10.7.0]

real    1m39.303s
user    1m39.536s
sys 0m0.713s

**Comment by codeforkjeff** [comment]
I'm seeing csv in MRI as 6x's faster than Rubinius.

This is my test script:
```
# cat read_csv.rb

require 'csv'

t_start = Time.now.to_f

count = 0
# 10,000 row file, ~4.5MB
# available at http://codefork.com/schoenberg_small.csv
CSV.foreach("schoenberg_small.csv") do |row|
  count += 1
end

elapsed = Time.now.to_f - t_start
rate = count / elapsed

puts "Finished in #{elapsed}s, at rate of #{rate} rows/sec"
```
Here's the output:
```
# ruby -v
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

# ruby read_csv.rb
Finished in 1.3033735752105713s, at rate of 7572.656211328679 rows/sec

# rbx -v
rubinius 2.4.1 (2.1.0 b332f133 2014-12-04 3.5.0 JI) [x86_64-linux-gnu]

# rbx read_csv.rb
Finished in 7.770043134689331s, at rate of 1270.2632184801419 rows/sec
```

Here's the profiler output: https://gist.github.com/codeforkjeff/c9fef79b5b091a911018

String#count is taking 36% of the total time, which seems high?

**Comment by chuckremes** [comment]
Might be an easy opportunity for some performance tuning. Want to try?
